### ISSUE TITLE
Callback Not Called When Clicking Out of Input

### ISSUE THREAD

**Issue by pixelshaded** [dangrossman/bootstrap-daterangepicker#1000]
To reproduce, go to http://www.daterangepicker.com/#ex4

Change the start date in the input of the control and click off the control without pressing tab/enter/etc. The date has changed on the calendars/control, but the input which is updated by the callback still shows the starting predefined range of Today.

This happens because when hide is called, this conditional is false:
if (!this.startDate.isSame(this.oldStartDate) || !this.endDate.isSame(this.oldEndDate))

Which handles calling the callback.

Investigating to find the root problem.

**Comment by pixelshaded** [comment]
It looks like the root issue is that the hide event is being called before the formInputsChanged event.

**Comment by pixelshaded** [comment]
https://github.com/dangrossman/bootstrap-daterangepicker/pull/1001

**Comment by pacificeyes** [comment]
Hi, 
I'm facing the issue as mentioned below:
1. I'm selecting the calendar option of 'Last 7 Days' and I can see the range populated for that criteria and the calendar options are hidden.
2. Next time, when I again launch the calendar options, select "Custom" option and without selecting any range, I click outside the popup or click cancel button, the calendar option popup gets closed.
3. Next time, when I launch the calendar options, I can see that the range calendars are visible and displays the range for last 7 days, though the label selection is on 'Last 7 Days'. In this case I do not want the range calendars to be shown. Only thing I would need is the highlight on 'Last 7 Days' option.

**Comment by nip3o** [comment]
I believe that this might have been introduced in 4870793183a891d2cd46271dafc4d563573c36f7. Re-enabling the out-commented line causes `endDate` to update every time the textbox is altered, so it is already correct when the hide-event occur. I do not know why this was out-commented from the start, but it seems like a more simple fix. @dangrossman any thoughts regarding this?

**Comment by dangrossman** [comment]
It was commented out because updating every time someone typed one letter/number results in trying to parse incomplete inputs that aren't valid dates, or are valid but unintentional dates (like year 0000 because the year hasn't been typed yet). That's not a behavior that should be restored.
