### ISSUE TITLE
rootScope model is not working 

### ISSUE THREAD

**Issue by binson143** [dangrossman/bootstrap-daterangepicker#1002]
$rootScope.daterange = { startDate: moment().startOf('month'), endDate: moment().endOf('month') };

//

```
 <input date-range-picker class="form-control date-picker hand-cursor" type="text" readonly="readonly"
                       ng-model="daterange" options="opts" style=" font-weight: bold; font-size: 14px;background: white">
```
this is my model  for all instance of date picker in different pages..but the model values is not changing when user changes the calendar value

**Comment by dangrossman** [comment]
This is not something I can help you with. You're probably using some kind of fork.
