### ISSUE TITLE
Use different method of initially hiding

### ISSUE THREAD

**Issue by wraybowling** [dangrossman/bootstrap-daterangepicker#1005]
I had spotty results with the picker being visible on page load. I couldn't find any place in the JS source where you're running a hide() function on DOM ready or when the body loads. I'm sure it's in there somewhere and I'm just not seeing it. Maybe that's something that's built in to bootstrap 3's JS so you felt it wasn't necessary.

Anyway, I'd recommend changing the template line to hide the element from the start so there's absolutely no question about it. (line 102)

    options.template = '<div class="daterangepicker dropdown-menu" style="display:none;">' +

**Comment by dangrossman** [comment]
Bootstrap.css specifies `.dropdown-menu { display: none }` and is a requirement of this library.

**Comment by wraybowling** [comment]
Bootstrap 2 doesn't have that. This, and the addition of the CSS below was literally all I needed to make Date Range Picker bootstrap 2 compatible. If you're only going to only support Bootstrap 3, say so. Otherwise, these seem like such small changes that make it accessible to a lot more folks.

```
.daterangepicker *{
  box-sizing: border-box;
}
```

**Comment by dangrossman** [comment]
Yes, I only support Bootstrap 3.

**Comment by dangrossman** [comment]
Yes, I only support Bootstrap 3.

However, the same declaration is in the Bootstrap 2 CSS.

dropdown-menu is hidden, so there's no reason to repeat this declaration

**Comment by wraybowling** [comment]
Not all versions of 2.x.

**Comment by dangrossman** [comment]
(1) This is irrelevant, since it's not supported

(2) It's understandable an app built on Bootstrap 2.x might not be rewritten, but there's no reason it can't be on the latest version of 2.x that was released if someone is *also* adding new UI libraries to that same application

In short, this is not an issue.
