### ISSUE TITLE
Multiple fields

### ISSUE THREAD

**Issue by hlarcher** [dangrossman/bootstrap-daterangepicker#1006]
I've previously opened an issue with the following description: 

"Hi, I have a form with several inputs with the plugin in single mode attached to them, when I type a date and press enter on the first field all goes well but when I do it on any of the other fields it does not close the calendar and in the apply.daterangepicker the e.element is pointing to the first field.
If I remove the first field it does the same but with the second.
So what I'm thinking is that the apply.daterangepicker is returning the first element with the plugin that it finds instead of returning the element itself.
Also, when I tab out of any field it doesnt fire the apply.daterangepicker."

which was closed because it could not be replicated but the fact is that it happens, however I was able to find that it only happens when I use the option "parentEl" because if I do the plugin fires the  "updateInputText" method in which the "this.element" somehow is always the first input that has the plugin attached and not himself.

**Comment by hlarcher** [comment]
I found that by pressing "enter" while focusing on the input the following event was being fired:

.on('click.daterangepicker', 'button.applyBtn', $.proxy(this.clickApply, this))

So as a fix I opted to add:

if (!options.singleDatePicker) 

around all the events being attached to 

this.container.find('.ranges')

because I don't think they make sense since a singleDatePicker doesn't have ranges

**Comment by dangrossman** [comment]
Closing this as I do not know how to fix it
