### ISSUE TITLE
Can I bind daterangepicker to a button?

### ISSUE THREAD

**Issue by ikirmitz** [dangrossman/bootstrap-daterangepicker#1007]
AFAIK datarangepicker only works if the parent element is a text input one. Is this true or is there a way to bind it to a different element type such as a bootstrap button?

Many thanks

**Comment by dangrossman** [comment]
It can be attached to any element in your page. I refer you to example #4, where it's attached to a `<div>` for example:

http://www.daterangepicker.com/#ex4
