### ISSUE TITLE
When turn on timePicker get message about 'Deprecation' from moment.js

### ISSUE THREAD

**Issue by KirillMehtiev** [dangrossman/bootstrap-daterangepicker#1008]
What it can be? 

![image](https://cloud.githubusercontent.com/assets/10028598/13604017/7016c426-e549-11e5-8820-e3bf34abccbd.png)

**Comment by dangrossman** [comment]
There's nowhere I parse a string into a date without a format, so I don't know what the cause of the warning is.

**Comment by KirillMehtiev** [comment]
Thanks for replay!
