### ISSUE TITLE
Time picker does not grey out when specifying a dateLimit and a maxDate

### ISSUE THREAD

**Issue by WaleedTayeb** [dangrossman/bootstrap-daterangepicker#1009]
Example from the demo page:

$('#demo').daterangepicker({
    "timePicker": true,
    "timePicker24Hour": true,
    "dateLimit": {
        "days": 7
    },
    "startDate": "03/03/2016",
    "endDate": "03/09/2016",
    "maxDate": "03/09/2016"
}, function(start, end, label) {
  console.log("New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')");
});

Specifying a max date along with a dateLimit will not cause the timepicker to be greyed out when attempting to select more than the specifying limit.

**Comment by dangrossman** [comment]
Feel free to try to fix this. I don't have time to mess with the time picker code myself. It's harder to wrap your head around than it seems.
