### ISSUE TITLE
locale format doesnt work right

### ISSUE THREAD

**Issue by matiazar** [dangrossman/bootstrap-daterangepicker#1011]
I have puted "format": "DD/MM/YYYY", inside locale

and it doesnt show good

this is last 3 month
12/01/2015 - 03/11/2016

it should be 01/12/2015 - 11/03/2016

**Comment by sbellver** [comment]
Why you close the issue? I have same problem :(

locale:
         {
             linkedCalendars: false,
             cancelLabel: 'Cancelar',
             applyLabel: 'Aplicar',
             fromLabel:'Desde fecha',
             toLabel:'Hasta fecha',
             customRangeLabel: "Elegir fechas",
             daysOfWeek:
                  ["Do","Lu", "Ma", "Mx", "Ju", "Vi", "Sa"],
              "monthNames":
                  ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
              firstDay: 1,
             format: 'DD/MM/YYYY'
          }

And shows as MM/DD/YYYY

**Comment by dangrossman** [comment]
There is no such problem with the library.

Feel free to share a fiddle or other live webpage if you'd like help.

**Comment by sbellver** [comment]
It's about versions problems (1.x)
Thanks.

**Comment by matiazar** [comment]
I closed it because I saw that I was usign a previuos version !
