### ISSUE TITLE
Daterange picker not rendering well

### ISSUE THREAD

**Issue by makrand-bkar** [dangrossman/bootstrap-daterangepicker#1013]
Hi 

Daterange picker is not rendering well on screen, not sure what the issue is, is it the bootstrap verion, or something else,
I do not see any errors on screen

![screen shot 2016-03-14 at 1 51 45 pm](https://cloud.githubusercontent.com/assets/33308/13754105/293aaa02-e9ec-11e5-9cd1-d65cea31886c.png)

**Comment by makrand-bkar** [comment]
I am using following versions

angular 1.3.2
bootstrap 3.3.6
//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"
and its CSS

is anybody else facing similar issues

**Comment by dangrossman** [comment]
No. Debugging your (private, unshared) combination of stylesheets is your responsibility alone. It's not a library issue.

**Comment by makrand-bkar** [comment]
Hi Dan

Agreed, I have created a sample application with Yeoman Yo Angular, it does not have anything else other than daterange picker and its giving the same issue

[](https://github.com/makrand-bkar/test-daterangepicker
)

**Comment by dangrossman** [comment]
I don't know anything about angular, and I'm not going to learn it to try your project. You can see what this library looks like with nothing but the included stylesheet at http://www.daterangepicker.com

**Comment by makrand-bkar** [comment]
i dont think this has to do with Angular, let me post this issue on angular-daterange picker forum ..

**Comment by makrand-bkar** [comment]
Hi 
I figured it out, actually I am getting the desired output, I was imagining that daterange picker will allow to select months individually for start month and end month, but it looks like there are only two arrow keys
to select, and this is working fine

closing the issue

**Comment by dangrossman** [comment]
You can have separate arrows for the start and end months, or separate dropdowns above the calendars to choose start and end months. They're the `linkedCalendars` and `showDropdowns` options.
