### ISSUE TITLE
DLS time not being able to select

### ISSUE THREAD

**Issue by siddhant4u** [dangrossman/bootstrap-daterangepicker#1014]
I'm using the daterange picker for  a while without any issues. However, recently I used the datepicker for a scenario where I want user to select the time when Day light saving change will happen and found that it will not allow user to select hour '01:00' if user is in GMT on short day light saving day (i.e. 29th March 2016) the time picker automatically reverts to 02:00 which is not what I wanted to store in database.

I understand javascript stores everything in local timezone. But there has to be simple way which I'm not able to find. Can anyone help me in this?

**Comment by avorsa** [comment]
Dear dangrossman/bootstrap-daterangepicker,
Thanks for you Interest in CountBOX products,
Our best team member will get back to you shortly.

-- 
Regards,
	
Andrey Stryukov
CoFounder and COO | CTO at CountBOX.
office:(312) 940-4641| direct:(773) 756-6847 
e: as@countbox.us | www.countbox.us 
640 N La Salle Rd | Suite  200 | Chicago, IL. 60654, USA
 

CONFIDENTIALITY NOTICE: The contents of this email message and any attachments are intended solely for the address(es) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified 
that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

**Comment by dangrossman** [comment]
29 March 01:00 AM is not a point in time that exists in GMT. The clock jumps from 12:59AM to 02:00 AM on that date. You cannot select a date or date range which does not exist on the calendar.

**Comment by siddhant4u** [comment]
thanks
