### ISSUE TITLE
Ranges show multiple times

### ISSUE THREAD

**Issue by Derekjohnson277** [dangrossman/bootstrap-daterangepicker#1016]
I have three date range pickers in my application and the ranges seem to be copied everytime there in a new instance of the date picker. For example my first picker has one copy of the ranges, the second has two copies, and the third has three copies. Do you know why it would be doing this? I have tried giving all the date pickers separate names/IDs and separate option lists but that hasn't worked.
![capture](https://cloud.githubusercontent.com/assets/13419128/13785477/b5278944-eaa1-11e5-990e-1d9e355daf63.PNG)

**Comment by dangrossman** [comment]
Looks to me like you've created a global options object for yourself and appended the same list of ranges into it each time you made a new picker. The duplicating of the ranges isn't something this library is doing.

**Comment by dangrossman** [comment]
Share your code if you'd like help with it.

**Comment by Derekjohnson277** [comment]
That's what I had thought as well, but I have tried making different options lists with different names, and it continues to do the same thing.

And here's the basic layout of the code, I have a main controller creating the datepicker and I use that across my application
`$scope.datePicker = { startDate: moment($scope.startDate, "MM-DD-YYYY hh:mm:ss A"), endDate: moment() };`
, and then each page in my application has a separate controller, in which I put the options for each datepicker with different names.
Here's the html:
`<input date-range-picker class="form-control date-picker" type="text" ng-model="datePicker" options="openOptions" />`
 So in the opens controller I have the openOptions, and in another controller I have otherOptions and so on. I hope this clarifies the problem, and if it's not something you can help with that's fine. Thanks for responding quickly!

**Comment by dangrossman** [comment]
A description of your code doesn't really help.

Here's a fiddle showing this problem doesn't exist in the library: https://jsfiddle.net/xok9uouL/2/

It's in your code.

**Comment by Derekjohnson277** [comment]
Alright cool thanks for the help.
