### ISSUE TITLE
Date and Time not showing in singledatepicker option

### ISSUE THREAD

**Issue by pdctpa** [dangrossman/bootstrap-daterangepicker#1017]
I even tried on your demo site, when I select singledatepicker, it does not show the time in the input. What should I write to achieve this?

`$(function () {
$(".datetimeinput").daterangepicker({
    "singleDatePicker": true,
    "showDropdowns": true,
    "timePicker": true,
    "autoApply": true,
        locale: {
            format: "MM/DD/YYYY h:mm A"
        }
});
});`

**Comment by dangrossman** [comment]
Here is your code, unchanged:

https://jsfiddle.net/qzqv8kLn/1/

The time is shown in the input.

**Comment by pdctpa** [comment]
Year is not changing in the input when I select 2022 year, please check. It only works for the current year.

**Comment by dangrossman** [comment]
No, that's working fine too.

Are you clicking a date in the calendar after changing the year to 2022? Changing the year just changes which calendar month is in view, not your selection.

**Comment by pdctpa** [comment]
Yes, you are right. I am sorry. After selecting from the dropdown I was not clicking on the calendar. Sorry for the trouble and thanks for your support.

**Comment by pdctpa** [comment]
Sorry to bother you again, I am using this picker for my schedule input where people can set future dates for reminders, How can I disable past dates selection from the calendar? 
I searched your doc, couldn't find on this or is it there? I want to disable all the previous dates from today. So that user wont be able to select any previous dates from the calendar.

**Comment by dangrossman** [comment]
Set `maxDate` to today's date.

**Comment by pdctpa** [comment]
Thank you, its minDate to disable previous dates, just found it in docs.
