### ISSUE TITLE
Moment.js: Deprecation warning

### ISSUE THREAD

**Issue by krid-sdnera** [dangrossman/bootstrap-daterangepicker#1019]
This is appearing at console when I use bootstrap-daterangepicker after picking an end date.

**The Warning**

Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.

**The Trace**

    DateRangePicker.prototype.renderTimePicker@http://hostname/daterangepicker.js:858:25
    DateRangePicker.prototype.updateView@http://hostname/daterangepicker.js:514:17
    DateRangePicker.prototype.clickDate@http://hostname/daterangepicker.js:1319:13

On line `858` of `daterangepicker.js` is a `isafter` comparison.

**Comment by dangrossman** [comment]
Thanks. Yes. There's already a few open issues that say the same thing. It'll be fixed.

**Comment by krid-sdnera** [comment]
Okay Cool Thanks.
