### ISSUE TITLE
Cannot change default format

### ISSUE THREAD

**Issue by hrydi** [dangrossman/bootstrap-daterangepicker#1022]
i was trying to change default format like this, but it doesn't work.

`$('input[name="tanggal"]').daterangepicker({
		locale: {
		  format: 'YYYY-MM-DD'
		},		
});`

**Comment by dangrossman** [comment]
Do you, perhaps, have a very very old copy of daterangepicker.js? The options aren't the same as they were years ago.

**Comment by hrydi** [comment]
ohh sorry, my fault
thank you.
this is really great tools btw.
