### ISSUE TITLE
Custom range. One month only

### ISSUE THREAD

**Issue by m4a1fox** [dangrossman/bootstrap-daterangepicker#1024]
Hi! How to display in custom range only one month?

**Comment by malle-pietje** [comment]
Define minDate and maxDate

**Comment by m4a1fox** [comment]
Already done. 
`filterSelector.daterangepicker({
        maxDate: moment(),
        minDate: moment().subtract(14, 'days'),
        dateLimit: { days: 14 },
        ranges: ranges,
        locale: locale
    }, cb);`

But got this: https://yadi.sk/i/lc2z1gAuqXk7L :(

**Comment by malle-pietje** [comment]
So you want only to display a single month "block"? AFAIK that's not possible; where would the daterangepicker display the end date then?

**Comment by m4a1fox** [comment]
Yep! You are write. I don't think about end date input. But it can be under start date if set to display only one month?!

**Comment by malle-pietje** [comment]
You can easily hide the right or left calendar depending on how you have
opened the daterangepicker, if you're using bootstrap. Not sure how to deal
with the other elements; you might need to just try it out.

----------------------------------------
Erik Slooff
J. Obrechtlaan 30
2132 KV  Hoofddorp
Tel: +31 23 5622 565
Mobile: +31 6 1177 0504
Email:  erik@slooff.net
----------------------------------------

2016-03-28 13:43 GMT+02:00 Maxim <notifications@github.com>:

**Comment by JaapMoolenaar** [comment]
Wouldn't the singleDatePicker option help you out in this case?

**Comment by kutalev** [comment]
You can just hide it using CSS:
```
.drp-calendar.right {
    display: none !important;
  }
```
The functionality of getting two dates even across different months will perfectly work

**Comment by rezsharmeen** [comment]
> You can just hide it using CSS:
> 
> ```
> .drp-calendar.right {
>     display: none !important;
>   }
> ```
> The functionality of getting two dates even across different months will perfectly work

Also you have to add the below config:
"linkedCalendars": false,

**Comment by vamshi9666** [comment]
> Wouldn't the singleDatePicker option help you out in this case?

range cannot be seleected if you use  `singleDatePicker `
