### ISSUE TITLE
Locales support

### ISSUE THREAD

**Issue by ywarnier** [dangrossman/bootstrap-daterangepicker#1025]
It would be nice to integrate the locale-enabled version of moment.js (available on http://momentjs.com/) in a way that, passing a variable when loading the daterangepicker, we could enable it in any locale.

**Comment by dangrossman** [comment]
I don't know exactly what this means. The `moment` object from loading moment.js is a global, so anything you set on it globally before creating a date picker would apply to the date picker's use of `moment` as well.

**Comment by ywarnier** [comment]
At the moment you are using moment.js. This prevents the datetimepicker to show names of days and names of months in other languages.
It so happens that moment.js has an "internationalized" version, so I haven't looked at it yet, but I believe just changing the inclusion of moment.js a bit would allow to load the international version automatically (although clearly you're the one that should make the call whether this is a good idea or not because it *is* a little more heavyweighted.

**Comment by dangrossman** [comment]
I don't do the including of moment.js, I just tell you to include it in your page. It's a dependency. Feel free to use moment-with-locales.js or however that works. I don't think you need anything special from me. My code already gets the names of days and months from the moment object. The global moment object. YOUR moment object, with whatever localization you've applied. No day or month names are hardcoded in daterangepicker.js.
