### ISSUE TITLE
Disable autoUpdateInput at initialization, enable only for dates changing

### ISSUE THREAD

**Issue by s-o-f** [dangrossman/bootstrap-daterangepicker#1028]
I'm using date range with format like: 'DD-MM' (only day and month, without year), "autoUpdateInput" sets to "true".
If input value is "30-12 - 07-01" then after initialization it's value automatically will be changed to "30-12 - 30-12" (because for daterangepicker "30-12 - 07-01" is not valid period).

But after selecting in calendar dates 30-12 and 07-01 i get in input value "30-12 - 07-01", thats correct value for me.
How i can disable input updating after initialization and enable for selected dates changing?

Example: https://jsbin.com/suwajuzogi/edit?html,css,js,output

**Comment by dangrossman** [comment]
Specify a `startDate` and `endDate` in your options
