### ISSUE TITLE
Auto populating input

### ISSUE THREAD

**Issue by dhershman1** [dangrossman/bootstrap-daterangepicker#1029]
Using a single date picker I dont have a need for the apply and cancel buttons but I also dont want the input box to automatically update with a date on click. I only want the date to be added once the button is clicked. I know I can do some work around magic but it doesn't seem like I can just update the input once a date is chosen.

**Comment by dangrossman** [comment]
You say this:

> I dont have a need for the apply and cancel

Then you contradict it in the next sentence by saying you do want a button to apply the selection:

> I only want the date to be added once the button is clicked

Then you say the opposite again, that you don't want a button:

> it doesn't seem like I can just update the input once a date is chosen

I have no clue what you want, sorry.

**Comment by dhershman1** [comment]
Yep I was modifying the statement as I went and played with it, I found what I needed was having a dumb dumb moment sorry.
