### ISSUE TITLE
minDate with time disabled wrong hours

### ISSUE THREAD

**Issue by nenya1840** [dangrossman/bootstrap-daterangepicker#1030]
For example:
```
$('.daterange').daterangepicker({
    startDate: "04-Oct-2016 09:00 am",
    endDate: "10-Nov-2016 05:00 pm",
    format: "DD-MMM-YYYY hh:mm a"
    timePickerIncrement: 1,
    timePicker: true,
    timePickerSeconds: false,
    minDate: "04-Oct-2016 09:00 am",
    maxDate: "10-Nov-2016 05:00 pm"
});
```
After changing from "AM" to "PM", hours dropdown will still disabled 1-8 hours option, which should not be the case.

I think line1214 condition `&& min_hour < 12` should be deleted in the library.

**Comment by dangrossman** [comment]
Could not reproduce with the options provided.

<img width="324" alt="ss" src="https://cloud.githubusercontent.com/assets/407706/14124867/f5772132-f5d5-11e5-81d5-a065f6576be7.png">

**Comment by SlowburnAZ** [comment]
I'm experiencing this in version 1.3.23

```javascript
$('.daterange).daterangepicker({
  timePicker: true,
  timePickerIncrement: 30,
  format: 'MM/DD/YYYY h:mm A',
  startDate: moment('07/20/2017 12:30 PM'),
  endDate: moment('07/20/2017 8:00 PM'),
  minDate: moment('07/20/2017 6:00 AM'),
  maxDate: moment('07/20/2017 8:00 PM')
});
```

![image](https://user-images.githubusercontent.com/5659169/28435226-04450b54-6d47-11e7-8596-0145c53e989e.png)

As you can see, I can't select a time of 1, 2, 3, 4, or 5 PM

**Comment by dangrossman** [comment]
Your screenshot is from v1 of this library, which is over two years old.

**Comment by SlowburnAZ** [comment]
@dangrossman 
Yes, I know...  in the case that I can't change this version out, is there something I can do to fix this one issue?

**Comment by dangrossman** [comment]
Since it's open source code, you can find and fix the bug. Nobody else is going to do it, sorry.

**Comment by SlowburnAZ** [comment]
Heh..  okay.  No problem.  Thanks.
