### ISSUE TITLE
Doesn't work with fastclick on iPad

### ISSUE THREAD

**Issue by Nevs08** [dangrossman/bootstrap-daterangepicker#1032]
Hi,

sorry for my bad English.

On iPad the daterangepicker doesn't work because of fastclick.

Does anyone had a solution for this?

Greetz from Germany,
Nevs08

**Comment by dangrossman** [comment]
I don't know what exactly this means, and I don't own an iPad to find out.

**Comment by virik** [comment]
We have the same problem.

When using Fastclick (https://github.com/ftlabs/fastclick) on iPad, the datepicker hides when we try to select a date. Does anyone know how to solve this?

Thanks.

**Comment by virik** [comment]
Compability with FastClick can be solved by adding "needsclick" class to the "prev", "next", "glyphicon" and "available" classes in daterangepicker.js.

Line 705:
html += '<th class="prev available needsclick"><i class="fa fa-' + arrow.left + ' glyphicon glyphicon-' + arrow.left + '" needsclick></i></th>';

Line 747:
html += '<th class="next available needsclick"><i class="fa fa-' + arrow.right + ' glyphicon glyphicon-' + arrow.right + '" needsclick></i></th>';

Line 841:
cname += 'available needsclick';
