### ISSUE TITLE
Add Composer package manager support.

### ISSUE THREAD

**Issue by pnikolov** [dangrossman/bootstrap-daterangepicker#1036]
I cannot find the package in http://packagist.org, it should be added manually via the packagist website.
A sample `composer.son` file contents should be:

```js
{
    "name": "dangrossman/bootstrap-daterangepicker",
    "type": "component",
    "description": "Date range picker component for Bootstrap",
    "license": "MIT",
    "authors": [
        {
          "name": "Dan Grossman",
          "email": "dan@dangrossman.info",
          "role": "Author"
        }
    ],
    "require": {
      "components/jquery": ">=1.10",
      "moment/moment": ">=2.9.0"
    }
}
```

After having this file, it should be registered manually in https://packagist.org/packages/submit

_Note:_
Also you can consider adding `components/bootstrap` as a recommended dependency if applicable.

**Comment by dangrossman** [comment]
This is not a PHP library.

**Comment by pnikolov** [comment]
Composer is not used only for a PHP libraries, it is a standard package manager.
