### ISSUE TITLE
isInvalidDate still allows me to future dates

### ISSUE THREAD

**Issue by LasseRafn** [dangrossman/bootstrap-daterangepicker#1038]
When I use isInvalidDate, I can still pick dates AFTER the invalid date, within my range. Is this normal?

I just tried to make some random invalid dates to test.

````
isInvalidDate: function (date) {
	return (Math.random() * 10) >= 3;
}
````

Screenshot: http://dsh.re/fe604

I want to restrict so I'm not able to select forward from the invalid dates, as I do not want invalid dates in my range. Any solutions?

**Comment by JaapMoolenaar** [comment]
I came here looking for this too. Sadly, that's not how the invalid date function works.
However, I made a fork and added an option "selectPastInvalidDate". Setting this to false should prevent selecting past the first date returned by isInvalidDate as true.

I hope you (and others?) wouldn't mind testing what I have too, and see if this is a viable option.
https://github.com/JaapMoolenaar/bootstrap-daterangepicker

**Comment by LasseRafn** [comment]
Oh, I sadly thought so!.. 

Thanks, I'll give it a shot! I've looked at it and, after a quick glance it appears that it should work as expected. I'll pull it to my local server and play with it before I use it in production. I'll report any problems that might occur :+1:

**Comment by JaapMoolenaar** [comment]
Great thanks!

I actually just pushed an update for adding extra classnames for certain dates, and uploaded a demo showing both new features to http://jaapmoolenaar.github.io/

**Comment by deepakgd** [comment]
` "isInvalidDate": ["05/19/2016","05/20/2016"]` Is It right? For me its not working can you please share some example

**Comment by dangrossman** [comment]
No, `isInvalidDate` is a function, not an array of strings.

**Comment by JaapMoolenaar** [comment]
Yes, it's a function like @dangrossman said, so in your case -if you want to use an array- you could do something like this:

```
isInvalidDate: function (date) {
    var formatted = date.format('MM/DD/YYYY');

    return ["05/19/2016","05/20/2016"].indexOf(formatted) > -1;
}
```

**Comment by deepakgd** [comment]
thaks @dangrossman my issue fixed

**Comment by dangrossman** [comment]
Thanks for the comments. Currently this option is good for disabling individual dates in a single date picker, and there is no code that prevents selecting a range that includes those dates in range mode. I would take a pull request that does that (and only that), similar to what @JaapMoolenaar did, if anyone cares to submit one in the future.

**Comment by bradleykins** [comment]
How do you pass this stuff to a non inline function?
{
    isInvalidDate: checkDates(???)
}

function checkDates(date) {
    var formatted = date.format('MM/DD/YYYY');

    return ["05/19/2016","05/20/2016"].indexOf(formatted) > -1;
}

?

**Comment by dangrossman** [comment]
```
var checkDates = function(date) {
    var formatted = date.format('MM/DD/YYYY');
    return ["05/19/2016","05/20/2016"].indexOf(formatted) > -1;
}

$(el).daterangepicker({
  isInvalidDate: checkDates
});
```

**Comment by dauni** [comment]
Not preventing the selection of dateranges over a forbidden date, but setting the MaxDate to forbidden date minus 1 day.
`dates.disabled` holds the array with forbidden dates.

```javascript
$('input[name="daterange"]').daterangepicker({
        option: value,
        isInvalidDate: function (date) {
            var formatted = date.format('YYYY-MM-DD');
            return dates.disabled.indexOf(formatted) > -1;
        }
    }).on('apply.daterangepicker', function (ev, picker) {
        dates.disabled.forEach(function (disdate) {
            if (picker.startDate.format('YYYY-MM-DD') < disdate && picker.endDate.format('YYYY-MM-DD') > disdate) {
                let day = moment(Date.parse(disdate)).subtract(1, 'days');
                picker.setEndDate(day);
            }
        });
    });
```

If I add to daterangepicker.js
```javascript
clickDate: function(e) { //Line 1300
...
...
this.element.trigger('clickRange.daterangepicker', this); //Line 1370
},
```
I can use `clickRange` as event instead of `apply` and if I add `picker.updateView();` after `picker.setEndDate(day);` my picker selects only a daterange till a forbidden date minus 1 day

**Comment by fayiza** [comment]
> Great thanks!
> 
> I actually  #just pushed an update for adding extra classnames for certain dates, and uploaded a demo showing both new features to http://jaapmoolenaar.github.io/



> Oh, I sadly thought so!..
> 
> Thanks, I'll give it a shot! I've looked at it and, after a quick glance it appears that it should work as expected. I'll pull it to my local server and play with it before I use it in production. I'll report any problems that might occur 👍
