### ISSUE TITLE
Set default range

### ISSUE THREAD

**Issue by PierceMcGeough** [dangrossman/bootstrap-daterangepicker#1040]
Is it possible to set the default range?

If i set custom dates from the input value it will show that it is custom dates even though it is the last 7 days.

```
ranges: {
   'Today': [moment(), moment()],
   'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
   // i want last 7 days as default
   'Last 7 Days': [moment().subtract(6, 'days'), moment()],
   'Last 30 Days': [moment().subtract(29, 'days'), moment()],
   'This Month': [moment().startOf('month'), moment().endOf('month')],
   'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
}
```

**Comment by dangrossman** [comment]
If your startDate and endDate match one of the predefined ranges, it will be highlighted. Your input must not match the "last 7 days" dates. You do not have to do anything to get this behavior, it is what's programmed.

**Comment by malle-pietje** [comment]
also important to understand is that when you have defined start/end of your default somewhere else, you need to reference those variables in "ranges" and not calculate them again. There will always be a slight difference in moment() which will show when the pull-down of the picker shows "custom range" as selected. Hope this make sense...

**Comment by dangrossman** [comment]
If you're not using the time picker, that's not the case, since only the date portion of the selection/ranges is compared.

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L1323

**Comment by malle-pietje** [comment]
Correct, I should've added that note.

**Comment by PierceMcGeough** [comment]
Thanks I see now what the error was. On setting the date via php ('7 DAYS AGO') it went back 7 days but didn't include today as the first of those 7 and made it 8 days in total

**Comment by malle-pietje** [comment]
I can recommend Carbon for PHP; it's syntax/feature set is quite similar to moment.js.

**Comment by ChezRD** [comment]
> moment() will be equal to moment() regardless of the exact millisecond they're initialized
nope. sometimes don't, espetially when by default comparsion in miliseconds
https://github.com/moment/moment/blob/develop/moment.js#L2112
pull request to fix some issues caused by lag of browser
#1045

**Comment by dangrossman** [comment]
I'm not comparing moment objects directly. It would not be affected by that bug.

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L1335
