### ISSUE TITLE
If using "Tab" to move to already populated daterange picker with time, time is reset to 0

### ISSUE THREAD

**Issue by birdy247** [dangrossman/bootstrap-daterangepicker#1041]
If a user has already selected a date & time on an input (which is a daterange timepicker field), and then they use the "tab" key to navigate to the field again, time in the dropdown is reset to 0.

.daterangepicker({
            "singleDatePicker": true,
            "timePicker": true,
            "timePicker24Hour": true,
            "autoApply": true,
            "locale": {
                format: 'DD-MM-YYYY'
            },
            "autoUpdateInput": false
        });

**Comment by dangrossman** [comment]
I don't know the reason for that. A PR fixing it would be accepted if you'd like to investigate.

**Comment by bmyrtil** [comment]
Was this issue ever resolved. Took me a while to track it down but this is the exact issue I am experiencing.
