### ISSUE TITLE
two digit date should be interpreted as current millennium (and century) 20xx not 00xx 

### ISSUE THREAD

**Issue by c4blackarrow** [dangrossman/bootstrap-daterangepicker#1042]
When typing 2/2/16 the date is interpreted as 02/02/0016.  The likelihood that the majority of users intend to enter the first millennium is extremely low.  The auto format should be smart enough to enter in 20 in front of the two digit date, as this meets the users expectations.

If you want to get overly fancy, or are worried this will not work in the year 2100 you can future proof it by look up the current year and use the first two digits to auto complete the entry (or first digit if they entered 2/2/102) Though I think you are safe deferring that particular functionality to the year 2099.

**Comment by dangrossman** [comment]
Feel free to submit a PR that accomplishes this.
