### ISSUE TITLE
Using the mouse, the user cannot set a new end date without reselecting the start date

### ISSUE THREAD

**Issue by c4blackarrow** [dangrossman/bootstrap-daterangepicker#1043]
When using the widget to adjust the date, the user can not set a new end date without reselecting the start date first.  Clicking into the end date field does not get interpreted by the widget as wanting to edit that date (or rather skip changing the start date), and that any subsequent click on the calendar should adjust the end date rather than setting a new start date.

This is particularly confusing because the default CSS has a blue highlight (at least in chrome) and is editable via typing.  This gives the user the expectation that they are editing the end date, however clicking edits the start date (which also has a blue highlight showing that to the widget it is the active field, but this is easy to overlook do to the blue glow on the focused end date field)

This is a common use case where the user may want to shorten or extend an event without changing when that event starts.

To support this change In auto apply mode, users skipping to the end field and then selecting a new end date should interpret as having finished their data entry and commit the change.

**Comment by dangrossman** [comment]
Feel free to submit a PR with your desired changes.
