### ISSUE TITLE
undefinedInvalidDate

### ISSUE THREAD

**Issue by dmironov0** [dangrossman/bootstrap-daterangepicker#1044]
Hi, I'm having a specific problem when **sometimes** I instantiate the plugin.

Let me show you a picture

![undefinedinvaliddate](https://cloud.githubusercontent.com/assets/7450379/14387780/568de4b2-fd81-11e5-97ee-4505d926a047.png)

This **only** happens when I'm developing at my local environment and happens just **sometimes**, and does not happen when I publish the app to an internet server

I haven't tested the datetime full time in the server so I don't know if the issue can possible be replicated on the server.

But, maybe is something with my local environment/os/local times?

This is how I'm instantiating it:
![code](https://cloud.githubusercontent.com/assets/7450379/14388014/60d0738a-fd82-11e5-8926-bfa7d27a4520.png)

Hope you could help me! And just for you to know, this plugin es **extremely, extremely good**

Thanks!

**Comment by nip3o** [comment]
I experience this when explicitly specifying `startDate: null`. Not setting any value for `startDate` at all works fine for me at least.

**Comment by dangrossman** [comment]
This library requires a valid startDate and endDate at all times. If you don't provide a value, it will default to today's date. "null" is not a valid value for this option.

**Comment by dmironov0** [comment]
Thanks guys, believe it or not, I was using at all times as 'startDate': moment(). I don't know how happened that in the screenshot, I can assume I was testing.
But right know I double checked and mi startDate is moment().

So really I don't know what is happening, because as I said before, it doesn't happen always, it happens sometimes. To try to test I refresh the browser with CTRL+F5 but sometimes it works, sometimes it doesn't. And I try the page in other browsers too, and the same happens.

So, still with no luck in knowing exactly what is happening!

Thanks guys!

**Comment by dangrossman** [comment]
You have `startDate: null` in your screenshot of the options you're using.

**Comment by dmironov0** [comment]
Yes yes, in the screenshot I have `startDate: null ` but **I changed it** to `startDate: moment()`
