### ISSUE TITLE
When using with bootstrap tooltip - tooltip is broken

### ISSUE THREAD

**Issue by telbiyski** [dangrossman/bootstrap-daterangepicker#1049]
for example:
<button class="btn btn-default" data-toggle="tooltip" title="date range" id="rangepicker">
<i class="fa fa-calendar"></i>
</button>

tooltip working with version 1.3.21
tooltip not working with latest version (2.1.19)

**Comment by dangrossman** [comment]
Feel free to investigate and submit a PR if it won't break anything else.
