### ISSUE TITLE
Want drops to 'left' or 'auto'

### ISSUE THREAD

**Issue by anupalusoft** [dangrossman/bootstrap-daterangepicker#1050]
Hi,

I want the daterange picker to opens in `left` of the input or `auto` adjust to the element view port.
I have a div which scrolls and in fixed position. I am not having that much space to show below daterange picker so bottom won't shows if I reach to end of the div and input is placed there. Also if its possible to stick the daterangepicker with the input position so that if input goes up with scrolling of div then picker also follows. 

So how can i do this?

**Comment by dangrossman** [comment]
You would have to program this yourself.

**Comment by anupalusoft** [comment]
@dangrossman How can I do and with what method ?
Would really help if you give me any fiddle or example. :)

**Comment by dangrossman** [comment]
There is no existing code that does what you want. You would have to write it.

**Comment by tihoho** [comment]
Dan, it's problem actually. I need automatical detect opens side (left or right) because I have a dynamic content, and I don't know how made dynamic detect side to open calendars. (excus for my english)
