### ISSUE TITLE
Auto drops orientation

### ISSUE THREAD

**Issue by EduardoMiguelCruz** [dangrossman/bootstrap-daterangepicker#1053]
`daterangepicker({
                    "orientation": "auto",
                    "timePicker": true,
                    "timePicker24Hour": true,
                    "startDate": "04/11/2016",
                    "endDate": "04/17/2016",
                }, function (start, end, label) {
                    console.log("New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')");
                }).on('showCalendar.daterangepicker', function (ev, picker) {
                    if (picker.element.offset().top + picker.container.outerHeight() > $(window).height()) {
                        picker.drops = 'up';
                    }
                    else {
                        picker.drops = 'down';
                    }
                });`

**Comment by lacco** [comment]
Thx for providing this snippet! I need to change the callback function a little bit to support scrolling:

```
$picker.on('showCalendar.daterangepicker', function(ev, picker) {
  if (picker.element.offset().top - $(window).scrollTop() + picker.container.outerHeight() > $(window).height()) {
    return picker.drops = 'up';
  } else {
    return picker.drops = 'down';
  }
});
```

**Comment by poradz** [comment]
In the latest version triggering move() function is needed, so it goes like this:

`$picker.on('show.daterangepicker', function (ev, picker) {
					if (picker.element.offset().top - $(window).scrollTop() + picker.container.outerHeight() > $(window).height()) {
						picker.drops = 'up';
					} else {
						picker.drops = 'down';
					}
					picker.move();
				})`

**Comment by H0w4rd** [comment]
Thank you. But I had to modify your version, I needed to add +30, because sometimes the picker was opening down and the buttons were out of visible area and I had to scroll down the whole page.
My version:
`picker.drops = (picker.element.offset().top - $(window).scrollTop() + picker.container.outerHeight() + 30 > $(window).height()) ? 'up' : 'down';`
