### ISSUE TITLE
singleDatePicker without an initial date

### ISSUE THREAD

**Issue by parker789** [dangrossman/bootstrap-daterangepicker#1056]
Hey Dan, 

I've looked around on here trying to find a solution to my problem, and have checked few different issues i thought were around the same idea, specifically #815 . I have the datepicker set using the code below, and all works.. but upon initialization the opened date picker displays the current date as already selected, so i can't select the current date.

```
$('#datepicker1').daterangepicker({
  singleDatePicker: true,
  autoUpdateInput: false,
}, function(date) {
  $('#datepicker1').val(date.format());
});
```
![screen shot 2016-04-19 at 8 53 59 am](https://cloud.githubusercontent.com/assets/4635313/14639777/52960e8c-060c-11e6-963d-a1c2103852d9.png)

**Comment by dangrossman** [comment]
This library does not support "no selected date". There is always a selected date. If you don't specify one via `startDate`, it will default to today's date. If you want a single date picker without a selection, you will want to choose a different library.

**Comment by parker789** [comment]
Thanks for the speedy reply, I was beginning to think that was the case.

**Comment by rmm5t** [comment]
@dangrossman Might a reasonable solution just be to allow the `callback` to be called if the selected date is the same as the currently selected date (well, that combined with `autoUpdateInput: false`)?

Right now, the `callback` is ignored if the same date as `startDate` is selected.

**Comment by rmm5t** [comment]
For future onlookers, here's another solution to this problem (use the `apply.daterangepicker` event to workaround the current known limitations of singleDatePicker usage):
https://github.com/dangrossman/bootstrap-daterangepicker/issues/815#issuecomment-220874445

**Comment by BohdanZhmud** [comment]
There is also a case when user manually inputs some incorrect value. Currently single datepicker applies previous date, but with empty intial value example provided in documentation it does not work this way. You may use 'hide.daterangepicker' to change value of input control using picker.startDate to workaround this limitation.

**Comment by yanup2913** [comment]
mmmmmmmmmmmmmmmmmmmm
