### ISSUE TITLE
Custom time range with group

### ISSUE THREAD

**Issue by Pantela777** [dangrossman/bootstrap-daterangepicker#1057]
I have hotel website, and want to add booking system. I use **bootstrap-daterangepicker** and think work nice, but can I add custom time range with group (Exp. http://i.imgur.com/78ihusE.png )

**Comment by dangrossman** [comment]
I have not programmed something like that. You would have to make it yourself.

**Comment by Pantela777** [comment]
I understand, but maybe you can tell me how I can do it...
Which of option/method...?

Thx.

**Comment by dangrossman** [comment]
There is no option or method that would create that interface. It doesn't exist except in your screenshot. You have to make it.
