### ISSUE TITLE
Custom month name in ranges

### ISSUE THREAD

**Issue by Niahm** [dangrossman/bootstrap-daterangepicker#1059]
i'm trying to show last month name

```
var lastMonthName = moment().subtract('month', 1).format('MMMM'); //March

$.ranges =  {
       lastMonthName : [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
 };
```
it shows **lastMonthName**  instead of **March**, any idea ?

**Comment by dangrossman** [comment]
This is just a JavaScript syntax question, not a date range picker issue.

    ranges[lastMonthName] = [moment...
    $.ranges = ranges
