### ISSUE TITLE
no format for start and end date separately

### ISSUE THREAD

**Issue by AlexCppns** [dangrossman/bootstrap-daterangepicker#1061]
I am having trouble separating the start and end date formats. What I want in practice is:

Apr 20 - Apr 21, 2016 if there is only one year and Apr 10, 2016 - Jan 6, 2017 if there are several years.

**Comment by dangrossman** [comment]
I recommend you set `autoUpdateInput: false` so that you can write your own code to display the selected dates in your webpage in whatever format you want. There's nothing in this library that will do what you want for you.

**Comment by AlexCppns** [comment]
Ok thanks.
