### ISSUE TITLE
In Predefined Ranges example, cannot pick Today

### ISSUE THREAD

**Issue by gjsmith66** [dangrossman/bootstrap-daterangepicker#1062]
We discovered this on our site today, but it is also present in the Predefined Ranges example posted here.  When first loading page, if you click on date range to get your choices, and then click on Today, nothing happens.  However, if you click tomorrow, you can then choose today after that.  This is an odd one, and after using DateRangePicker for the last three years with this behavior, a user just discovered it.

Thanks.

**Comment by dangrossman** [comment]
This is not a bug. Your callback function is invoked whenever the selected date range changes. Clicking "today" when it is already selected is not a change. Clicking "tomorrow" when today is selected is a change. So is going back to "today" after clicking "tomorrow". If you have not set an initial range when you created your picker the `startDate` and `endDate` will default to the current date (" today"!).

**Comment by gjsmith66** [comment]
Thanks for your quick response.  However, does this mean that your example "Predefined Ranges" has a bug?  If you click on the range and select Today, it does not do anything?  This is the same behavior that we are seeing (probably because this example is how I configured our date picker).  Using your example, what would you change to prevent this behavior?  

Thanks for your help!

**Comment by mrtristan** [comment]
Hey there, great library!

so if you take a peek here you can see an example of the problem: http://www.daterangepicker.com/#ex4

Your initial text of the button has something 'other than today' so clicking 'today' does nothing... The initial text of the button in my project is 'choose a date'.

it sounds like i would have to jump through a hoop or two to not have a predefined date. not to sound overly critical but that sounds like some missing capability there.

is there an approach you would advise taking to pull off what i'm looking to do?

Thanks again!

**Comment by dangrossman** [comment]
Just set a `startDate` and `endDate` that don't match one of your predefined ranges.
