### ISSUE TITLE
Moment issue makes bootstrap-daterangepicker unusable

### ISSUE THREAD

**Issue by jeffa87** [dangrossman/bootstrap-daterangepicker#1063]
Please see for details https://github.com/moment/moment/issues/3124

**Comment by dangrossman** [comment]
This is not bootstrap-datetimepicker (the thing being discussed at that link), it's bootstrap-daterangepicker.

**Comment by jeffa87** [comment]
More specifically read about it here http://stackoverflow.com/questions/36701138/moment-array-prototype-some-called-on-null-or-undefined When I do an npm install bootstrap-daterangepicker, there is a directory under bootstrap-daterangepicker with node_modules\moment. The moment.js file in there is being used and that's 2.13 and it causes problems. If I copy the one from bootstrap-daterangepicker into the node_modules\moment directory then everything works fine.

**Comment by dangrossman** [comment]
What do you want me to do about it? 

Isn't the only solution to this for you, as someone using both things in your project, to use the same version of moment in both places?

**Comment by jeffa87** [comment]
If I do an npm install bootstrap-daterangepicker outside of the area where our project resides, it will install moment 2.13 in the node_modules directory under bootstrap-daterangepicker. It's not caused by our project. Maybe I'm not understanding something correctly but it appears that it tries to use 2.13. It's only been a problem for us since moment released 2.13

**Comment by dangrossman** [comment]
Everything you've linked says the problem only exists where you create a moment object with a pre-2.13 version of moment.js, then pass that object to moment 2.13. This requires having two copies of moment.js in your project. This will not be the case if you were only using bootstrap-daterangepicker and its copy. There is no issue with this library or moment 2.13, only when you do that passing of objects between different versions.

**Comment by jeffa87** [comment]
Ok, I think I understand the issue that I have. Since we use an earlier version of moment in our project that's the issue like you said.  Because of the way bootstrap-daterangepicker defines moment like     "moment": "^2.9.0" in package json, 2.13.0 is downloaded. Just out of curiosity, wouldn't defining it as     "moment": "2.9.0" prevent issues like this from happening? Sorry about the issue opened, just trying to understand what was breaking.

**Comment by dangrossman** [comment]
There is no hard dependency on the specific version 2.9.0 so I would not write that. ^2.9.0 means that version or newer 2.x.x, which accurately describes the dependency.

**Comment by jeffa87** [comment]
Had it been defined as 2.9.0 I believe it wouldn't cause an issue. Basically 2.13.0 of moment is not compatible with any previous version of in 2.x.x so they really screwed up.

**Comment by dangrossman** [comment]
I think what's screwed up is including multiple copies of a date manipulation library in one codebase, and passing objects between them. Your project is what's screwed up, not the moment library. It is not a reasonable expectation for anyone to do that, or for them to write code to handle that.
