### ISSUE TITLE
Positioning when drops is up

### ISSUE THREAD

**Issue by askanhan** [dangrossman/bootstrap-daterangepicker#1064]
If you change "drops" property to "up" to open daterangepicker on top of input label, the dialog is shown at the first click correctly. Later, if you click again, the dialog is opened at the top of page, or very far from the input label.

So, i can not use the property "drops" effectively.
![drp](https://cloud.githubusercontent.com/assets/5607648/14770732/c8ca2f5a-0a78-11e6-84db-4eb127521aee.PNG)

**Comment by dangrossman** [comment]
It works correctly at http://www.daterangepicker.com/#config

I can't help you with just a screenshot

**Comment by dangrossman** [comment]
Closing due to no followup
