### ISSUE TITLE
End Time Being selected on its own In Reference to #1065

### ISSUE THREAD

**Issue by loushps** [dangrossman/bootstrap-daterangepicker#1067]
in Reference of issue that was closed due to no Follow Up #1065
here is my follow up.

1) Choose 26 April as a start date By clicking on 26 April 2016
2) Hover over  1 April by moving the cursor to 1 April 
(You will see that the End Date have taken the Value 1 April 2016)
3) Don't Click on 1 April, Instead go to the Start Date Time textbox and change 2016 to 2015 and click on Enter

Now Check the End Date Time, it selected the Value 1 April 2016 without the user's intervention, it considered the value of the last Cursor hover location on the calendar to be the End Date 

You may Check the Gif for better illustration 
![issue1](https://cloud.githubusercontent.com/assets/18657898/14814281/54afdf66-0bae-11e6-9bf5-07694f958f9a.gif)

**Comment by dangrossman** [comment]
Yes, that bug exists. Feel free to try to fix it (without breaking the ability to type dates, or to hover over them and see their values in the inputs) and submit a PR.
