### ISSUE TITLE
You must create a separate option 'Inialize Date on start' instead of 'autoUpdateInput'

### ISSUE THREAD

**Issue by gtzinos** [dangrossman/bootstrap-daterangepicker#1072]
You must create a separate option 'Inialize Date on start' instead of 'autoUpdateInput', because someone needs autoupdate function but not the auto inialization.

**Comment by gtzinos** [comment]
For now, we must bind an onclick event on apply button to update the value back to the parent element. You can make it more flexible.

**Comment by dangrossman** [comment]
The date range picker has an apply event you can listen for to update your page. You don't have to bind to the button yourself. It's in the documentation under "events". Alternatively, you can leave `autoUpdateInput` on and clear your element after initializing the picker. Another option is not needed.

**Comment by gtzinos** [comment]
Yes, we can bind the apply event, but into this event how can we retrieve the selected values ? 

      $('#datepicker').on('apply.daterangepicker', function(ev, picker) {
          //$('#datepicker').val("start date - end date);
      });

**Comment by dangrossman** [comment]
There is example code in the documentation.

http://www.daterangepicker.com/#events

**Comment by gtzinos** [comment]
Oh thank you very much.
