### ISSUE TITLE
How to retrieve selected values into apply event ?

### ISSUE THREAD

**Issue by gtzinos** [dangrossman/bootstrap-daterangepicker#1073]
Yes, we can bind the apply event, but into this event how can we retrieve the selected values ?

    $('#datepicker').on('apply.daterangepicker', function(ev, picker) {
        //$('#datepicker').val("start date - end date"   
    });

**Comment by juliomac** [comment]
You can get it through:

        var StartDate = new Date($('#dateRange').data('daterangepicker').startDate);
        var EndDate = new Date(new Date($('#dateRange').data('daterangepicker').endDate).setHours(0,0,0,0));

Notice that I added ```setHours(0,0,0,0)```  so it returns the Date with time set on 00:00:00.00 rather than 23:59:59.99. This is useful for querying data on MongoDb, for instance.

**Comment by dangrossman** [comment]
It's in `picker.startDate` and `picker.endDate`, per the example at http://www.daterangepicker.com/#events

**Comment by gtzinos** [comment]
Ok thank you !!!
