### ISSUE TITLE
Better interaction of "input initially empty" (e.g. no filter) and predefined ranges

### ISSUE THREAD

**Issue by denishaskin** [dangrossman/bootstrap-daterangepicker#1074]
We use predefined ranges, but the default display of our data is All Dates (e.g. no date filter applied).  

Ideally after the page is initially displayed, if the user clicked on our date filter button DateRangerPicker would display, with the list of predefined ranges and 'Custom Range' and no calendar being shown until 'Custom Range' is clicked.

However, because we initially have no start or end dates defined (e.g. no filter in place), when DateRangePicker is shown it defaults start+end dates to today, doesn't match any of the predefined ranges, and so selects 'Custom Range' and shows the calendar right away.

(I can sort of avoid this by adding a predefined range of "Today", but that date range doesn't make sense in our application.)

I can also almost sort of work around it by adding an event listener on `show.daterangepicker` and setting the start and end dates to one of the ranges, but there seems to be a timing issue and tihs is only set the second time the daterangepicker is shown, and at that point it seems to think it has to show the calendar.

Ideally, if start and end date aren't set but there are predefined date ranges, when DateRangePicker is shown it would not show the calendar and would not default to selecting any of the predefined ranges (nor the Custom Range selection).

**Comment by dangrossman** [comment]
Set the start and end dates (`startDate` and `endDate` options) to match one of the predefined ranges when you create the date range picker, not later when it's shown.

**Comment by denishaskin** [comment]
That worked, thank you.  I think I hadn't gone that path as I thought it was hard in our app to determine one of the predefined ranges at that point, but it was actually pretty easy.

**Comment by zschiffelbein** [comment]
Is there a way to have the date range picker default with no value (or All Time)? I am using the it as a filter and would prefer to default the filter with no value and then allow the user to select "Today". Currently the plugin believes that Today is already selected so it requires the user to click to a different range and back to Today.
