### ISSUE TITLE
Calendar is not well rendered in firefox

### ISSUE THREAD

**Issue by rbecheras** [dangrossman/bootstrap-daterangepicker#1076]
- In chrome : http://postimg.org/image/ylrrubua1
- In firefox : http://postimg.org/image/4id92dr0p

> I come from https://github.com/luisfarzati/ng-bs-daterangepicker/issues/65

**Comment by dangrossman** [comment]
Two things:

(1) There's no such rendering problem in Firefox. Here's a screenshot from the same page:

<img width="482" alt="ss" src="https://cloud.githubusercontent.com/assets/407706/15017476/c16898d8-11e3-11e6-8ec9-e68c3c39e50d.png">

I would guess you have some plugin/extension blocking a stylesheet from loading, or customizing the page CSS?

(2) That fork is based on v1 of this library, which was replaced by v2 a year ago. It's dozens of releases behind.

**Comment by rbecheras** [comment]
Ok so it's my bad, sorry
