### ISSUE TITLE
JQuery Validator using Tooltip -- breaks and tries to use the calendar as the tool tip.

### ISSUE THREAD

**Issue by ElleRae** [dangrossman/bootstrap-daterangepicker#1082]
Please see the attached document for screenshots.  The issue is that on the datepicker fields I use validation and a tool tip when the input is invalid or non-existent and the field is required. Unfortunately the datepicker seems to be highjacking the tooltip ID and code and is breaking the tooltip.

Can you please tell me what needs to be done to fix this?

[jqueryvalidatorerror.docx](https://github.com/dangrossman/bootstrap-daterangepicker/files/262487/jqueryvalidatorerror.docx)

**Comment by dangrossman** [comment]
There is no special tooltip hijacking code, and I don't know what combination of things you're using to try to reproduce this. I'm not going to download and open a Word document from a stranger on the internet, sorry. That's how people get malware.

**Comment by ElleRae** [comment]
Wow, you could have asked me to upload the images instead.  I already consulted with the developer of the validation plugin and he said this was an issue with your datepicker, which was confirmed by another thread that you closed without any answer.  Very disappointing behavior.
