### ISSUE TITLE
DD/MM/YYYY doesn't work when I use keyboard

### ISSUE THREAD

**Issue by abelondev** [dangrossman/bootstrap-daterangepicker#1083]
I create a picker like this:
   $('input[name="dataOn"]').daterangepicker({
			        singleDatePicker: true,
			        showDropdowns: true,
			         locale:{
				format: 'DD/MM/YYYY',
				},
			    }, 

But when I type it still use 'MM/DD/YYYY' format but when I select it uses  'DD/MM/YYYY'

**Comment by dangrossman** [comment]
I could not reproduce this. I used your code and typed "01/12/2016" in the input, and December 1 2016 was selected in the calendar.
