### ISSUE TITLE
Cannot update end date w/out start date resetting

### ISSUE THREAD

**Issue by raydawg2000** [dangrossman/bootstrap-daterangepicker#1084]
What setting do i have to configure to be able to only update the end date?  Currently when I change the end date the start date also gets reset and I basically have to redo the whole date range selection.  This is not ideal especially when the dates are far apart

1.  Open date range
2. Select new end date
3. Start date also gets reset
4.  Must redo date range selection to be able to apply changes.

![animation](https://cloud.githubusercontent.com/assets/14985776/15257728/8d49c37c-18fc-11e6-9227-0e22005dc912.gif)

**Comment by dangrossman** [comment]
Whether you're selecting a start or end date of a range is determined by the order of clicks, not which calendar you click on. The first date you click is the start of a new range, and the second date is the end, which completes the selection. There is no setting that changes this behavior.
