### ISSUE TITLE
Firefox only : Time selects don't work when calendar is triggered from a partial.

### ISSUE THREAD

**Issue by kiwipal** [dangrossman/bootstrap-daterangepicker#1086]
In firefox, when you load a partial using underscoreJS template system, and then assign a calendar to an element added to the dom from the partial, everything is correct, but clicking on the time selector do not show the options list.

This is maybe a Firefox DOM bug, because it doesn't occur with oher major browsers, including IE, Chrome...

Please notice that it is not a css problem. I tried removing them without fixing the bug.
The same calendar works well outside of partials.
I also tried to remove all parameters without success.

An finally, I tested with different version of your calendar script.

To give you some ideas, I tried to use JS to show the select list (it is possible actually, to simulate the user click)... and it fails.

Assigning a select2js on the time select work, but it breaks your script with all dates turning to NaN.

Curious.
If you have the courage, please have a look :-)

**Comment by dangrossman** [comment]
I have no time to investigate bugs, but pull requests fixing them do get merged eventually.
