### ISSUE TITLE
Suggestion: Option to use old date selection mode

### ISSUE THREAD

**Issue by JustASquid** [dangrossman/bootstrap-daterangepicker#1094]
In recent versions of the date range picker, the startdate and enddate are selected by alternating clicks.

Previous versions of the picker had a different method of selecting dates - the left panel was reserved for the start date, and the right panel was reserved for the end date.

![The old date range picker](http://i.imgur.com/JXPNomn.png)

The new method definitely feels more intuitive to a new user, however the old method is generally faster to use, as you can change the start date and end dates independently, without having to repick the entire date range.

We've recently upgraded to the latest date range picker, and many of our users have reported productivity losses due to the new method - our app requires heavy use of this picker in certain areas, and every extra click is wasted time.

It would be valuable for an option to exist which can enable the calendar to use the old ('left-right') instead of the new ('flexible') method.

**Comment by dangrossman** [comment]
I would recommend you continue using the version that works the way your users want. Just because there's a newer one doesn't mean you have to use it.

**Comment by tapia** [comment]
Downgrading to an older version isn't always a good idea. There are lots of bugfixes and additional features that we'd like to keep. It would be really great having this feature back 😊

**Comment by JustASquid** [comment]
I tend to agree with @tapia on this one. Plus, one of the reasons we upgraded was for bootstrap 3 support, which the old version doesn't have (AFAIK).

**Comment by tapia** [comment]
@JustASquid: just FYI (And sorry for the off-topic), version 1.3.x, which has the old calendar behaviour, has indeed support to bootstrap 3. Just use the included `daterangepicker-bs3.css` css file.

**Comment by JustASquid** [comment]
Thanks @tapia, I didn't know that! I'll look into it. However I still agree with your original sentiment that downgrading isn't a good solution to this problem. It's only a matter of time until we need a new feature or bugfix, then we're stuck.
