### ISSUE TITLE
when i click the right calendar the left value also changed ? 

### ISSUE THREAD

**Issue by 0704681032** [dangrossman/bootstrap-daterangepicker#1099]
![image](https://cloud.githubusercontent.com/assets/3282178/15696233/23c1a9d0-27e1-11e6-90d6-b399fc1e2c88.png)
how can i prevent this ? i hope it can behave like this : when i click left only left value changed

just as follows:  the two calendar behaves alone and donot affect others 

![image](https://cloud.githubusercontent.com/assets/3282178/15696247/45a9e878-27e1-11e6-9bce-3fe643f531b1.png)

**Comment by dangrossman** [comment]
Your first click is the start of the date range you're selecting, your second click is the end of the range. It does not matter which calendar you click on for either selection. This cannot be changed.
