### ISSUE TITLE
Improve Documentation Of Methods

### ISSUE THREAD

**Issue by davidklebanoff** [dangrossman/bootstrap-daterangepicker#1101]
I discovered that there are some useful methods, such as `toggle()` and `remove()`, that are available but were not documented [in the docs](http://www.daterangepicker.com/#methods).

**Comment by dangrossman** [comment]
They are not meant to be part of the public API. They just exist to make the internals more organized.

**Comment by davidklebanoff** [comment]
Ah, understood. Well, I invite you to consider adding such methods to the public API as they are very useful.
