### ISSUE TITLE
Same month selection in left and right calendar results in a weird UI.

### ISSUE THREAD

**Issue by System64** [dangrossman/bootstrap-daterangepicker#1109]
Hi,
with this configuration
 **"showDropdowns": true,
    "linkedCalendars": false,** 
same month can be selected from both left and right calendar, which results in a little weird UI, have a look at the screenshot. Same month is selected in left and right calendar.
![screen shot 2016-06-07 at 7 41 24 pm](https://cloud.githubusercontent.com/assets/3858750/15860953/b0557712-2ce8-11e6-92c3-fb599b64848b.png)

It would be better if same month is also disabled in the right calendar, like when June is selected in left calendar, right calendar month dropdown has months disabled upto June, it should be including June.
For December it should show, January of the next year.

**Comment by dangrossman** [comment]
It's not weird to see June on both sides when you explicitly went and asked to see June on both sides, after the website owner disabled the setting that would prevent June from being on both sides (linkedCalendars).

**Comment by Trainmaster** [comment]
@dangrossman The point is that one shouldn't be allowed to see June on both sides. Imho it doesn't make sense. Or is there a specific use-case you can think of?

Enabling 'linkedCalendars` isn't always a solution because it forces the months to be sequential.
