### ISSUE TITLE
Date more than right calendar can be selected in the left calendar

### ISSUE THREAD

**Issue by System64** [dangrossman/bootstrap-daterangepicker#1110]
with this configuration 
`"showDropdowns": true,
"linkedCalendars": false`
 Select start date from the right calendar, from the left calendar change the month dropdown to a month greater than month selected in right calendar. Now, the end date can be selected from left calendar which is greater than right calendar. Although value updated in the input box are always correct, this is little weird from UI perspective. 
Have a look at the screenshot
![screen shot 2016-06-07 at 7 42 04 pm](https://cloud.githubusercontent.com/assets/3858750/15861639/82a2ecc6-2cea-11e6-8865-8ff176c21330.png)

I think this case is not handled, it could be handled in a similar way as handled, when the start date is selected from right calendar, say 1st January, 2016 and then, month is changed from month dropdown of right calendar to say march, and end date is selected as 2nd March, 2016. After the selection updated UI shows, 1st January, 2016 in the left calendar and 2nd March, 2016 on the right calendar.

**Comment by dangrossman** [comment]
I have minimal time to spend on this 4-year-old side project, so I do not take feature requests. Please open an issue only if there is a bug that needs to be fixed.

**Comment by System64** [comment]
@dangrossman: thanks for writing this plugin, but i guess this is an issue needs to be fixed, if you get time or can you please keep it open, So that someone else might fix it.

**Comment by dangrossman** [comment]
I'm not convinced this is an issue that needs to be fixed. If you want to prevent the user from choosing non-chronological months in the UI, leave `linkedCalendars` turned on.

**Comment by System64** [comment]
Yeah, its absolutely true.
I could use linkedCalendars: true, but again they gets confused with linked calendar as after end date selection if it is more than a month, since its a linked calendar, start date is visible on the UI, and the end date is not, so this create confusion for them.
![screen shot 2016-06-08 at 12 26 03 am](https://cloud.githubusercontent.com/assets/3858750/15870943/d9d7a5ac-2d0f-11e6-83b0-80593c7211ca.png)

To avoid this, I thought its better to keep the linkedCalendars: false, so that start and end date are visible to them, but again there are some corner cases with it. 
In term of functionality there is no issue, but its just some of the users are having a different feeling about it. If you can show me the direction, I could code it myself and make a pull request.
