### ISSUE TITLE
disable the date picker,but allow only the time picker

### ISSUE THREAD

**Issue by maczj** [dangrossman/bootstrap-daterangepicker#1113]
Can we use only the time picker or at least make user can change the date?

**Comment by dangrossman** [comment]
No. This request doesn't make sense. It's like buying a car because you want a clock. You don't need a big javascript library to choose just times. Just put a few `<select>` elements in your webpage.

**Comment by maczj** [comment]
Well.. you got the point there.. i think i need some sleep before i make some silly question again.. thanks man.. :))
