### ISSUE TITLE
End time dropdown is not updating when setting setEndDate() and then updateView()

### ISSUE THREAD

**Issue by gbsmit03** [dangrossman/bootstrap-daterangepicker#1114]
When I call 'picker.setStartDate(startDateTime);' and 'picker.setEndDate(endDateTime);' and then  'picker.updateView();' all the fields in the picker update with the correct information besides the end time drop down.

I checked the code and it looks like the renderTimePicker function is preserving the current time based on what is set the the drop down HTML. I'm a little confused on why it is being preserved and was wondering what issue was this fixing?

**Comment by dangrossman** [comment]
`updateView()` is not part of the public API. You should not be calling it from your code.

**Comment by dangrossman** [comment]
I've made a change that might fix this, please feel free to get the latest code and try it out.

**Comment by dangrossman** [comment]
I've made a change that might fix this, please feel free to get the latest code and try it out.

**Comment by gbsmit03** [comment]
I just tested it and it resolved the issue I was seeing.

**Comment by gbsmit03** [comment]
One more question should `setStartDate()` and `setEndDate()' update the current view if it is open? The reason I'm calling `updateView()` because the current view is not updating when I call the setters. It does update if I close the picker and open it back up.

**Comment by dangrossman** [comment]
No, because I can't imagine why you'd call them while the view is open.
