### ISSUE TITLE
Can't set Last Year range

### ISSUE THREAD

**Issue by lecamarade** [dangrossman/bootstrap-daterangepicker#1117]
@version: 2.1.21

This range won't appear.
ranges: {
"Last Year": [moment().subtract(1, "y").startOf("year"), moment().subtract(1, "y").endOf("year")];
}

**Comment by dangrossman** [comment]
I used this code and the range appeared.

You probably have a `minDate` or `maxDate` in your options as well, and they exclude this range of dates.

**Comment by lecamarade** [comment]
The minDate it is. Sorry.
