### ISSUE TITLE
Need built in support to remove Custom Date Range from selection.

### ISSUE THREAD

**Issue by dhanendra-kumar** [dangrossman/bootstrap-daterangepicker#1118]
There should be some option through which we can hide custom date range button.

**Comment by dhanendra-kumar** [comment]
I am working on it. :)

**Comment by dhanendra-kumar** [comment]
Closed it by mistake.

**Comment by dangrossman** [comment]
Oh, so you're the guy who thought it'd be funny to e-mail me from none@none.com.

**Comment by dhanendra-kumar** [comment]
@dangrossman 
I haven't ever sent any email to you.
