### ISSUE TITLE
Single DaterangePicker not updating current date to input element

### ISSUE THREAD

**Issue by syednizamudeen** [dangrossman/bootstrap-daterangepicker#1125]
### Issue:

When _Input Initially Empty_ using Single date picker as mentioned in below JSfiddle. I cannot select the date which is provided in `startDate` for first time only. How to make this possible?

[https://jsfiddle.net/a0myhnku/1/](https://jsfiddle.net/a0myhnku/1/)

Note:- `startDate` is today date

### Requirement: 

- Input field should be Empty by default
- user will Choose and apply date

**Comment by dangrossman** [comment]
Your callback function is only triggered when the `startDate` or `endDate` changes, not if someone clicks the already selected date. 

I suggest you listen for the `apply` event, like the "Input Initially Empty" example code does:

http://www.daterangepicker.com/#ex5
