### ISSUE TITLE
Single date with predefined labels

### ISSUE THREAD

**Issue by baskarsugumar** [dangrossman/bootstrap-daterangepicker#1126]
I want to create single datepicker with predefined dates as it is possible with ranges. So, if user clicks on it, it will show predefined values (like today, yesterday, this week, last week...) and a possibility to select the from date(singleDatePicker:true) and time custom.

I didnt see such an application in examples but since it is very simple use case for daterangepicker, i believe it should be somehow possible.

**Comment by dangrossman** [comment]
That is not possible with this library.

**Comment by gilhanan** [comment]
@baskarsugumar I need something like your needs, can you share please which solution did you choose?
