### ISSUE TITLE
Default: No dates

### ISSUE THREAD

**Issue by agrandin** [dangrossman/bootstrap-daterangepicker#1127]
Hi,
How would I configure it to use no dates as default? 
My use case:

I have a form where the clients can enter either event date range, or order date range. Or both, but both should not be required to set. Now if I set a default date to none it says invalid date. How do I set a default start and endDate to none, and only have a value if the users enters one using the daterange picker.

**Comment by dangrossman** [comment]
This is as close as you can get with this library: http://www.daterangepicker.com/#ex5

**Comment by agrandin** [comment]
I tried that, this is my code

<script>
                $(function() {

  $('input[name="orderdaterange"]').daterangepicker({
      autoUpdateInput: false,
      locale: {
          cancelLabel: 'Clear',
          format: 'YYYY-MM-DD'
      },
      "showWeekNumbers": true,
                "showISOWeekNumbers": true,
  });


  $('input[name="orderdaterange"]').on('apply.orderdaterange', function(ev, picker) {
      $('input[name="orderdaterange"]').val(picker.startDate.format('YYYY-MM-DD') + ' - ' + picker.endDate.format('YYYY-MM-DD'));
  });

  $('input[name="orderdaterange"]').on('cancel.orderdaterange', function(ev, picker) {
      $(this).val('');
  });

});
</script>


and my input field looks like this

<input type='text' class='daterange brodform' name='orderdaterange' value='' style='width:160px;'>

and it is empty even after selecting an range.

**Comment by dangrossman** [comment]
The events triggered by the date range picker are named `apply.daterangepicker` and `cancel.daterangepicker`. 

https://jsfiddle.net/cpjw4vvx/2/
