### ISSUE TITLE
setStartDate and setEndDate don't work

### ISSUE THREAD

**Issue by multiwebinc** [dangrossman/bootstrap-daterangepicker#1130]
This does not seem to work correctly. Nothing appears in the console, however the calendar is unable to render correctly (see screenshot below):

```
var startDate = '2016-06-17';
var endDate = '2016-06-18';
$('#daterangepicker').data('daterangepicker').setStartDate(startDate);
$('#daterangepicker').data('daterangepicker').setEndDate(endDate);
```

![datepicker](https://cloud.githubusercontent.com/assets/901732/16130652/7f1bd624-33c7-11e6-90f7-8223aa2be230.png)

However this *does* work correctly:

```
$('#daterangepicker').data('daterangepicker').startDate = moment(startDate);
$('#daterangepicker').data('daterangepicker').endDate = moment(endDate);
```

I'm using version 2.1.21.

**Comment by dangrossman** [comment]
YYYY-MM-DD is not the default format string if you don't specify one, but you're passing strings to these functions

The same way you cast it to a moment object in "this does work correctly", pass a moment object to `setStartDate` and `setEndDate`

I think that will address your issue

**Comment by multiwebinc** [comment]
I am using the same format as [the docs](http://www.daterangepicker.com/#options), which uses `YYYY-MM-DD`.

**Comment by dangrossman** [comment]
I should probably update the docs then

Did this fix your issue or not?

**Comment by multiwebinc** [comment]
Yes, it did.

**Comment by dangrossman** [comment]
Great, thanks :+1:

**Comment by multiwebinc** [comment]
Perhaps you could do some checking on the format/type of the arguments provided in `setStartDate()` and `setEndDate()` as well to make sure they are compatible.

**Comment by dangrossman** [comment]
Feel free to send a pull request that adds those checks if you'd like it to happen in the near future

**Comment by multiwebinc** [comment]
OK, I created a pull request that should hopefully work.
