### ISSUE TITLE
Not working in iOS Meteor+Cordova app

### ISSUE THREAD

**Issue by JustinWestphal** [dangrossman/bootstrap-daterangepicker#1131]
The daterangepicker picker works great on mobile in a browser like Safari, but when packaged into an app (it's a Meteor app, so using Cordova to bundle everything), running natively on iOS, merely clicking anywhere on the picker just closes it. You can't select anything, change any dates, or anything.

Any fixes for this? What could be causing it? I'm not an advanced enough developer to suss out a solution by myself, so any help would be greatly appreciated!

**Comment by dangrossman** [comment]
I don't know what Meteor apps or Cordova are, and I don't own an iDevice or Apple anything, so you're *really* out of luck today.

**Comment by JustinWestphal** [comment]
[Meteor JS](https://www.meteor.com/)
[Cordova](https://cordova.apache.org/)
[Quick](https://testobject.com/) [Google](https://testobject.com/) [results](http://testdroid.com/) [for](https://testfairy.com/) [testing](https://www.applause.com/iphone-app-testing/).

**Comment by dangrossman** [comment]
That's interesting. Since this isn't something I can help you with, I'm closing this.

**Comment by JustinWestphal** [comment]
Wow. I'm noticing a trend of devs on GitHub responding to support requests with "That's nice, fix it yourself", but this is getting silly.

**Comment by dangrossman** [comment]
Do you think we're your employees or something?

**Comment by dangrossman** [comment]
I'm really quite upset about that comment you made. Why do you think this is silly? Why do you expect me to learn an entirely new development stack and tool set for you? We've never met. I have already worked 10 hours today, I'm pretty tired. I have my own priorities and obligations. I wrote this little library four years ago. Sharing it doesn't make me an indentured servant of the over 1000 people a day that download it in all perpetuity. I try to be a helpful person, and have responded to some 1,130 issues before this one. But I'm certainly not obligated to provide support to you and your unique stack, especially when doing so would require a huge chunk of my time.

**Comment by Shuunen** [comment]
just don't close bugs because you don't have time to fix them
