### ISSUE TITLE
alwaysShowCalendars not working

### ISSUE THREAD

**Issue by mroftalp** [dangrossman/bootstrap-daterangepicker#1136]
is the option `alwaysShowCalendars: true` not working or its just me? I set it to true but it still hides the calendar.

**Comment by dangrossman** [comment]
It's just you, or perhaps some combinations of options and code you're using? 

Here's the website for this library, where you can see it in action: http://www.daterangepicker.com/#config

Go check off the `alwaysShowCalendars` checkbox and observe that the calendars are not hidden.

**Comment by mroftalp** [comment]
I'm using meteor.js. It hides whenever I pick a predefined range like `Today` but it remains open when I pick from custom range.

**Comment by dangrossman** [comment]
Sounds like you're using an old version of the code that predates that option existing

**Comment by mroftalp** [comment]
dangrossman:bootstrap-daterangepicker@2.1.13 <- this is my version

**Comment by dangrossman** [comment]
Yes, that is too old.

**Comment by dangrossman** [comment]
https://github.com/dangrossman/bootstrap-daterangepicker/releases/tag/v2.1.18

**Comment by mroftalp** [comment]
Oh. Is someone else handling the meteor package? It has your name on it, I thought it was official

**Comment by mroftalp** [comment]
https://atmospherejs.com/dangrossman/bootstrap-daterangepicker

**Comment by dangrossman** [comment]
Must be. I don't know anything about meteor, I didn't make a package.
