### ISSUE TITLE
Select month feature request

### ISSUE THREAD

**Issue by turigeza** [dangrossman/bootstrap-daterangepicker#1138]
Very nice job you have done thank you for your work.

It would be nice when you clicked on a month it would select it as a range similar to how the date picker works in google analytics. Maybe even add it to the selection so you could easily select a month or several months.

![screen shot 2016-06-20 at 17 44 43](https://cloud.githubusercontent.com/assets/9335740/16202697/b61f6498-370e-11e6-86bf-ed37106bd791.png)

**Comment by dangrossman** [comment]
Thanks for the suggestion. I don't really take feature requests; I don't have much time to work on them. There would be a lot of things to consider when implementing this feature -- there are dozens of combinations of settings that could result in an entire month being an invalid selection -- `minDate`, `maxDate`, `dateLimit`, crossing an `isInvalidDate`, the current state of the time pickers on either side...

**Comment by turigeza** [comment]
No problem :) Still nice job.
