### ISSUE TITLE
Issue regarding singledatepicker. 

### ISSUE THREAD

**Issue by selvaathi** [dangrossman/bootstrap-daterangepicker#1139]
Hi,

I want to use predefined date ranges like 'All Data', 'Last Month', 'Last 3 Months', 'Last 6 Months', 'Last 1 Year', 'Custom Range'.

#Regarding label to be shown when selecting particular label.

When I select Last 1 Month, last month date is set. When I select Last 3 Months, start date of last 3 month is set.

My requirement is when I select All Data, the date is set to Jan 1 1970, but I want the label to be retained as 'All Data' instead of Date Jan 1 1970. This is required only for this particular label(All Data), for the remaining it is required to show the date.

#Regarding singleDatePicker without timePicker.

I use singleDatePicker with all the above options(predefined date ranges). When I use "timePicker": true, only then I am able to see singleDatePicker, But in the Custom Range, I don't want to show TimePicker component. Is it possible to achieve singleDatePicker without timepicker component.

#Regarding Custom Range in singleDatePicker.

When I click on daterange picker component, it is always showing singleDatePicker component. Whereas it should be shown only when I click Custom Range label.

Herewith I have attached the files which I used.(DateRangePicker.html file is renamed as DateRangePicker.txt)  

PS:- If I don't use 'singleDatePicker' & timePicker, then it works perfectly. ie., when I click on Custom Range,only then Date Range picker component is shown. If I select any other component like Last 1 Month, Last 3 Months it doesn't show Custom Range. This is what I expect when using singleDatePicker also.

[css_js.zip](https://github.com/dangrossman/bootstrap-daterangepicker/files/324940/css_js.zip)

[DateRangePicker.txt](https://github.com/dangrossman/bootstrap-daterangepicker/files/324942/DateRangePicker.txt)

**Comment by dangrossman** [comment]
The `ranges` option is not meant to be available when `singleDatePicker` is enabled; it is a bug that some combination of options will result in the ranges list not being hidden. As far as putting text versus dates inside some label, that's code you can write in your callback function or event listener.
