### ISSUE TITLE
cancel or clear button in a singleDatePicker

### ISSUE THREAD

**Issue by bellerbrock** [dangrossman/bootstrap-daterangepicker#1142]
Hi Dan, the bootstrap-daterangepicker is a great open-source tool, thanks for all the hard work!

Nearly everything just works, and well. But I'm having trouble figuring out how to allow users to cancel or clear a selection they've made within a singleDatePicker. Is the cancel button option only implemented in the multiple date pickers?

**Comment by dangrossman** [comment]
That's correct, there are no buttons on the single date picker

The cancel button doesn't clear selections on the date range picker either; it just dismisses the dialog

If you want a single date picker, there are many of those to choose from, and at least some of them I'm sure support the notion of "nothing is selected", unlike this library

**Comment by bellerbrock** [comment]
Thanks @dangrossman, fair enough. I did see other options out there, but I couldn't find any up to the standards of this library. So I ended up just attaching a clear button with bootstrap's 'input-group-btn' class. 

Here's a JSFiddle in case anyone wants to implement the same functionality:
https://jsfiddle.net/bellerbrock/Lvepbr2d/39/

**Comment by GrEg00z** [comment]
A simple solution should be to add in your CSS  : 

`.daterangepicker.single.ltr .ranges {
  display : block !important;
}`

**Comment by jonnylink** [comment]
....But why drop the button for a single date? While there are other date pickers, using multiple date pickers would leave a page looking inconsistent :\

**Comment by askonieczny** [comment]
For anyone that comes across this page (like I did)- adding the timePicker option allows you to use a singleDatePicker with a clear button. Obviously not the best solution if you don't need to know the time for a selected date- but its the simplest solution

**Comment by JamesPoel** [comment]
`.daterangepicker.single .drp-buttons { display:block !important; }`

**Comment by sanaullah005** [comment]
$('.date').datepicker({
        format: "yyyy-mm-dd",
        language: "en",
        //autoclose: true,
        clearBtn: true,
        todayHighlight: true,
        update: '',
        clear: 'glyphicon glyphicon-trash',
        close: 'glyphicon glyphicon-remove'
    });

I hope it works.
