### ISSUE TITLE
autoApply option does not work with timePicker

### ISSUE THREAD

**Issue by ecordani** [dangrossman/bootstrap-daterangepicker#1143]
Hi,
if you set 
```
{
    "autoApply": true,
    "timePicker": true
}
```
the Apply e Cancel buttons are still visible.

**Comment by ecordani** [comment]
Sorry, I've seen this lines of code
```
        //can't be used together for now
        if (this.timePicker && this.autoApply)
            this.autoApply = false;
```
but I don't understand why...

**Comment by dangrossman** [comment]
Because if you close the picker automatically when clicking a date, the user never gets to choose a time.
