### ISSUE TITLE
Request for a new option when "linkedCalendars": false

### ISSUE THREAD

**Issue by rwsansom** [dangrossman/bootstrap-daterangepicker#1145]
After some user testing using the linkedCalendars:false option, we received consistent feedback that users were confused when the date range was less than 31 days, and displayed the same month side-by-side, (e.g., January | January).

We then found that if minimum distance of the endMonth was startMonth+1... (e.g., January | February) the users were never confused.

Could you add an option for setting the minimum distance the endMonth can be from the startMonth?  See attached image for example.

Thank you

![image](https://cloud.githubusercontent.com/assets/8225893/16350427/9a792e10-3a2c-11e6-9347-bbbcd9b3d892.png)

**Comment by dangrossman** [comment]
Why are your users scrolling the right month back to the same as the left month, then becoming confused? There's already code that always makes sure the UI doesn't arrange itself that way unless the user forces it that way.

**Comment by dangrossman** [comment]
The UI never arranges itself in the "confusing to the user" way on its own. If you had January first to 21st selected, it would open with January and February shown. I will not be adding a new option to set a minimum distance between the months. It is too niche and strange a problem (the user asked to be shown january, then was confused when they saw january?) to be worth maintaining yet another option for all eternity. Sorry.

**Comment by rwsansom** [comment]
Thank you for the response. I agree, maintaining an option for all eternity makes no sense. 

However, I still see a UX pitfall in even allowing the user to get itself into the "Jan 2016 | Jan 2016" situation. Why they do it? who knows, but they do -- If there's a pit to fall into, the user will find a way to do it... and then complain that it wasn't their fault.  

As I read back through my initial submission, I realize that what I was really asking about (but didn't clearly explain the first time) was is if it possible to prohibit the user from even getting into the situation?

They are getting into the situation by clicking the "<" on the endMonth. Can they get out of it? Yes, but it still disrupts their experience.

So if there's a way to hide the "<" from the endMonth when the endMonth is one month after the startMonth, the pitfall is removed.

<   Jan 2016   >  |  <   Feb 2016   >
vs.
<   Jan 2016   >  |       Feb 2016   >

**Comment by dangrossman** [comment]
I'll leave this open so I remember to think about that next time I have time to look at this repo

**Comment by dangrossman** [comment]
I think it would be nice to hide the arrows in this instance, but I don't have time to implement it myself
