### ISSUE TITLE
How do you guys solve this kind of issue with timezones?

### ISSUE THREAD

**Issue by alexrada** [dangrossman/bootstrap-daterangepicker#1147]
I know the plugin doesn't support timezones, and I'm not asking for it.
Just wanted to know how you guys solved this issue, if you came across it.:

I'm building a web app working with clients from various timezones

Let's say I'm in UTC +9 hours. (my browser accessing the app). Client account timezone is in UTC +3 hours. (saved in the database). Let's say I want to create a task for 15PM in my client account timezone. And I don't know the difference between my browser/his timezone.

When I want to select a specific time/date it shows as following:
- the value displayed here in the input is in client account timezone (utc + 3). -> correct
- the value of the input field is in utc time.-> correct
- the time/date value in the dropdown selection shows time for my browser (utc + 9) 

How do I make the dropdown to completely ignore browser timezone and display the values in client account zone (utc + 3)? 

How do I select a time like 15.00 for my client? 12.00 UTC or 19.00 my browser time?

![image](https://cloud.githubusercontent.com/assets/1150584/16377664/629f68a6-3ca2-11e6-9d61-65dcf4052ce2.png)

Here's a stackoverflow link:
http://stackoverflow.com/questions/38052019/how-to-display-client-time-when-selecting-date-time-using-grossman-daterangepick

**Comment by dangrossman** [comment]
> I don't know the difference between my browser/his timezone

You have access to your browser's time zone in JavaScript. You have the client's timezone saved. The difference is just subtraction, so you do know it. But you don't need to, so it doesn't matter.

> How do I select a time like 15.00 for my client?

Select 15:00 from the dropdown menus, and submit the form. Your form will have the text "27/06/2016 15:00" in one of the inputs. When you process the form in your server-side code, you treat that as UTC+3, the timezone you have saved in your database. 

Your code doesn't need to know anything about the browser's time zone.

Similarly, you'd want to set "27/06/2016 15:00" as your `startDate` to display it in the UI. 

The only time your application needs to be time zone aware is when saving or retrieving dates from the database. The front-end javascript code and UI widgets don't need to do anything with time zones so long as you're passing around dates as formatted strings. The string "3 PM" carries no time zone information.

Just my input, and what's worked for me in apps where every user can set a time zone just like yours.

**Comment by alexrada** [comment]
Thank you.

Thanks for answering.

First thing is that I can't select 15.00 from the dropdown menus (they are disabled, up to my browser time). But this is probably because I'm sending startDate without UTC?

The only way I see is to personally select 19.00, which picker transforms into 15.00 (for client account time) and save it by subtracting the client offset in the database.

I'll try to work with the timezone difference behind the scenes. (my browser - client account)
Thanks.

**Comment by dangrossman** [comment]
Set the `startDate` and `endDate` according to your client's time zone, not yours, so that 15:00 is pickable. You want to choose 3PM, so choose 3PM, IMO! It doesn't make sense to "choose 7PM and have a glorified `<select>` box contain logic to transform that to 3PM", it's not the UI's job.
