### ISSUE TITLE
Can daterangepicker just support timepicker?

### ISSUE THREAD

**Issue by YeZhiqiuSev** [dangrossman/bootstrap-daterangepicker#1149]
just timepicker,can it? ![image](https://cloud.githubusercontent.com/assets/18155748/16438323/4c43695a-3de1-11e6-9bcc-b0b92b15c503.png)

**Comment by dangrossman** [comment]
No. I suggest a `<select name="time"><option value="0">0:00</option><option value="1">1:00</option>...</select>`.
