### ISSUE TITLE
End Date Calendar does not show the current month of selected date

### ISSUE THREAD

**Issue by duynguyen0511** [dangrossman/bootstrap-daterangepicker#1151]
The issue can be reproduced on the demo page on http://www.daterangepicker.com/

Step1: Select 01/01/2015 and 10/31/2015 as your dates

Step2: open the calendar again. You will see the Start Calendar is Jan 2015, however the End Calendar is Feb 2015. It should be October because the end date is 10/31/2015

Screenshot is attached

![date-range-picker](https://cloud.githubusercontent.com/assets/436950/16456520/56e456d2-3dd5-11e6-9163-bd9940b5ea22.png)

**Comment by dangrossman** [comment]
See: `linkedCalendars`

http://www.daterangepicker.com/#options

**Comment by duynguyen0511** [comment]
thanks.

cant believe I missed that
