### ISSUE TITLE
showing a single month in range mode

### ISSUE THREAD

**Issue by rbalicki2** [dangrossman/bootstrap-daterangepicker#1152]
Is it possible to display a single month, but also have ranges enabled? Thank you!

**Comment by dangrossman** [comment]
It's not. The date range picker always has two calendars, not one.

**Comment by rbalicki2** [comment]
I found a good workaround.

```
.calendar.right {
  display: none !important;
}
```

with `linkedCalendars: false` enables this use case.

**Comment by bryan0** [comment]
I have a change which adds a singleMonthView and allows modifying the date input as a range (e.g. "1/1/2016 - 1/12/2016").  fork is here: https://github.com/bryan0/bootstrap-daterangepicker
