### ISSUE TITLE
How to Select Multiple range select option ?

### ISSUE THREAD

**Issue by pranaysonisoft** [dangrossman/bootstrap-daterangepicker#1155]
How to Select Multiple range select option ?

Please add Multiple range in same date picker.

For Example User can Select  Flight 

From-  5-July-2016   To -  8-July-2016

OR

From-  15-July-2016   To -  21-July-2016

**Comment by dangrossman** [comment]
Thanks for the suggestion, but I won't be adding that

**Comment by pranaysonisoft** [comment]
OK, dangrossman

you know any other daterangepicker support multiple range in single date picker ?

**Comment by dangrossman** [comment]
No, I've never seen that

**Comment by briem-bixly** [comment]
Google Analytics has this functionality, just fyi :)

**Comment by dangrossman** [comment]
Unfortunately Google Analytics isn't a date picker library...
