### ISSUE TITLE
Setting startDate with YYYY-MM-DD string causes NaN calendar

### ISSUE THREAD

**Issue by rgagnon24** [dangrossman/bootstrap-daterangepicker#1159]
Sample Markup:
&lt;input id="someDiv-dt" name="cutDate" type="hidden" value="2016-01-14"/&gt;
&lt;div id="someDiv" class="form-control"&gt;
   &lt;i class="glyphicon glyphicon-calendar"&gt;&lt;/i&gt;&nbsp;
   &lt;span&gt;2016-01-14&lt;/span&gt; &lt;b class="caret"&gt;&lt;/b&gt;
&lt;/div&gt;

Sample JS:
$("#someDiv").daterangepicker(
   {
      startDate: "2016-01-14",
      singleDatePicker: true,
      autoApply: true
 });

Before clicking on the div, you see:
![capture1](https://cloud.githubusercontent.com/assets/546197/16666278/90de4b86-444c-11e6-823b-8671e4c0eab6.PNG)

When you click it, you get:
![capture2](https://cloud.githubusercontent.com/assets/546197/16666290/9a6a4ccc-444c-11e6-87a6-2be7bb5c8437.PNG)

**Comment by rgagnon24** [comment]
Heh.  I read the source code to find this one....

I added:

locale: { format: "YYYY-MM-DD" }

to the options, and now it works.  Maybe a documentation could be in order?

Closing the ticket as I found the solution, but maybe others will use this for reference

**Comment by joshtidsbury** [comment]
I just stumbled upon this one as well. Doesn't actually seem to matter what you put in there, the issue arises. I've tried with moment objects as well.

**Comment by dangrossman** [comment]
@joshtidsbury That sounds like a totally different issue!

**Comment by joshtidsbury** [comment]
Rather than pile onto this thread, I've created a new one:
[https://github.com/dangrossman/bootstrap-daterangepicker/issues/1160](url)
