### ISSUE TITLE
Setting minDate and maxDate yields invalid picker

### ISSUE THREAD

**Issue by joshtidsbury** [dangrossman/bootstrap-daterangepicker#1160]
Here is what I'm using to instantiate the picker:

```
$("#component_time_range").daterangepicker({
		timePicker: true,
		timePickerIncrement: 5,
		timePicker24Hour: true,
		autoUpdateInput: false,
		minDate: moment("2016-06-13T00:00:00-07:00"),
		maxDate: moment("2016-06-17T00:00:00-07:00"),
		locale: {
			format: "YYYY-MM-DD HH:mm",
			cancelLabel: "Clear"
		}
	});
```

I've tried all sorts of permutations and combinations to try and get this to work, and I can't seem to get a valid picker:

<img width="671" alt="screen shot 2016-07-07 at 12 40 27 pm" src="https://cloud.githubusercontent.com/assets/12789521/16667178/07414858-4440-11e6-9ab1-b1e0d45763b8.png">

Something has changed between version 2.1.17 and 2.1.23, as using 2.1.17 doesn't exhibit this issue.

**Comment by dangrossman** [comment]
I was not able to reproduce this bug.

I used your code exactly as shown, with the current version of the daterangepicker.js (2.1.23).

<img width="733" alt="ss" src="https://cloud.githubusercontent.com/assets/407706/16667361/1cc2b1fc-445a-11e6-8bcc-a0bcbd34c77e.png">

**Comment by dangrossman** [comment]
Please provide a valid `startDate` and `endDate` since the default values of today's date don't fall between your `minDate` and `maxDate`

**Comment by joshtidsbury** [comment]
Confirmed that setting a start and end date fixes the issue.

But what if you want to start without a date or time selected? Effectively, the field should start blank until you choose something, and the picker shows you the available range to start selecting from.

**Comment by dangrossman** [comment]
This library has never supported not having a date selected internally. The value in your field is entirely under your control, however.

http://www.daterangepicker.com/#ex5

**Comment by joshtidsbury** [comment]
It did effectively work that way, but I'm already handling the field and picker separately, so I'll mark this as closed now. Thanks!
