### ISSUE TITLE
Feature Request: highlight date BeforeShow

### ISSUE THREAD

**Issue by apaleja** [dangrossman/bootstrap-daterangepicker#1161]
Is it possible to have function that takes a day as a parameter and this function can be called for each day before it is displayed. It will be helpful for many features. i.e.
 - Highlight Selected Dates
 - Enable/Disable Selected Dates etc

**Comment by dangrossman** [comment]
Yes, this feature already exits. It is the settings `isInvalidDate` for enabling/disabling dates, and `isCustomDate` for adding custom CSS classes to specific dates.

**Comment by versedi** [comment]
Could you add a simple example to the docs how to use this function? 
I was lucky to find this issue, it does work this way :)
