### ISSUE TITLE
End-date not selected after focusing daterangepicker_end

### ISSUE THREAD

**Issue by bsa01** [dangrossman/bootstrap-daterangepicker#1163]
After using tab or mouse to set focus to 'daterangepicker_end' input, selecting a day in the calendar as end day has no effect because the new 'formInputsBlurred' method is called instead of 'clickDate'.

**Comment by mckayb** [comment]
I'm also having this issue.

**Comment by dangrossman** [comment]
Feel free to take a stab at fixing it. The goal is to be able to edit the end date of the selection by editing the input or by clicking a date. I'm not sure how to accomplish that myself.
