### ISSUE TITLE
Dynamically update maxDate using setMaxDate function

### ISSUE THREAD

**Issue by goyalr41** [dangrossman/bootstrap-daterangepicker#1164]
Hi,

Is it possible to update maxDate, so that once the page is loaded one doesn't need to refresh it again to find updated maxDate. For ex: I load the page at 12:23 PM, every time will be greyed out after that. Is it possible I can keep resetting it after few seconds via a function like setMaxDate?

Thanks,
Raman

**Comment by dangrossman** [comment]
You can call `$.daterangepicker(options)` again to set new options, as often as you'd like, without reloading the page.
