### ISSUE TITLE
Format isn't a member of the locale object, but documentation says it is.

### ISSUE THREAD

**Issue by davewthompson** [dangrossman/bootstrap-daterangepicker#1165]
In order to customise the date/time format, you need to set the 'format' value of the options object. However, the documentation erroneously states that format is a member of the 'locale' object.

**Comment by dangrossman** [comment]
It is a member of the locale object. Are you by chance using a several year old copy of the library?

**Comment by davewthompson** [comment]
The one from 7 months ago from NPM, https://www.npmjs.com/package/semantic-ui-daterangepicker. So yes, pardon me! Thanks Dan. Do you have any plans to publish an official version to NPM?

**Comment by dangrossman** [comment]
The official version is on NPM. You're writing in an issue on `bootstrap-daterangepicker`, not `semantic-ui-daterangepicker`.

**Comment by davewthompson** [comment]
Oh, I'm really sorry Dan! Please ignore this, and delete if possible!
