### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by mtermoul** [dangrossman/bootstrap-daterangepicker#1167]
Is it possible to show only one calendar in the daterange dropdown? currently when you click on the input field, the daterange control will always show two calendars (this month + next month)

What I want is to see only one month or one calendar.

**Comment by dangrossman** [comment]
I responded to your e-mail with this question long ago. Why didn't you get back to me?

Do you want people to choose a range of dates from this one calendar?

**Comment by mtermoul** [comment]
Sorry I didn't get that first email. 
Anyway, yes I want to select a date range using a single calendar on the dropdown!
If not possible, then do you know any other alternatives or workarounds?

**Comment by dangrossman** [comment]
In that case I can't help you. You can't do that with this library, and I've never seen a date range picker on the web with only one calendar.
