### ISSUE TITLE
Can we disable dates? 

### ISSUE THREAD

**Issue by eddythemeddy** [dangrossman/bootstrap-daterangepicker#1168]
In the case of a booking website, can we pre-disable dates when loaded via ajax?

you can do this in jquery datepicker.. will it be the same functionality?  Also will disabling dates allow u to not be able to overlap your range?

Thank you!!

**Comment by dangrossman** [comment]
You can disable dates with the `isDisabledDate` option. Here's an example: https://jsfiddle.net/2s0hpfcx/1/
