### ISSUE TITLE
Use with tablesorter

### ISSUE THREAD

**Issue by swinston100** [dangrossman/bootstrap-daterangepicker#1170]
Hi
Thanks for your great tool, really hope i can get it working.
I'm trying to implement the following example: http://jsfiddle.net/abkNM/2188/
but am seeing the following error in console

`Uncaught TypeError: e is not a function`

Any idea why this may be happening? Thanks!

Steven

**Comment by dangrossman** [comment]
I see no errors in my console on that page, and the date picker code you're using is years-old. I cannot help you with that version.
