### ISSUE TITLE
next/previous month buttons not working on iPad

### ISSUE THREAD

**Issue by judodan** [dangrossman/bootstrap-daterangepicker#1174]
I'm having a problem with the next and previous month buttons when using from iPad.  When I click them, the date range picker closes.  Examining code in the outsideClick method, I find that when using regular chrome browser that the following:

            `target.closest(this.container).length`

is returning 1.  But when I switch chrome to emulate an iPad, it returns 0.  I stepped through both instances and it looks to me that the this.container variable is the same in both instances.

Is this a known issue or is there something I am doing incorrectly?  (I can supply sample code if that helps.)

Thanks.

**Comment by dangrossman** [comment]
I have no clue, and I have no iDevices. If you want this fixed, you'll likely have to do that :)

**Comment by judodan** [comment]
The chrome debugger will emulate for you. :)  This is where I reproduced and was able to find the difference.  I will continue trying to fix, was hoping it was already addressed. :(

If I can fix, I will, of course, submit the patch. :)
