### ISSUE TITLE
Select the startDate and the endDate in two inputs.

### ISSUE THREAD

**Issue by lininu** [dangrossman/bootstrap-daterangepicker#1175]
I make two inputs and I want to trigger endDate select when I click the second input.

Step:
1. click the second input.
2. just choose the endDate, I don't want to re-select the startDate.
As this example: http://codepen.io/Inu/pen/grKLwN

Now I focus the `[name="daterangepicker_end"]` to fulfill the result.
But to focus the input of `[name="daterangepicker_end"]` make me hard to use TAB key to seek the next input in the form.
Does there any method keep the startDate, and I can only select the endDate? 

Thank you.

**Comment by dangrossman** [comment]
This library does not support a two input interface.

**Comment by elenitaex5** [comment]
Maybe it could be good support and option to have one or two input interface. I have the same problem. But now, I have to edit the plugin to support two inputs.

**Comment by Dakshank** [comment]
+1

**Comment by jj-wd** [comment]
Solved it like this:

HTML
`                <p><label>'.__('Check In / Out Date','siteminder').'</label><br /><input name="daterange" id="daterange" type="daterange" /></p>
                <input name="check_in_date" id="check_in_date" type="date" hidden /></p>
                <input name="check_out_date" id="check_out_date" type="date" hidden /></p>`

JS
`    $('#daterange').daterangepicker({
        autoApply: true,
    }, function(start, end, label) {
        console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
        $("#check_in_date").val(start.format('YYYY-MM-DD'));
        $("#check_out_date").val(end.format('YYYY-MM-DD'));
    });`
