### ISSUE TITLE
Configuring initial month selections

### ISSUE THREAD

**Issue by tthordarson** [dangrossman/bootstrap-daterangepicker#1179]
Hello,

First of all, great plug-in that you've made! 

My requirement is to allow selection of days preceding today's date. The plugin out of the box has current month and next month set as the initial month selections. For my requirement, it doesn't make any sense to have next month selected as all of the days occurring on it are future days. Is there any way for me to specify which months are selected initially in the date range picker?

Thanks!

![daterangepicker-initial-months](https://cloud.githubusercontent.com/assets/6975170/17228162/dfaa9a64-54df-11e6-9299-3e68dd481c11.PNG)

**Comment by dangrossman** [comment]
There's not a separate setting for this. What months are shown is determined automatically based on the current `startDate` and `endDate` selected (the selected date range). That defaults to today's date if you don't specify any.

If you want to change the logic around what months are shown, here's the function to edit, `updateMonthsInView`:

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L550

**Comment by tthordarson** [comment]
Thanks, Dan. I just wrote a little extension for my situation in case anyone else is interested.

`if (this.daterangepicker) {
    var updateMonthsInView = this.daterangepicker.prototype.updateMonthsInView;

    // This modifies the daterangepicker to show on the right the current month and on the left the prior month
    // if maxDate is set to be today's date. The reason why is because by default it shows the current month on
    // left and the next month on right when there is no initial value. It makes no sense if you cannot select any
    // of the dates in the month on the right.
    this.daterangepicker.prototype.updateMonthsInView = function () {
        if (moment().diff(this.maxDate, 'days') === 0) {
            var currentMonth = moment({ month: moment().month() });
            var lastMonth = moment({ month: moment().subtract(1, 'months').month() });
            this.rightCalendar.month = currentMonth;
            this.leftCalendar.month = lastMonth;
        }

        updateMonthsInView.call(this);
    };
}`

**Comment by RudeySH** [comment]
Thanks @tthordarson! I was able to make it much more concise.

```js
// do this after initializing daterangepicker
var drp = $(myElement).data('daterangepicker');
drp.leftCalendar.month = moment().subtract(1, 'month');
drp.rightCalendar.month = moment();
```
