### ISSUE TITLE
Can't set minDate/maxDate in a created daterangepicker

### ISSUE THREAD

**Issue by dogcalas** [dangrossman/bootstrap-daterangepicker#1185]
I create a daterange picker with this options.
```
    $('.daterange').daterangepicker({
        format: 'YYYY/MM/DD HH:mm:ss',
        timePickerIncrement: 5,
        timePicker12Hour: true,
        timePickerSeconds: false
    });

```
Then, I tried to change the minDate using this:
```
    $('.daterange').daterangepicker({
maxDate:'2016/01/01',
minDate:'2016/01/05'
    });
```
But the daterange not change.

**Comment by dangrossman** [comment]
When you call `.daterangepicker` a second time, you are creating an entirely new date range picker. You need to pass all of the options, not just something you want to change. The default date format string, which you're not overriding in the second instantiation, is not YYYY/MM/DD, so those `minDate` and `maxDate` options are going to be seen as invalid as well.

**Comment by dangrossman** [comment]
Also, `format` is part of the locale object, not a top-level option. Use something like this:

    $('.daterange').daterangepicker({
      locale: {
        format: 'YYYY/MM/DD HH:mm:ss'
      },
      timePicker: true,
      timePickerIncrement: 5,
      timePicker12Hour: true,
      timePickerSeconds: false,
      minDate: '2016/01/01 00:00:00',
      maxDate: '2016/01/05 23:59:55'
    }

**Comment by StanleyNguma** [comment]
I had this problem and I was able to go around it.
On the daterangepicker.js file I added this function:

`setMinDate: function(minDate) {
            if (typeof minDate === 'string')
                this.minDate = moment(minDate, this.locale.format);

            if (typeof minDate === 'object')
                this.minDate = moment(minDate);

            if (!this.timePicker)
                this.minDate = this.minDate.startOf('day');

            if (this.timePicker && this.timePickerIncrement)
                this.minDate.minute(Math.round(this.minDate.minute() / this.timePickerIncrement) * this.timePickerIncrement);

            if (!this.isShowing)
                this.updateElement();

            this.updateMonthsInView();
        },`

Then on my HTML page I used the following line to call that function
` $('input[name="date_picker"]').data('daterangepicker').setMinDate(moment());`

I hope this helps

**Comment by pjaaar** [comment]
Hi,

I just wanna let you know that I had the same needs as @dogcalas and the solution provided by @StanleyNguma is working

**Comment by cornelRaiu** [comment]
@StanleyNguma you should also add 

`if (this.minDate && this.startDate.isBefore(this.minDate)) {
                this.startDate = this.minDate.clone();
                if (this.timePicker && this.timePickerIncrement)
                    this.startDate.minute(Math.round(this.startDate.minute() / this.timePickerIncrement) * this.timePickerIncrement);
            }`

before

`if (!this.isShowing)
                this.updateElement();
`

That way it keeps the original functionality in case the startDate is set before the minDate.

This is the full function code for setMinDate and setMaxDate:
`setMinDate: function(minDate){
            if (typeof minDate === 'string')
                this.minDate = moment(minDate, this.locale.format);

            if (typeof minDate === 'object')
                this.minDate = moment(minDate);

            if (!this.timePicker)
                this.minDate = this.minDate.startOf('day');

            if (this.timePicker && this.timePickerIncrement)
                this.minDate.minute(Math.round(this.minDate.minute() / this.timePickerIncrement) * this.timePickerIncrement);

            if (this.minDate && this.startDate.isBefore(this.minDate)) {
                this.startDate = this.minDate.clone();
                if (this.timePicker && this.timePickerIncrement)
                    this.startDate.minute(Math.round(this.startDate.minute() / this.timePickerIncrement) * this.timePickerIncrement);
            }

            if (!this.isShowing)
                this.updateElement();

            this.updateMonthsInView();
        },

        setMaxDate: function(maxDate){
            if (typeof maxDate === 'string')
                this.maxDate = moment(maxDate, this.locale.format);

            if (typeof maxDate === 'object')
                this.maxDate = moment(maxDate);

            if (!this.timePicker)
                this.maxDate = this.maxDate.startOf('day');

            if (this.timePicker && this.timePickerIncrement)
                this.maxDate.minute(Math.round(this.maxDate.minute() / this.timePickerIncrement) * this.timePickerIncrement);

            if (this.maxDate && this.startDate.isAfter(this.maxDate)) {
                this.startDate = this.maxDate.clone();
                if (this.timePicker && this.timePickerIncrement)
                    this.startDate.minute(Math.floor(this.startDate.minute() / this.timePickerIncrement) * this.timePickerIncrement);
            }

            if (!this.isShowing)
                this.updateElement();

            this.updateMonthsInView();
        }`

**Comment by proxy-m** [comment]
@dangrossman , why don't implement this functional in release?

**Comment by tejasm-itpath** [comment]
@cornelRaiu  Thanks You saved my time. :)

**Comment by H4Himanshu** [comment]
$('input[name="date_picker"]').data('daterangepicker').setMinDate(moment()); is not working for me . Console giving error .setMinDate is not a function

**Comment by dangrossman** [comment]
There is no setMinDate function... you set the minDate through the options object when you create the picker. You can change it by recreating the picker with your new options.

**Comment by StanleyNguma** [comment]
@H4Himanshu can you kindly post the JS code for better analysis

**Comment by dangrossman** [comment]
He did post his JS code...

**Comment by StanleyNguma** [comment]
@H4Himanshu check my comment up here or follow this  [link](https://github.com/dangrossman/bootstrap-daterangepicker/issues/1185#issuecomment-254212548)

**Comment by csala** [comment]
@StanleyNguma I suggest adding the following two rows into [your function](https://github.com/dangrossman/bootstrap-daterangepicker/issues/1185#issuecomment-254212548)

```
if (this.startDate < this.minDate)
    this.setStartDate(this.minDate);
```

This ensures that if the minDate being set is greater than the actual selected date the input value is properly updated.

**Comment by highstone** [comment]
Would definitely give this a +1. And although I understand @dangrossman and the code is posted indeed, it would really benefit the functionality of the component if these two setters were added. It helps validating the user input (or better prevent the user from clicking the wrong dates that need to be validated afterwards) and keeps the using code clean and simple. Perhaps a 3.0.4 release? ;-)

**Comment by bharatc94** [comment]
@dogcalas 
You need set maxDate and minDate like below :
you should store in variable then use it.

var prev_date = new Date();
prev_date.setDate(prev_date.getDate() - 1);  
// prev_date returns yesterdays date

    $('input[name="daterange"]').daterangepicker({
        opens: 'left',
        showDropdowns: true,
        autoUpdateInput: false,
        **maxDate: prev_date,**
        locale: {
            cancelLabel: 'Clear',
            format: 'MMM DD, YYYY'
        }
    }); 
and 
if u want to allow user to select prev dates only 
ex. Date of birth u can use this prop.
**startDate : prev_date**
