### ISSUE TITLE
TimePicker and Single Date Picker Apply

### ISSUE THREAD

**Issue by czuvich** [dangrossman/bootstrap-daterangepicker#1189]
Issue -> The date selected is not being applied to the picker.

Steps to Reproduce ->
* Set timePicker to false
* Set singleDatePicker to true
* Click the arrow buttons to select a month + year
* Click Apply

The date is not being applied.

**Comment by dangrossman** [comment]
Two things:

(1) Those options do not generate an interface with an Apply button to click

(2) Those steps do not include selecting a date

...

**Comment by czuvich** [comment]
Oh nevermind. User error... didn't pick a day.
