### ISSUE TITLE
Support date ranges relative to "now"

### ISSUE THREAD

**Issue by jaapz** [dangrossman/bootstrap-daterangepicker#1193]
I would like to be able to select date ranges relative to now.

For example, in Grafana you can select a date range for the last 6 hours, which they define as `now-6h`.

**Comment by dangrossman** [comment]
```
$('#yourelement').daterangepicker({
  ranges: { 
    'Last 6 Hours': [moment().subtract(6, 'hours'), moment()]
  }
}
```
