### ISSUE TITLE
Presets with a value rather than a date range

### ISSUE THREAD

**Issue by WilliamStam** [dangrossman/bootstrap-daterangepicker#1194]
i have a project that makes use of your daterange plugin. my only gripe with it is that when you use presets it changes them to a "date range" (i know its in the name).

the daterange field sends the value to the backend who then returns the records and saves a "this is what the user searched for" variable to the users profile. the problem now is that since its passing a date range if the user last used "30 days ago" and then logs in again a week later the values wont be the same. 

since you allow adding custom labels n such to the presets wont it make sense to also allow a "value"?

as in

````
 ranges: {
           'Today': "today",
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            .....
        }
````

when you select that label it puts the "value" into the field instead and disregards the "apply this to the range calendars thing". will send "today" to the backend. 

be a case of doing something like ` if (typeof options.ranges[range] === 'string'){` im trying to go through the code at the moment to possibly add a pull-request. but my code wont be as elegant as yours. i also dont know where all the range stuff gets applied

**Comment by dangrossman** [comment]
What you send to your back end is entirely up to you. This front-end javascript library isn't sending anything to any servers. The word "Today" is provided to your callback function when the user clicks that predefined range. You can "send it to your back end" if you want, with AJAX or by putting it into a hidden form field.

**Comment by WilliamStam** [comment]
so then i would have to have a "mask" input somehow to show that the user selected "Yesterday" instead of  08/09/2016 - 08/10/2016 etc. suppose i could make it work. 

i finished editing the code for my PR but then found it broke some other places. might just ditch it and try work something from this instead. 

pity tho cause that functionality would be pretty sweet. thanks for the response.

**Comment by dangrossman** [comment]
In your callback function, put this line: `$('#yourelement').val(label);`

Made it work :)

**Comment by WilliamStam** [comment]
well seems the above needs to be wrapped in a settimeout. 

for those interested heres my hacked together code for it

````
var format = 'YYYY-MM-DD';
	var ranges ={
		"All":[_dates.earliest,_dates.latest],
		"Today": [
			moment().startOf('day').format(format),
			moment().endOf('day').format(format)
		],
		"Yesterday": [
			moment().startOf('day').subtract(1,"day").format(format),
			moment().endOf('day').subtract(1,"day").format(format),
		],
		"Last 7 Days": [
			moment().startOf('day').subtract(7,"day").format(format),
			moment().endOf('day').format(format)
		],
		"Last 30 Days": [
			moment().startOf('day').subtract(30,"day").format(format),
			moment().endOf('day').format(format)
		],
		"Last 60 Days": [
			moment().startOf('day').subtract(60,"day").format(format),
			moment().endOf('day').format(format)
		],
		"Last 120 Days": [
			moment().startOf('day').subtract(120,"day").format(format),
			moment().endOf('day').format(format)
		],
		"Future": [
			moment().endOf('day').format(format),
			_dates.latest
		]
		
	};
	var startDate, endDate;
	
	
	//console.log($("#date-picker").val())
	//console.log(ranges['Today'])
	var lab = $("#date-picker").val();
	if (typeof ranges[lab] !== "undefined"){
		startDate =  ranges[lab][0];
		endDate =  ranges[lab][1];
	}
	
	
	
	
	
	
	
	
	$("#date-picker").daterangepicker({
		"showDropdowns": true,
		"autoApply": true,
		"startDate":startDate,
		"endDate": endDate,
		"locale":{
			format:'YYYY-MM-DD',
			"separator": " to ",
		},
		"ranges": ranges,
		"minDate": _dates.earliest,
		"maxDate": _dates.latest,
		"opens":"center",
		"onClose"          : function () {
			
			setTimeout(function () {
				
				
				var val = $("#date-picker").val();
				if (val != $("#date-picker").attr("data-date-picker")) {
					$("#filter-form").trigger("submit");
				}
				
			}, 400);
			
		}
		
	}, function(start, end, label) {
		if (label!="Custom Range"){
			setTimeout(function () {
				$('#date-picker').val(label)
			});
		}
		
		setTimeout(function () {
			console.log($('#date-picker').val())
			
			var val = $("#date-picker").val();
			if (val != $("#date-picker").attr("data-date-picker")) {
				$("#filter-form").trigger("submit");
				
			}
		}, 400);
		
		
		
	}).val(lab)

````

**Comment by dangrossman** [comment]
You don't need a timeout -- if you're going to have code that manages the value in your input yourself, you'd want to set the `autoUpdateInput: false` option so the library doesn't do it
