### ISSUE TITLE
first picker does not reset to selected date on loss of focus

### ISSUE THREAD

**Issue by scoobah36** [dangrossman/bootstrap-daterangepicker#1195]
so this is a bit of a crazy one that we found while using this widget. and we confirmed while using the examples on your site.

steps:
- click on the input box at the top for the first date so it has focus
- select a date
- now click on the second date input so it has focus
- select a date
- now when the focus moves back to the first date input it is broken in that if you move the cursor off of the widget the first picker will keep whichever date was last hovered instead of the selected first date

This only happens in IE from what i can tell and it seems to be any version of IE including Edge

**Comment by dangrossman** [comment]
I'm probably just doing something wrong, but I'm not seeing this behavior in IE or Edge at http://www.daterangepicker.com

**Comment by CurseMundi** [comment]
This is not a issue, it's just a unfriendly design. When you click on the input box at the top for the first date , the first date input has focus. Then you select a date first time, the second date input has focus. But when you select a date second time, the first date input has focus again and the second date is already been selected. If you imagine there is a thrid date input , the date input is focusing is the third not the first. It looks like a loop!
 And if you move the mouse out of the box , you will see the first date input is right!
