### ISSUE TITLE
2.1.24（bug）singleDatePicker:true,input text empty value; singleDatePicker:false, click date

### ISSUE THREAD

**Issue by zyz** [dangrossman/bootstrap-daterangepicker#1198]
1. **singleDatePicker:true**, input text empty  value defult startDate is today
2. **singleDatePicker:false**, click date input daterangepicker_start and daterangepicker_end same date
Emergency BUG

**Comment by zyz** [comment]
Emergency BUG

**Comment by dangrossman** [comment]
You haven't described any bugs
