### ISSUE TITLE
jquery version in bower version

### ISSUE THREAD

**Issue by starplanet** [dangrossman/bootstrap-daterangepicker#1201]
bower.json's jquery version is '1.9.0-2', but package.json is '>=1.9.0'.

If I use bower to install the package, the jquery version will be downgrade to 1.12.4 from 3.1.0.

Can you adjust jquery version in bower.json ?

**Comment by dangrossman** [comment]
I'm just following the dependencies for Bootstrap, since this is a Bootstrap plugin

They didn't support jQuery 3 last time that was updated, I can add it now
