### ISSUE TITLE
Feature request: linkedCalendar = false && independent = true

### ISSUE THREAD

**Issue by mikealmond** [dangrossman/bootstrap-daterangepicker#1203]
In the previous version (v1.3) the two calendars were independent with each other. That meant that if you select a start and end date, the right calendar would always adjust the end date. This was removed in v2.0 and now you have to select the end date input before selecting a new end date. 

When you have time selection enabled, this is even more confusing, as the time selection is independent,  but the calendars are not. Is there anyway to make the calendars work independently from one another like the previous version? 

## Old selection method
![](https://d3vv6lp55qjaqc.cloudfront.net/items/3P0d3H3I3J230d111f0p/Screen%20Recording%202016-08-15%20at%2010.54%20AM.gif?v=c49d792b)

## New
![](https://d3vv6lp55qjaqc.cloudfront.net/items/2x2i2C2E2Q2v3K0m2w1V/Screen%20Recording%202016-08-15%20at%2010.55%20AM.gif?v=f98acb8e)

**Comment by dangrossman** [comment]
No, there's no feature like that, if you want the old behavior then use the old version
