### ISSUE TITLE
Not reset when input invalid date

### ISSUE THREAD

**Issue by lomotony** [dangrossman/bootstrap-daterangepicker#1206]
![screenshot - 08182016 - 10 23 43 am](https://cloud.githubusercontent.com/assets/6621024/17759901/f5434c0a-652d-11e6-9211-b4feeebcc874.png)

When i input a invalid date, it not reset to previous data. Who can tell me why?

**Comment by dangrossman** [comment]
Because nobody's written code to make that happen presumably

**Comment by lomotony** [comment]
Why i input `2016/08/1800`, it reset to the previous date when lose focus?

**Comment by dangrossman** [comment]
Read the code if you'd like to know, I don't have time for Q&A
