### ISSUE TITLE
npm? bower?

### ISSUE THREAD

**Issue by andrewboy** [dangrossman/bootstrap-daterangepicker#1207]
Hello!

Is this repo got npm or bower?

**Comment by dangrossman** [comment]
Yes, it's on both.

**Comment by andrewboy** [comment]
I haven't found it and the web page not write anything from it. :(

**Comment by dangrossman** [comment]
The packages have the same name as this repository, which contains the bower.json/package.json corresponding to them.

npm install bootstrap-daterangepicker
bower install bootstrap-daterangepicker
