### ISSUE TITLE
Custom Timezone Date

### ISSUE THREAD

**Issue by Nagasubba-Reddy** [dangrossman/bootstrap-daterangepicker#1210]
Hi,

Is there any way to pass a custom timezone to daterangepicker instead of choosing browser timezone.
It will be very much helpful if it has an option to pass custom timezone.
Please suggest.

Thank You.

Regards,
Subbu

**Comment by dangrossman** [comment]
That's probably something you'd do with the global moment object, which is the source of all dates and times in this library

http://momentjs.com/timezone/
