### ISSUE TITLE
html dropdown list element

### ISSUE THREAD

**Issue by Nagasubba-Reddy** [dangrossman/bootstrap-daterangepicker#1211]
Hi,

Is there any way to add a new html dropdown element in daterangepicker.
In one of our project we need to add a custom dropdown element which consist of number of months like 1,2,3 etc.
Please suggest.

Thank You.

Regards,
Subbu

**Comment by dangrossman** [comment]
I don't understand what your project's requirements have to do with my library. You can add any dropdowns you want to your webpage.
