### ISSUE TITLE
Wrong week number for 2016 ISO and Normal

### ISSUE THREAD

**Issue by pkerblaze** [dangrossman/bootstrap-daterangepicker#1213]
We are at week 34 for the 2016-08-22,
On the configuration generator, it display : 
for "showWeekNumbers": true, we have week 35
for "showISOWeekNumbers": true, we have week 33

It look like the ISO isn't right, and there is the same problem in Excel : 

> Excel doesn't handle week numbers correctly per ISO 8601 unfortunately and you end up with items like this. Per the ISO standard week numbers are Mon-Sun and week 1 always contains Jan 4th. As a result week 1 for 2016 should be 1/4-1/10/2016, January 1-3 are in week 53 of 2015 per the ISO standard.

**Comment by dangrossman** [comment]
Go to http://www.daterangepicker.com/#config

Check off "locale (with example settings)" to make Monday the first day of the week

Check off "showWeekNumbers" and you'll see that we're in week 35

Check off "showISOWeekNumbers" and you'll see that we're in week 34

That's correct according to the ISO calendar I found.
