### ISSUE TITLE
Picker UX after update

### ISSUE THREAD

**Issue by davidbuttar** [dangrossman/bootstrap-daterangepicker#1217]
Is there a way via config to have the date range selection mechanism that same as it was in version 1.3.21?

I recently updated a number of my dependency libraries, including this one.

Previously, we had the left panel (of the calendar) for the start date, and the right panel for the end date; one could modify either in any order.
Now, both pages of the calendar are sequential, and for either the start or the end; first date selected selects the start, the second selects the end. I'm finding this significantly more confusing than the previous behaviour.

It would be great to be able to have it work similar to how it used to via config.

**Comment by dangrossman** [comment]
No. This is how every two-calendar date range selection widget I could find on the web worked. Every hotel booking site, every flight search engine, every analytics tool (except those that used two separate inputs and calendars). First click selects the start of the range, second click selects the end. If this is how it works everywhere on the web, your site being different is what would be significantly confusing to users. If you want to be different, then you can stay on the old version, it's a UI widget there aren't security concerns or anything keeping you from staying on whatever version you want.

**Comment by davidbuttar** [comment]
Fair enough, sound reasoning.
