### ISSUE TITLE
Auto display the calendar without the need to click on the input field

### ISSUE THREAD

**Issue by dbr0** [dangrossman/bootstrap-daterangepicker#1218]
Hi,
I'll probably end up using this repo in my next project so thanks for your time developing this for us.

My question (rather than an issue) is can the calendar be always displayed (with hidden input field) without the need to click on the input field to display the calendar element or should I implement this functionality by myself.

**Comment by dangrossman** [comment]
There's no setting that does that, you need to do it yourself. Shouldn't be hard to do. Trigger the `show()` method and comment out the body of the `hide()` method would probably do it.

**Comment by chozabu** [comment]
@dangrossman  I'm aware this is closed - but this would be a fantastic little tweak to have! Would you be interested in a PR for this?

**Comment by dangrossman** [comment]
There's already a PR open for this

**Comment by chozabu** [comment]
@dangrossman I see!

in case anyone stumbles on this page: https://github.com/dangrossman/bootstrap-daterangepicker/pull/1245
