### ISSUE TITLE
Time Picker going to be included?

### ISSUE THREAD

**Issue by lupoair** [dangrossman/bootstrap-daterangepicker#1219]
Just wanted to know if there is a time picker to be included in the future?

**Comment by dangrossman** [comment]
You can add a time picker by setting `timePicker: true`

http://www.daterangepicker.com/

**Comment by lupoair** [comment]
Oh, yes, but I meant a time picker not a drop down select box something ui friendly.

**Comment by dangrossman** [comment]
A dropdown select box is a UI friendly time picker. It's the way people have been setting times on the web for decades.
