### ISSUE TITLE
showCalendar.daterangepicker disable dates via ajax

### ISSUE THREAD

**Issue by gdycus** [dangrossman/bootstrap-daterangepicker#1225]
When "showCalendar.daterangepicker" is fired I need to make an ajax call to the server to get a list of dates to disable. Is it possible to disable dates on the calendar inside showCalendar.daterangepicker? Thanks!

**Comment by dangrossman** [comment]
No. You can only change options by recreating the date range picker, and you can't do that while it's just become visible on the screen. You would want to get your list of dates to disable at some other time.

**Comment by gdycus** [comment]
Basically as the user goes forward or back a month, I will pass the current visible date range to the server and get a list of dates to disable and then disable those dates on the calendars. Do you have a suggestion on how to accomplish this?

**Comment by dangrossman** [comment]
Disable all the dates you want disabled at once, not just those in the visible month. What you want to do won't work, unless you make your own custom version.

**Comment by gdycus** [comment]
Would you be open to adding an attribute like data-date="8/29/2016" on each table cell? This way I could manually loop through each day and if I find a match I could add the invalid class.

**Comment by dangrossman** [comment]
No

**Comment by gdycus** [comment]
Ok. Thx
