### ISSUE TITLE
Initialization lose timer

### ISSUE THREAD

**Issue by Emyleen** [dangrossman/bootstrap-daterangepicker#1227]
Hello, I have an issue when I want to initialize the daterangepicker with 2 date with time.

I use setStartDate but I can't give a format with time, I just can give the date.

Can you help me? Thank you !

`var dateDepart = '30/08/2016'; //I want to begin at 12:15:00 
var dateFin = '15/09/2016'; //I want to end at 15:30:00
$('#session-date').data('daterangepicker').setStartDate(dateDepart);
$('#session-date').data('daterangepicker').setEndDate(dateFin);`

**Comment by dangrossman** [comment]
```
$('#session-date').daterangepicker({
  locale: {
    format: 'DD/MM/YYYY HH:mm:ss'
  },
  startDate: '30/08/2016 12:15:00',
  endDate: '15/09/2016 15:30:00'
});
```
