### ISSUE TITLE
When predefined range is selected how to show range name in input instead of dates?

### ISSUE THREAD

**Issue by envision** [dangrossman/bootstrap-daterangepicker#1229]
For example when selecting predefined range "Last month", how to show "Last month" text in input instead of date range?

As the date range is two separate dates, we surely are needed to handle them as separate parameters within logic (i.e. for doing API calls with), so this input field is just presentation field for the UI.

**Comment by dangrossman** [comment]
The name of the range clicked is provided to your callback function as the third parameter. You can use that to update your input there.

On September 4, 2016 12:45:04 PM EDT, Janne Kurkinen <notifications@github.com> wrote:
>For example when selecting predefined range "Last month", how to show
>"Last month" text in input instead of date range?
>
>As the date range is two separate dates, we surely are needed to handle
>them as separate parameters within logic (i.e. for doing API calls
>with), so this input field is just presentation field for the UI.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dangrossman/bootstrap-daterangepicker/issues/1229

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
