### ISSUE TITLE
Is it possible to use range-picker but leave one date blank?

### ISSUE THREAD

**Issue by pawel-kozera** [dangrossman/bootstrap-daterangepicker#1230]
Hello,
thanks for great plugin! I'm trying to use date range picker but I need to have option to leave one date ('from' or 'to') blank. I need an open set. Is it possible with the current functionality?

**Comment by dangrossman** [comment]
No. Perhaps you don't need a range picker then, but instead two text boxes with two single date pickers.

**Comment by pawel-kozera** [comment]
I thought so, thanks!
