### ISSUE TITLE
Is there a description of the document in markdown format?

### ISSUE THREAD

**Issue by guohuihot** [dangrossman/bootstrap-daterangepicker#1231]
Is there a description of the document in markdown format?

**Comment by dangrossman** [comment]
What document?

**Comment by guohuihot** [comment]
![image](https://cloud.githubusercontent.com/assets/3119995/19552371/21206ed0-96e2-11e6-91f5-bebedcb9547f.png)
And readme as on the plug-in description of the document

**Comment by dangrossman** [comment]
I'm not sure what you're asking for

README.md markdwown: https://raw.githubusercontent.com/dangrossman/bootstrap-daterangepicker/master/README.md

README.md rendered: https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/README.md

**Comment by guohuihot** [comment]
I want a document about your plugin in markdown.

**Comment by dangrossman** [comment]
That describes README.me. A document about the plugin in markdown.
