### ISSUE TITLE
Unique picker identifiers

### ISSUE THREAD

**Issue by limax84** [dangrossman/bootstrap-daterangepicker#1238]
Hi,
Is there a way somehow to provide to the picker a unique identifier to allow css selection of one specifically ?
Thanks

**Comment by dangrossman** [comment]
There's not an option for that, you'd have to code it yourself

**Comment by limax84** [comment]
Ok, I see, thanks for the quick reply, however I need to understand something.

On a page with multiple pickers dynamically added (throw dynamically added elements) those pickers stay forever in the body because I can't select them to remove them from the DOM. I tried to attached them to something else using "parentEl" BUT then the picker is generated using the element width as its own max-width...

**Comment by dangrossman** [comment]
You want to remove a picker from the DOM?

`$(yourelement).data('daterangepicker').remove();`

**Comment by limax84** [comment]
Yeah but IF myElement is body it will remove them all at once, and if myElement is the dynamically added trigger element, the generated picker is too small (same width as its prentEl)

**Comment by dangrossman** [comment]
"yourelement" refers to the element you attached the date range picker to, with `$(yourelement).daterangepicker()`, not your `parentEl` setting. It would remove only one picker.

**Comment by limax84** [comment]
Ohhh I skipped the ".data()", cool thanks a lot for your time. Great job btw ;)
