### ISSUE TITLE
Use 2 input[type=text] instead of 1

### ISSUE THREAD

**Issue by NicolaeCasir** [dangrossman/bootstrap-daterangepicker#1239]
Hi. Please help me. It's possible to use DRP with 2 inputs instead of 1?
For exemple i have this form:
![captura de ecran din 2016 09 15 la 21 11 36](https://cloud.githubusercontent.com/assets/8903698/18561548/0c14eae4-7b89-11e6-9d33-3bfa3402ac68.png)

I need start date to be in first input and end date in second.
Thank you.

**Comment by dangrossman** [comment]
Only by using two single date pickers (`singleDatePicker: true`), one attached to each input.
