### ISSUE TITLE
autoApply / autoUpdateInput Not Working In Single Date Picker

### ISSUE THREAD

**Issue by OptrixAU** [dangrossman/bootstrap-daterangepicker#1243]
I don't know if it's something in my particular scenario, but when I'm using the control as a **single** date picker (ie. with the singleDatePicker option set to true), I find that the autoApply and autoUpdateInput options have no effect.

**Comment by dangrossman** [comment]
Do you also have timePicker enabled?

**Comment by OptrixAU** [comment]
Ahh, yes, I do. So the autoApply options don't function when the time-picker is enabled. Is this by design? 

Thanks for the very quick response - it's a great script.

**Comment by dangrossman** [comment]
How would you know if the user is done choosing the date and time? They could click any of the 3-5 things (calendar, hour, minute, second, am/pm) in any order. When would it be "auto applied"? It's ambiguous, which is why you need a button.

**Comment by OptrixAU** [comment]
*HEAD SMACK* - of course, since 'Apply' closes the panel, you can't auto-apply when there's a time involved as there are multiple elements to click on. 

I was thinking that there may have been a setting to make the changes to the date/time immediately reflected in the input control (even while the calendar control is still up), with a single 'close' button rather than the the 'Apply' and 'Close/Cancel' buttons. But there's little real advantage to it, so I'll stick to your existing design. 

Thanks for the prompt reply to a stupid user issue!

**Comment by dangrossman** [comment]
No prob. It's not a stupid question. Doesn't seem like any two date picker widgets work alike.
