### ISSUE TITLE
set initial date

### ISSUE THREAD

**Issue by soongsta** [dangrossman/bootstrap-daterangepicker#1247]
Hi there 

Is there a way to set the initial date on show.daterangepicker?
eg https://jsfiddle.net/60dfn1ok/

Cheers

**Comment by dangrossman** [comment]
Yeah, that's the `startDate` option, and there's also a `setStartDate(date)` method. Both are in the documentation and used in the examples at http://www.daterangepicker.com/

````
$('input[name="birthdate"]').daterangepicker({
    startDate: '02/04/2008'
});
````

**Comment by soongsta** [comment]
I have tried this  
 startDate: moment($(this).val()),
and this
startDate: moment($(this).val()).format("D MMM YYYY"),
but when the calendar appears, I see undefined invalid date
See image below

The initial date I have is "01 Nov 2003"

https://cloud.githubusercontent.com/assets/17092846/18732306/9bb2a120-80a5-11e6-9e24-e26b8d54ae7a.png

**Comment by dangrossman** [comment]
Sounds like that's not a valid moment/date object you're passing as the setting value. Check that this.val() and moment(that) are the objects you expected.

**Comment by soongsta** [comment]
I managed to get a workaround by doing this:

        $('.datefield').on('show.daterangepicker', function (ev, picker) {
            var test = moment($(this).val()); //.format("D MMM YYYY");
            //console.log('test=' + test);
            $(this).data('daterangepicker').setStartDate(test);
            $(this).data('daterangepicker').setEndDate(test);
            picker.updateCalendars();
        });

for some reason, it kept on showing the current date

Thanks for your help

**Comment by dangrossman** [comment]
Why are you setting it on the show event, instead of when you make the picker?

**Comment by soongsta** [comment]
For some reason it did not want to accept the value.
So I commented it out.

        $('.datefield').daterangepicker({
            singleDatePicker: true,
            autoUpdateInput: false,
            //startDate: moment($(this).val()).format("D MMM YYYY"),
            locale: {
                cancelLabel: 'Clear',
                format: 'DD MMM YYYY'
            }
        }, function (start, end, label) {
            //
        });

And then force the value on the show event
When I set the autoUpdateInput to true, it would display the todays' date
I am thinking it has to do with the leading zero for DD
Or that it just does not like DD MMM YYYY as the initial value

**Comment by dangrossman** [comment]
The `startDate` option accepts a date object, moment object or string matching your date `format` setting. A date in "D MMM YYYY" is none of those things, so that's not a valid value to set for the option.

**Comment by soongsta** [comment]
Ahhh, that makes sense now
Thanks

**Comment by soongsta** [comment]
Actually, the format string was DD MMM YYYY, which it did not like.
Anyways, the work-around using the show event works for me
