### ISSUE TITLE
Calendar appears right after initialization

### ISSUE THREAD

**Issue by nqtien310** [dangrossman/bootstrap-daterangepicker#1248]
````
$("#date-range-input").daterangepicker();
````
Somehow, Invoke the above code will immediately show the Calendar, what I expect is the Calendar only show up when user click on `#date-range-input` textbox

**Comment by dangrossman** [comment]
Sounds like you're missing the Bootstrap stylesheet, which sets the initial `display: none` on dropdown elements.
