### ISSUE TITLE
Problem with selecting 1 same date for start and end date

### ISSUE THREAD

**Issue by nqtien310** [dangrossman/bootstrap-daterangepicker#1250]
I want to add a "Today" range which will select today for both `startDate` and `endDate`, it works fine actually. All I wanna do is to adjust the displaying of the textbox a little bit.
so instead of `09-26-2016 - 09-26-2016` , just display `09-26-2016`.

FYI , I could manage to update the textbox's value in the callback, but this solution isn't suitable for our current code architecture. So I wonder if we have any setting for this ?

**Comment by dangrossman** [comment]
No there's not a setting for this, you should update the textbox's value in the callback, or an event listener for the `apply.daterangepicker` event.
