### ISSUE TITLE
Current date always shown in calendar-table

### ISSUE THREAD

**Issue by selvaathi** [dangrossman/bootstrap-daterangepicker#1251]
Hi, 

I want to show date value(which is fetch from DB) in daterangepicker component. It shows correct date in daterange component, but it is not shown correct value in calendar table. Value fetched from DB is Aug-28-2016,in daterange components it shows correct value, but in calendar-table it always shows current date value. Attached image for reference. 

Can you please help me to overcome this issue. 

Regards,
Selva

![datemismatch](https://cloud.githubusercontent.com/assets/19972430/18911320/0eb9b480-859a-11e6-8fcf-69d9b1ead5e9.png)

**Comment by aldrinm** [comment]
Is your locale and date format set correctly? see http://www.daterangepicker.com/#config

**Comment by selvaathi** [comment]
I have attached my configurations here. 
[DateRangePicker.txt](https://github.com/dangrossman/bootstrap-daterangepicker/files/497973/DateRangePicker.txt)

**Comment by aldrinm** [comment]
The documented way of updating the date is $('#reportrange').data('daterangepicker').setStartDate('08/28/2016'); Also do check your initialization code especially around locale. It looks all messed up.

**Comment by dangrossman** [comment]
If you do not specify a `startDate` and `endDate` dates, the beginning and end of the currently selected range at initialization, they will both default to today's date.

**Comment by selvaathi** [comment]
@aldrinm thanks for clarification. After using this $('#reportrange').data('daterangepicker').setStartDate('08/28/2016'); it works fine.
