### ISSUE TITLE
Show only one calendar for Date Range

### ISSUE THREAD

**Issue by satyajitsd** [dangrossman/bootstrap-daterangepicker#1253]

**Comment by dangrossman** [comment]
You can't do that

**Comment by satyajitsd** [comment]
HI,
Currently we have UI where we give radio buttons and drop-down to have different business dates and custom date.
This is very heavy component and developed in FLEX.
We find daterangepicker can satisfy all our conditions.
We are trying to achieve as attached here.
![single_calendar_for_date_range](https://cloud.githubusercontent.com/assets/22521829/18954177/5cd0bb48-866f-11e6-9b61-987d082baa9e.png)

**Comment by satyajitsd** [comment]
I have tried this making changes by providing flag in options.

dateParams = {
                        options: {
                            //maxDate: moment().add(1, 'month'),
                            //minDate: moment().add(-1, 'month'),
                            defaultSelectedRange: defaultDate,
                            singleDatePicker: false,
                            **_hideRightCalendar : true,_**
                            tooltip: true,
                            clearable: true,
                            customPicker : 'Range',
                            ranges: dateRanges,
                            locale:dateRangeLocale,
                            showCustomRangeLabel:true
                       }
                    };


and by changing just a template based on this flag -

if (typeof options.template !== 'string' && !(options.template instanceof $)){

            if(this.hideRightCalendar){

                options.template = '<div class="daterangepicker dropdown-menu">' +
                    '<div class="calendar left">' +
                        '<div class="calendar-table"></div>' +
                    '</div>' +
                    '<div class="ranges">' +
                        '<div class="range_inputs">' +
                            '<button class="applyBtn" disabled="disabled" type="button"></button> ' +
                            '<button class="cancelBtn" type="button"></button>' +
                        '</div>' +
                    '</div>' +
                '</div>';

            }else{

                options.template = '<div class="daterangepicker dropdown-menu">' +
                '<div class="calendar left">' +
                    '<div class="daterangepicker_input">' +
                      '<input class="input-mini form-control" type="text" name="daterangepicker_start" value="" />' +
                      '<i class="fa fa-calendar glyphicon glyphicon-calendar"></i>' +
                      '<div class="calendar-time">' +
                        '<div></div>' +
                        '<i class="fa fa-clock-o glyphicon glyphicon-time"></i>' +
                      '</div>' +
                    '</div>' +
                    '<div class="calendar-table"></div>' +
                '</div>' +
                '<div class="calendar right">' +
                    '<div class="daterangepicker_input">' +
                      '<input class="input-mini form-control" type="text" name="daterangepicker_end" value="" />' +
                      '<i class="fa fa-calendar glyphicon glyphicon-calendar"></i>' +
                      '<div class="calendar-time">' +
                        '<div></div>' +
                        '<i class="fa fa-clock-o glyphicon glyphicon-time"></i>' +
                      '</div>' +
                    '</div>' +
                    '<div class="calendar-table"></div>' +
                '</div>' +
                '<div class="ranges">' +
                    '<div class="range_inputs">' +
                        '<button class="applyBtn" disabled="disabled" type="button"></button> ' +
                        '<button class="cancelBtn" type="button"></button>' +
                    '</div>' +
                '</div>' +
            '</div>';

            }

        }``

**Comment by satyajitsd** [comment]
Let me know if this is ok and can be done.
