### ISSUE TITLE
Show / hide daterangepicker 

### ISSUE THREAD

**Issue by luigonsec** [dangrossman/bootstrap-daterangepicker#1255]
Hi! is there a way for showing/hiding daterangepicker ? I would need avoid daterange closing after clicking in a defined range. So I have thought listen the event 'apply.daterangepicker' and show calendar when this event occurs, but by the moment I have not found a good solution.

**Comment by aldrinm** [comment]
set `autoApply` to `false` and implement the `apply.daterangepicker` and `cancel.daterangepicker` see http://www.daterangepicker.com/#options
