### ISSUE TITLE
When using a Spain locale some months are shown double or invalid

### ISSUE THREAD

**Issue by jorisdesmedt** [dangrossman/bootstrap-daterangepicker#1256]
I am using MomentJs to localise my dates and when I use a Spanish locale I see following bugs.
In the screenshot below I selected from the 1st of february until the 31th of May. As you can see you see twice the month March, and when you click the next month arrow he jumps to May instead of April.

![image](https://cloud.githubusercontent.com/assets/11277191/19067769/e52cc56e-8a1f-11e6-83b8-18e62150959c.png)

Also when I move ahead a few months I get an invalid date for the month October as you can see in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/11277191/19067898/7856a5b2-8a20-11e6-9539-d6a3b45a6b9b.png)

Also using moment timezone I use a different timezone than my pc's timezone.

**Comment by dangrossman** [comment]
Feel free to try to fix this and send a PR
