### ISSUE TITLE
How to put only start-date in input field after selection

### ISSUE THREAD

**Issue by Necromant1k** [dangrossman/bootstrap-daterangepicker#1259]
hello. i need a help 
is it possible to put only start date from date range picker? after selection 
i no need to show start - end dates 
i need only Start date to show in my input field after selection 
Thank you!

**Comment by dangrossman** [comment]
```
$('#yourelement').daterangepicker({
  autoUpdateInput: false
}, function(start, end, label) {
  $('#yourelement').val(start.format('MM/DD/YYYY'));
});
```
