### ISSUE TITLE
Show chosen date range label as text input value

### ISSUE THREAD

**Issue by ddavydov** [dangrossman/bootstrap-daterangepicker#1260]
I have a project where we have daterangepicker with some predefined ranges like `Today`, `Yesterday`, `This Week`, and we found that in some cases it's better to see the chosen range as a label, not as actual date. For example when choosing `Today` the input should have its label as a value:
![environet 2016-10-05 15-33-14](https://cloud.githubusercontent.com/assets/511782/19113164/0e08c1e4-8b11-11e6-9692-345651748f73.png)

Does it make sense to have such feature, so this behaviour will be handled by passing some configuration option? I can create PR if needed.

**Comment by dangrossman** [comment]
No new options are needed to accomplish this. Put the label into your input/element in your callback function or `apply.daterangepicker` event listener. Example:

````
$('#yourelement').daterangepicker({
  autoUpdateInput: false,
  ranges: {
    'Today': [..., ...],
    'Yesterday': [..., ...]
  }
}, function(start, end, label) {
  $('#yourelement').val(label);
});
````

**Comment by paveldvorak5** [comment]
How can I replace custom range label with the actual date range? Comparing text is not an option. Mayle label should be empty when it's custome range.
