### ISSUE TITLE
Is there a way to highlight the region between two dates in a custom date range?

### ISSUE THREAD

**Issue by blairg23** [dangrossman/bootstrap-daterangepicker#1262]
I'd like to see the dates between two dates in a custom date range highlighted, similar to this example: 

http://jsfiddle.net/o96fjdbk/

Is there currently a way to do this or can you provide one?

**Comment by dangrossman** [comment]
The selected date range is already highlighted. You don't need to do anything special.

http://www.daterangepicker.com/

**Comment by blairg23** [comment]
I don't see the highlighting... it just shows the start date and end date highlighted, not the dates in between. Did you see my example in jsfiddle?

**Comment by dangrossman** [comment]
The dates in between are highlighted. If you don't see it, perhaps adjust your monitor settings.

**Comment by blairg23** [comment]
Oh wow, yeah it's very light. Is it possible to adjust those settings via a CSS setting or something?

**Comment by dangrossman** [comment]
Yep

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.scss
