### ISSUE TITLE
Yesterday button not highlighting with time selector

### ISSUE THREAD

**Issue by VinothiniBalakrishnan** [dangrossman/bootstrap-daterangepicker#1263]
This is not an issue. I need below kind of implementation. If anyone knows how to achieve this please let me know.

Initial requirement is show buttons to select yesterday, today, last 7 days and so on up to 1 year and custom date. I am done with that. Please see this fiddle https://jsfiddle.net/r7mfdtpe/2/ for demo. when we open the calendar yesterday should be highlighted.

After that requirement changed to show HH:MM dropdown When user choose custom button. So I changed the implementation to like this fiddle https://jsfiddle.net/z4bsL2ce/2/. My problem is after introduce timePicker: true Yesterday button not highlighting when open calendar first time. I tried to change

> var startDate = moment().subtract(1, 'd')
> var endDate = moment().subtract(1, 'd')

to like

> 
> var startDate = moment().subtract({hours: XX, minutes: XX, seconds: XX});
> var endDate = moment().subtract({hours: XX, minutes: XX, seconds: XX});
> 
> var startDate = moment().subtract(XX, 'hours')
> var endDate = moment().subtract(XX, 'hours')

I don't have any clue on why yesterday is not highlighting.

**Comment by dangrossman** [comment]
This makes yesterday highlighted, by making sure time portion of the dates match:

https://jsfiddle.net/z4bsL2ce/5/

**Comment by VinothiniBalakrishnan** [comment]
Thank you so much @dangrossman
