### ISSUE TITLE
Update event for hovered date within picker?

### ISSUE THREAD

**Issue by spandadk** [dangrossman/bootstrap-daterangepicker#1265]
Not a bug, but clarification.

I have autoUpdateInput set to false and am updating two separate input fields with the chosen to/from date from the picker as so:

$('.date-range-picker').on('apply.daterangepicker', function(ev, picker) {
	$('.date-range .date-from').val(picker.startDate.format('DD-MM-YYYY'));
	$('.date-range .date-to').val(picker.endDate.format('DD-MM-YYYY'));
});

Do any update event exist that would allow me to update the input value with the date being hovered (just like you do within the picker)?

**Comment by dangrossman** [comment]
No, there's no event like that. You will need to edit the library to incorporate your inputs if you want that behavior. Good thing it's open source and you can do that easily!
