### ISSUE TITLE
AngularJS Floating labels overlap

### ISSUE THREAD

**Issue by kroese** [dangrossman/bootstrap-daterangepicker#1268]
When using this control in combination with AngularJS floating labels, after selecting the date, the text will overlap the label because the label doesn't float upwards. But if you click again inside the textbox when this happens, the label does float away and the overlap is gone. 

So it seems the Daterangepicker is not generating the necessary events (like onChange) for Angular to detect that the inputbox is not empty anymore, and it will only detect the input is changed after the next click.

Does anyone how I can force this event? For example by manually firing `'onchange'` from the `'apply.daterangepicker'` event?

**Comment by dangrossman** [comment]
Sorry, but I don't know anything about Angular and don't intend to learn it to answer your question. Feel free to try adding whatever events you think are necessary, and if they work, I'd be happy to take a PR that adds that tweak for Angular users.
