### ISSUE TITLE
update to bootstrap 4?

### ISSUE THREAD

**Issue by bona1337** [dangrossman/bootstrap-daterangepicker#1271]
Hello there,

is there a plan to update the daterangepicker to bootstrap 4? 
I know its still alpha but... setting up a new project with angular2 and bootstrap version 3 right now makes no sense to me.. so we are using the alpha version... would be nice to have the daterangepicker (which is definitly needed - don't know why hundreds of online-booking-portals still use a self made "daterangepicker" which looks absolutly awful)

is there such a plan on the roadmap or?

**Comment by dangrossman** [comment]
This library doesn't actually use anything in Bootstrap except the default styles

So you can use it with Bootstrap 4, or without Bootstrap, by adding a few things to your stylesheet

There is no roadmap, this is just a side project I needed for a website 4 years ago

If it's easy to adapt the CSS for Bootstrap 4, I'm sure I'll add in a stylesheet for it after that's out
