### ISSUE TITLE
Copying the start and end dates to other text field inputs

### ISSUE THREAD

**Issue by mistaq** [dangrossman/bootstrap-daterangepicker#1272]
Using the daterangepicker, after setting a date range, I would like to copy both the starting and ending dates and put them into other text field inputs with JavaScript/jQuery. 

Coding wise, it's as it stands via this StackOverflow [link](http://stackoverflow.com/questions/40021126/daterangepicker-copying-field-input-to-another-field-input). Another user there has provided a way of getting the start date, but not the end date unfortuanately (nevertheless, this is useful for if I want to just have a single date picker rather than a range).

**Comment by dangrossman** [comment]
The end date is in `picker.endDate` in that code, just like `picker.startDate` was used.

You can also just put the code in your callback.

````
$(yourelement).daterangepicker({
  //options
}, function(start, end, label) {
  $('#other_text_field_1').val(start);
  $('#other_text_field_2').val(end);
});
````

**Comment by mistaq** [comment]
Oh thanks. One thing - I tried this out with a slightly different input and it didn't work:

In the JS:

$("#sessions.0.date_start").val(picker.startDate.format('DD/MM/YYYY'));

In the Bootstrap:

<input type="text" name="sessions.0.date_end" id="sessions.0.date_start" value="" />

It seems as if the id is incompatible with the JS.

**Comment by dangrossman** [comment]
That is a jQuery limitation, nothing specific to this library or bootstrap. Here is the documentation:

https://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/
