### ISSUE TITLE
[Question] - Way to set global defaults?

### ISSUE THREAD

**Issue by stephenycchang** [dangrossman/bootstrap-daterangepicker#1276]
Is there a way to set global defaults? 
I use this throughout different views but would prefer not to initialize and pass in the defaults each time. 

Would I be able to target a class selector with an on() to initialize dynamically when I ajax other views in?

Thanks!

**Comment by dangrossman** [comment]
No

But you can always edit your copy of daterangepicker.js to have your defaults in it

**Comment by alexkb** [comment]
@dangrossman wouldn't *"But you can always edit your copy of daterangepicker.js to have your defaults in it"* take you off the upgrade path?

There's a [PR](https://github.com/dangrossman/daterangepicker/pull/897) to do this, but it's a few years old now. Any reason why this was never merged or why you've never implemented support for this in the past? Having a global config object for options (as you suggested in #1571) doesn't seem like good practice to me?

**Comment by dangrossman** [comment]
This was added last year

https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js#L1513

https://github.com/dangrossman/daterangepicker/releases/tag/v2.1.26

Sorry it's not well documented
