### ISSUE TITLE
Bug in October Month

### ISSUE THREAD

**Issue by rafaelharus** [dangrossman/bootstrap-daterangepicker#1277]
When selected in October the initial and final day, the plugin skips one day, for example, selected day 16 and it automatically changes the end date to day 17. This happens every year only in October.

**Comment by dangrossman** [comment]
I cannot reproduce that. It must be locale-dependent. October 16th is the day of daylight savings time in Brazil, but not where I live. Feel free to try to fix it...

**Comment by rafaelharus** [comment]
Ok!, thks...
