### ISSUE TITLE
How to add custom class to daterangepicker? 

### ISSUE THREAD

**Issue by Necromant1k** [dangrossman/bootstrap-daterangepicker#1278]
Hello. 
How i can add custom class to daterangepicker ( to main div , where days inputs and etc.) 
i want to make his postion not absolute. 
Thanks !

**Comment by dangrossman** [comment]
Edit daterangepicker.js or template option

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L96

**Comment by shusharin** [comment]
`$(".daterangepicker").daterangepicker({
                    locale: {
                        direction: 'some-css-class'
                    }
                });`

**Comment by shusharin** [comment]
Or in daterangepicker.js after 167 line add:

`if (typeof options.customClass === 'string') this.customClass = options.customClass;`        
` this.container.addClass(this.customClass);`

And initialize: 
`$(".daterangepicker").daterangepicker({ customClass: 'some-css-class' });`

**Comment by dimanbulgar** [comment]
var picker = $('#selector').daterangepicker().data('daterangepicker');
picker.container.addClass('daterangepicker_custom_class');

**Comment by lcmandujanoa** [comment]
Using jquery and Boostrap's date range picker you can find those elements by order after the page is loaded and add a custom class. I used the following code: 
`$(document).ready(function () {
            $('body').find('.daterangepicker').eq(0).addClass('customClassOne');
            $('body').find('.daterangepicker').eq(1).addClass('customClassTwo');
        });`

**Comment by faisal3956** [comment]
> Using jquery and Boostrap's date range picker you can find those elements by order after the page is loaded and add a custom class. I used the following code:
> `$(document).ready(function () { $('body').find('.daterangepicker').eq(0).addClass('customClassOne'); $('body').find('.daterangepicker').eq(1).addClass('customClassTwo'); });`

this is out of the box solution thanks
