### ISSUE TITLE
New option for open position in a modal center dialog

### ISSUE THREAD

**Issue by dpmontero** [dangrossman/bootstrap-daterangepicker#1279]
Hi!

I suggest a new option for open daterangepicker position inside in a modal bootstrap dialog center screen, for example like this:
![modal date dialog](https://cloud.githubusercontent.com/assets/16160165/19603935/591cae4e-97b3-11e6-9965-2070a6952e04.png)

Good job!

**Comment by dangrossman** [comment]
Cool. Fork and make a "modal date picker" plugin. I'm not making one :)
