### ISSUE TITLE
Option to disable subsequent from - to - from date selection

### ISSUE THREAD

**Issue by baconalot** [dangrossman/bootstrap-daterangepicker#1281]
The current implementation for selecting a custom date range is switching between the from and to date input fields where the one that is being updated is the one that is currently selected (blue border). This is very counter intuitive since selecting a date on the right calendar can update the `from` date and vice versa.  
I would like a option were I can disable this so that the behavior would be: select date on left calendar -> from date updated; select date on right calendar -> to date is updated

**Comment by dangrossman** [comment]
Here you go, download v1: https://github.com/dangrossman/bootstrap-daterangepicker/releases/tag/v1.3.23
