### ISSUE TITLE
How to set a minimum date range limit?

### ISSUE THREAD

**Issue by sitehopper** [dangrossman/bootstrap-daterangepicker#1282]
Is there a way to set a minimum date range limit? For example, I want to set minimum limit of 3 days so date the user can only select a date range of 3 days or more.

**Comment by dangrossman** [comment]
There is not an option for that, you have to code it yourself

**Comment by sitehopper** [comment]
Clear. thanks for the answer!

**Comment by ChristianLJ** [comment]
@sitehopper did you manage to do this? I am looking for this option as well.

**Comment by rbijkercom** [comment]
@ChristianLJ 
I created the function `customRangeSearch`  that you can add to the `beforeShow` option of the datepicker.
You can see it in action on https://oceantrips.com/

```
function customRangeSearch(input) {
   if (input.id == 'to') {
       var minDate = new Date($('#from').val());
       minNrDays = 3;
       minDate.setDate(minDate.getDate() + minNrDays);
       return {
           minDate: minDate
       };
   }
   return {}
}

$('.tour-search-form #from, .tour-search-form #to').datepicker({
   beforeShow: customRangeSearch,
});
```
