### ISSUE TITLE
Ranges Option sometime missing

### ISSUE THREAD

**Issue by tanghoong** [dangrossman/bootstrap-daterangepicker#1284]
Hi, my range options set as below. But when i initial load different date value into page, range option sometime will missing from list. Would be good if always show those options.

`    ranges: {
       'Last 7 Days': [moment().subtract(6, 'days'), moment()],
       'Last 30 Days': [moment().subtract(29, 'days'), moment()],
       'Last 60 Days': [moment().subtract(59, 'days'), moment()],
       'Last 90 Days': [moment().subtract(89, 'days'), moment()],
       'This Month': [moment().startOf('month'), moment().endOf('month')],
       'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
    }
`
Normal:
![normal_range_option](https://cloud.githubusercontent.com/assets/4799387/19797211/49e7db2e-9d1c-11e6-81c9-4626c06fcc61.png)

No normal:
![missing_range_option](https://cloud.githubusercontent.com/assets/4799387/19797230/65bbae02-9d1c-11e6-8727-6171e8952179.png)

**Comment by dangrossman** [comment]
I see some crossed out dates in that screenshot. Any `minDate` or `maxDate` you set is going to apply to predefined ranges as well. They're being hidden because the date ranges they represent are not valid according to your options.

**Comment by tanghoong** [comment]
Thanks @dangrossman  for the reply. Ya, its does affected when the maxDate option was set.
It is intelligent design to detect if the date ranges they represent are not valid.

Here is the simulate for the issues.
http://codepen.io/tanghoong/pen/mrZxGx?editors=1010

**Comment by tanghoong** [comment]
@dangrossman , Issue solved. Inside ranges option , i should use *moment(maxDate)* instead of *moment()*.
