### ISSUE TITLE
Calendar "from" date selection reset when input has focus

### ISSUE THREAD

**Issue by GeorgeKagan** [dangrossman/bootstrap-daterangepicker#1285]
Hello,

As can be seen on the demo on the official website: http://www.daterangepicker.com/#config

1) Open the date range picker.
2) Click inside any of the 2 text inputs.
3) Now select a "from" date and then a "to" date.

**Result**: second click resets the previous "from" selection.
**Should be**: second click selects the "to" date.

Is it a known problem? Or is it a feature?
Thanks

Video of the steps:
[nimbus-video.zip](https://github.com/dangrossman/bootstrap-daterangepicker/files/560434/nimbus-video.zip)

**Comment by dangrossman** [comment]
Looks like a bug

**Comment by timenomad** [comment]
OK, do you have time to fix it?
Or maybe I try it myself and create a pull request?

**Comment by giladmatko** [comment]
Hi @dangrossman .
I've encountered the same problem.
Do you have any idea when it is about to be fixed?

Thanks!

**Comment by asurabhi** [comment]
Just encountered the issue.
When can we expect the fix?

**Comment by dangrossman** [comment]
You should not expect a fix unless you program it

There is nobody with committed time to this 4-year-old open source repository
