### ISSUE TITLE
How to set minimum range from minDate?

### ISSUE THREAD

**Issue by mrdubz** [dangrossman/bootstrap-daterangepicker#1287]
Now I can choose two of the same date. 
How to set a minimum of days in range?

Thanks

**Comment by dangrossman** [comment]
There is no option for that, you have to program it yourself

**Comment by mrdubz** [comment]
So, this worked for me)

.start-date.in-range {
	pointer-events: none;
}

**Comment by jpspringall** [comment]
Hi mrdubz,

I'm trying to do the same thing, but you give the full example of where you used:

.start-date.in-range {
pointer-events: none;
}

I looked in the documentation but couldn't find it.

Cheers

James

**Comment by mrdubz** [comment]
Hi, James
Thats all. Just add this in your stylesheets
