### ISSUE TITLE
Set min/max hours enabled

### ISSUE THREAD

**Issue by odecharette** [dangrossman/bootstrap-daterangepicker#1288]
Hi

First, thanks for this awesome plugin !
I use the Date and Time Range picker
Is it possible to set min and max for times ?

Thanks !

![2016-11-02_13h58_19](https://cloud.githubusercontent.com/assets/18335078/19929636/8bb24abc-a104-11e6-8bce-afdb63c8e705.png)

**Comment by dangrossman** [comment]
No
