### ISSUE TITLE
Update documentation - drp-snippet-3-js

### ISSUE THREAD

**Issue by webdevnerdstuff** [dangrossman/bootstrap-daterangepicker#1292]
On your webpage, for the example of set start and end date you have the following example:
https://gist.github.com/dangrossman/e1a8effbaeacb50a1e31#file-drp-snippet-3-js

This example is missing the locale > format option to make it work out of the box. Otherwise the following is needed for it to work:

The - in the date should be a forward slash / and the numbers switched around. I'm using this along with moment. Using the current example it outputs "Invalid Date".

daterangepicker: v2.1.24
moment: v2.15.2

```
//create a new date range picker
$('#daterange').daterangepicker({ startDate: '03/05/2005', endDate: '03/06/2005' });

//change the selected date range of that picker
$('#daterange').data('daterangepicker').setStartDate('03/01/2014');
$('#daterange').data('daterangepicker').setEndDate('03/31/2014');
```

**Comment by dangrossman** [comment]
Thanks
