### ISSUE TITLE
Unable to install using Bower

### ISSUE THREAD

**Issue by gbarrigap** [dangrossman/bootstrap-daterangepicker#1297]
When I try to install using bower, the following messages are displayed:

    $ bower install bootstrap-daterangepicker
    bower bootstrap-daterangepicker#*           cached https://github.com/dangrossman/bootstrap-daterangepicker.git#2.1.24
    bower bootstrap-daterangepicker#*         validate 2.1.24 against https://github.com/dangrossman/bootstrap-daterangepicker.git#*
    bower jquery#1.9.1 - 2                      cached https://github.com/jquery/jquery-dist.git#2.2.4
    bower jquery#1.9.1 - 2                    validate 2.2.4 against https://github.com/jquery/jquery-dist.git#1.9.1 - 2
    bower jquery#1.9.1 - 3                      cached https://github.com/jquery/jquery-dist.git#3.1.1
    bower jquery#1.9.1 - 3                    validate 3.1.1 against https://github.com/jquery/jquery-dist.git#1.9.1 - 3
    bower jquery#>=1.8.3                        cached https://github.com/jquery/jquery-dist.git#3.1.1
    bower jquery#>=1.8.3                      validate 3.1.1 against https://github.com/jquery/jquery-dist.git#>=1.8.3
    bower jquery#>=1.7                          cached https://github.com/jquery/jquery-dist.git#3.1.1
    bower jquery#>=1.7                        validate 3.1.1 against https://github.com/jquery/jquery-dist.git#>=1.7
    bower                                    ECONFLICT Unable to find suitable version for jquery

I have `jquery#3.1.1` on my installation.

The `bower.json` file on this repo shows this dependency on jQuery: `"jquery": "1.9.1 - 3"`

Is it ignoring the newer versions of jQuery?

**Comment by dangrossman** [comment]
This is the same dependency the Bootstrap library itself has

https://github.com/twbs/bootstrap/blob/v4-dev/bower.json

**Comment by gbarrigap** [comment]
You're right, Dan! I will clone directly with git, for the time being.

Thanks!

**Comment by gbarrigap** [comment]
Dan, double checking this issue, I came to the realisation that bower is using the last tagged version, which currently is v2.1.24, and in that version, the bower.json file indicates `"jquery": "1.9.1 - 2"` instead of `"jquery": "1.9.1 - 3"`, as stated in master.

Check it out!

[v2.1.24](https://github.com/dangrossman/bootstrap-daterangepicker/blob/v2.1.24/bower.json)
[master](https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/bower.json)
