### ISSUE TITLE
Re initiation didn't change the ranges from the date picker

### ISSUE THREAD

**Issue by arojohnson** [dangrossman/bootstrap-daterangepicker#1298]
Hey there,

I am using date range picker, I need to change the ranges dynamically. When I do it by manually the UI is not changing. Could you please help me?

`ranges: {}` - I am updating this key with my dynamically generated object. But not UI not changing

**Comment by dangrossman** [comment]
To change options, call $(element).daterangepicker(options) a second time, the same way you initially created it.
