### ISSUE TITLE
Date picker is broken when maxDate is before current date

### ISSUE THREAD

**Issue by minhnq013** [dangrossman/bootstrap-daterangepicker#1304]
This happened with the following options: 
- maxDate is before currentDate.
- SingleDatePicker
- TimePicker

```
$('#demo').daterangepicker({
    "singleDatePicker": true,
    "timePicker": true,
    "startDate": "11/15/2016",
    "endDate": "11/21/2016",
    "maxDate": "2/2/2000"
}, function(start, end, label) {
  console.log("New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')");
});
```

The date picker will display NaN for all date selection. 
I traced the code and find out that when singleDatePicker is true, "endDate" is set to equal to "startDate".  With timePicker enabled, the script check and see that "endDate" is after "maxDate" and timePicker initial value will be disabled, this later on also break "calendar" parsing and output every date selection as NaN.

**Comment by dangrossman** [comment]
Garbage in, garbage out. Don't set a startDate that shouldn't be selectable.

**Comment by minhnq013** [comment]
Sorry I forgot to mention, even without setting the startDate/EndDate (and that is the actual situation I want to reproduce but the demo box set start/end date by default).

Without setting the start/end date, date-range-picker will set them to current date by default, which cause the problem. 

Maybe the start/end date can be set to the input max/min date when:
- A min or max is is provided.
- Start/end date are not set.

**Comment by jeyakrishnanp** [comment]
@dangrossman - Still getting the same error even after try with suggestion

**Comment by jeyakrishnanp** [comment]
@minhnq013 - Do you have any solution for this, or do you fixed this

**Comment by dangrossman** [comment]
There is no such error/bug to solve. If you set a maxDate in the past without a startDate/endDate, they get set to the maxDate as well. 

![ss](https://cloud.githubusercontent.com/assets/407706/26695128/b383d8a2-46d7-11e7-9218-02b64103bb7c.png)

**Comment by jeyakrishnanp** [comment]
@dangrossman 

if (scope.startDate) {
            debugger;
              configuration.startDate = scope.startDate;
            }
            if (scope.endDate) {
              configuration.endDate = scope.endDate;
            }
            debugger;
            if (scope.minDate) {
              configuration.minDate = scope.minDate;
            }
            if (scope.maxDate) {
              configuration.maxDate = moment(scope.maxDate);
            }

            configuration.autoApply = true;

            if (scope.datePickerType == 'Single') {
                configuration.singleDatePicker = true;
            }

            if (scope.timePicker) {
                configuration.timePicker = true;
                configuration.timePickerSeconds = true;
                configuration.autoApply = false;
            }

            if (scope.hourFormat == "24") {
                configuration.timePicker24Hour = true;
            }

            if (scope.customRanges && scope.dateLimit) {

                configuration.dateLimit = {
                    'days': scope.dateLimit
                };
                if (Number(configuration.dateLimit.days) == 0 || isNaN(configuration.dateLimit.days)) {
                    delete configuration.dateLimit;
                }
            }

            configuration.opens = "right";
            configuration.drops = "down";
            //configuration.locale = {};
            configuration.locale = lcI18n.getLocalizedValue("lcList.dateRangePickerLocale");
            configuration.locale.format = moment.localeData().longDateFormat(i18nDate) + ' ' + moment.localeData().longDateFormat(i18nTime);
            if (scope.datePickerType == 'Range') {
                if (scope.customRanges) {
                    configuration.ranges = {};
                    configuration.ranges[configuration.locale['Last Month']] = [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')];
                    configuration.ranges[configuration.locale['Last 3 Months']] = [moment().subtract(3, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')];
                    configuration.ranges[configuration.locale['Last 6 Months']] = [moment().subtract(6, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')];
                    configuration.ranges[configuration.locale['Last 12 Months']]= [moment().subtract(12, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')];
                }
            }
            configuration.showDropdowns = true;
            configuration.linkedCalendars = false;


> above is my directive using date range picker, but getting NaN, when setting past date as max date

**Comment by jeyakrishnanp** [comment]
@dangrossman ^^ do you have any idea on the above configuration, why it showing NaN

**Comment by dangrossman** [comment]
No, because the above configuration has a bunch of variables whose values I don't know.

**Comment by jeyakrishnanp** [comment]
@dangrossman 
Please find below is configuration

{  
   "maxDate":"2017-05-27T19:26:14.000Z",
   "autoApply":false,
   "timePicker":true,
   "timePickerSeconds":true,
   "timePicker24Hour":true,
   "opens":"right",
   "drops":"down",
   "locale":{  
      "separator":" - ",
      "applyLabel":"Apply",
      "cancelLabel":"Cancel",
      "fromLabel":"From",
      "toLabel":"To",
      "customRangeLabel":"Custom",
      "daysOfWeek":[  
         "Su",
         "Mo",
         "Tu",
         "We",
         "Th",
         "Fr",
         "Sa"
      ],
      "monthNames":[  
         "Jan",
         "Feb",
         "Mar",
         "Apr",
         "May",
         "Jun",
         "Jul",
         "Aug",
         "Sep",
         "Oct",
         "Nov",
         "Dec"
      ],
      "Today":"Today",
      "Yesterday":"Yesterday",
      "Last 7 Days":"Last 7 Days",
      "Last 30 Days":"Last 30 Days",
      "Last Month":"Last Month",
      "Last 3 Months":"Last 3 Months",
      "Last 6 Months":"Last 6 Months",
      "Last 12 Months":"Last 12 Months",
      "This Month":"This Month",
      "firstDay":1,
      "format":"MM/DD/YYYY h:mm:ss A"
   },
   "ranges":{  
      "Last Month":[  
         "2017-05-01T04:00:00.000Z",
         "2017-06-01T03:59:59.999Z"
      ],
      "Last 3 Months":[  
         "2017-03-01T05:00:00.000Z",
         "2017-06-01T03:59:59.999Z"
      ],
      "Last 6 Months":[  
         "2016-12-01T05:00:00.000Z",
         "2017-06-01T03:59:59.999Z"
      ],
      "Last 12 Months":[  
         "2016-06-01T04:00:00.000Z",
         "2017-06-01T03:59:59.999Z"
      ]
   },
   "showDropdowns":true,
   "linkedCalendars":false
}

**Comment by dangrossman** [comment]
I just used your config, copied and pasted no changes, and there's no problem with the picker it creates:

![ss](https://cloud.githubusercontent.com/assets/407706/26697584/97610506-46e0-11e7-92e0-97e552731cb7.png)

**Comment by dangrossman** [comment]
And working with maxDate: moment()

![ss](https://cloud.githubusercontent.com/assets/407706/26697660/cbe1787e-46e0-11e7-8e14-b55651b6cdeb.png)

**Comment by jeyakrishnanp** [comment]
@dangrossman Yes I too agree, it is working for moment(), but if I give moment().subtract(5, 'days') it is not working. that time only it is showing NaN for me

**Comment by dangrossman** [comment]
If you provide a startDate and endDate equal or before that maxDate, there is no problem again

**Comment by jeyakrishnanp** [comment]
@dangrossman - Thanks, It is working for me.

**Comment by raheel-te** [comment]
@dangrossman this is showing the NaN values only for the January for me.
<img width="708" alt="screen shot 2017-09-18 at 10 02 50 am" src="https://user-images.githubusercontent.com/20162504/30529618-b044fdd4-9c58-11e7-8bf6-c269d66db259.png">

My code is 
<img width="694" alt="screen shot 2017-09-18 at 10 02 14 am" src="https://user-images.githubusercontent.com/20162504/30529623-bc67ef5e-9c58-11e7-9041-6012cbd2230b.png">

**Comment by dangrossman** [comment]
"format" is a part of the locale object, not a top level option

"firstDay" can be 0-6 I believe, 7 is not valid

I don't know what's in your "from" and "to" to know if they are valid

**Comment by csiszarattila** [comment]
There is a small issue if you only set maxDate to a past date, then startDate dont respect that and will be set to current date. 

You can reproduce this:

$('#demo').daterangepicker({
    "endDate": "12/15/2017",
    "maxDate": "10/11/2017"
}, function(start, end, label) {
  console.log("New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')");
});

If startDate is not given by config, then it should respect the maxDate when setting it to a default value.
Note: endDate respect maxDate

**Comment by suneethap** [comment]
{
  "locale": {
    "format": "MMM DD, YYYY hh:mm A"
  },
  "showDropdowns": true,
  "opens": "right",
  "drops": "down",
  "timePicker": true,
  "parentEl": "#mainContent",
  "startDate": "Mar 15, 2019 06:34 PM",
  "endDate": "Mar 15, 2019 06:34 PM",
  "minDate": "Jan 07, 2019 04:11 PM",
  "maxDate": "Jan 16, 2019 04:11 PM"
}

**Comment by dangrossman** [comment]
This code actually doesn't display NaN on the current version of this library, though it probably should! Don't set options that conflict and you won't break it. Your startDate and endDate are after your maxDate. You're the developer, you're responsible for writing sane code.
