### ISSUE TITLE
times not showing up in date range

### ISSUE THREAD

**Issue by bnowacky** [dangrossman/bootstrap-daterangepicker#1305]
https://jsfiddle.net/bnowacky/m0ac1bfb/

Page Features: 
- Multiple date pickers.
- Ability to create fields dynamically. 
- Date picker added to each field dynamically.

Problems: 
- The time is not showing up in the date picker field. But if you do $(this_field).val(), the corrected value is there. 
- Trying to do $(this_field).data('daterangepicker'), but value returns undefined. (trying to remove date picker as the 'minus' is clicked and those elements are removed from the page. 

I'm sure I'm missing something small, but I've seen this same behavior in the fiddle as well as my page i"m building out. I've seen similar behavior on the demo site on the 'customizer field.

Any idea what I'm missing?

**Comment by dangrossman** [comment]
> The time is not showing up in the date picker field

You wrote this code which puts only the date in the field

````
$('.js_datepicker').on('apply.daterangepicker', function(ev, picker) {
     $(this).val(picker.startDate.format('MM/DD/YYYY') + ' - ' + picker.endDate.format('MM/DD/YYYY'));
   });
````

> Trying to do $(this_field).data('daterangepicker'), but value returns undefined

I don't see that code

**Comment by bnowacky** [comment]
Holy crap! I can't believe I missed something so stupid !!! Sorry for the waste of time. 

Data.remove() : I added it in the binding on the 'minus' click, but it's not a huge deal. Just trying to keep the DOM clean if possible. 

Thanks for pointing out something so obvious I should have caught it. I'm going to go cry in a corner as everyone points and calls me 'noob'
