### ISSUE TITLE
Issues with calendar hiding when use custom ranges

### ISSUE THREAD

**Issue by gtsvetanov** [dangrossman/bootstrap-daterangepicker#1307]
Hello, first of all I want to say "Thank you" for this beauty full with nice options for customization.

Before explanation of my post I wanna say that I'm not using bootstrap with for this widget (not all of bootstrap, because it's too heavy for simple date range picker as in my case). 

So the problem I've saw is when I change ranges to use start of day and end of day and here is my options for widget:
```
var dateRangePickerOptions = {
	'showDropdowns': true,
	'timePicker': true,
	'timePicker24Hour': true,
	'autoApply': true,
	'ranges': {
		'Today': [moment().startOf('day'), moment().endOf('day')],
		'Yesterday': [moment().subtract(1, 'days').startOf('day'), moment().subtract(1, 'days').endOf('day')],
		'Last 7 Days': [moment().subtract(6, 'days').startOf('day'), moment().endOf('day')],
		'Last 30 Days': [moment().subtract(29, 'days').startOf('day'), moment().endOf('day')],
		'This Month': [moment().startOf('month').startOf('day'), moment().endOf('month').endOf('day')],
		'Last Month': [moment().subtract(1, 'month').startOf('month').startOf('day'), moment().subtract(1, 'month').endOf('month').endOf('day')]
	},
	'maxDate': moment().endOf('day').format('MM/DD/YYYY H:mm'),
	'opens': 'center',
	'locale': {
		customRangeLabel: 'Custom range',
		format: 'MM/DD/YYYY H:mm',
		'daysOfWeek': [
			'Su',
			'Mo',
			'Tu',
			'We',
			'Th',
			'Fr',
			'Sa'
		],
		'monthNames': [
			'January',
			'February',
			'March',
			'April',
			'May',
			'June',
			'July',
			'August',
			'September',
			'October',
			'November',
			'December'
		],
		'firstDay': 1
	},
};
```

Before that my widget looks like this:
![before change](https://cloud.githubusercontent.com/assets/12787187/20621056/71e50972-b305-11e6-8869-c3775d0c6b9c.png)

After change it looks like this (after adding .startOf('day') and .endOf('day') in ranges as it is on sample code):
![after change](https://cloud.githubusercontent.com/assets/12787187/20621057/71e745e8-b305-11e6-8a33-6a60b9974eaf.png)

As I can see on daterangepicker element there is a missing class "show-calendar", so I decide to made a simple fix in my case with adding this:
`$('.daterangepicker').addClass('show-calendar');`

Also I use the same code when someone select range directly from ranges because after that when I open the widget again I had the same situation. So I add this code:
```
$('.dateRangePickerInput').on('apply.daterangepicker hide.daterangepicker', function(ev, picker) {
	$('.daterangepicker').addClass('show-calendar');
});
```

I hope this will help to improve the library. Also as attached file you can find a minimal CSS required in my case, so if you don't want use whole Bootstrap you can use it but I think you may change a lot of selectors which selecting all elements as inputs, selects and etc starting with ".daterangepicker".
[daterangepicker-css.zip](https://github.com/dangrossman/bootstrap-daterangepicker/files/612978/daterangepicker-css.zip)

P.s. - On screenshots you'll see some translated texts on my mother language so look at the code if this can confuse you :)

Thanks again for this library and sorry for my English :) 

Best regards,
Georgi!

**Comment by dangrossman** [comment]
That is by design. The calendars are only shown when "Custom Range" gets clicked, not when a predefined range is selected.
