### ISSUE TITLE
Angular directive for bootstrap-daterangepicker is not working inside a modal

### ISSUE THREAD

**Issue by rahmonov** [dangrossman/bootstrap-daterangepicker#1309]
[Angular Daterange Picker](https://github.com/fragaria/angular-daterangepicker) (angular directive for bootstrap-daterangepicker) is working on other pages, except for inside [ngDialog](https://github.com/likeastore/ngDialog/) (a modal).

Giving me this error:

    el.daterangepicker is not a function

It is as if bootstrap-daterangepicker file was not included in HTML. 

What could be the problem?

Maybe there is a way to *restart* `bootstrap-daterangepicker` once the modal opens?

**Comment by dangrossman** [comment]
That other project is probably the place to ask

I know nothing about angular or nganything
