### ISSUE TITLE
Need to disable the 'Apply' button till the calendar is 'dirty'

### ISSUE THREAD

**Issue by VaibhavP17** [dangrossman/bootstrap-daterangepicker#1314]
Hi, 

I have a requirement to disable the 'apply' button if there are no changes in the calendar values. How can this be achieved ? Any pointers ?

Thanks in advance.

**Comment by dangrossman** [comment]
No, but good luck with that, I'm sure you'll figure it out

**Comment by satish9323** [comment]
Hi @VaibhavP17 , did u find out the solution?

**Comment by VaibhavP17** [comment]
@satish9323 I was manage to work out a solution but that is not on top my head right now. And I dont have access to the codebase which I was working upon at that time. :(
