### ISSUE TITLE
May Month shows invalid when having `firstDay` set to 7

### ISSUE THREAD

**Issue by AngeloAballe** [dangrossman/bootstrap-daterangepicker#1316]
<img width="645" alt="screen shot 2016-12-07 at 4 24 05 pm" src="https://cloud.githubusercontent.com/assets/8985783/20960083/99790a04-bc99-11e6-9d07-85799338536b.png">

This shows when I'm having locals in options.

**Comment by dangrossman** [comment]
7 is not a valid value. The weekdays are numbered 0 through 6.

**Comment by AngeloAballe** [comment]
Stupid mistake. Sorry mate!
