### ISSUE TITLE
Some functionalities not working in case of singleDatePicker

### ISSUE THREAD

**Issue by kuldeep-k** [dangrossman/bootstrap-daterangepicker#1317]
I trying to use daterangepicker as datetime picker, Which is working fine with following code.

      function openDatePicker(obj, extras)     {
         obj.daterangepicker({
                showDropdowns: true,
                autoUpdateInput: false,
                startDate: extras.date,
                singleDatePicker: true,
                timePicker: true,
                timePicker24Hour: true,
                applyClass: 'bg-slate-600',
                cancelClass: 'btn-default',
                locale: {
                    format: 'MM/DD/YYYY HH:mm'
                }
            });
      }

But I have some issues.

 1) First apply/cancel button not showing at all. 
 2) Second I need to set date after daterangepicker is applied example on some event. Following code I found not working.

          obj.daterangepicker({
                //showWeekNumbers: true,
                showDropdowns: true,
                autoUpdateInput: false,
                startDate: extras.date,
                singleDatePicker: true,
                timePicker: true,
                timePicker24Hour: true,
                applyClass: 'bg-slate-600',
                cancelClass: 'btn-default',
                locale: {
                    format: 'MM/DD/YYYY HH:mm'
                },
                //autoApply: false
            },
            function(chosen_date) {
                obj.val(chosen_date.format('MM/DD/YYYY HH:mm'));
            });

 Third I need to set one date field after choosing date from another field, Let say plus 5 day from chosen date. I tried event 'apply.daterangepicker' on first date which not executing when I close picker after click outside, Also i tried hide.daterangepicker which is executing but give empty date value.

I am using version 2.1.23

**Comment by dangrossman** [comment]
1. I used your code exactly, and the apply/cancel buttons are visible

2/3. Your callback function will be called whenever a _new_ date is chosen, and the `apply.daterangepicker` event will be triggered whenever the apply button is clicked. 

Clicking outside the date picker without making any change will not trigger either function, but there is no change to the date for you to react to so I don't know why it should.

If you want to get the picker's current date inside the hide event or any other code, you can do this:


````var selected = obj.data('daterangepicker').startDate;````

**Comment by kuldeep-k** [comment]
I am using bootstrap limit less theme (https://themeforest.net/item/limitless-responsive-web-application-kit/13080328). Look like they have modified css/js to suit their theme, which is causing issues as sample example works as you say.
