### ISSUE TITLE
DD MMM YYYY format works only for english. How to set locale for moment used?

### ISSUE THREAD

**Issue by ustaswolf** [dangrossman/bootstrap-daterangepicker#1320]
see http://jsfiddle.net/hdg79gf2/

**Comment by dangrossman** [comment]
I think this is what you need

http://momentjs.com/docs/#/i18n/loading-into-browser/

**Comment by ustaswolf** [comment]
I think No. I want to add multiple daterangepickers on same page with different languages. Please advice

**Comment by dangrossman** [comment]
I don't have any advice for you

**Comment by blackotruck** [comment]
@ustaswolf the momentjs docs does explain how to change locale locally, see [Changing locales locally 1.7.0+](http://momentjs.com/docs/#/i18n/instance-locale/).

Although I do get to change the moment locale, datarangepicker is showing undefined invalid dates.
