### ISSUE TITLE
detect whether date selected using ranges or calendars

### ISSUE THREAD

**Issue by asurabhi** [dangrossman/bootstrap-daterangepicker#1328]
Hi Dan!
Thanks for providing such a useful library. It saved lot of time for me. Due to some strange requirements, i need to detect whether date range is selected using ranges in dropdown or using calendars. Please let me know is it possible to get that info using library or is it easy to modify library to get that info.

**Comment by dangrossman** [comment]
```
$('#daterange').daterangepicker({
  ranges: {
     'Last 7 Days': [moment().subtract(6, 'days'), moment()],
    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
    'This Month': [moment().startOf('month'), moment().endOf('month')],
    'Last Month': [moment().subtract(1, 'month').startOf('month'), 
          moment().subtract(1, 'month').endOf('month')]
    }
}, function(start, end, label) {
    if (label == null || label == 'Custom Range')
        console.log("date selected in calendars");
});

```

**Comment by asurabhi** [comment]
This won't work with autoApply=false, right?

**Comment by dangrossman** [comment]
Yes it will

**Comment by asurabhi** [comment]
oh! This won't work for me. i have to use autoApply=true.

**Comment by dangrossman** [comment]
It works when autoapply = true or autoapply = false
