### ISSUE TITLE
Deprecation warning with moment 2.17.1

### ISSUE THREAD

**Issue by trsh** [dangrossman/bootstrap-daterangepicker#1334]
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: false, _f: undefined, _strict: undefined, _locale: [object Object]
Error

**Comment by dangrossman** [comment]
Are you using a very old copy of this library?

**Comment by trsh** [comment]
2.1.19. Should I upgrade?

**Comment by dangrossman** [comment]
Yes.
