### ISSUE TITLE
Week picker option

### ISSUE THREAD

**Issue by rtw-nz** [dangrossman/bootstrap-daterangepicker#1339]
Newbie here, not sure if this is how it works, but I'd like to add a week picker option, would a PR like that be considered for merging?

**Comment by dangrossman** [comment]
Probably not. It's only been requested one other time in 4 years as far as I can remember, so wouldn't be worth adding the extra complexity/maintenance to the library if so few will be using it.

**Comment by rtw-nz** [comment]
Ok, glad I checked before spending too much time on it. I'm quite keen to contribute in someway, I guess this is quite a mature project so might not the best place for a first timer to start contributing?
