### ISSUE TITLE
AM/PM output

### ISSUE THREAD

**Issue by askl56** [dangrossman/bootstrap-daterangepicker#1341]
Hey Dan,

Happy new year!

Great work on the plugin. Is there an easy way of implementing an AM/PM selector as opposed to the precise times?

Cheers,

Andrew

**Comment by dangrossman** [comment]
The time picker has an AM/PM selector by default, please clarify

**Comment by askl56** [comment]
Within the time picker you can select a time but i just want to select either AM or PM.

**Comment by dangrossman** [comment]
You'll need to make that yourself then

Perhaps just hide/rearrange the other select boxes with CSS
