### ISSUE TITLE
03/22 can not be selected

### ISSUE THREAD

**Issue by AliAkbarLatifi** [dangrossman/bootstrap-daterangepicker#1342]
Hey,

03/22 can not be selected for end date.

**Comment by dangrossman** [comment]
Yes it can

![ss2](https://cloud.githubusercontent.com/assets/407706/21742692/1f753986-d4c1-11e6-9748-d052b50621ae.PNG)

![ss1](https://cloud.githubusercontent.com/assets/407706/21742694/2441e680-d4c1-11e6-9873-db5daf621c21.PNG)

**Comment by AliAkbarLatifi** [comment]
Thanks for your answer.
I checked it again, The issue is related to time zone.
Please set your system time zone as Tehran-Iran and please let me know.

**Comment by dangrossman** [comment]
3/22 is the day daylight savings time goes into effect in Iran. I'm sure that's the cause. I don't know how to fix it, however.
