### ISSUE TITLE
Trigger apply when hitting Enter while in Input field

### ISSUE THREAD

**Issue by milankalinic** [dangrossman/bootstrap-daterangepicker#1344]
### Description
When autoapply option is enabled (so we do not see "apply" button) and user changes the dates in input boxes and then hit Enter, it only updates the calendar but does not trigger Apply on it. 

### Current behaviour
Manually changing the input start and end dates via keyboard, then hitting enter while focused in input box just updates the calendar selection.

### Expected behaviour
If user hits Enter while in start or end date, the calendar selection should be applied.

**Comment by dangrossman** [comment]
Please code this if you want it included
