### ISSUE TITLE
Start date and end date became the same after choose end date.

### ISSUE THREAD

**Issue by ryanouyang** [dangrossman/bootstrap-daterangepicker#1346]
![20170110203132](https://cloud.githubusercontent.com/assets/360426/21806409/0ae2f408-d774-11e6-83e5-c0b4f5d23e1b.jpg)

**Comment by MrHamaga** [comment]
Are you sure this isn't the same issue as described in the following pull request #1258? 

That what you see is the date you are currently hovering over.
