### ISSUE TITLE
Disabled Days

### ISSUE THREAD

**Issue by tbwnetwork** [dangrossman/bootstrap-daterangepicker#1347]
Is there anybody who needs this daterangepicker with the option to disable specific dates? I ask because i did some changes and now its possible to disable days.

if anybody needs/wants this option then i can upload the modified script

**Comment by ryanrishi** [comment]
I would love to see this!

**Comment by tbwnetwork** [comment]
[daterangepicker_mod.zip](https://github.com/dangrossman/bootstrap-daterangepicker/files/697376/daterangepicker_mod.zip)

use:
$('#selector').daterangepicker({
	"disabledDays":  new Array('02.20.2017','02.23.2017','02.25.2017')
});

i hope it helps anybody

**Comment by ryanrishi** [comment]
Nice! You should make a pull request to get this in. I suggest calling the property `disabledDates`, since `disabledDays` sounds more like Monday, Tuesday, etc.

On a related note, I'll probably make a PR for `disabledDays` with similar functionality, but takes in an array of days.

**Comment by tbwnetwork** [comment]
[daterangepicker_mod.zip](https://github.com/dangrossman/bootstrap-daterangepicker/files/698464/daterangepicker_mod.zip)
you're right. it make more sense to call it disabledDates. I have changed it. Use now:

$('#selector').daterangepicker({
"disabledDates": new Array('02.20.2017','02.23.2017','02.25.2017')
});

**Comment by tbwnetwork** [comment]
[daterangepicker_mod.zip](https://github.com/dangrossman/bootstrap-daterangepicker/files/698494/daterangepicker_mod.zip)

you're right. it make more sense to call it disabledDates. I have changed it. So, to disable dates use now:

$('#selector').daterangepicker({
"disabledDates": new Array('02.20.2017','02.23.2017','02.25.2017')
});

and to disable Week days use

$('#selector').daterangepicker({
"disabledDays": new Array('Mon','Tue','Wed') //Mon, Tue, Wed, Thu, Fri, Sat, Sun
});

**Comment by MrHamaga** [comment]
Does the dates follow the format specified in the locale, or always the format above (dd-mm-yyyy)?

**Comment by tbwnetwork** [comment]
the dates will follow the specified format in the locale

**Comment by dangrossman** [comment]
This option already exists, it's `isInvalidDate`

**Comment by bexvibi** [comment]
How can i disable weekdays except specified date ?

**Comment by dangrossman** [comment]
In your isInvalidDate function, return true if it's a weekday that is not the specified date.
