### ISSUE TITLE
date selected for start and end date is getting replaced by current date in incognito browser 

### ISSUE THREAD

**Issue by QMKhan** [dangrossman/bootstrap-daterangepicker#1351]
![image](https://cloud.githubusercontent.com/assets/17005790/21926026/1110ed92-d9a6-11e6-92c4-34390d8095bb.png)

when we are using web app in incognito mode the date selected for start and end date is getting replaced by current date in incognito browser 
in non incognito mode its working fine

**Comment by dangrossman** [comment]
Your screenshot shows a date range selected of 1/10/17 to 1/13/17. Your inspector shows the end date input within the date picker UI contains 1/13/17. These are consistent. I do not understand the bug report.

**Comment by QMKhan** [comment]
its working good now when i cleared by browser
