### ISSUE TITLE
timePicker: false

### ISSUE THREAD

**Issue by zancheng** [dangrossman/bootstrap-daterangepicker#1354]
When I set (timePicker: false, maxDate: new Date() ), the second calendar can not choose the today, but the first calendar can choose today.

$('#date-range').daterangepicker({
				timePicker: false,
				format: 'YYYY-MM-DD',
				maxDate:moment(),
				separator: ' ~ ',
				endDate:new Date()
			});

![image](https://cloud.githubusercontent.com/assets/20456859/21973577/a0145378-dbfc-11e6-8807-c2ee172e0699.png)

**Comment by dangrossman** [comment]
That is a screenshot and options from v1 of this plugin. The last release of v1 was some time in 2015, then v2 was released. Please update your code.
