### ISSUE TITLE
Re-evaluate isInvalidDate function

### ISSUE THREAD

**Issue by rhyek** [dangrossman/bootstrap-daterangepicker#1356]
I need to update the disabled dates based on some variables of my application being changed (filters). Is there a way I can manually execute the `isInvalidDate` function to update which dates are invalid without reloading the page?

**Comment by dangrossman** [comment]
Yes, call $.daterangepicker() a second time with your new options (including the new isInvalidDate). You can call it at any time to recreate the date picker without reloading your webpage.
