### ISSUE TITLE
Predefined Ranges in forms

### ISSUE THREAD

**Issue by justdan0227** [dangrossman/bootstrap-daterangepicker#1357]
When using Predefined Ranges in a form, using the example, I'm not seeing it returned in the POST variables, even if I give it a name.  All of the other examples use INPUT, this one uses DIV.  How do I get the results passed back in the POST variables?

**Comment by dangrossman** [comment]
Write code in your callback function to put the two dates into hidden inputs.

**Comment by justdan0227** [comment]
Hey Dan thanks, however how do I get the start and end in the callback.  Sorry I'm a PHP programmer and only a novice javascript programmer and was looking for an example in the docs.

**Comment by dangrossman** [comment]
They're passed to the callback.  There are examples on the website for this library.

http://www.daterangepicker.com/#ex4

````
<input type="hidden" name="start" id="start">
<input type="hidden" name="end" id="end">

$('#reportrange').daterangepicker({
  ...options...
}, function(start, end, label) {
    $('#start').val(start);
    $('#end').val(end);
});
````

**Comment by justdan0227** [comment]
Thanks I'll try that.. I didn't see where .val(start) and .val(end) were getting set that I could query it..
