### ISSUE TITLE
[Feature](Options): When editing the range can we keep the previous end date selected?

### ISSUE THREAD

**Issue by tsmith39** [dangrossman/bootstrap-daterangepicker#1358]
It would be nice the be able move the start date without having to again select the end date. As well as being able to the select an end date without have to reselect the already selected start date. 

I think this plugin used to work like this pre version 2.0 so maybe we have an option to use old style of selection.

:)

**Comment by dangrossman** [comment]
Nothing stopping you from using v1 if you want

The UX of this one is based on the UX of other date range pickers I found across the web (from Google, hotel searches, flight searches, analytics tools, etc), and will not be changing
