### ISSUE TITLE
Triggering a picker programmatically to show for an element that has already been initialized as daterangepicker().

### ISSUE THREAD

**Issue by bs-thomas** [dangrossman/bootstrap-daterangepicker#1365]
Hello there,

I was wondering if there is any way of triggering a picker to show for an element that has already been initialized as daterangepicker().

Your help is appreciated.  Thank you!

**Comment by dangrossman** [comment]
Clicking on the element triggers the date picker to show

You can click programmatically, with .click() or .trigger('click')
