### ISSUE TITLE
How to set void initial date?

### ISSUE THREAD

**Issue by wzup** [dangrossman/bootstrap-daterangepicker#1366]
I want to set:
```
{
    startDate: undefined,
    endDate: undefined
}
```
Your docs say nothing about such a use case:
![date range picker for bootstrap - google chrome 2017-01-23 13 05 36](https://cloud.githubusercontent.com/assets/3880497/22192183/b93b8cde-e16c-11e6-8b2a-350131a21272.png)

How to set void date?

**Comment by dangrossman** [comment]
This is not supported at all.

**Comment by wzup** [comment]
Then what's your approach for that use case?
Initial date is not pre-selected. I want user to select a date. What's your best practices for that?

**Comment by dangrossman** [comment]
I have no answer for you, there is always a date selected in this widget, if that doesn't meet your requirements then you can't use it as is

**Comment by wzup** [comment]
Actually it is a common use case. 
For example, Airbnb. Initially dates are not pre-selected. Guest is preselected only. So I was asking about this uses case - when labels are something like "Select a date" string.

![dp airbnb - google chrome 2017-01-23 13 31 32](https://cloud.githubusercontent.com/assets/3880497/22192632/7c475250-e170-11e6-938d-069533685235.png)

**Comment by dangrossman** [comment]
I understand.

**Comment by JordanSayner** [comment]
Im looking to do this exact thing. I can set a default value on my input form, but the plugin overrides it. Im trying to do what Airbnb does.

**Comment by dangrossman** [comment]
Use `autoUpdateInput: false` and this plugin will never override/put anything in your input, per the linked example.

**Comment by JordanSayner** [comment]
Awesome, I've updated and works spot on now. Thanks.
