### ISSUE TITLE
Proper method of daterangepicker open in the button trigger?

### ISSUE THREAD

**Issue by eiabdulsamad** [dangrossman/bootstrap-daterangepicker#1369]
What is the best method of open when button click? 

I added this code, but toggle each time. 
`$('#daterangepicker').data('daterangepicker').toggle(); `

I need to open daterangepicker in the one click then close next click. 
Please refer this video:
http://srecorder.com/uploads/2017-01-24_13.47.05.mp4

Thank you.

**Comment by dangrossman** [comment]
`$('#id-of-your-icon').daterangepicker();`

It will bind to the click event of whatever you attach it to itself. You do not need to write your own code to show or hide it.
