### ISSUE TITLE
Update to BS4

### ISSUE THREAD

**Issue by john-999** [dangrossman/bootstrap-daterangepicker#1374]
It would be nice if you could set up a version that works with Bootstrap 4.

**Comment by dangrossman** [comment]
Bootstrap 4 has been in alpha for over 18 months. Perhaps if it ever gets to a release candidate stage I'll look into what changes are needed.

**Comment by paltman** [comment]
BS4 is now released

**Comment by dangrossman** [comment]
I just swapped out Bootstrap 3 for 4 on a page with the date range picker, and it worked fine without any changes. Is there something that needs updating?
