### ISSUE TITLE
What Can I make for put in  portuguese? 

### ISSUE THREAD

**Issue by marcosvicente** [dangrossman/bootstrap-daterangepicker#1375]

**Comment by dangrossman** [comment]
You can set your locale through the `moment.js` library that the date picker uses for all dates, times and strings:

http://momentjs.com/docs/#/i18n/

Or you can override every string in this library via options. For an example to follow, click "Locale (with example settings)" in the configuration generator:

http://www.daterangepicker.com/#config

**Comment by marcosvicente** [comment]
Thanks very much!
