### ISSUE TITLE
February on the left, January on the right

### ISSUE THREAD

**Issue by mityukov** [dangrossman/bootstrap-daterangepicker#1376]
Hi,

Can't fix the issue: calendar shows two months in reverse direction.

What I've found out:
The dynamically created div has that "opensright" class which, removing of which (via DevTools) fixes the issue)
`<div class="daterangepicker dropdown-menu ltr show-calendar opensright" ...>`

I've tried to add an option: `opens: 'left'` to the "constructor" -- no luck :(

Is there a way to get rid of it?

Here's the full init code:

```javascript
var drpLocale = {
    "format": "DD.MM.YYYY",
    "separator": " - ",
    "applyLabel": "Выбрать",
    "cancelLabel": "Очистить",
    "fromLabel": "От",
    "toLabel": "До",
    "customRangeLabel": "Предустановки",
    "weekLabel": "Н",
    "firstDay": 1
};

$('input[name="daterange"]').daterangepicker(
    {
        locale: drpLocale,
        // opens: 'left', // does not fix anything..
        startDate: moment(this.dateFrom, 'YYYY-MM-DD').format('DD.MM.YYYY'),
        endDate: moment(this.dateTo, 'YYYY-MM-DD').format('DD.MM.YYYY')
    },
    (start, end, label) => {
        this.dateFrom = start.format('YYYY-MM-DD');
        this.dateTo = end.format('YYYY-MM-DD');
    }
);
```

**Comment by dangrossman** [comment]
I could not reproduce the issue using your code

**Comment by mityukov** [comment]
@dangrossman I am not sure if I could reproduce it in a pen… But maybe there is an option to force direct order or to force it not adding "opensright" class to the <div> it generates?

I'll check if my theme has its own scripts that could add this class, meanwhile..

**Comment by mityukov** [comment]
Ok. There is nothing forcing "opensright" in my theme, nor this class is actually responsible. The picker has this same class in your demo, yet it has proper order of panels.

Could anything in CSS cause the order of panels to be changed?

In terms of CSS, I'm using this theme:
https://colorlib.com/polygon/gentelella/profile.html

**Comment by mityukov** [comment]
Workaround: pass "opens" option but with non-recognizable value.
E.g.: `right: 'xxx',`

(found it out trying to pass `right: 'middle'`)

This way it still opens to the right (and I actually need that), but the order is not changed.

Maybe this info would give you any insights.

**Comment by dotob** [comment]
had the same issue, and i could resolve it the same way...
