### ISSUE TITLE
How to disable the "apply" button in initial time (just daterangepicker opening time)?

### ISSUE THREAD

**Issue by eiabdulsamad** [dangrossman/bootstrap-daterangepicker#1377]
Hi,

"Apply" button enabled only when picked a date or when mouse clicking in the calendar area, It's possible?

Thank you

**Comment by eiabdulsamad** [comment]
@dangrossman 
Example: Today's date is disabled, but I can get this date. "Apply" button disabled, I think that is simple solution.
Please refer this screenshot
http://image.prntscr.com/image/e4aa97205a2a4e9eb682dbefb1cd8af3.png

**Comment by dangrossman** [comment]
Set the `startDate` and `endDate` options when you create your picker, so that they don't default to today's date, a date you want to be disabled.
