### ISSUE TITLE
Calendar Shows January, but when selecting Feb 1, it selects March 1

### ISSUE THREAD

**Issue by SQLGuruZA** [dangrossman/bootstrap-daterangepicker#1379]
Not sure if this is the correct forum to post this, but could not find any contact details.
I am having an issue with the daterangepicker in that I have a Start and End picker.
Yesterday, when the date was Jan 30 and the user tried to select Feb 1, it changed to March 1.
I have attached a pic to explain what happened. Please note that I am using the latest version of the code.

![001](https://cloud.githubusercontent.com/assets/22474740/22518792/953fbdd6-e8b6-11e6-8907-f0bb6e210f78.jpg)

**Comment by dangrossman** [comment]
I could not reproduce that, and those screenshots don't look like they're from this library

**Comment by SQLGuruZA** [comment]
my sincere apologies.... it appears that this is the plugin being used: https://github.com/smalot/bootstrap-datetimepicker
