### ISSUE TITLE
Is it possible to make it so that the picker positions itself so that it is always inside the viewport?

### ISSUE THREAD

**Issue by stefangabos** [dangrossman/bootstrap-daterangepicker#1381]

**Comment by dangrossman** [comment]
There's not an option for that, but you could probably code it

**Comment by rlamorea** [comment]
FWIW, a quick and dirty way to do this is to react to the `show.daterangepicker` event, like:

```
$('#mydate').on('show.daterangepicker', function(e, picker) {
   var $e = $(e.target);
   var cBounds = picker.container.get(0).getBoundingClientRect();
   var pBounds = $e.get(0).getBoundingClientRect();
   var viewport = { width: window.innerWidth, height: window.innerHeight };
   var doMove = false;
   if (cBounds.right > viewport.width && (pBounds.right - cBounds.width) >= 0) { 
      picker.opens = 'left'; doMove = true; 
   }
   if (cBounds.bottom > viewport.height && (pBounds.top - cBounds.height) >= 0) {
      picker.drops = 'up'; doMove = true;
   }
   if (doMove) { picker.move(); picker.show(); }
});
```

**Comment by vgavro** [comment]
@dangrossman will you consider PR that is using some positional library for that, such as https://github.com/FezVrasta/popper.js ? It seems pretty common task, and this quickfix can't resolve issues such as position near input element on page scrolling, etc.

**Comment by sstenn** [comment]
This did it for me;

    $('#date').on('showCalendar.daterangepicker', function (ev, picker) {
        if (picker.element.offset().top - $(window).scrollTop() + picker.container.outerHeight() > $(window).height())
            return picker.drops = 'up';
        else
            return picker.drops = 'down';
    });

**Comment by stefangabos** [comment]
wait, the date picker is always inside the viewport...can you please show me an example where it isn't?

**Comment by stefangabos** [comment]
oh, you mean once the page is scrolled?
