### ISSUE TITLE
Update moment inverted param

### ISSUE THREAD

**Issue by awmottaz** [dangrossman/bootstrap-daterangepicker#1382]
See [here](http://momentjs.com/guides/#/warnings/add-inverted-param/), `moment.js` changed the order of arguments for the `.add()` and `.subtract()` methods. The current implementation gives warnings in the console, e.g.

```
Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.
```

**Comment by dangrossman** [comment]
I couldn't find any `.add()` or `.subtract()` calls in the library which are in the wrong order. Are you sure you have a current version yourself?

**Comment by awmottaz** [comment]
Right you are. My fault—I was using [this](https://www.npmjs.com/package/daterangepicker) NPM package which points to this repo. Clearly it is way out of date.

**Comment by dangrossman** [comment]
Got it. This is the correct one which I keep updated, I don't have access to that other repo:

https://www.npmjs.com/package/bootstrap-daterangepicker
