### ISSUE TITLE
Display single calendar for date range picker

### ISSUE THREAD

**Issue by Michael-Brooks** [dangrossman/bootstrap-daterangepicker#1383]
Would it be possible to add an option for displaying a single calendar with left and right arrows when using the date range functionality?

We currently have a site where customers become confused with two calendars being displayed when being asked to select a date range, they would rather see a single calendar where they can click the left and right arrows.

**Comment by dangrossman** [comment]
No such option exists, but nothing stops you from customizing the code for your site

**Comment by anandsinghkunwar** [comment]
@michaek Did you solve this? I need a similar functionality as well.

**Comment by itayganor** [comment]
+1!
