### ISSUE TITLE
Disabling time interval

### ISSUE THREAD

**Issue by onelazy** [dangrossman/bootstrap-daterangepicker#1384]
I'm not sure if there is already a funtion for this, but i would ask anyway. Is there a way to disable time interval in the picker and dont include it to the result for computing the total hours like if I want to disable 12:00 PM to 1:00 PM then I selected 11:00 AM to 2:00 PM the total hours will be 2 hrs only? Thanks.

**Comment by dangrossman** [comment]
No there's not anything like that

**Comment by onelazy** [comment]
Is there a work around for this ? This is for the purpose of stripping breaktime in the computed result

**Comment by dangrossman** [comment]
Writing code to compute the hours minus break time would be the workaround

There's nothing built-in to the daterangepicker library that will do it for you, sorry

**Comment by Lemar101013** [comment]
Is there a way to disable a specific time range in timepicker?..for example: i want disable 12am-7:59am and 5:01pm to 12:00am because its a non working hours.. I've been looking for a solution but can't find one.. Hope someone could help me..thank u

**Comment by onelazy** [comment]
Hi Lemar,

I came across the same problem when I'm beginning to understand this
beautiful utility. So I dont mind sharing to you the quick fix for this.
There is an available function for this which is the "minDate" -- here you
are going to set your minimum date and time like so :

minDate: getCurrentDateToday() +" 8:30 AM", where getCurrentDateToday() is
a function that gets the current date today(where the format depends on
what you need in my case it is:  MM/DD/YYYY).

I hope this helps you. Goodluck!
