### ISSUE TITLE
Custom Range date selection issue

### ISSUE THREAD

**Issue by skasgarv** [dangrossman/bootstrap-daterangepicker#1386]
**Issue 1:**
When choosing a date range, assume Jan 1st to Jan 31st, first date field takes Jan 1st and second date field is highlighted. After clicking the second date, **the first date field is re-highlighted and date changes from Jan 1st to Jan 31st** until the mouse is on the calendar. When we move the mouse away from the calendar, then we can see the spread from Jan 1st to Jan 31st.

**Issue 2:** 
A second, even more-confusing case is where you want to edit just the second date of the range. Again, in the case of Jan 1st to Jan 31st, imagine you’d like to edit the second date to Jan 14. When I click on the “Jan 31, 2017” field to select it to be changed, **the first date field is re-selected and repopulated with the new date which should have the second date field**. This could obviously cause confusion, sending some users into an endless cycle of clicking dates. This appears to be a bug with the component.

Please look into the issue and I hope it can be resolved. Thanks

**Comment by dangrossman** [comment]
Issue 1: This is not an issue. The inputs reflect what your mouse is hovering over to preview what clicking will do.

Issue 2: I could not reproduce at http://www.daterangepicker.com

**Comment by skasgarv** [comment]
@dangrossman I am able to replicate Issue 2 at  http://www.daterangepicker.com 
I double checked. The first field is getting re-populated. 
Please check the attached image
![dateissue](https://cloud.githubusercontent.com/assets/18016940/22846202/627ee048-efb4-11e6-83c0-303fc8dfd3fb.png)

**Comment by dangrossman** [comment]
Your reproduction steps said "When I click on the “Jan 31, 2017” field to select it to be changed", but I do not see your cursor in the second text box

**Comment by skasgarv** [comment]
The image attached is after clicking Jan 31st field and changing it Jan 15th. So the spread should be from Jan 1st to Jan 15th but in the image you can see that its Jan 15th to Jan 15th. The cursor moves back to the first date field as soon as I click a date.

**Comment by dangrossman** [comment]
When I click Jan 31st and change it to Jan 15th, I see Jan 1 to Jan 15 in the text boxes. Are you still hovering your mouse over Jan 15 and that's why you see 1/15 to 1/15? That's "issue 1" again , which is not an issue.

**Comment by skasgarv** [comment]
Hey. Sorry for the delayed response. I was travelling.
I did fork your repository and made some minor tweaks to suit my application.
Reason: My users were a bit confused on the date selection and  hence I needed to tweak.

http://rawgit.com/skasgarv/bootstrap-daterangepicker/feature/hoverDateFunction/example/amd/index.html

Could you please have a look at the change once and if you feel that the patch is no better then we can drop this issue once and for all.

Thanks a lot for your time and patience. Please have a look.
