### ISSUE TITLE
Cannot apply default date range

### ISSUE THREAD

**Issue by ninetensfive** [dangrossman/bootstrap-daterangepicker#1388]
When you want to select date range like this:
- start date = today
-end date = today
and when these are initial values nothing happens.
This check here is causing the problems:
"//if a new date range was selected, invoke the user callback function
            if (!this.startDate.isSame(this.oldStartDate) || !this.endDate.isSame(this.oldEndDate))"
If you want to select range in same day the only way is to first select other range.
In initial state this check is unnecessary.

**Comment by dangrossman** [comment]
Working as intended

The callback notifies you of changes to the selection, not every time the apply button is clicked

There's a separate `apply.daterangepicker` event for that
