### ISSUE TITLE
Calendar overwrites start date instead of end date if you click the end date input

### ISSUE THREAD

**Issue by mazondo** [dangrossman/bootstrap-daterangepicker#1392]
To recreate:

1. Open datepicker, select starting date
2. Click on the end date input field
3. click the next month once or twice
4. Select an end date

When you click to the next month, the selected field reverts to the start date instead of staying on the end date.  This can be recreated on the demo pages as well in any browser.

**Comment by dangrossman** [comment]
When you click on the text input, then click out of the text input, your selection of the end date becomes whatever's in the text input. I can't think of any way for the picker to know that your mental state is "I want to pick an end date" when there's already a range selected and you click a new date... that's how you start a new selection.

**Comment by mazondo** [comment]
It seems to me that if you haven't entered any values into the end input field, that it would stay as the active field until input is entered, either via manual entry or selecting a date.

Had the user typed a date into the end field, or otherwise entered one, then I'd agree.  But since it's empty still it seems weird to jump back to the start date.

**Comment by dangrossman** [comment]
If you had emptied the field, that actually would've been what happened. But it wasn't empty, it had a valid date in it when you left the text field by clicking on something outside of it, so that date was accepted as what you wanted the end date to be.

**Comment by mazondo** [comment]
hmmm, fair enough.  It does initialize with a value in both the start and end fields even when the input is blank.

Are there any options to initialize the date picker without any values selected in those fields?

This issue doesn't come up a ton, but for whatever reason we have new users who think of those fields more like "tabs" and they'll click them in order to indicate " I want to set the start date now" and "I want to set the end date now".

**Comment by dangrossman** [comment]
You could always hide the inputs or make them readonly. It's open source code, a starting point for you to build what's best for your site. There's not a way to initialize this date range picker with no dates selected.

**Comment by mazondo** [comment]
I understand it's open source, I wasn't looking for some extra work just for my project 😄

Appreciate the time, I'll see if I can figure out a way to work around it for our use case.
