### ISSUE TITLE
Set Hour and minute

### ISSUE THREAD

**Issue by Megamil** [dangrossman/bootstrap-daterangepicker#1399]
How do set "hourselect" and minuteselect init?

**Comment by dangrossman** [comment]
The initial date range selected is set through the `startDate` and `endDate` options, which you can provide as a formatted string, a Date object or a Moment object. Your string or date or moment object can include hours and minutes and seconds.

**Comment by acelance** [comment]
How do set "Hour" view only ,I do need to show "Month" and "Day"
