### ISSUE TITLE
Update NPM?

### ISSUE THREAD

**Issue by mathisloge** [dangrossman/bootstrap-daterangepicker#1405]
Hey there!
Npm versipn [https://www.npmjs.com/package/daterangepicker](https://www.npmjs.com/package/daterangepicker) is still on version 0.0.3

**Comment by mathisloge** [comment]
#802  find this issue already

**Comment by dangrossman** [comment]
You are at http://github.com/dangrossman/bootstrap-daterangepicker

The NPM package is https://www.npmjs.com/package/bootstrap-daterangepicker

I do not own the package you linked, I have no ability to update it. I have contacted the owner several times over the years and he does not respond.
