### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by mohaneldia** [dangrossman/bootstrap-daterangepicker#1406]
hi, the template created is not removed when calling remove method which causes a memory leak in single page frameworks like ember, angular.

**Comment by codeepic** [comment]
@mohaneldia can you elaborate a bit?

**Comment by trileminh94** [comment]
Same to me, I think problem is not belong to bootstrap-daterangepicker. Error is because your jquery version is too low, so it will caused error when remove datepicker. For me, using jquery 3.2, everything will be ok.

**Comment by mohaneldia** [comment]
create a new date-range-picker and destroy it. now you have new unwanted DIVs present in body tag. repeat the previous sentence.

**Comment by dangrossman** [comment]
This code is already there which removes that:

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L1608

I just checked a live page, called `$('#element').data('daterangepicker').remove()` and the date range picker DIV was removed from the document.
