### ISSUE TITLE
Can we localize the range strings when adding our customized ranges?

### ISSUE THREAD

**Issue by anshuljindal2008** [dangrossman/bootstrap-daterangepicker#1409]
For example if I have some custom range like 'Last 30 days'  .Do we have the ability to localize it?

**Comment by dangrossman** [comment]
"Last 30 days" is not hardcoded anywhere in this library. Your range names can be in any language.

**Comment by anshuljindal2008** [comment]
Thanks for your reply
I understand that range names can be in any language .The problem is localizing it dynamically.Once defined I am not able to change the range names , like I can change the customRangeLabel or for that matter months.If I give a variable instead of any hard-coded string , the code breaks.

**Comment by dangrossman** [comment]
Why does your code break?

**Comment by anshuljindal2008** [comment]
It takes the variable name and not the variable value.So for `var lastThirty = 'Last 30 Days'` . If i use lastThirty   in the ranges json , it prints lastThirty and not Last 30 days in my dropdown

**Comment by dangrossman** [comment]
````
var lastThirty = 'Last 30 Days';
myRanges = {};
myRanges[lastThirty] = [moment(), moment().subtract(29, 'day')];

$("#yourelement').daterangepicker({
  ranges: myRanges
});
````

**Comment by anshuljindal2008** [comment]
Thanks. 
I will try this
