### ISSUE TITLE
autoApply option does not hide buttons when timePicker/timePicker24Hour is true

### ISSUE THREAD

**Issue by jimmyberny** [dangrossman/bootstrap-daterangepicker#1412]
When autoApply is set to true the expected behaviour is to hide buttons Cancel and Apply, this works well if timePicker is not setted; otherwise not.
![selection_306](https://cloud.githubusercontent.com/assets/5862051/23663945/1a543006-034c-11e7-8195-95b41dd77e90.png)

**Comment by dangrossman** [comment]
That is by design. 

There is no way for the picker to know that the user is done selecting a date and time, that is, when it should "auto apply" the selection.

An "auto apply" feature can exist for choosing dates because it's obvious a selection has been made after two dates have been clicked.

**Comment by jimmyberny** [comment]
But if autoApply ends updating text field, I guess, we really don't need to know when user has selected the desired time.
