### ISSUE TITLE
Doesn't detect outside changes to input field

### ISSUE THREAD

**Issue by marc-gist** [dangrossman/bootstrap-daterangepicker#1420]
Love this program; but having issues when trying to update the inputfield from another function.

if i do
    $('#enddate').val('some date').trigger('change');

The updated date shows in the input field, however, when I click on it, the daterangepicker uses the old value, not the new value.
How do I notify daterangepicker that the date has changes.
Note: I'm using it in singleDatePicker: true mode

Thanks!

**Comment by dangrossman** [comment]
Instead of `$('#enddate').val('some date')`, perhaps do `$('#enddate').data('daterangepicker').setStartDate('some date')`?
