### ISSUE TITLE
autoUpdateInput  not apply for Single Date Picker

### ISSUE THREAD

**Issue by kamleshbhalde** [dangrossman/bootstrap-daterangepicker#1429]
i wanted to off autoUpdateInput for Single date picker, i will update it as mention below:
  $('input[name="birthdate"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
       autoUpdateInput: false
    }

but it won't work

**Comment by dangrossman** [comment]
That code works perfectly.

**Comment by kamleshbhalde** [comment]
[datepicker issue.zip](https://github.com/dangrossman/bootstrap-daterangepicker/files/864161/datepicker.issue.zip) -- video attached for issue, its not working.

**Comment by dangrossman** [comment]
That's not a video

I ran your code in the console at http://www.daterangepicker.com and it worked as expected there

**Comment by kamleshbhalde** [comment]
its working, its my mistake, i miss bind new value to input field, now its work fine, Thanks for support.

working code if someone facing same issue.
https://codepen.io/kamleshbhalde/pen/XMYgXK
