### ISSUE TITLE
Fontawesome and glyphicon are hardcoded.

### ISSUE THREAD

**Issue by sschueller** [dangrossman/bootstrap-daterangepicker#1432]
It would be great if I could override and specifically set what class I want to use for the icons. If you use custom fonts classes (like you can generate at http://fontello.com/) you can't use them with the date range picker.

**Comment by dangrossman** [comment]
This library is advertised as a Bootstrap component and those are the Bootstrap icon sets

I do not wish to make all the icons into options

You can edit your copy of the code to use whatever icons you want

**Comment by sschueller** [comment]
In Bootstrap 4 glyphicon has been dropped and font awesome is something you need to addas icons are no longer part of bootstrap.

**Comment by dangrossman** [comment]
That's good to know. Maybe when Bootstrap 4 isn't an alpha and there's a Bootstrap 4 version of this component things will be different. Not today however.

**Comment by jeradrutnam** [comment]
@dangrossman , Bootstrap 4 is released and glyph icons are no longer part of bootstrap framework. I too would prefer to have this as an extension point rather maintain a customized version at product-end. And would happy to contribute if you like.
