### ISSUE TITLE
Incorrect weeks display in ISO format

### ISSUE THREAD

**Issue by chinnonsantos** [dangrossman/bootstrap-daterangepicker#1435]
I was using an outdated version **(1.3.21)**, after upgrading to the newest
**(2.1.25)** I enabled and disabled the _'showISOWeekNumbers'_ option, but
still the weeks calculation is wrong, since in ISO rule the **year 2015 has 53 weeks** (the same goes for 2004, 2009, 2020 ...) following the rule of the week starting on **Monday**. For this calculation to work out the rule of **ISO 8601** is simple:

1. Week begins on Monday ("locale": {"firstDay": 1} is OK!)

2. The first week of the year must include the Thursday, in short,
you must have at least the last 4 days of the week (Thursday, Friday,
Saturday or Sunday), this is considered the first week of the year along
with the previous rule.

I have tested several times in my application and did not calculate
correctly, decide to compare with the [site example](http://www.daterangepicker.com/#config), and the here also
does not calculate correctly, even enabling the option
**('showISOWeekNumbers': true)** and setting the first day as _Monday_, **Locale ": {" firstDay ": 1}**.

This problem only affects who wants to use the weeks display in ISO format,
because the rest of the calendar has no error, but I can not correct it
alone, it seems that who is doing these calculations to the [moment.js](https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/moment.js)
library. I need your help.

**After some tests -------------------------------------------------------------------------------------**

**I did a test, it includes a log before the loop (line 780 of [daterangepicker.js](https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L780))**

```
Console.log ('Normal:' + calendar [0] [0] .week ());
Console.log ('ISO:' + calendar [0] [0] .isoWeek ());
```

**I realized that the arrays were correct when I listed the month of December 2009:**

> Log - 1st week of December
> Normal: 49
> ISO: 49
> 
> Log - last week of December
> Normal: 1
> ISO: 53 (now, that's right ...)

**Then replace the code (line 784 of [daterangepicker.js](https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L784))**

```
// add week number
if (this.showWeekNumbers)
    html + = '<td class="week">' + calendar [row] [0] .week () + '';
else if (this.showISOWeekNumbers)
    html + = '<td class="week">' + calendar [row] [0] .isoWeek () + '';
```

By this:

```
// add week number
if (this.showWeekNumbers) {
    if (this.showISOWeekNumbers) {
        html + = '<td class="week">' + calendar [row] [0] .isoWeek () + '';
    } else {
        html + = '<td class="week">' + calendar [row] [0] .week () + '';
    }
}
```

**With this successfully correctly displaying the weeks in ISO 8601, with the
years of 2004, 2009, 2015, 2020 and others with 53 weeks correctly,
there was no failure in the weeks calculation array but in the code that
made the verification if the user wanted Work with ISO or not.**

Sorry for not doing a Pull Request, I'm running out of time to download the whole project, edit and send again, some collaborator for kindly analyze the issue and update. Thank you.

**Comment by dangrossman** [comment]
It sounds like you set both `showWeekNumbers: true` and `showISOWeekNumbers: true` in your options, and you'd have the desired week numbers if you had set only `showISOWeekNumbers: true` without needing to change any code. Is that right?
