### ISSUE TITLE
Run on.apply when clicking on a button

### ISSUE THREAD

**Issue by FelixBorgmann** [dangrossman/bootstrap-daterangepicker#1436]
Hi,
I want to run my $('#reportrange').on('apply.daterangepicker', function(ev, picker) {}); event. when clicking on another Button. $('#reportrange').apply(); is not working. Is there an easy way to do this?
Thanks in advance!

**Comment by dangrossman** [comment]
Try `$('#reportrange').trigger('apply.daterangepicker');` or, put your code into a named function that you call from both places.
