### ISSUE TITLE
DD-MM-YYYY

### ISSUE THREAD

**Issue by webiummedia** [dangrossman/bootstrap-daterangepicker#1441]
I am currently implementing this plugin on a french website. The client asked that the date format uses the European standards which is: DD-MM-YYYY

```
$(function() {
    $('#input1').daterangepicker(
    {
        "autoApply": true,
        "showDropdowns": true,
        locale: {
          format: 'DD-MM-YYYY'
        },
    }
});
```

The format option does not seem to work as expected and ends up using MM/DD/YYYY. When I feed him with a start and end date in DD-MM-YYYY format I get invalid dates. Also, is it possible to change the "English" values with a french translation?

**Comment by dangrossman** [comment]
Do you have a very very old copy of this library? The option names changed some years ago. Your code works fine on the current version. 

> is it possible to change the "English" values with a french translation?

Yes. Check off "locale (with example settings)" in the configuration generator:

http://www.daterangepicker.com/#config

Or set a French locale in your moment.js object globally.

**Comment by webiummedia** [comment]
Old hmm ... I downloaded this a few days ago ... let me grab a fresh copy from github. Thx for the quick reply!

**Comment by webiummedia** [comment]
I am on the last version. I am using the CDN link:
`<script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>`

**Comment by dangrossman** [comment]
Like I said, the code you've shared works. I used it without changing anything. It shows "31-03-2017 - 31-03-2017" in the input.

**Comment by webiummedia** [comment]
Thx man i had an empty local var causing everything to go crazy down the script.
