### ISSUE TITLE
cannot select current date when set autoUpdateInput: false

### ISSUE THREAD

**Issue by imansyaefulloh** [dangrossman/bootstrap-daterangepicker#1442]
I dont want start_date field remain empty, because this field is not required, so i use autoUpdateInput: false, but if i'm set autoUpdateInput: false i can not choose the current date, if i choose the current date at the first try, the start_date field still empty, but if i choose other date first, and choose the current date again it will work.

here's my code

```html
<div class="input-group">
    <input type="text" name="start_date" class="form-control" id="start_date" value="<?php echo set_value('start_date'); ?>">
    <span class="input-group-btn">
        <button class="btn default date-range-toggle" type="button">
            <i class="fa fa-calendar"></i>
        </button>
    </span>
</div>
```

```javascript
$('input[name="start_date"]').daterangepicker({
    "singleDatePicker": true,
    "showDropdowns": true,
    "autoUpdateInput": false,
    "autoApply": true
}, function (start_date) {
    $('#start_date').val(start_date.format('YYYY-MM-DD'));
});
```

**Comment by dangrossman** [comment]
Your callback function will only be triggered when a new selection is made. As the current date is the already selected date, clicking it again will not trigger your code. You can listen for the `apply.daterangepicker` event instead like in the "input initially empty" example:

http://www.daterangepicker.com/#ex5

**Comment by SompalSingh** [comment]
Current date is the already selected, so clicking it again will not trigger automatically. Use it as:

$('input[name="start_date"]').daterangepicker({
        "singleDatePicker": true,
        "showDropdowns": true,
        "autoUpdateInput": false,
        "autoApply": true
    });
    $('input[name="start_date"]').on('apply.daterangepicker', function(ev, picker) {
        $(this).val(picker.startDate.format('YYYY-MM-DD'));
    });
