### ISSUE TITLE
Datepicker flying towards input when first open.

### ISSUE THREAD

**Issue by phiterf** [dangrossman/bootstrap-daterangepicker#1446]
This is happening:

![lp](https://cloud.githubusercontent.com/assets/12252332/24801524/f8caa630-1b7a-11e7-88bf-043b2bdb9bc5.gif)

The datepicker is flying towards the input...

It only happens the first time I open it, and I'm not sure if it is because it's inside the modal.

Also, when I click outside the modal, the modal closes but the datepicker don't.

Any fixes?

I'm using Chrome 57.0.2987.133 (64-bit) and bootstrap v3.3.6 for the modal.

The version of the Daterangepicker is 2.1.25

**Comment by dangrossman** [comment]
There's no animation code in this library or its stylesheet, which means that "flying in" transition is coming from your own stylesheet or javascript code. That isn't something I can help with. I suggest starting with the inspector in your browser.

**Comment by phiterf** [comment]
How about the problem when closing the modal that won't close the datepicker as well?
