### ISSUE TITLE
Default date cannot be empty?

### ISSUE THREAD

**Issue by warmwhisky** [dangrossman/bootstrap-daterangepicker#1453]
Am I correct in saying that you cannot start with an empty input as default? I simply want my users to add a birth-date (which is required). How ever if they don't set it themselves, their birth-date will be what ever the default date is. Any ideas how to clear the default without using http://www.daterangepicker.com/#ex5 ; obviously because if that is set they cannot even set a date.

**Comment by dangrossman** [comment]
> obviously because if that is set they cannot even set a date

Huh?

**Comment by warmwhisky** [comment]
Ah ha I see. Its the documentation. The title "Input Initially Empty"is a little bit misleading. when in actual fact you cannot have one input initially empty as it stays empty?

**Comment by dangrossman** [comment]
I don't understand what you're saying at all.

* In this example, under the word "Demo:" is an input on a webpage. 

* When the page is loaded, this input contains no value, it is "empty". 

* When you click on this input, a date range picker appears.

* When you choose dates on the picker, the input on the webpage displays the chosen dates

It is only empty until someone uses the picker.

**Comment by warmwhisky** [comment]
Sorry I am not being clear about what I was trying to do. If it is a single input as in this birth-date example http://www.daterangepicker.com/#ex3 ; can it be empty initially?

**Comment by dangrossman** [comment]
Yes. Exactly the same way as in example 5, but add "singleDatePicker: true" to your options.

**Comment by abidingotter** [comment]
> Yes. Exactly the same way as in example 5, but add "singleDatePicker: true" to your options.
I don't believe this is the case.  When you set singleDatePicker:true, the Apply and Cancel buttons don't show since they are in the ".ranges" div which is turned off during single mode.
