### ISSUE TITLE
Locale with format "DD/MM/YYYY" not working

### ISSUE THREAD

**Issue by lcjury** [dangrossman/bootstrap-daterangepicker#1454]
I'm trying to init a date range picker with the format "DD/MM/YYYY".

Inside the picker range selector I see the dates in the defined locale format, but when I click on the "Apply" button, the input is updated with the wrong format (MM/DD/YYYY).

**Comment by dangrossman** [comment]
Share all of your code.

**Comment by lcjury** [comment]
The input inside the form
```
<input class="form-control" type="text" data-toggle="daterangepicker" maxlength="23" name="timestamp" data-filter-type="date-range">  
```

and the JS call to date range picker
 ```
    $('[data-filter-type="date-range"]').daterangepicker({
         showDropdowns: true,
         ranges: {
             'Hoy': [moment(), moment()],
             'Ayer': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
             'Esta semana': [moment().startOf('week'), moment().endOf('week')],
             'Última semana': [moment().subtract(6, 'days'), moment()],
             'Últimas 2 semanas': [moment().subtract(13, 'days'), moment()],
             'Este mes': [moment().startOf('month'), moment().endOf('month')],
             'Mes anterior': [moment().subtract(1, 'month').startOf('month'),
                 moment().subtract(1, 'month').endOf('month')]
         },
         autoUpdateInput: true,
         applyClass: 'btn-sm btn-primary',
         cancelClass: 'btn-sm btn-default',
         locale: {
             format: 'DD/MM/YYYY',
             applyLabel: 'Aplicar',
             cancelLabel: 'Limpiar',
             fromLabel: 'Desde',
             toLabel: 'Hasta',
             customRangeLabel: 'Seleccionar rango',
             daysOfWeek: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
             monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre',
                 'Diciembre'],
             firstDay: 1
         }
     });

```

**Comment by dangrossman** [comment]
Well, here's a page using your code, unaltered:

http://jsfiddle.net/wvwd4pme/10/

When I click apply, the date in the input is in the format DD/MM/YYYY.

**Comment by gotephodevishal** [comment]
Thanks @dangrossman your jsfiddle solved my problem.i was also stuck in getting dates in DD/MM/YYYY format,but your example solved my problem.

**Comment by brunotdantas** [comment]
Solved my problem, Thanks a lot @lcjury

**Comment by ranakhurram666** [comment]
@dangrossman I am facing same issue. I appreciate that your solution is working. But can you explain why it is working. Because I am doing the same thing 
`locale: {
    format: 'DD/MM/YYYY'
}`

**Comment by jester6san** [comment]
> 
> 
> @dangrossman I am facing same issue. I appreciate that your solution is working. But can you explain why it is working. Because I am doing the same thing
> `locale: { format: 'DD/MM/YYYY' }`

same and it's frustrating
