### ISSUE TITLE
Manual open / close?

### ISSUE THREAD

**Issue by monovertex** [dangrossman/bootstrap-daterangepicker#1455]
Hi! Is there any way to disable the automatic opening / closing of the picker and implement my own actions that open or close it?

**Comment by dangrossman** [comment]
It's open source code, so of course you can implement anything you want. 

Here's a pointer to get started:

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L435

**Comment by monovertex** [comment]
Thanks, @dangrossman! I didn't realize that you could attach bootstrap-daterangepicker to other elements as well.
