### ISSUE TITLE
Question: Is it possible to extend daterangepicker to display other calendars?

### ISSUE THREAD

**Issue by misamae** [dangrossman/bootstrap-daterangepicker#1456]
Is it possible to extend daterangepicker to display other calendars? For example Persian Calendar?

**Comment by dangrossman** [comment]
Probably not easily

But here's the `renderCalendar` function if you want to start rewriting

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L627

**Comment by misamae** [comment]
@dangrossman thanks!

**Comment by misamae** [comment]
It was easier that I thought as there is a plugin for momentjs for persian calendar is available. Can I put this on npm registry? https://github.com/misamae/bootstrap-daterangepicker/tree/persian-calendar
