### ISSUE TITLE
Time not displayed on page load

### ISSUE THREAD

**Issue by webiummedia** [dangrossman/bootstrap-daterangepicker#1457]
Hi thx for this awesome plugin really!
I have a display problem though. I need to load the page with a predefined date and time loaded in the calendar box. But for some reason, the date and time are not displayed right. (Completly ignoring my default value)

I entered a default value in my input box:
`<input class="datepicker hasDatepicker" name="arrive" value="03-01-2017 10:00" size="40" id="dp1493148674282">`

As you can see the starting value is set to: 03-01-2017 10:00

And that renders as 25-05-2017 0:00:
![image](https://cloud.githubusercontent.com/assets/4869819/25404272/3de034e6-29cd-11e7-8b80-aa929bec70fa.png)

my script looks like this:
```
$('.datepicker').daterangepicker({
    timePicker: true,
    timePickerIncrement: 30,
    "locale": {
        "format": "DD-MM-YYYY H:mm",
        "applyLabel": "Appliquer",
        "cancelLabel": "Supprimer",
        "fromLabel": "De",
        "toLabel": "À",
        "customRangeLabel": "Custom",
        "weekLabel": "S",
        "daysOfWeek": [
            "Di",
            "Lu",
            "Ma",
            "Me",
            "Je",
            "Ve",
            "Sa"
        ],
        "monthNames": [
            "Janvier",
            "Février",
            "Mars",
            "Avril",
            "Mai",
            "Juin",
            "Juillet",
            "Août",
            "Septembre",
            "Octobre",
            "Novembre",
            "Décembre"
        ],
        "firstDay": 1
    },
    "timePicker24Hour": true,
    singleDatePicker: true,
    showDropdowns: true
});
```

**Comment by webiummedia** [comment]
Ok so my workaround was to initiate the script from the frontend with the dynamic date as "startDate" ... Not really the best way to solve this. If no startDate is provided then the script should check for a value in the input field. This is definitely a bug to be solved.

**Comment by dangrossman** [comment]
Your input is missing `type="text"`

If you add that, then the value in the input field will be used

http://jsfiddle.net/2nw8jjLk/

**Comment by webiummedia** [comment]
omg your right >.< Really did not see that one lol thx works great now.
