### ISSUE TITLE
Feature: Option to add class to month/year <select> tags

### ISSUE THREAD

**Issue by kevlarr** [dangrossman/bootstrap-daterangepicker#1458]
First of all - thanks for such a phenomenal plugin.

Would love to have a configuration option that lets one apply classes to the `<select>` tags (month dropdown, etc) generated here: https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L725

Reason being, we have a few classes that do a lot to prettify form inputs, and I would love to get these ones to match.

Would a PR be acceptable?

**Comment by dangrossman** [comment]
No I don't think that needs to be an option. Nobody else has ever asked for that.

I'm pretty sure you can target those `<select>`s with CSS as is, too.

But thanks for asking.

**Comment by kevlarr** [comment]
Totally get it. We have a bunch of styling pulled into a project from outside, so we can't just add a selector to the CSS rules. But yeah, that's a super narrow use case, it isn't much more effort just to copy/paste all the different CSS, and those styles aren't highly likely to change anyways.

Figured I'd try though!
