### ISSUE TITLE
date range format is not working

### ISSUE THREAD

**Issue by prashant93** [dangrossman/bootstrap-daterangepicker#1459]
Hi I have applied date format as YYYY-MM-DD(screen shot 1) it's working but it's not working when applied 
MM-DD-YYYY(screen shot 2)

![image](https://cloud.githubusercontent.com/assets/4151470/25527951/dc05b804-2c38-11e7-8d45-893c83f3efaf.png)

![image](https://cloud.githubusercontent.com/assets/4151470/25527926/bcab0428-2c38-11e7-9ab8-f333bb2d2d91.png)

**Comment by dangrossman** [comment]
Your screenshot shows "MM-DD-YYY" not "MM-DD-YYYY"

**Comment by prashant93** [comment]
Thanks for answering, Date format was mistakenly typed. Issue is basically from our side,
startDate and endDate should be outside locale.

**the wrong setting from our side:**
"locale": {
        "format": "MM/DD/YYYY",
 "startDate": "04/23/2017",
    "endDate": "04/29/2017"
        "separator": " - ",
        "applyLabel": "Apply",
        "cancelLabel": "Cancel",
        "fromLabel": "From",
        "toLabel": "To",
        "customRangeLabel": "Custom",
        "weekLabel": "W",
        "daysOfWeek": [
            "Su",
            "Mo",
            "Tu",
            "We",
            "Th",
            "Fr",
            "Sa"
        ],
        "monthNames": [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"
        ],
        "firstDay": 1
    },
   
**the correct settings on your site:**

"startDate": "04/23/2017",
    "endDate": "04/29/2017"
"locale": {
        "format": "MM/DD/YYYY",
        "separator": " - ",
        "applyLabel": "Apply",
        "cancelLabel": "Cancel",
        "fromLabel": "From",
        "toLabel": "To",
        "customRangeLabel": "Custom",
        "weekLabel": "W",
        "daysOfWeek": [
            "Su",
            "Mo",
            "Tu",
            "We",
            "Th",
            "Fr",
            "Sa"
        ],
        "monthNames": [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"
        ],
        "firstDay": 1
    },
