### ISSUE TITLE
Ranges are displayed in top right corner on init

### ISSUE THREAD

**Issue by Messer262a** [dangrossman/bootstrap-daterangepicker#1461]
Datepickers are being added to body(not attached to any element) and displayed on init. After clicking on fields in datepicker dom they start working normally (open and close in proper place).

**Comment by dangrossman** [comment]
I can't do anything with this description...

**Comment by Messer262a** [comment]
![image](https://cloud.githubusercontent.com/assets/26827978/25551992/ed273d0c-2c96-11e7-9777-6b8ea07a0e52.png)
When my angular component is inited, daterangepicker is partially displayed(ranges only) in incorrect position (zero position, related to body). I'm using this angular 2 component 
https://github.com/evansmwendwa/ng2-daterangepicker

**Comment by dangrossman** [comment]
I still have no way to start helping you with this. Good luck.
