### ISSUE TITLE
Calendar on page

### ISSUE THREAD

**Issue by webiummedia** [dangrossman/bootstrap-daterangepicker#1462]
I need to show on a page a calendar to show available dates for a rental but not trigured by an input field as no date selection should be possible. It's only an informative calendar that should be displayed straight on the page. Obviously, I need to be able to feed him dates that should appear blocked. Also the first and last day of a rental should be diagonally striped to show somebody else can arrive the same day a rental starts.

![image](https://cloud.githubusercontent.com/assets/4869819/25557063/3c652a10-2cd7-11e7-87d7-a1d31476055e.png)

Can we do this using this plugin?

**Comment by dangrossman** [comment]
There's no set of options that will do that for you. You will need to write your own code to meet your client's requirements.

But you can certainly use this library as a starting point, rather than start from scratch.

Good luck.
