### ISSUE TITLE
Multiple daterangepickers on same page

### ISSUE THREAD

**Issue by xjpmauricio** [dangrossman/bootstrap-daterangepicker#1464]
If you put two daterangepickers on the same page, and use the setStartDate and setEndDate methods on both, only one of them get's updated.

**Comment by vmitchell** [comment]
@xjpmauricio 
Do it like this $(first-daterangepicker-selector).data().daterangepicker.startDate = new Date()
etc..

**Comment by katkusmt** [comment]
Encountered this issue as well. I updated one daterangepicker, but the value did not change, updated the other one and both the values changed to the correct ones. 

I am using VueJs debugging tool to inspect the changes of values.

Any ways to resolve this?

**Comment by dangrossman** [comment]
I don't know why that would happen, and it didn't happen when I just tried it
