### ISSUE TITLE
Start or End date mandatory or not...

### ISSUE THREAD

**Issue by cmwalolo** [dangrossman/bootstrap-daterangepicker#1468]
It's not working as expected... If both dates are null, It's normal you should have some default values to be shown in the calendar. But values should only be updated when selecting a value. When clearing the dates from the text boxes and apply, the calendar date is reset to the value.

**Comment by dangrossman** [comment]
There is always a date range selected when using this picker. I do not fully understand what you're looking for.

**Comment by cmwalolo** [comment]
Hi Dan, 
I would like to handle null values... start or end date not required. So we could pass null values, and they will stay null till something is selected...  When clearing the text box on start date, or end date and applying , it should return the according null values if nothing has been selected.  I don't see the use of refreshing the selected days in the text box on hover.

Effectively on Edge or Chrome it looks to work better I made a test a few days ago but it could be on IE10 and the calendars were totally not synchronized.

**Comment by dangrossman** [comment]
This plugin does not support null values
