### ISSUE TITLE
endDate befor minDate

### ISSUE THREAD

**Issue by apmyp1990** [dangrossman/bootstrap-daterangepicker#1472]
When I set minDate = tomorrow, the endDate of the preselected range is before the startDate. How can I fix this?

![image](https://cloud.githubusercontent.com/assets/20161590/25892680/611be802-3575-11e7-872b-ed878b4ac29a.png)

![image](https://cloud.githubusercontent.com/assets/20161590/25892791/d8343a52-3575-11e7-93f4-fd5a7c2e72a8.png)

**Comment by dangrossman** [comment]
Provide a valid initial startDate and endDate

**Comment by apmyp1990** [comment]
Why do I have to set a startDate and endDate when I do not want to have a preselected datepicker?

**Comment by dangrossman** [comment]
This date picker always has a date range selected

It does not support nulls/no selection

If that is a requirement you need a different library or make your own
