### ISSUE TITLE
Input gets hidden when using jQuery and Prototype.js

### ISSUE THREAD

**Issue by pbondoer** [dangrossman/bootstrap-daterangepicker#1473]
In the software I'm working on, it's not unusual to have pages where both jQuery and Prototype.js are used. I tried to use this control in one of these pages, but as soon as I'd select a date, it would hide the input.

JSFiddle: https://jsfiddle.net/kc8cd2e0/4/ (if you remove Prototype, it will work as expected)

From what I could gather, the problem is jQuery is calling `hide()` when dealing with the `hide.daterangepicker` event. If only jQuery is present, this is not an issue, however since Prototype also has a `hide()` method it will get triggered - which will of course hide the control.

I believe the problem lies on the line:
```javascript
 this.element.trigger('hide.daterangepicker', this);
```

Using [`triggerHandler`](http://api.jquery.com/triggerHandler/) fixes my use case, and doesn't seem to break anything (though I haven't had time to extensively test it):
```javascript
 this.element.triggerHandler('hide.daterangepicker', this);
```

See [this commit](https://github.com/pbondoer/bootstrap-daterangepicker/commit/9813abb8721cdad198d1567a44efaf14e0495412).

Was there any reason not to use `triggerHandler` over `trigger` in the first place? If not, and you feel my changes are okay, then let me know and I'll submit a PR with the patch. :sparkles:

**Comment by pbondoer** [comment]
Since then we've been looking into this, and thanks to @mflorea here's an alternative fix:

```javascript
$('input').on('hide.daterangepicker', function(event) {
  // Overwrite at instance level the 'hide' function added by Prototype.js to the Element prototype. This removes the 'hide' function only for the event target.
  this.hide = undefined;
  // Restore the 'hide' function after the event is handled (i.e. after all the listeners have been called).
  setTimeout(function () {
    // This deletes the local 'hide' key from the instance, making the 'hide' inherited from the prototype visible again (the next calls to 'hide' won't find the key on the instance and thus it will go up the prototype chain).
    delete event.target['hide'];
  }, 0);
});
```
JSFiddle: https://jsfiddle.net/kc8cd2e0/6/

**Comment by dangrossman** [comment]
As `trigger` and `triggerHandler` have different behaviors, I'm not going to swap those. Glad you found an alternate fix.

**Comment by pbondoer** [comment]
Yeah, looking back I realize that, it's probably not desired to only trigger the namespaced events, for example if one would want to know when something is hidden and would listen to `hide`, then `triggerHandler` wouldn't actually tell them something was hidden as it would only trigger the listeners to `hide.daterangepicker`.

I hope at least the workaround will help those that are in the same situation! :)
