### ISSUE TITLE
support moment format syntax 

### ISSUE THREAD

**Issue by djangosdk** [dangrossman/bootstrap-daterangepicker#1474]
Hi,
You are using at line 140 
 ```if (typeof options.locale.format === 'string')```
and the use it like ```this.startDate = moment(options.startDate, this.locale.format);```

While moment supports multiple formats and accepts it as array
 https://momentjs.com/docs/#/parsing/string-formats/
example: moment("12-25-1995", ["MM-DD-YYYY", "YYYY-MM-DD"]);

Kindly consider removing  ```if (typeof options.locale.format === 'string')``` 
so we can use it like 
```js
{
   "locale": {
        "format":  ["MM-DD-YYYY", "YYYY-MM-DD"]
   }
}
```
**Benefits:**

1. default option can be anything but then user can define more formats by overriding this option
1. It overcomes a problem where there are many moment formats which are ```moment.variables``` and not a ```string``` like ```moment.ISO_8601```, so they can placed inside array but with string restriction, it is not possible

By this people would just add ```"format":  ["MM-DD-YYYY", "YYYY-MM-DD",moment.ISO_8601,moment.others ] ```easily with no hassel

**Comment by dangrossman** [comment]
No thanks. The ability to pass multiple formats to moment.js is to help in parsing user input in ambiguous formats. The format option in this library is to set how you want dates to be displayed by this picker, which is not ambiguous, and cannot have multiple values.

**Comment by djangosdk** [comment]
Ok but this does not solve using ```moment.variables``` problem ?? which is not ambiguous
