### ISSUE TITLE
setStartDate() does not clear initial date

### ISSUE THREAD

**Issue by jmonetcr** [dangrossman/bootstrap-daterangepicker#1476]
In the SingleDatePicker mode, when I use the setStartDate method, the picker shows with two dates selected. Is there a way to clear the original date selected?

**Comment by dangrossman** [comment]
Sounds like a bug. Until it's fixed, can you call setStartDate() and setEndDate() with the same date? That should make sure only one date is selected.

**Comment by jmonetcr** [comment]
That worked perfectly.. thank you!! I should probably submit this somewhere else, but it would be great to add setMinDate and setMaxDate.  But this is working great, thank you!!!!!
