### ISSUE TITLE
Calendar with 'Custom Range' option - inconsistency between Start/end Dates and start/end months displayed 

### ISSUE THREAD

**Issue by Wakhan** [dangrossman/bootstrap-daterangepicker#1484]
Month of Start/End Dates are NOT consistent with the start/end months displayed.
End Month is always Start month + 1 month (see attached file)
![image](https://cloud.githubusercontent.com/assets/8542927/26394081/e3c57338-407c-11e7-89ba-284270332fa8.png)

**Comment by dangrossman** [comment]
Working as intended

Also see `linkedCalendars` option in documentation
