### ISSUE TITLE
Click Apply on Load

### ISSUE THREAD

**Issue by alexandremix** [dangrossman/bootstrap-daterangepicker#1485]
I want something like this at the end of the scripts

$('#reservation').daterangepicker( clickApply());

Just want to trigger the apply event with the dates that are already selected

**Comment by dangrossman** [comment]
````
function myApplyCode() { 
  //your code
}

$('#reservation').on('apply.daterangepicker', function() {
  myApplyCode();
});

myApplyCode();
````

**Comment by alexandremix** [comment]
I want to force the $('#reservation').trigger('apply.daterangepicker') to Apply I dont want to create a custom function. My skills on Jquery+ Javascript are too bad.

The datepicker executes something when i click the apply.

I just want to simulate clicking in the apply button when the page loads

**Comment by alexandremix** [comment]
unfortunatly $('#reservation').trigger('apply.daterangepicker')
does not trigger the function

**Comment by dangrossman** [comment]
It triggers the apply event. What you are actually asking is to trigger your callback function. There is not a public method to do that. You should make it a function and call it in both places.

**Comment by alexandremix** [comment]
ok so i put the function(start, end, label) inside myapply code?
and I call the picker

 $('#reservation').daterangepicker(
{
   "autoApply": true,
    locale: {
      format: 'DD-MM-YYYY'
    },
    startDate: '2017-01-01',
    endDate: '2017-01-31'
}, myapplycode() ?
