### ISSUE TITLE
startDate not working?

### ISSUE THREAD

**Issue by m3ldro** [dangrossman/bootstrap-daterangepicker#1488]
Hallo,
this is my code and is not working.
```
var stDate = '20/08/2012';
    $('#rappData').daterangepicker({
            singleDatePicker: true,
            startDate: stDate,
            showDropdowns: true,
            locale: {
                format: 'DD/MM/YYYY'
            }
        });
```

Starting date is not shown on the input box and the dropwdown menù its full of NaN cells.
I read a lot of post about it but i still haven't found any solution.

What i'm wrong?
Thanks a lot.

**Comment by augustbend** [comment]
same issue here.

**Comment by dangrossman** [comment]
This is what happens when I run your code unmodified at http://www.daterangepicker.com (via the console):

![ss](https://cloud.githubusercontent.com/assets/407706/26562903/d27eff66-4498-11e7-8bf0-bd7db051f282.png)

So, no problems there. Are you running a several-years-out-of-date version of the library perhaps? Some option names changed between v1 and v2.

**Comment by m3ldro** [comment]
Hi, thanks for reply, actually i'm using 1.3.21 version.

Anyway i found that solution, i leave it here for anyone who needs it.

`  
     moment.locale('it');
     var  dataDefault = moment(dataDefault, 'DD/MM/YYYY');

    $('#rappData').daterangepicker({
            singleDatePicker: true,
            locale: {
                format: 'DD/MM/YYYY'
            },
            startDate: dataDefault,
            showDropdowns: true        
        });

        $('#rappData').val(dataDefault.format('DD/MM/YYYY'));`

I'm using this code to set a custom starting value (dataDefault).

**Comment by dangrossman** [comment]
The problem was that you're using 1.3.21 which is years old, and has different options. There is no "locale.format" for example. Your solution will not help anyone using the library available at this repo.
