### ISSUE TITLE
Toggling vs show/hide, with inputs, buttons and divs.

### ISSUE THREAD

**Issue by Techn1x** [dangrossman/bootstrap-daterangepicker#1490]
I've implemented the date range picker in my website and it is working really well, very impressed with it, thanks!

One thing I noticed was that when using a button for the picker, the date picker would show() (and not hide() on a subsequent click), but when using a div it would toggle()

I prefer the toggle() behaviour so I have opted to use a div to open the picker. I found the code that does this;
https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L436-L445

Looking at that, by opting for a div, I then lose out on keyboard bindings to my toggle div.

What would be the best way to either:
- Use a button but have it do a toggle() OR
- Use a div and have the other events (keydown, etc.) also binded to it?

I tried a few different jquery commands to bind things how I need but couldn't quite get it right. Also, I am curious why the different behaviours between button/input/div?

I know this is a very minor question but I am curious nonetheless!

Thanks

**Comment by dangrossman** [comment]
I honestly don't remember why that behavior was chosen 5+ years ago, but I probably shouldn't change it on people now.
