### ISSUE TITLE
Typing Control-A when on an input goes to Custom Range

### ISSUE THREAD

**Issue by jgb** [dangrossman/bootstrap-daterangepicker#1493]
Hello,

I've got a date + time picker with ranges, when I open it to select between the available ranges, and I type Control-A, it jumps automatically to Custom Range.
Is this on purpose? Or a bug?
It happens when I try the demo on the homepage as well.

Thanks,

jgb

**Comment by dangrossman** [comment]
1. Why are you hitting CTRL+A?

2. What is selected when you hit CTRL+A?

I can't reproduce this. I don't understand the problem.
