### ISSUE TITLE
Question: How can I unambiguous identify selected range?

### ISSUE THREAD

**Issue by feki** [dangrossman/bootstrap-daterangepicker#1497]
Hi,

I need to identify selected range independently from localization. How can I achieve this goal?

**Background:**
In multi language website I use date range picker in data filter. State of data filter can be save on server. But date criterion must be in relative form (`'today'`, `'lastYear'`, etc.), not in absolute (`{ startDate, endDate }`). Then, after load of filter state from server, I want to set dates in date range picker relatively to actual date.

Thanks for your advice.

**Comment by dangrossman** [comment]
Which predefined range was clicked is the 3rd parameter passed to your callback function.

````
$('#element').daterangepicker(options, function(start, end, label) {
  //label contains the predefined range label that was clicked
});
````
