### ISSUE TITLE
Drop downs not working in modal window

### ISSUE THREAD

**Issue by sledgey** [dangrossman/bootstrap-daterangepicker#1498]
I am loading a form in a modal window and the drop down options aren't displaying within that window. If I shift the contol anywhere outside of the window the functionality returns.

**Comment by sledgey** [comment]
Hmm, the modal window is a red herring. The problem is to do with the proximity of multiple date fields

**Comment by dangrossman** [comment]
There's not enough information here for me to help

**Comment by sledgey** [comment]
Yes, don't worry. It's just something I can work through. There's obviously some conflict from my css. I think I've nearly got it sorted. I was just being lazy and only started thinking my way through it once I'd posted the issue. Sorry to have bothered you with it
