### ISSUE TITLE
after end date select need to stop jump over to first selected date. 

### ISSUE THREAD

**Issue by iftakharhossain** [dangrossman/bootstrap-daterangepicker#1499]
After end date select the calendar jump to 1st select date. I need to stop that.

**Comment by dangrossman** [comment]
I would suggest setting `linkedCalendars: false` in your options then

**Comment by iftakharhossain** [comment]
thanks

**Comment by iftakharhossain** [comment]
is there have any way to only stop the jump event, after select end date?
thanks in advance.

**Comment by dangrossman** [comment]
no
