### ISSUE TITLE
Any option to change the header month year display format

### ISSUE THREAD

**Issue by rksbala** [dangrossman/bootstrap-daterangepicker#1501]
Thank you for providing very good plugin for date range selection.

I would like to know is there any option to change the header display format. 
e.g 2017 年 7 月 for Hong Kong locale.
@version used: 2.1.17

Based on below code I don't see option to change. Please do let me know is there any option to change header month & year format.
var dateHtml = this.locale.monthNames[calendar[1][1].month()] + calendar[1][1].format(" YYYY");

![image](https://user-images.githubusercontent.com/6780344/26915759-ed03eb36-4c44-11e7-9024-739eed44f928.png)

**Comment by dangrossman** [comment]
Check off "locale (with example settings)" at http://www.daterangepicker.com/#config

**Comment by rksbala** [comment]
Thanks for quick reply.
There is option to change the header using config.
Yes, moment locale lib added globally. But my requirement is to change the display format of the header. Current displayed as 'MMM YYYY' instead of this 'YYYY MMM' (2017 年 7 月)

**Comment by dangrossman** [comment]
There is not an option for that, but you have already identified the code to change.
