### ISSUE TITLE
Option to remove default selection?

### ISSUE THREAD

**Issue by mart-st-manov** [dangrossman/bootstrap-daterangepicker#1504]
If there is one I can't find it. I'm using daterange picker as a filter in tables. Finally managed to make it work like it should except I don't want a selected option when the filter has not been applied yet. If I give undefined as start and end dates the field is clear, yes, but in the option "Today" is selected and if I select it again it gives "Invalid date".

**Comment by dangrossman** [comment]
No, there is always a startDate and endDate selected internally, you cannot set them to null. 

This is close as it gets for a filter: http://www.daterangepicker.com/#ex5
