### ISSUE TITLE
iOS Issue

### ISSUE THREAD

**Issue by Cranavvo** [dangrossman/bootstrap-daterangepicker#1507]
Hello,

I came across an issue whilst using bootstrap-daterangepicker on iOS devices.

Whenever I tap on the select tools they appear and disappear instantly.

I've recorded the issue here: https://www.youtube.com/watch?v=SOg6hrK4-K0&feature=youtu.be

**Comment by dangrossman** [comment]
Pretty sure that has something to do with being inside a modal and not iOS. There are lots of modal scripts/styles that conflict with select boxes inside the modals for some reason. Try removing the tabindex from your modal if it has one, that seems to work for some people.

**Comment by Cranavvo** [comment]
Thanks for the reply, however the issue persists even with the removal of the tabindex.

Would it be safe to say this is a CSS issue rather than plugin, or are you unsure?

**Comment by dangrossman** [comment]
https://github.com/dangrossman/bootstrap-daterangepicker/issues?utf8=%E2%9C%93&q=modal

It comes up occasionally and everyone seems to fix it without me making any changes to the plugin. Most of the issues I just checked said the tabindex attribute was the cause.
