### ISSUE TITLE
Can we set default options?

### ISSUE THREAD

**Issue by meteorlxy** [dangrossman/bootstrap-daterangepicker#1509]
Every time calling `.daterangepicker()`, I have to set some options in common, especially some `locale` options (which are not covered by the locale setting of `moment.js`).

So can we set default options globally?

**Comment by dangrossman** [comment]
Not via this library, but you can certainly put your default options into a variable, then copy/reuse that as needed to achieve it yourself.

**Comment by meteorlxy** [comment]
I've created an pull request #1510, which works well on my own code.

It's inspired by the way that `datatables.js` sets the default options.
