### ISSUE TITLE
Dynamically set range title using object or function?

### ISSUE THREAD

**Issue by newportsolutionsgroup** [dangrossman/bootstrap-daterangepicker#1511]
We are calculating the quarter (Q1, Q2, Q3, Q4) for the current and prior year to use as range options.

For example:
```
    $('.daterange').daterangepicker({
        ranges: {
          'Last 90 Days': [moment().subtract(89, 'days'), moment()],
          'This Year': [start_date, end_date],
          q1.title: [q1.start_date, q1.end_date]
        }
    });

```
However when using an object or function for the ranges array title, an error is thrown:
` Uncaught SyntaxError: Unexpected token .`

I am able to use an object or function to set the array values of the range.
For example this works:
```
 $('.daterange').daterangepicker({
        ranges: {
          'Last 90 Days': [moment().subtract(89, 'days'), moment()],
          'This Year': [start_date, end_date],
          'Q1 2017' : [q1.start_date, q1.end_date]
        }
    });
```
**It should be possible to set the range title using an object or function.**
Has anyone overcome this issue or is this an enhancement?

**Comment by dangrossman** [comment]
This is just a matter of javascript syntax

````
myRanges = {};
myRanges[q1.title] = [q1.start_date, q1.end_date];

$('.daterange').dateRangePicker({
  ranges: myRanges
});
````

**Comment by newportsolutionsgroup** [comment]
Okay! Now this makes sense + works like a charm. Thanks very much.
