### ISSUE TITLE
Error showing first week of year

### ISSUE THREAD

**Issue by luigonsec** [dangrossman/bootstrap-daterangepicker#1512]
Hi! I am using version: 2.1.24 of daterangepicker. I am having the following problem. The first week of year is working fine in 2017 but not in other years. The first week starts the first monday of year and as you can see in picture below it seems don't work fine.

![captura de pantalla de 2017-06-27 23-31-42](https://user-images.githubusercontent.com/6770083/27611098-2fc78cd8-5b91-11e7-911a-a8b6e1ff1a8d.png)

First week of year can't contain days of december. How could I fix it? I have not see any parameter to configure that.

Thanks.

**Comment by dangrossman** [comment]
Use `showISOWeekNumbers: true`, not `showWeekNumbers: true` for your desired result.

**Comment by luigonsec** [comment]
Working fine for 2015

![image](https://user-images.githubusercontent.com/6770083/27626966-587e2354-5bea-11e7-8a25-1b948b4612b7.png)

But still not working in 2014 and previous years
![image](https://user-images.githubusercontent.com/6770083/27626945-41d56284-5bea-11e7-9ae0-eaa2d9643987.png)

**Comment by dangrossman** [comment]
That appears correct to me

https://www.epochconverter.com/weeks/2014

**Comment by luigonsec** [comment]
I am now understanding. I didn't know about this. But now I have a doubt about the difference between `showWeekNumbers` and `showISOWeekNumbers` parameters? I have manually modified my moment.js library

    function getSetISOWeek (input) {
        //var week = weekOfYear(this, 1, 4).week;
        var week = weekOfYear(this, 1, 1).week; // this makes first week which contains first monday of year
        return input == null ? week : this.add((input - week) * 7, 'd');
    }

Is there a way to configure the calendar for that? It's a customer request and we was mantaining and old library with that week day system and now he is requesting the same...
