### ISSUE TITLE
DateRangePicker with pre-defined ranges and no initial value does not update on clicking Today

### ISSUE THREAD

**Issue by fsmirne** [dangrossman/bootstrap-daterangepicker#1513]
1) Create a DateRangePicker like below:

function cb(start, end) {
	$('#date-range span').html(start.format('MMM D, YYYY') + ' - ' + end.format('MMM D, YYYY'));
	$("#start-date").val(start.format());
	$("#end-date").val(end.format());
}	

$('#date-range').daterangepicker({
	autoUpdateInput: false,
	ranges: {
		'Today': [moment(), moment()],
		'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
		'This Week': [moment().startOf('week'), moment()],
		'Last Week': [moment().subtract(1, 'week').startOf('week'), moment().subtract(1, 'week').endOf('week')],
		'This Month': [moment().startOf('month'), moment()],
		'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
		'This Year': [moment().startOf('year'), moment()],
		'Last Year': [moment().subtract(1, 'year').startOf('year'), moment().subtract(1, 'year').endOf('year')]
	},
}, cb);

$('#date-range').on('apply.daterangepicker', function (ev, picker) {
	$("#start-date").val(picker.startDate.format());
	$("#end-date").val(picker.endDate.format());
});

$('#date-range').on('cancel.daterangepicker', function (ev, picker) {
	$('#date-range span').html('Date Interval');
	$("#start-date").val('');
	$("#end-date").val('');
});

2) Click on the dropdown and select Today.

3) #start-date and #end-date are updated, but dropdown is not. This is due to line 1137 & 1138 in daterangepicker.js v2.1.25: 

if (!this.startDate.isSame(this.oldStartDate) || !this.endDate.isSame(this.oldEndDate))
        this.callback(this.startDate, this.endDate, this.chosenLabel);

Solution:

The check for same startDate and endDate is not correct. The callback should be made regardless.

**Comment by dangrossman** [comment]
Working as intended. The callback is fired only when the date range has changed. Use the apply event if you want to run code in response to applying the existing range.

**Comment by fsmirne** [comment]
I understand what you're saying, but if I put code in the apply event to change the span i.e. calling the cb function, then the cb function with execute twice when the date range has changed.

In my opinion, the behavior I'm suggesting is better than executing code twice.

Just my $0.02

**Comment by dangrossman** [comment]
You don't have to write your code in two places. Just put it in the apply function and don't have a callback.

**Comment by fsmirne** [comment]
Ah! I hadn't thought about that. That's what I'm going to do. Thank you for the suggestion!
