### ISSUE TITLE
Dynamically update dates in options

### ISSUE THREAD

**Issue by Niflou** [dangrossman/bootstrap-daterangepicker#1516]
Hi, 

I have the same problem than @garyelephant explained here : https://github.com/dangrossman/bootstrap-daterangepicker/issues/1137 but since this is a while and closed I'm creating a new post. I Hope this is the correct way to do.

The problem is the following : the dates set in the options are fixed dates. So if you spend time in your application, the range are slowly but surely becoming totally invalid. If you have something like : "Last 10 minutes" in your range options, or - worse - something like `maxDate: moment()` then as far as I know you are blocked. I didn't find any clean way to sort this out with the actual version of daterangepicker. 

The solution (using the callback) proposed in gary's post is an ugly workaround because the UI of daterangepicker is not updated when the user is rolling over the preset range. Even the dates in the input boxes are not updated.

Maybe you could use functions instead of fixed dates in the options, something like : 
```
ranges: {
    'Last 15 minutes': function() { return [ moment().subtract(15, 'minute') , moment() ]; }
    'Last 30 minutes': function() { return [ moment().subtract(30, 'minute') , moment() ]; }
},
maxDate: function() { return moment(); }
```
So the dates are not fixed anymore. And there are methods to detect if the options are functions or not so you can even provide both methods to end user. 

An other solution would be to provide a "reloadOptions" method, at least for dates like ranges or maxDate to let us update manually the dates before the popup displays but that would require more methods to manipulate the popup because the update has to happen before the popup open not once it's opened.

Do you see a better way to go ? Did I miss something ?

Thanks,

**Comment by dangrossman** [comment]
You're not missing anything. There is no solution for this provided by this library.
