### ISSUE TITLE
How Do you set the Custom Range Interval for startDate and endDate

### ISSUE THREAD

**Issue by dflow** [dangrossman/bootstrap-daterangepicker#1522]
Custom range is always a month between dates
 and it updates startDate when picking the endDate.
For example cannot set  range between June and August , It is updated to July and August

**Comment by olgashev** [comment]
Not always if you use option: linkedCalendars: false

**Comment by dangrossman** [comment]
Click on a start date, click on the arrow to scroll the months wherever you want, click on an end date. There is no interval/limit to selectable dates.

**Comment by ovidius72** [comment]
I need the same feature. Is it possible to set a default custom range without having to scroll and select dates manually ?
