### ISSUE TITLE
Preset multiple click issue.

### ISSUE THREAD

**Issue by brettmeyerowitz** [dangrossman/bootstrap-daterangepicker#1525]
When there are multiple daterangepicker controls on a page there is an issue where the incorrect div.rangerangepicker object is not loaded after previously clicking on a range preset.

**Comment by dangrossman** [comment]
I don't follow.

**Comment by brettmeyerowitz** [comment]
When I have multiple textboxes on a webpage and then add the plugin to each
control there is a problem.

The first time you click in a control the div loads up but not again after
that.

**Comment by dangrossman** [comment]
There are multiple date range pickers on the page at http://www.daterangepicker.com and they all open multiple times OK
