### ISSUE TITLE
Hide calendar inputs

### ISSUE THREAD

**Issue by toncid** [dangrossman/bootstrap-daterangepicker#1527]
Hello,

Would it be possible to add a config option to toggle calendar inputs:

![screen shot 2017-07-06 at 12 47 57](https://user-images.githubusercontent.com/1837897/27907840-8730dc22-6249-11e7-85d1-a24af76bd018.png)

I cannot seem to find a way to do it except via external CSS. 

Suggestions? Thoughts?

**Comment by toncid** [comment]
Added a pull request.

**Comment by toncid** [comment]
Added a pull request #1528.

**Comment by negativefix** [comment]
+1.  Having an option to hide inputs would be great.

**Comment by stefkes** [comment]
+1 don't really the point of having a manual input on top of the calendar. Default hidden with option to show would make more sense.

**Comment by arulnithi** [comment]
+1 I am currently using external CSS to hide this
