### ISSUE TITLE
Mark 'today'

### ISSUE THREAD

**Issue by chrisribal** [dangrossman/bootstrap-daterangepicker#1530]
Though this is a date ranger picker, where the current 'today' date isn't so interesting i think, that it would help the user to orientate. Is it possible to implenet a 'showToday' option that would just add a custom css class to the current date?

**Comment by dangrossman** [comment]
You can use the `isCustomDate` option to add a custom CSS class to any date.

````
isCustomDate: function(date) {
  if (date is today) return 'special class name';
}
````

**Comment by adFedorovich** [comment]
"date is today"  - does not work ahahahah)) no, sure, how i can use isCustomDate

**Comment by itajackass** [comment]
How can i add also a title to a cell? for example i'd like to add class "christmas", to color the cell to red, and check if a cell has a class "christmas", if yes add a title="Christmas day"

**Comment by itajackass** [comment]
I tried with:

    .on('show.daterangepicker', function(ev, picker) {
	  $(picker.container[0]).find(".newyear").attr("title","New Year");
    $(picker.container[0]).find(".customholiday").attr("title","Custom holiday");
	})

It work great if holiday is inside the actual view. But if I need to scroll calendar, it doesn't work.

my fiddle: https://jsfiddle.net/h9qdbaxo/2/

**Comment by dangrossman** [comment]
@itajackass You can add your code in the `renderCalendar` function: https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js#L773
