### ISSUE TITLE
integrate daterangepicker with a meteor project

### ISSUE THREAD

**Issue by diego77777** [dangrossman/bootstrap-daterangepicker#1532]
Hi, I'm quite new with meteor, I tried inserting these lines in `main.html`

```
<!-- Include Required Prerequisites -->
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/3/css/bootstrap.css" />
 
<!-- Include Date Range Picker -->
<script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
```

these lines in a template, `templates/devices.html`
`<input type="text" id="daterange">`

and these lines in `devices.js`
```
Template.devices.onRendered( function() {
$('input[name="daterange"]').daterangepicker();
//I tried also
//document.getElementById('daterange').daterangepicker() but throws an error
}
```
But this does not work at all, it throws an error. What I'm doing wrong?

**Comment by scottblinch** [comment]
If your element is `<input type="text" id="daterange">`, attempting to select it with `$('input[name="daterange"]')` is not going to work, as there is no `name` attribute.

While there may be other issues, I'd start by trying `$('#daterange').daterangepicker();` instead. It would also be helpful if you posted your error.
