### ISSUE TITLE
How to update "options" programmatically?

### ISSUE THREAD

**Issue by PhouvanhKCSV** [dangrossman/bootstrap-daterangepicker#1535]
I want to set "drops" option programmatically after it initialed.

here is my code

```javascript
myDtp.daterangepicker({
    singleDatePicker: true,
    showDropdowns: true,
    drops: 'bottom',
    minDate: moment().format('DD/MM/YYYY'),
});
```

Is it possible to update "drops" option to "up" later?

**Comment by dangrossman** [comment]
Yes, by calling $.daterangepicker() a second time with the new options.
