### ISSUE TITLE
When dateLimit is set to 'days': 0, and using two calendars, is it possible to not require the user to click the same date twice?

### ISSUE THREAD

**Issue by SlowburnAZ** [dangrossman/bootstrap-daterangepicker#1536]
Using version 2.1.25

So, my users need to be able to select a starting and ending time, so I need to show two calendars, but I also need to limit them to picking a single date.  So, in the config, I set:
```
dateLimit: {
  'days': 0
}
```

Since that config is limiting the user to a single day, is there some way I can make it so that the user doesn't need to click the same date twice in order to set the 'start' and 'end' date?  I think it would be more intuitive if, since only one day is available, to automatically set the start and end date when they click a day on the calendar.

**Comment by SlowburnAZ** [comment]
Is there an event that fires when the start date is picked, so I could then somehow set the end date programmatically (by firing whatever event is normally fired when the user clicks the end date)?

**Comment by dangrossman** [comment]
You need to rethink your UI. It doesn't make sense to drop down two calendars and have people click a date twice to identify a single date. They will be super confused and not be able to use your form.

Add a single date picker to your form to choose the single date. Add two text inputs or `<select>`s to your form to choose the start and end times.
