### ISSUE TITLE
Both fields display the last date

### ISSUE THREAD

**Issue by antonreshetov** [dangrossman/bootstrap-daterangepicker#1539]
When you select a period, both fields display the last date
![2017-07-27 10 29 07](https://user-images.githubusercontent.com/17480987/28659078-bfcc5246-72b6-11e7-80d6-0a384a717b20.png)

**Comment by dangrossman** [comment]
The active field displays the date under your mouse pointer as you move it. It's displaying February 19 because your pointer was sitting there when you took the screenshot.
