### ISSUE TITLE
Can I change the style from the daterangepicker?

### ISSUE THREAD

**Issue by kinamartinez** [dangrossman/bootstrap-daterangepicker#1540]
Hello, someone know how can I change the style completly, for the daterangepicker? colors, and the distribution of the columns and the buttons, etc. I need to create my own stylish datepicker...any help i will apreciate it.

**Comment by dangrossman** [comment]
Same way you change the style of anything on a webpage, through CSS

Start with `daterangepicker.css`

**Comment by kinamartinez** [comment]
Thank you :) silly question, but I am new ..

**Comment by kinamartinez** [comment]
Hello Again, One question, I changed the style of the datepicker, but still need to change the date style like the attachment, but I didnt find any class to modify, Do you know how to change it?
![image](https://user-images.githubusercontent.com/24204769/28818025-a0ecdfc6-76b2-11e7-9ef5-8c07bc551b0b.png)
Thank you so much

**Comment by kinamartinez** [comment]
Mine right now is like this:
![image](https://user-images.githubusercontent.com/24204769/28818211-23dc6b04-76b3-11e7-90d8-ce518dc56f86.png)
