### ISSUE TITLE
Date Start Custom Style

### ISSUE THREAD

**Issue by kinamartinez** [dangrossman/bootstrap-daterangepicker#1541]
Hello, I need to know if I can Style just the date, this is how I need it, but i didnt find any class or ID to change in CSS
![dates](https://user-images.githubusercontent.com/24204769/28818786-d6ef8194-76b4-11e7-9abe-0b57d08f9cab.PNG)

This is how I have it:
![olddates](https://user-images.githubusercontent.com/24204769/28818837-01c58f26-76b5-11e7-8298-7f7ff3f12d52.PNG)

**Comment by dangrossman** [comment]
You'll need to *add* some classes/IDs for you to target with styles. For example, by adding the extra markup in your custom callback function or by editing the library code.

**Comment by arulnithi** [comment]
Hey kinamartinez, 

Could you provide some insight into how you were able to style the ranges to be above the calendar table, and how you got the time-input to be below?
I am trying to get the time-input to appear below  and to make the range labels to be a drop-down but I just can't seem to get them to do so :(

**Comment by kinamartinez** [comment]
Hello.. I will send you the css that I used to change the datepicker like
my company application needed..

/*DateRangePicker*/
.daterangepickerBigInput {
  width: 100%;
  border: none;
}

.daterangepicker {
  flex-direction: row;
  width: 531px !important;
  border: 1px solid #e3e3e3;
  border-radius: 0px;
}

.ranges {
  height: 35px;
  display: inline-flex;
  flex-direction: row;
  padding: 0px;
  margin: 4px;
  border-bottom: 1px solid #e3e3e3;
}

.ranges ul {
  margin: 0px;
  padding: 0px;
  display: -webkit-box;
  font-weight: bold;
}

.ranges li {
  padding: 3px 16px !important;
  font-size: 12px;
  background-color: #ffffff;
  color: rgba(13, 37, 50, 0.6);
  border-radius: 0;
  border: none;
}

.ranges li.active {
  background-color: #ffffff;
  border-bottom: 2px solid #9fd44e;
  color: #9fd44e;
  border-top: none;
  border-right: none;
  border-left: none;
}

.ranges li:hover {
  background-color: #ffffff;
  border-bottom: 2px solid #9fd44e;
  color: #9fd44e;
  border-top: none;
  border-right: none;
  border-left: none;
}

.applyBtn {
  margin-top: 310px;
  margin-left: 249px;
  height: 75px;
  background-color: #9fd44e;
  border: none;
  width: 113px;
  border-radius: 0px;
  border-left: 1px solid #ffffff;
  font-weight: bold;
  font-size: 16px;
  background-image: url("assets/images/apply-arrow.svg");
  background-repeat: no-repeat;
  background-position: 45px 51px;
}

/*.applyBtn-withHours {*/
/*margin-top: 350px;*/
/*margin-left: 249px;*/
/*height: 75px;*/
/*background-color: #9fd44e;*/
/*border: none;*/
/*width: 110px;*/
/*border-radius: 0px;*/
/*border-left: 1px solid #ffffff;*/
/*font-weight: bold;*/
/*font-size: 16px;*/
/*background-image: url("assets/images/apply-arrow.svg");*/
/*background-repeat: no-repeat;*/
/*background-position: 45px 51px;*/
/*}*/

.cancelBtn {
  display: none;
}

.daterangepicker.ltr .calendar.left {
  order: 2;
  margin-right: 22px;
}

.daterangepicker.ltr .calendar.left .calendar-table {
  padding-right: 18px;
  padding-left: 11px;
  border-right: 1px solid #e3e3e3;
}

.daterangepicker.ltr .calendar.right {
  margin-left: -9px;
}

.daterangepicker .calendar {
  display: flex !important;
  flex-direction: column-reverse;
}

.daterangepicker_input {
  display: flex;
  flex-direction: column-reverse;
}

th.prev.available i {
  color: #d3d8da;
}

th.next.available i {
  color: #d3d8da;
}

td.active.start-date.available {

  background-color: rgba(159, 212, 78, 0.49);
  background-image:
url("assets/images/calendar-first-date-selected.svg") !important;
  background-size: cover;
  color: #0d2532;
  border-bottom-left-radius: 16px;
  border-top-left-radius: 16px;
}

td.active.end-date.available {
  background-image:
url("assets/images/calendar-last-date-selected.svg") !important;
  background-size: cover;
  background-color: rgba(159, 212, 78, 0.49);
  color: #0d2532;
  border-bottom-right-radius: 16px;
  border-top-right-radius: 16px;
}

.daterangepicker td.available:hover {
  border-radius: 16px;
}

td.in-range.available {
  background-color: rgba(159, 212, 78, 0.49);
}

i.fa.fa-calendar.glyphicon.glyphicon-calendar {
  display: none;
}

i.fa.fa-clock-o.glyphicon.glyphicon-time {
  color: transparent;
  background-image: url("assets/images/time-icon.svg");
  padding-right: 5px;
  padding-bottom: 3px;
  background-size: cover;
}

.daterangepicker .daterangepicker_input i {
  left: 2px;
  top: 6px;
}

select.hourselect {
  border-radius: 2px;
  border-color: #e3e3e3;
}

select.minuteselect {
  border-radius: 2px;
  border-color: #e3e3e3;
}

select.secondselect {
  border-radius: 2px;
  border-color: #e3e3e3;
}

.daterangepicker .input-mini {
  border: none;
  border-radius: 0px;
  background-color: #9fd44e;
  margin: 18px 0 -8px 0;
  height: 75px;
  color: #ffffff;
}

.daterangepicker .input-mini.active {
  border: none;
  border-radius: 0px;
  background-color: #9fd44e;

}

div.calendar.left {
  position: relative;
}

div.calendar.left div.daterangepicker_input input.input-mini.form-control {
  position: absolute;
  right: 56px;
  margin-top: 83px;
  width: 209px;
}

div.calendar.right {
  position: relative;
}

div.calendar.right div.daterangepicker_input input.input-mini.form-control {
  position: absolute;
  right: 94px;
  margin-top: 83px;
  width: 209px;
}

.daterangepicker.dropdown-menu {
  z-index: 1000000;
}

.daterangepicker th.month {
  font-family: "Open Sans";
}

div.calendar-table table.table-condensed tbody {
  font-family: "Open Sans";
}

span.tooltiptext.tooltipScroll::-webkit-scrollbar-thumb {
  background-color: #dcdcdc;
  border-radius: 3px;
  height: 51px;
}

**Comment by kinamartinez** [comment]
and the component

@Component({
    selector: 'date-range-picker',
    template: `
    
        <input #dateRangeInput type="text"
class="daterangepickerBigInput" readonly/>
    
`
})


I hope that this can help you

**Comment by arulnithi** [comment]
This was super helpful! Thank you 😃
