### ISSUE TITLE
QUESTION: Is it possible to set the second calendar to the same month of the first one?

### ISSUE THREAD

**Issue by SlowburnAZ** [dangrossman/bootstrap-daterangepicker#1542]
If I configure the two calendars to be unlinked, is there a way then to configure things so the second calendar starts off by showing the same month as the first?

**Comment by dangrossman** [comment]
No, that sounds confusing for the user (why is everything mirrored twice?). If you want to do it, you can edit the code that determines which months are in view:

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L556

**Comment by SlowburnAZ** [comment]
Ok, thanks.
