### ISSUE TITLE
Feature Request: "Ranges" select buttons for singleDatePicker mode

### ISSUE THREAD

**Issue by AllenJB** [dangrossman/bootstrap-daterangepicker#1543]
I would like to be able to have buttons that select predefined dates when using singleDatePicker mode, similar to the "ranges" buttons in range mode.

This appears to work as expected with some minor CSS tweaks to force the buttons to be shown and "pseudo ranges" for values: https://jsfiddle.net/AllenJB/pjshvjLz/

It would obviously be nice for this functionality to work "out of the box" as my current solution won't work well with multiple instances on the page where you want some to have buttons and some to not.

It should be relatively easy to get rid of the "pseudo-ranges" requirement on the options with something like the following on initialization of the ranges option array: If we're in single date picker mode, and the value is not an array, make it an array containing the same value twice.

The "ranges" option label issue can be worked around by allowing the option to also be called something else (obviously you want to keep "ranges" for compatibility, but copying the option value from one key to another during init is trivial) - perhaps "customButtons"

If you are aware of any known issues I haven't detailed here, please let me know (Are there reasons this functionality has been disabled?)

I intend to work on a PR for this when I get some time.

Related:

* https://github.com/dangrossman/bootstrap-daterangepicker/issues/522
* https://github.com/dangrossman/bootstrap-daterangepicker/issues/609
* https://github.com/dangrossman/bootstrap-daterangepicker/issues/1126
* https://github.com/dangrossman/bootstrap-daterangepicker/issues/1139

**Comment by jackytrue** [comment]
Is there any way to restrict the year range in the dropdown as well?

**Comment by iHadDream** [comment]
prefect solve question

**Comment by Developer314** [comment]
@AllenJB 
Can you help me to set singleDatePicker to true for the 'custom range' in ranges? 
```
$('input[name="filterByDate"]').daterangepicker({
        timePicker: true,
        timePickerIncrement: 30,
        autoUpdateInput: false,
        locale: {
          format: 'MM/DD/YYYY h:mm A'
        },
        ranges: {
          'Today': [moment(), moment()],
          'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days': [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month': [moment().startOf('month'), moment().endOf('month')],
          'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
      })
```
Here is my view file looks https://www.dropbox.com/s/pfvn4ga8mnxi213/Screen%20Shot%202018-05-09%20at%206.55.48%20PM.png?dl=0

**Comment by vj9497** [comment]
@AllenJB 
Can you help me to set singleDatePicker to true for the 'custom range' in ranges? 
```
$('input[name="filterByDate"]').daterangepicker({
        timePicker: true,
        timePickerIncrement: 30,
        autoUpdateInput: false,
        locale: {
          format: 'MM/DD/YYYY h:mm A'
        },
        ranges: {
          'Today': [moment(), moment()],
          'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days': [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month': [moment().startOf('month'), moment().endOf('month')],
          'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
      })
```
Here is my view file looks https://www.dropbox.com/s/pfvn4ga8mnxi213/Screen%20Shot%202018-05-09%20at%206.55.48%20PM.png?dl=0
