### ISSUE TITLE
locale.monthNames doesn't work in input

### ISSUE THREAD

**Issue by Nicknixer** [dangrossman/bootstrap-daterangepicker#1551]
See picture, my names of month doesn't show in inputs.

![picker](https://user-images.githubusercontent.com/4386705/29317590-555a40de-81d5-11e7-94f4-734d84314996.png)

Settings:

`

            this.pickerOptions.settings = {
            skipCSS: true,
            opens: 'left',

            showWeekNumber: true,
            showDropdowns: true,
            buttonClasses: "button button-md button-small button-small-md",
            applyClass: "button-success button-success-md",
            cancelClass: "button-default button-default-md button-md-light",
            locale: {
                format: "D MMMM YYYY",
                separator: " - ",
                applyLabel: "Выбрать",
                cancelLabel: "Отменить",
                fromLabel: "С",
                toLabel: "По",
                weekLabel: 'Нед.',
                customRangeLabel: "Свой вариант",
                daysOfWeek: [
                    "Вс",
                    "Пн",
                    "Вт",
                    "Ср",
                    "Чт",
                    "Пт",
                    "Сб"
                ],
                monthNames: [
                    "Январь",
                    "Февраль",
                    "Март",
                    "Апрель",
                    "Май",
                    "Июнь",
                    "Июль",
                    "Август",
                    "Сентябрь",
                    "Октябрь",
                    "Ноябрь",
                    "Декабрь"
                ],
                firstDay: 1
            }
        };
`

Help me, please.

**Comment by dangrossman** [comment]
Date strings are parsed and printed using the Moment.js library. You can set your locale in that library to have the correct month names. http://momentjs.com/docs/#/i18n/
