### ISSUE TITLE
Prevent selected range with invalid date

### ISSUE THREAD

**Issue by benlegault** [dangrossman/bootstrap-daterangepicker#1552]
I would like to be able to select only dates that are within a range with no invalid date inside the rage.  Let's say that wednesday is an invalid date, I would like to be able to select or monday, thuesday, or thursday and on...not from monday to friday.

**Comment by dangrossman** [comment]
This library does not provide that functionality, you will need to implement that requirement yourself

**Comment by olasunkanmi04** [comment]
Is this functionality available now?
