### ISSUE TITLE
Can't select single Sunday of the 33 week, DST time related

### ISSUE THREAD

**Issue by jlanzarotti** [dangrossman/bootstrap-daterangepicker#1553]
This is a bit tricky and hard to explain. 

On machines that are in a UTC location that makes a day difference, the Sunday of week 33 is impossible to single select. The selector will select the sunday and next monday. 

1- If I set my machine in UTC-0/UTC+ locations the problem does not happen. 
2- If I set my machine in UTC- / UTC-3 for example, I can reproduce it, due the UTC-3 has a -1 day difference, lets say UTC-0 is Thursday and UTC-3 is still Wednesday.  

Setting a timezone in the machine that satisfices this day difference agains UTC-0, try to select Aug 13th as a single day, week 33. For the next year 2018, try to select Aug 12th as a single date, week 33. You can reproduce it with the next years as well.

This is an example, 01:24:54 Thu UTC / Machine set to 22:24:45 Wed GMT-3 

![screen shot 2017-08-16 at 22 24 00](https://user-images.githubusercontent.com/2772605/29392030-a9800296-82d1-11e7-9991-7a4644825555.png)

Try to just select the 13th is impossible.

**Comment by jlanzarotti** [comment]
UPDATE: This seems to only happen when the DST is going to occur. My test in "Santiago - Chile" that is GMT-3 where I can reproduce the problem.

**Comment by dangrossman** [comment]
Here's a possible workaround: https://github.com/dangrossman/bootstrap-daterangepicker/issues/1520

I don't even have a proper computer right now as it's at a repair center getting fixed, I'll be on vacation next week, and I have a full workload for at least a month after I get back, so I won't be making any changes here myself for a while. 

Hopefully doing a new major version of this library before the end of the year, and I will try to avoid these DST issues next time around.

**Comment by jlanzarotti** [comment]
Thanks @dangrossman ! the workaround seems to work. I'll close this one for now.
