### ISSUE TITLE
Pull Down preselect Today as active

### ISSUE THREAD

**Issue by vaske** [dangrossman/bootstrap-daterangepicker#1559]
Hi there,

When start and end date are null, when we show up date range dropdown `Today` has been selected as default value, is there any chance to prevent this behavior?

Cheers,
M

**Comment by kumkanillam** [comment]
Me too passing the empty value for the default value which I introduced for  `All time` range selection. everything works well, except drop-down selected `today` as value internally.

**Comment by dangrossman** [comment]
No you can't prevent this, there is always a selection internally, if you don't provide a startDate/endDate then they will default to today's date.
