### ISSUE TITLE
Wrong date being disabled

### ISSUE THREAD

**Issue by agrandin** [dangrossman/bootstrap-daterangepicker#1562]
Wrong date are being disabled in my calender view. 

I provided an array of available dates, and it does not have 2017-09-18 but in the calender view it is 2017-09-19 that is not being able to be selected.

Example in fiddle below
https://jsfiddle.net/n1xmjw1d/

**Comment by dangrossman** [comment]
It's because you're using toISOString().slice() to get the date portion of the date object for some reason, but toISOString() also shifts you to time zone GMT+0...

https://jsfiddle.net/e3oyzLw5/
