### ISSUE TITLE
Custom Range calendars only displaying downwards

### ISSUE THREAD

**Issue by ILBACE** [dangrossman/bootstrap-daterangepicker#1563]
Hi,

I am having an issue where the custom range is only displaying downwards as per the attached image
![daterange](https://user-images.githubusercontent.com/31657463/30061948-cc89748c-928c-11e7-97d6-6dd65b4cbb80.jpg)

<BR><BR>
I need the two calendars to show side by side like this
![sidebyside](https://user-images.githubusercontent.com/31657463/30062028-12b1c31a-928d-11e7-9bf6-b2c89d01350e.jpg)

**Comment by dangrossman** [comment]
Your webpage or container is too narrow for everything to appear side by side
