### ISSUE TITLE
Ranges as a dropdown option

### ISSUE THREAD

**Issue by arulnithi** [dangrossman/bootstrap-daterangepicker#1566]
Hi, I was wondering if there is any inbuilt option to display ranges as a dropdown? This will be useful if we have many ranges and it starts to affect the size of the datepicker, or just if we want to have the dropdown option available. I currently feel the only way to do this is to use Jquery and change the DOM object

**Comment by dangrossman** [comment]
As a dropdown within the dropdown? No. This is open source code, you can change the code of the library to suit your needs, you don't have to manipulate it with jquery after the fact.
