### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by Sartani** [dangrossman/bootstrap-daterangepicker#1567]
So I read you won't support it while it's in alpha. Well, it's in beta now and their site defaults to it. So does this now support it or if not, will it in the near future?

**Comment by itelmenko** [comment]
Can anybody forced it to work with bootstrap 4?

**Comment by Sartani** [comment]
Yeah, I got it to work with bootstrap 4. Basically all you need to do is include https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css and it will get the missing glyphs from there.

**Comment by dangrossman** [comment]
That's right, it already works with Bootstrap 4 without changes other than missing icons since Bootstrap doesn't load any by default
