### ISSUE TITLE
Not working with scoped bootstrap

### ISSUE THREAD

**Issue by jtlindsey** [dangrossman/bootstrap-daterangepicker#1573]
I'm using daterange picker and I have bootstrap scoped to a class "bootstrap-scope" ONLY things in that div get the bootstrap class. I did this for a project where bootstrap was only acceptable for the tables. For some reason the daterangepicker is not attaching to the element properly.

Shows up on another part of the page with some crazy formating and when i click on it jumps to another part of the page and throws an error.
`Cannot read property 'format' of undefined` as if it can't attach to an element. 

Any ideas?

**Comment by dangrossman** [comment]
This library does depend on bootstrap's CSS

If you hope for someone else to help you with your page, you should provide a webpage or fiddle that demonstrates the issue they can look at

StackOverflow is a good place to ask as well, and they'll expect the same
