### ISSUE TITLE
The last second day of month : wired issue

### ISSUE THREAD

**Issue by higherstar** [dangrossman/bootstrap-daterangepicker#1574]
var daterange_start_date = moment();
var daterange_end_date = moment().add(1, 'day');

$('.select-date').daterangepicker(
           {
               startDate: daterange_start_date,
               endDate: daterange_end_date,
               minDate: moment(),
               autoApply: true,
               ranges: {
                   'Today': [moment(), moment()],
                   'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                   'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                   'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                   'This Month': [moment().startOf('month'), moment().endOf('month')],
                   'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
               },
               opens: 'left',
               format: 'MMMM DD, YYYY',
               locale: {
                   format: 'MMMM DD, YYYY',
                   daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                   monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                   firstDay: 1
               },
               applyClass: "daterangepicker_apply",
               cancelClass: "daterangepicker_cancel"
           },
           function (start, end) {
               $('#rc-ar').val(start.format('MM-DD-YYYY'));
               $('#rc-de').val(end.format('MM-DD-YYYY'));
               $("#check-in-out-date, .mobile-view #check-in-out-date").removeClass('has-error');
               startDate = start;
               endDate = end;
           }
       );

The problem is that when start date is set as the second date from the end of month, the daterangepicker is not fully compiled.
Only when today is the last second date from the end of month.

**Comment by dangrossman** [comment]
Can you provide a webpage, fiddle or code that demonstrates the problem you're describing? I'm not getting it from your description and the code you did provide seems to work fine to me.
