### ISSUE TITLE
AMD path of the UMD wrapper pollutes the global namespace

### ISSUE THREAD

**Issue by aluanhaddad** [dangrossman/bootstrap-daterangepicker#1578]
I realize this is intentional, as stated in a comment above it, but the code on line [14 of this library](https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L14) overwrites any property of the global object with the name `daterangepicker` when registering as AMD.

This inconsistent with the CommonJS path.

I would like to use this library but it pollutes my global namespace.

This should be deprecated and removed.

**Comment by dangrossman** [comment]
Are you saying the UMD template is wrong?

https://github.com/umdjs/umd/blob/master/templates/returnExportsGlobal.js

**Comment by aluanhaddad** [comment]
@dangrossman I am saying that the wrong one is being used. See https://github.com/umdjs/umd/blob/master/templates/returnExportsGlobal.js#L2

**Comment by aluanhaddad** [comment]
@dangrossman Sorry if I wasn't clear.

The issue is that when loading this package as AMD, it still registers a global. This is not necessary.

UMD has many templates and some of them mix loader/environment detection with unconditional global registration along certain paths and it's actually rather confusing.

If this package is loaded in a CommonJS environment, it does not pollute the global namespace. But if it is loaded in an AMD environment it does.

The template that should be used is https://github.com/umdjs/umd/blob/master/templates/returnExports.js

While that has a confusing name, it actually creates a global when and only when there is no AMD loader available and a CommonJS environment is not detected.

**Comment by DevGps** [comment]
is there any update on this being implemented and merged into master deployment?

**Comment by aluanhaddad** [comment]
@DevGps I created #1611 for this but it is a breaking change as undisciplined AMD users may have incorrectly referenced the global. However, that seems like an edge case as this is a jQuery plugin.
