### ISSUE TITLE
It has a error with webpack

### ISSUE THREAD

**Issue by threescales** [dangrossman/bootstrap-daterangepicker#1579]
WARNING in ./node_modules/bootstrap-daterangepicker/node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/Users/zhangyouming/work/pickever/fe_app/node_modules/bootstrap-daterangepicker/node_modules/moment/src/lib/locale'
 @ ./node_modules/bootstrap-daterangepicker/node_modules/moment/src/lib/locale/locales.js 65:16-60
 @ ./node_modules/bootstrap-daterangepicker/node_modules/moment/src/lib/locale/locale.js
 @ ./node_modules/bootstrap-daterangepicker/node_modules/moment/src/moment.js
 @ ./node_modules/bootstrap-daterangepicker/daterangepicker.js
 @ ./node_modules/react-bootstrap-datetimerangepicker/lib/index.js
 @ ./src/operation/components/activity/wechatGroupSetup.tsx
 @ ./src/operation/operation.tsx
 @ ./src/operation.tsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./operation.tsx

**Comment by dangrossman** [comment]
I don't know anything about webpack and can't help you with this

**Comment by threescales** [comment]
I find the question too.
![image](https://user-images.githubusercontent.com/15061441/31448588-6f808e16-ae6a-11e7-855e-d862368a7e77.png)
@dangrossman

**Comment by dangrossman** [comment]
What is DatetimeRangePicker? 

Are you on the github page of the wrong library entirely?
