### ISSUE TITLE
Feature request: an event after the first date is selected + option to advance the calendar

### ISSUE THREAD

**Issue by amarnathm** [dangrossman/bootstrap-daterangepicker#1580]
Great software!

Feature request: an event after the first date is selected will be helpful in some situations. Also, while adding text to each date is possible, will be helpful to make this process easier. Finally, an option to change the opened months after the first date is selected will be helpful. 

Thanks!

**Comment by dangrossman** [comment]
Hi, there's nobody here that takes and develops feature requests, but thanks

**Comment by shailu26** [comment]
i also want this feature cause for custom range my requirement is when use selectes any start date from custom range than it should able to select only 30 days
