### ISSUE TITLE
moment.js replacement with date-fns for reducing size

### ISSUE THREAD

**Issue by rahul-sr** [dangrossman/bootstrap-daterangepicker#1582]
Can we replace moment.js dependency with date-fns: [https://github.com/date-fns/date-fns](https://github.com/date-fns/date-fns),
since it can drastically reduce the size of the library?
Here is a brief comparison: [https://github.com/date-fns/date-fns/issues/275#issuecomment-264934189](https://github.com/date-fns/date-fns/issues/275#issuecomment-264934189)
@dangrossman  I would be happy to pick it up, if suggested.

**Comment by bcamarneiro** [comment]
This would be cool.

**Comment by dangrossman** [comment]
No, this would be a breaking change
