### ISSUE TITLE
"parentEl" correct usage?

### ISSUE THREAD

**Issue by morrow95** [dangrossman/bootstrap-daterangepicker#1583]
figured it out

**Comment by chopstik** [comment]
I had an issue with the `parentEl` option. The dropdown range was crushed and displaying incorrectly when used on an input that was floating right. I inserted the following bootstrap html and used `parentEl: '#date-picker-dom'` and got the range picker to work as expected.
`<div class="row">
    <div class="col-sm-12" id="date-picker-dom" style="position: absolute;"></div>
</div>`
