### ISSUE TITLE
Show Buttons Apply & Cancel with singleDatePicker

### ISSUE THREAD

**Issue by BrunoEngComp** [dangrossman/bootstrap-daterangepicker#1584]
Does not show buttons with singleDatePicker: true, only show when "timePicker": true

**Comment by dangrossman** [comment]
Because they serve no purpose in that situation

**Comment by dkennedy26** [comment]
It does serve a purpose, we have encountered the same issue. It's not intuitive to force the user to click out of the calendar to update the value, it needs a confirmation/apply button.

**Comment by dangrossman** [comment]
Click out of the calendar? What? After clicking on a date, the calendar disappears, and the value is updated. There is no other action to take.

**Comment by dkennedy26** [comment]
Not when you also have the time selector; the calendar remains open until you click out of it.

**Comment by dangrossman** [comment]
When there is a time selector, there is an apply and cancel button. Your comments don't make sense.

**Comment by dkennedy26** [comment]
perhaps I'm using a different or older version. I'll check and update.
