### ISSUE TITLE
Strange issue when formatting - utc and timezones

### ISSUE THREAD

**Issue by morrow95** [dangrossman/bootstrap-daterangepicker#1589]
I need to allow the user to select a date/time in a chosen timezone regardless of the timezone their device is.  In this example, I am forcing "America/Los_Angeles".   I am manually applying and cancelling values.  I am also creating a second hidden input value `#sc-datestart-db` that shows the current selected date/time in a different format.

Here are the step to reproduce the problem : 

- refresh page (there is no date/time selected - it is empty at the moment)

- Choose Oct 19 @ 12:30pm
display value is "Thursday, October 19, 2017 @ 12:30 PM" **CORRECT**
#sc-datestart-db value is "Thu Oct 19 2017 12:30:00 GMT-0700" **CORRECT**

- Now I change to Oct 20 @ 12:30pm
display value is "Friday, October 20, 2017 @ 12:30 PM" **CORRECT**
#sc-datestart-db value is "Fri Oct 20 2017 09:30:00 GMT-0700" **WRONG**

Why when I change it the second time it mysteriously takes 3 hours away though still in the correct timezone?  It just so happens that my current timezone is 3 hours ahead of "America/Los_Angeles".

I don't understand why it shows correctly initially then doesn't the second time.  Even stranger is I can change it back to Oct 19 @ 12:30pm and the values are correct again.

```
$('#sc-datestart').daterangepicker({
    "singleDatePicker": true,
    "showWeekNumbers": true,
    "timePicker": true,
    "timePickerIncrement": 30,
    "autoApply": false,
    "autoUpdateInput": false,
    "locale": {
        "cancelLabel": "Clear"
    },
    "parentEl": "#sd-datestart",
    "startDate": moment.utc().tz('America/Los_Angeles').startOf('day').hour(12),
    "endDate":   moment.utc().tz('America/Los_Angeles').add(2, 'year').endOf('day'),
    "minDate":   moment.utc().tz('America/Los_Angeles').startOf('day').hour(12),
    "maxDate":   moment.utc().tz('America/Los_Angeles').add(2, 'year').endOf('day'),
    "opens": "right",
    "cancelClass": "btn-secondary"
}).on('apply.daterangepicker', function(ev, picker) {
	$('#sc-datestart').val(picker.startDate.format('dddd, MMMM D, YYYY [@] h:mm A'));
	$('#sc-datestart-db').val(moment.utc(picker.startDate).tz('America/Los_Angeles'));
	$(this).valid(); //jquery validation script
}).on('cancel.daterangepicker', function(ev, picker) {
	$(this).val('');
	$('#sc-datestart-db').val('');
	$(this).valid(); //jquery validation script
});
```

**Comment by dangrossman** [comment]
You'll never get this to work correctly, this library is not time zone aware and will not maintain whatever time zone you used consistently. Take the date and time chosen by the user as strings, and consider them in whatever time zone you want them to be in. Build your own date object, don't use the one you get from the picker. You can reliably say "the user chose October 19th at 7:30 PM" and then create a date object with that info in whatever time zone you want.

**Comment by morrow95** [comment]
So are you saying I can't use your plugin since the picker will never create the correct strings?  I didn't think this would be a problem since its requires moment.js, but it sounds as though you are only using that for formatting rather than as a whole?

**Comment by morrow95** [comment]
Lot of manipulation on my end, but was able to make this work.  Creating is not really a problem.  I take the the non-timezone specific date/time string from the daterangepicker and convert it to a utc timestamp which is timezone specific in php (I know the timezone ahead of time) and store in the database.

What was tough is editing a record already set.  I have to convert the UTC timestamp back into a string in that given timezone to use as a start date among other things in the daterangepicker initialization.  Decent amount of ajax and posting going on for all of that.

In the end it was doable, but involved a decent amount of work to get it done.
