### ISSUE TITLE
点击几次，背景会变成部分透明

### ISSUE THREAD

**Issue by zhaoyumei** [dangrossman/bootstrap-daterangepicker#1590]
![image](https://user-images.githubusercontent.com/23609837/31811278-85323e82-b5b1-11e7-931c-d07c14855115.png)

选择日期，背景会部分透明

**Comment by g8up** [comment]
Translated Words:
The part of background in the datepicker panel became opacity after picking date.

**Comment by dangrossman** [comment]
I don't know why

I think it's your stylesheet
