### ISSUE TITLE
daterangepicker prob.. Is there a way to disable a specific time range in timepicker?..

### ISSUE THREAD

**Issue by Lemar101013** [dangrossman/bootstrap-daterangepicker#1591]
Is there a way to disable a specific time range in timepicker?..for example: i want disable 12am-7:59am and 5:01pm to 12:00am because its a non working hours.. I've been looking for a solution but can't find one.. Hope someone could help me..thank u

**Comment by dangrossman** [comment]
This library does not have that ability
