### ISSUE TITLE
Displaying the months inverted

### ISSUE THREAD

**Issue by javierpacareu** [dangrossman/bootstrap-daterangepicker#1595]
I'm having a problem with the component because is showing the pair of month inverted:
Any idea of how to solve it

`
<div id="daterangepicker-mesas" class="pull-left" style="background: #fff; cursor: pointer; padding: 5px 10px; margin-left: 10px; border: 1px solid #ccc; width: fit-content;">
    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
    <span></span> <b class="caret"></b>
  </div>
</div>
`

`var start = moment().startOf('month');
    var end = moment().endOf('month');
    var init = function (start, end) {
        $('#daterangepicker-mesas span').html(start.format('DD-MM-YYYY') + ' - ' + end.format('DD-MM-YYYY'));
    }
   init(start, end);
  
    $('#daterangepicker').on('apply.daterangepicker', function(ev, picker) {
    //do something, like clearing an input
    var start = picker.startDate.format('YYYY-MM-DD');
    var end = picker.endDate.format('YYYY-MM-DD');
    console.log({start: start, end: end});

  });
    $('#daterangepicker').daterangepicker({},init);`

**Comment by dangrossman** [comment]
Does removing your stylesheet file from the page fix it? Conflicting class names / styles perhaps?

**Comment by b-hicks** [comment]
I'm having the same issue as well, but it only occurs when I run my web application in chrome, not firefox.

**Comment by timm3** [comment]
I noticed this issue a few months ago. From what I could see, it has to do with the 'float: left' being handled differently between Chrome and Firefox. The website I've noticed it on uses the Inspinia Bootstrap theme, if that helps. I have not tried to replicate this in an environment without said theme.
