### ISSUE TITLE
fa or glyphicon not both

### ISSUE THREAD

**Issue by tiberiumihai** [dangrossman/bootstrap-daterangepicker#1597]
Hi there,

I saw that the classes look something like this: "fa fa-calendar glyphicon glyphicon-calendar".

Is there a way to set only a specific icon set?

I enabled both fa and glyphicon and for some reason, glyphicon is not rendered.

"\1f4c5" is rendered but "\e109" is not. In browser glyphicon-calendar content is "\e109" and is rendered as a square.

It would be nice if we can set only specific icons like in boostrap's datepicker:
```
icons: {
  time: 'fa fa-time',
  date: 'fa fa-calendar',
  up: 'fa fa-chevron-up',
  down: 'fa fa-chevron-down',
  previous: 'fa fa-chevron-left',
  next: 'fa fa-chevron-right',
  today: 'fa fa-screenshot',
  clear: 'fa fa-trash',
  close: 'fa fa-remove'
}
```

Or maybe there is another way to solve this?

![image](https://user-images.githubusercontent.com/12754525/32227928-57e6f448-be55-11e7-99ad-89ae3eb68bcd.png)

**Comment by Virus-X** [comment]
+1 for configuration option!
I'm using primarily icomoon icons, so hardcoded fontawesome is not good for me at all, I had to patch library.

**Comment by dangrossman** [comment]
When I get started on V3, if there are icons, I will make it configurable
