### ISSUE TITLE
Autoupdating maxDate, minDate and ranges as time passes

### ISSUE THREAD

**Issue by fracz** [dangrossman/bootstrap-daterangepicker#1600]
The example configuration of `maxDate`, `minDate` and `ranges`

```js
{
  timePicker: true,
  maxDate: moment(),
  ranges: [
   'Today': [moment().startOf('day'), moment()],
  ]
}
```

becomes "obsolete" when the page with datepicker is opened for a long time. For example, in one hour from now, the `maxDate` should be "now", not 1 our before. Also, the `Today` range should respect the time that has passed already since the first render.

My suggestion: the confuguration should allow to configure functions that return the dates instead of instantiating them once during init. Then, if the configiration contains functions and when a range is selected or the validation takes place - the plugin should execute the function in order to get actual settings.

Example:

```js
{
  timePicker: true,
  maxDate: function(){ return moment(); },
  ranges: [
   'Today': [function(){ return moment().startOf('day'); }, function(){ return moment(); }],
  ]
}
```

Whad do you think about such solution?

**Comment by dangrossman** [comment]
Perhaps in a future version
