### ISSUE TITLE
Calendar is open as soon as the Page Loads

### ISSUE THREAD

**Issue by akarpas** [dangrossman/bootstrap-daterangepicker#1603]
I have used the example at https://projects.skratchdot.com/react-bootstrap-daterangepicker/ and the Calendar works fine, the only issue is that as soon as the page is loaded (without pressing on the button) the calendar picker is already open in the corder of the page. Is there a way to fix this?

When the page loads and then I click on the button, the calendar reappears in the correct position under the button, and then works fine.

**Comment by dangrossman** [comment]
I don't see a calendar anywhere on load.  I checked in Chrome, Firefox, IE.
