### ISSUE TITLE
AOT serve

### ISSUE THREAD

**Issue by ASiraan** [dangrossman/bootstrap-daterangepicker#1606]
ERROR in Error at /home/fidgerald/Orographic/Jonathan-Ng2/node_modules/ngx-bootstrap/datepicker/daypicker.component.d.ts.DayPickerComponent.html(53,38):  ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" [ERROR ->]let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].sec")
Error at /home/fidgerald/Orographic/Jonathan-Ng2/node_modules/ngx-bootstrap/datepicker/daypicker.component.d.ts.DayPickerComponent.html(53,59):  ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" let-rowz="$implicit" [ERROR ->]let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6].sec")

**Comment by dangrossman** [comment]
I don't think you're at the right repository; this is bootstrap-daterangepicker not "datepicker" or "daypicker".

**Comment by ASiraan** [comment]
My bad,
