### ISSUE TITLE
Two months one input

### ISSUE THREAD

**Issue by bartek1234321** [dangrossman/bootstrap-daterangepicker#1610]
Hi, is it possible to set up calendar with two months and one input field?

**Comment by dangrossman** [comment]
That's the default behavior of this library

http://www.daterangepicker.com/#examples

**Comment by bartek1234321** [comment]
sorry it's wrong question, is it possible to set up one calendar with two months and one input field with one date value? so i need one calendar with two months displayed and one input field with only one value

**Comment by dangrossman** [comment]
No

**Comment by bartek1234321** [comment]
ok, thanks for fast reply.
