### ISSUE TITLE
How to hide 2nd calendar

### ISSUE THREAD

**Issue by dorogoff** [dangrossman/bootstrap-daterangepicker#1615]
Hello,
thanks for this plugin, I have a small question, hope for yur help. 

Any chance to hide 2nd calendar and left only first one? I mean I want to use singleMode but for range :) is it possible with hack or something like that?

Thanks!

**Comment by dangrossman** [comment]
There is no option for this, so you would have to edit the code yourself, or perhaps hide it with CSS.
