### ISSUE TITLE
need dropdowns box instead of list items for Predefined Ranges ?

### ISSUE THREAD

**Issue by ahmedzohaib** [dangrossman/bootstrap-daterangepicker#1618]
HI
  I have requirement in y current project to add drop-downs for Predefined Ranges. I have modified that file **daterangepicker.js**  locally and achieve this thing. I have some other requirements and i need to do that as well. i want to become a contributor in this project and i want that the file i will modify should be on upstream ? can we do this thing ii need answers for that i hope you will welcome me .

**Comment by dangrossman** [comment]
I don't understand your request. If you've made changes to meet your requirements, what is the purpose of this issue?

**Comment by ahmedzohaib** [comment]
The issue is that i have made changes locally but we are using upstream
repo from cdn . Is it possible to add these changes in upstrean reoo and
available for every one .

**Comment by dangrossman** [comment]
Thanks for clarifying. No you cannot add your personal customizations to the upstream repository, as we don't all have the same requirements as your project. You can host your own copy of your own repository on a CDN somewhere, like Cloudflare or CDNJS.
