### ISSUE TITLE
Prev Month question

### ISSUE THREAD

**Issue by soongsta** [dangrossman/bootstrap-daterangepicker#1619]
Hi There

Is there a way to decrement the current displayed value

The following code works

'Last Month': [moment().startOf('month').subtract(1, 'month'), moment().subtract(1, 'month').endOf('month')],

Is it possible to do

'Last Month': [moment( $(this).startDate  ).startOf('month').subtract(1, 'month'), moment( $(this).startDate ).subtract(1, 'month').endOf('month')],

I cant seem to get this to work

**Comment by dangrossman** [comment]
I don't know what you're setting as the "current displayed value", so it's hard to write code to modify that

**Comment by dangrossman** [comment]
Does this help?

https://gist.github.com/dangrossman/0c6c911fea1459b5fd13#file-drp-snippet-6-js

**Comment by soongsta** [comment]
Wow, thanks for the super fast response. I was looking for a way to decrement the date range by 1 month eg if displayed value is "1 Dec 2017 - 31 Dec 2017", clicking "Prev Month" would display "1 Nov 2017 - 30 Nov 2017". Clicking it again would display "1 Oct 2017 - 31 Oct 2017", etc etc. I dont think predefined ranges are the way to do this.

**Comment by dangrossman** [comment]
So "Prev Month" is some other part of your webpage" And the "would display" is also some other part of your webpage? What part of this needs to interact with this library?

**Comment by soongsta** [comment]
Yes, that's the correct assumption. I was hoping to have a defined range of 'Prev Month', which would keep on subtracting a month. I currently have a defined range of 'Last Month' (see below)

 'Last Month': [moment().startOf('month').subtract(1, 'month'), moment().subtract(1, 'month').endOf('month')],

Which will take the current date, and subtract 1 month.
If I wanted to go back another month, the above would not work

I have also tried

 function (start, end, label) {
   console.log('start=' + start);
   console.log('end=' + end);
   console.log('label=' + label);   
   var picker = $(this);   
   if (label == 'Prev Month') {
	   start = moment(start).startOf('month').subtract(1, 'month');
	   end = moment(end).subtract(1, 'month').endOf('month');
	   console.log('start=' + start);
	   console.log('end=' + end);
	   console.log('start=' + start.format('DD MMM YYYY'));
	   console.log('end=' + end.format('DD MMM YYYY'));
	   picker.startDate = start;
	   picker.endDate = end;
   }
}

which did not seem to work

**Comment by dangrossman** [comment]
````
function createPicker(start, end) {
  $('#config-demo').daterangepicker({
    ranges: { 'Previous Month': [moment(start).startOf('month').subtract(1, 'month'), moment(end).subtract(1, 'month').endOf('month')] }
  }, function(start, end, label) {
    createPicker(start, end);
  });
}
createPicker(moment(), moment()); //initial date picker
````

**Comment by soongsta** [comment]
That looks great, Thanks!

Does the events 'apply.daterangepicker' need to be recreated as well?
I have autoUpdateInput set to false.

And I am using a class name instead of an element id to identify the daterange text input. And it does not seem to be populated the value into the text input.

**Comment by dangrossman** [comment]
`autoUpdateInput: false` means "do not automatically update my input", so "it does not populate the value into the text input" is the expected result of using that option

If you're doing something with the `apply.daterangepicker` event I think may need to reattach the event listener in the `createPicker` function.

**Comment by soongsta** [comment]
Thanks, this has helped :-)
