### ISSUE TITLE
Feature request: Index of selected range

### ISSUE THREAD

**Issue by sunco007** [dangrossman/bootstrap-daterangepicker#1621]
Would be nice that you can detect the index of the selected element when a range is configured. This way you can save it on a cookie or something

Of course, needs a kind of "selected" as in a select/option

**Comment by dangrossman** [comment]
The name of the range is passed to your callback function when one is clicked. You can save this. You can "select" a predefined range by setting the startDate and endDate to match that range, it will be highlighted automatically.

**Comment by sunco007** [comment]
Let's say I have a range called "last 5 days" so it will return dic 3 to dic 7 

Tomorrow it will return dic 4 to dic 8

That's why I need to save the index, not the returned date

**Comment by dangrossman** [comment]
You will have saved "Last 5 days", not "dic 3 to dic 7", so you can calculate "dic 4 to dic 8" and set those dates.
