### ISSUE TITLE
Initialize value not working without default type text

### ISSUE THREAD

**Issue by sergiobelya** [dangrossman/bootstrap-daterangepicker#1622]
If an input element contains initial values
and `input` not has attribute `type="text"` (default for html)
initialize value is incorrect.
See https://github.com/dangrossman/bootstrap-daterangepicker/blob/v2.1.25/daterangepicker.js#L287

Maybe
`if ($(this.element).is('input[type=text]') || $(this.element).prop('type') === 'text') {`
will resolved this problem.

**Comment by dangrossman** [comment]
Or add `type="text"` to your input

**Comment by sergiobelya** [comment]
That's exactly what I did.
But attribute `type="text"` is redundant.
