### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by jigneshparmar126** [dangrossman/bootstrap-daterangepicker#1623]
`
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.16.2",
    "babel-preset-env": "^1.6.1",
    "bootstrap": "4.0.0-alpha.6",
    "browser-sync": "^2.18.13",
    "browser-sync-webpack-plugin": "^1.2.0",
    "cross-env": "^5.1.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.1.1",
    "laravel-mix": "^1.6.1",
    "lodash": "^4.17.4",
    "vue": "^2.5.9"
  },
  "dependencies": {
    "@riophae/vue-treeselect": "0.0.3",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "element-ui": "^2.0.7",
    "js-beautify": "1.6.14",
    "moment": "^2.19.2",
    "node-sass": "4.5.3",
    "raven-js": "^3.20.1",
    "select2": "^4.0.4",
    "vee-validate": "^2.0.0-rc.25",
    "vue-multiselect": "^2.0.3",
    "vue-slider-component": "^2.4.6",
    "vue-star-rating": "^1.5.1",
    "vue-tinymce-editor": "^1.4.4",
    "vuejs-paginate": "^1.5.0"
  }
}
`

/cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js

**Comment by dangrossman** [comment]
There's nothing I can do with this blob of text from your project.
