### ISSUE TITLE
issue with from to to picker

### ISSUE THREAD

**Issue by vishalsingh119** [dangrossman/bootstrap-daterangepicker#1624]
hi,

i added two input with daterange picker . now i need that if user select 10 in from section(first input), then in to date picker(secound input) , date must start from 10.

**Comment by dangrossman** [comment]
When a date is chosen in the first picker, your callback function will be triggered and passed the new selection.

In that callback function, recreate the second picker (`$(secondel).daterangepicker(options...)`) with a `minDate` option set to the date that was selected in the first picker.

**Comment by vishalsingh119** [comment]
Thanks for quick response. We already added thse option. Have a look into code-

For first picker-
$('#startdate').daterangepicker({
	applyClass:"riseup-btn reset-success-btn",
	cancelClass:"riseup-btn riseup-btn-cancel",
	singleDatePicker: true,
	dateLimit: {
        "days": 60
    },
	"locale": {
        "format": "MMM DD YYYY"
	}});

for the second input-
       var maxdate = new Date();
	var mindate = new Date(maxdate.setDate(maxdate.getDate() + 1));
	maxdate.setMonth(maxdate.getMonth() + 3);
	$('#enddate').daterangepicker({
	applyClass:"riseup-btn reset-success-btn",
	cancelClass:"riseup-btn riseup-btn-cancel",
	singleDatePicker: true,
	minDate:mindate,
	maxDate:maxdate,
	startDate: mindate,
	endDate: mindate,
	dateLimit: {
        "days": 60
    },
	"locale": {
        "format": "MMM DD YYYY"
	}});


but its not working

**Comment by dangrossman** [comment]
You have not written any code that does anything when a user selects a date in the first picker ("from").

**Comment by vishalsingh119** [comment]
Hi, 
I made a fiddle for you for better understanding.
https://jsfiddle.net/vishalsingh119/8auw2rcp/

Plz see into the issue, and guide me how to fix this.

**Comment by dangrossman** [comment]
https://jsfiddle.net/8auw2rcp/2/

**Comment by vishalsingh119** [comment]
Thanks a lot and quick response is appreciated.
