### ISSUE TITLE
Ranges and apply

### ISSUE THREAD

**Issue by templth** [dangrossman/bootstrap-daterangepicker#1625]
Hello,

I successfully implemented ranges with ng2-datarangepicker / bootstrap-daterangepicker. They are correctly displayed and when I click on them, the range is selected. I would like to change a bit the behavior and not close the range picker dialog when clicking on a range but only display the range on the picker. The ranger dialog would be closed when clicking on the "apply" button... Is something possible using configuration only?

Thanks very much for your answer!

**Comment by dangrossman** [comment]
No, you have to edit code. You'd have to comment out the last line of the `clickRange` function: https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L1204
