### ISSUE TITLE
Release 2.1.26 introduces es6 dependency

### ISSUE THREAD

**Issue by fdelayen** [dangrossman/bootstrap-daterangepicker#1626]
Hi !

The last release 2.1.26 introduces an es6 dependency at this line (1641) of daterangepicker.js : 

> let implementOptions = $.extend(true, {}, $.fn.daterangepicker.defaultOptions, options);

I think it should be avoided as it's the only one and it drops a range of browser support. Or may be you should provide an es5 build of this library.

At this point, a **_var_** would not change anything :P

**Comment by dangrossman** [comment]
Didn't notice when I merged that patch from someone, thanks

**Comment by fdelayen** [comment]
No problem, thanks for quick merge :)
