### ISSUE TITLE
Date range pickers not  setting different time zone date format.

### ISSUE THREAD

**Issue by pratiksha-chandel** [dangrossman/bootstrap-daterangepicker#1634]
options="{locale: {format : 'MM/DD/YYYY'}}"
Html file change :+1: 
< input options="{locale: {format : 'MM/DD/YYYY'}}" class=" your class name" logic -function >

javascript file change

  if(vm.isAutomated) {
                   vm.params.start ="11/14/2017, 09:41:19" ;
                   vm.params.end ="12/14/2017, 09:41:19" ;
                    getOrders(vm.customerId, vm.params);
                }

I have tried out this way. Its working for now but want exact solution .
I have given hard coded value .
Help me in that.

**Comment by dangrossman** [comment]
1. I don't understand your question
2. This library has no code that reads options from HTML tags like that
3. Your format (MM/DD/YYYY) does not match your dates (MM/DDDD/YYYY, HH:ii:ss?)

**Comment by pratiksha-chandel** [comment]
< input dateRangeOptions ="{locale: {format : 'MM/DD/YYYY'}}" > 
 working for me for now,
Problem i am facing .
  1 ] Date picker getting fails for different time zone.

**Comment by pratiksha-chandel** [comment]
What should I do for this? Any change required .
I am working on Angularjs.

**Comment by dangrossman** [comment]
I still don't understand your question, and I don't know anything about angularjs.

**Comment by pratiksha-chandel** [comment]
Ok , I am trying from my end lets figure out and will post update here.
Thank you .

**Comment by shivbachan14** [comment]
If i'm not mistaken so you are looking for date formatting. Please try below code for what ever date format you want.

 $filter('date')($scope.print.todate, 'MM/dd/yyyy')
