### ISSUE TITLE
Why dropdown disappears when I shrink browser window?

### ISSUE THREAD

**Issue by antonpegov** [dangrossman/bootstrap-daterangepicker#1635]
Can you please explain positioning principals of popup. I cant understand why for my first dropdown has **style="top: 193px; left: 350.125px; right: auto;..."** - that is great, but second one has **style="top: 193px; left: auto; right: 0px;..."** which is totally wrong. And its depends of window width and distance from left corner of browser window!

Video: [link](https://www.screencast.com/t/ey0MZQJNOF)

**Comment by dangrossman** [comment]
I don't remember the principals behind some code I wrote 5 years ago, but you can look at it:

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L1043

I don't think you have to worry about users of your site, that are in the process of choosing a date for something, deciding to stop mid-thought to drag the edge of their browser window around their screen.
