### ISSUE TITLE
Daterangepicker month name dropdown issue in IOS 10

### ISSUE THREAD

**Issue by jituthakur91** [dangrossman/bootstrap-daterangepicker#1636]
When selecting a month name from month dropdown in IOS 10.0, month selection of IOS opening multiple times, its open even I am selecting a date range.

You can see the issue on below link:-
https://drive.google.com/open?id=1NEmq3W-zDKBjKqYd2rViu6pZ6m_U1Iyt

**Comment by dangrossman** [comment]
Your link goes to a "You need permission" page

**Comment by jituthakur91** [comment]
You can check on this link : https://youtu.be/L_U3F_No2ko

**Comment by dangrossman** [comment]
Well isn't that strange. 

I don't own any Apple devices to even look at this.

Feel free to submit a PR if you can fix it.
