### ISSUE TITLE
Set 'parentEl' cause the <div> attached correctly in html but not shown

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [dangrossman/bootstrap-daterangepicker#1638]
I am using the newest version and found that if I define `parentEl` as shown in the document (like `#someID`), when I click an input, another `<div>` is attached under the input, but not shown in the view. 

Definition:

```
$(document).ready(function(){
    $('#TimePlan').daterangepicker({
        // locale: {
        //     format: 'DD-MM-YYYY hh:mm'
        // },
        timePicker: true, 
        timePicker24Hour: true,
        timePickerIncrement: 15,            //time interval of minutes
        format: "MM/DD/YYYY HH:mm",
        // autoApply: true,                    //update range automatically without apply and cancel buttons
        // autoUpdateInput: true,              //update the value of <input> automatically
        parentEl: '#TimePlan'               //string, jQuery selector of the parent element, if not provided: 'body'
    }, function(start, end, label) {
        var diff = (moment.duration(end - start)).humanize();
        alert("Time diff:" + diff)
        
    });
});
```
The attached `<div>` and the `<input>`:
```
<input class="form-control" id="TimePlan" name="TimePlan" >
<div class="daterangepicker dropdown-menu ltr show-calendar opensright" style="xxx">
    <div class="calendar left">...</div>
    <div class="calendar right">...</div>
    <div class="ranges">...</div>
</div>
</input>
```

So it does not affect the use, but I am curious if the dropdown menu is already attached around the input, why `parenEl`, specially when you define something, it make the dropdown disappear. Confirmed in Chrome 63.0 and IE 11.

**Comment by dangrossman** [comment]
The `parentEl` determines where in the DOM the date range picker is attached.

The default is the `<body>` element of the page.

The main reason this option exist is to allow you to use a date picker in a modal or other stacking element, where attaching the picker to the `<body>` would result in it being hidden behind the modal or some other element. Instead, you can set the `parentEl` to the modal container.

It does not make sense to set the `parentEl` to an input, since an input is an inline element.

**Comment by WesternGun** [comment]
OK... so how about add this explanation in the doc? I was wondering what it is for and now you clarify this, thx!

**Comment by dangrossman** [comment]
The explanation that already exists in the doc seems sufficient, as nobody else has posted an issue like this in the 5 years it's been there. Sorry.

**Comment by Rvldo** [comment]
hmm
