### ISSUE TITLE
make hour select to be two-digit

### ISSUE THREAD

**Issue by lex-em** [dangrossman/bootstrap-daterangepicker#1639]
please add parameter for printing hours select in two-digit mode

**Comment by dangrossman** [comment]
How dates or times are printed is already fully configurable

**Comment by lex-em** [comment]
okay, how I can print hours in two diggit mode? option text is not formatted and has values 1,2,3... Instead of 01,02,03ююю
```
html = '<select class="hourselect">';

            var start = this.timePicker24Hour ? 0 : 1;
            var end = this.timePicker24Hour ? 23 : 12;

            for (var i = start; i <= end; i++) {
                var i_in_24 = i;
                if (!this.timePicker24Hour)
                    i_in_24 = selected.hour() >= 12 ? (i == 12 ? 12 : i + 12) : (i == 12 ? 0 : i);

                var time = selected.clone().hour(i_in_24);
                var disabled = false;
                if (minDate && time.minute(59).isBefore(minDate))
                    disabled = true;
                if (maxDate && time.minute(0).isAfter(maxDate))
                    disabled = true;

                if (i_in_24 == selected.hour() && !disabled) {
                    html += '<option value="' + i + '" selected="selected">' + i + '</option>';
                } else if (disabled) {
                    html += '<option value="' + i + '" disabled="disabled" class="disabled">' + i + '</option>';
                } else {
                    html += '<option value="' + i + '">' + i + '</option>';
                }
            }

            html += '</select> ';
```

**Comment by lex-em** [comment]
at that time minutes select option has padded values
```
                var padded = i < 10 ? '0' + i : i;
```

**Comment by lex-em** [comment]
@dangrossman can you ask me?

**Comment by guilleCM** [comment]
@lex-em I've faced the same problem. I have found a solution, even though it is not the cleanest one. Every time the daterangepicker container element changes, I call to a function to overwrite the inner html for each option of the .selecthour element. We need to call this function when we click some date in the calendar, when we change the daterangepicker container, or when we open the datepicker dropdown.

So when you mount your datepickerinput you should do something like this:

```
let $datePickerInput = $(youInputRef); 
$datePickerInput.on('show.daterangepicker', padHours);      
$datePickerInput.data().daterangepicker.container.find('.calendar').on('mousedown.daterangepicker', 'td.available', padHours);
$datePickerInput.data().daterangepicker.container.on('change', padHours);

function padHours() {
    let hourSelects = $datePickerInput.data().daterangepicker.container.find('.hourselect');
    for (let select of hourSelects) {
        for (let opt of select) {
            if (opt.innerHTML.length === 1) {
                opt.innerHTML = "0"+opt.value;
            }
        }
    }
}
```

Hope it helps!

**Comment by JoeWoodward** [comment]
This issue still isn't fixed. I can't see anyway to configure this. Changing the locale format doesn't change the select format, am I missing something @dangrossman 

![2019-03-06 at 14 51](https://user-images.githubusercontent.com/442279/53864586-7275d700-401f-11e9-8c0d-32e94cbdf1b5.png)

**Comment by JoeWoodward** [comment]
Need to add padding to https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js#L930
