### ISSUE TITLE
Why does calendar show after page load and stay at a strange position?

### ISSUE THREAD

**Issue by yutzuch** [dangrossman/bootstrap-daterangepicker#1640]
To make the question more clearly, I've screenshot my page.
I keep the top of the browser so that you can see the position.
![question](https://user-images.githubusercontent.com/32250756/34192299-2cef4a56-e588-11e7-82c2-8a6b5f976a33.png)
Also, as you can see, the buttons aren't in the correct style.

Codes below.
HTML:
`<div id="datepicker" style="width: 230px; cursor: pointer; padding: 2px 6px; border: 1px solid #ccc; background: #fff; text-align: left;"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;<span></span></div>`
javascript:
`$('#datepicker').daterangepicker({
  ranges: {
    'Today': [moment(), moment()],
    'Last 7 days': [moment().subtract(6, 'days'), moment()],
    'Last 30 days': [moment().subtract(29, 'days'), moment()],
    'This week': [moment().startOf('week'), moment().endOf('week')],
    'This month': [moment().startOf('month'), moment().endOf('month')],
    'This year': [moment().startOf('year'), moment().endOf('year')],
  }
}, cb);
cb(start, end);
function cb(start, end) {
  $('#datepicker span').html(mformatdate(start) + ' - ' + mformatdate(end));
  //do something
}`
Thanks.

**Comment by dangrossman** [comment]
This would happen if your page were missing the Bootstrap stylesheet

**Comment by yutzuch** [comment]
Thanks! It does work when using Google CDN but still fails when using local.
