### ISSUE TITLE
Changelog is missing

### ISSUE THREAD

**Issue by dezoxel** [dangrossman/bootstrap-daterangepicker#1641]
I'm updating package from `2.1.25` to the latest version (`2.1.30`) and want to verify changelog for any potential issues, but I can't find any info about that.

It is common practice to have the file like `CHANGELOG.md` in the project root. Currently, I have no understanding of how can I ensure that updating the package will not break something.

**Comment by dangrossman** [comment]
Read the Releases page of the repo

There are no changes for 2.1.27->2.1.30 because all that changed was the version number
