### ISSUE TITLE
When I select a DST transition datetime which repeats itself, there is no DST option to distinguish them

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [dangrossman/bootstrap-daterangepicker#1642]
My timezone is CET and during DST time, when the hours leaps forward (02:00 -> 03:00), for example, in 2018.03.25, if I select 02:00, it jumps automatically to 03:00, which is great. (:+1: )

But, when the hour leaps backwards, for example, during 2017.10.29 02:00 to 03:00, there is not DST option to distinguish the hour I choose is the first one or the second one. Something like "summer/winter" checkbox. For instance, if I choose first summer time 02:30 and then winter time 02:30, there is a difference of an hour.

If I want to calculate the difference a span of time which includes these transition hours, can it be a problem?

**Comment by dangrossman** [comment]
I'm not the right person to ask this

**Comment by WesleyBlancoYuan** [comment]
OK I am checking the code, after some research into moment.js and moment-timezone.js, I have something. I don't know if you can give some advice if I launch a PR to achieve this: 
when you select a date-time, in start or end calendar, if this time is in the DST transition time span which repeats itself twice, according to the detected timezone(using `moment.tz.guess()`), it shows an alert telling the user that he is choosing an ambiguous time and shows a checkbox to select whether he means the early or later moment(if not chosen, moment.js always chooses the early one).

I would appreciate if you can tell me which is the right moment to insert this logic, in which function. I wonder if `updateFormInput` is the right place.

**Comment by dangrossman** [comment]
It's gonna be part of your webpage, not part of this library

I do not want to add any timezone code to this library
