### ISSUE TITLE
Start date and End date is unseleceted

### ISSUE THREAD

**Issue by aravinthanpnk** [dangrossman/bootstrap-daterangepicker#1646]
I am using the _2.1.27_ version. I had an issue with two date pickers. When I am trying to select the end date twice (i.e) select the start date as 20 dec & end date as 20 Jan ( later changed the end date as 21 Jan ). In this case, the start date is unselected. Also, the end date is unselected when selecting the end date first then start date. This feature really hard to use. Please make an option for this. I expect to work like _1.3.11_ version.

Also, need an option to select the default date when _drop-down_ or _month_ changes (i.e) select 1st as start and 30th as the end date.  Else provide the event for a month and year changes.

**Comment by dangrossman** [comment]
You should stay on V1 if you want that behavior. It's not coming back.
