### ISSUE TITLE
Show "ranges" labels according to the selected language

### ISSUE THREAD

**Issue by sanjaypanchal-131** [dangrossman/bootstrap-daterangepicker#1647]
I want to show the "ranges" according to the selected language.

`$('#demo').daterangepicker({
    "ranges": {
        "Today": [
            "2017-12-29T13:15:22.095Z",
            "2017-12-29T13:15:22.095Z"
        ],
        "Yesterday": [
            "2017-12-28T13:15:22.095Z",
            "2017-12-28T13:15:22.095Z"
        ],
        "Last 7 Days": [
            "2017-12-23T13:15:22.095Z",
            "2017-12-29T13:15:22.095Z"
        ],
        "Last 30 Days": [
            "2017-11-30T13:15:22.095Z",
            "2017-12-29T13:15:22.095Z"
        ],
        "This Month": [
            "2017-11-30T18:30:00.000Z",
            "2017-12-31T18:29:59.999Z"
        ],
        "Last Month": [
            "2017-10-31T18:30:00.000Z",
            "2017-11-30T18:29:59.999Z"
        ]
    },
    "locale": {
        "format": "MM/DD/YYYY",
        "separator": " - ",
        "applyLabel": "Apply",
        "cancelLabel": "Cancel",
        "fromLabel": "From",
        "toLabel": "To",
        "customRangeLabel": "Custom",
        "weekLabel": "W",
        "daysOfWeek": [
            "Su",
            "Mo",
            "Tu",
            "We",
            "Th",
            "Fr",
            "Sa"
        ],
        "monthNames": [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"
        ],
        "firstDay": 1
    },
    "alwaysShowCalendars": true,
    "startDate": "12/23/2017",
    "endDate": "12/29/2017"
}, function(start, end, label) {
  console.log("New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')");
});`

In the above code, I want to show "Today", "Yesterday" etc. according to the selected language. 

How we can do that? Can you please help?

**Comment by dangrossman** [comment]
These labels are provided by you and not the library. You will need to write your own code in your page to provide them in the selected language.

**Comment by sanjaypanchal-131** [comment]
How can I assign the variable in the label? 

I have values for different languages in variables. While initializing, I want to use these variables as labels. Can you please let me know how we can do that?

**Comment by dangrossman** [comment]
something like....

````
var myRanges = {};
myRanges[label1] = [start_date, end_date];
myRanges[label2] = [start_date, end_date];
...

$('#date').daterangepicker({
  ranges: myRanges
});
````

**Comment by sanjaypanchal-131** [comment]
Thank you very much Dan. It worked for me.
