### ISSUE TITLE
linkedCalendars not initialized error?

### ISSUE THREAD

**Issue by ron0** [dangrossman/bootstrap-daterangepicker#1648]
Hi Dan,
First - great work!

I noticed that after an update (which I did not track) that the from and to calendars in range mode selecting Custom were behaving strangely.  I think this is a duplicate of issues 1434, 1489 and maybe 1503 and 1630.

I realized that the calendars were behaving as linked, even though I had not set that parameter.  Setting it to false clears the problem.

Is linkedCalendars set to true by default?  Or is it unitialized and causing these issues?

Thanks,
Ron

**Comment by dangrossman** [comment]
`linkedCalendars` has been `true` by default since its introduction in 2015
