### ISSUE TITLE
how to set minDate and maxDate after click the  previous date

### ISSUE THREAD

**Issue by LSYUN** [dangrossman/bootstrap-daterangepicker#1649]
I want to limit the maxDate or minDate after picking up the first date while the option "single" in daterangepicker is false. For example, I click "5/11/2017" as the startDate/endDate, then the second click only around "5/10/2017" to "5/12/2017"  are available as endDate/startDate . Which means, the max range is one month . I found the "**clickPrev**" function , but I don't know how to use it.  And does "clickPrev" function can fix my problem? Or is there any way to watch the first click?

Here was what I tried:

$('#selectorId').data('daterangepicker').clickPrev($(this));

**Comment by dangrossman** [comment]
That is an internal function, not something you should be calling.

To limit the date range selection to 1 month, you would use the `dateLimit` option

````
$('#selectorId').daterangepicker({
  dateLimit: { 'months': 1 }
  //+ your other options
});
````

**Comment by LSYUN** [comment]
Thanks a lot! It is what I want!
