### ISSUE TITLE
Display Issue with chrome

### ISSUE THREAD

**Issue by dev-ayaz** [dangrossman/bootstrap-daterangepicker#1651]
some users face issue with chrome that daterangepicker display & then auto hide.
Users are unable to select date.

**Comment by dangrossman** [comment]
Gonna need more to go on than that...

**Comment by dev-ayaz** [comment]
When a user click on date input field daterangepicker appears & then suddenly disappear. 
When i inspect the element the display property auto toggle.
first display set to block & then none automatically.

**Comment by dangrossman** [comment]
That doesn't happen at http://www.daterangepicker.com in Chrome. This library is downloaded hundreds of times a day, and nobody else has opened an issue about this. My point is that I can't help you if I can't see/reproduce the bug. You should share a live webpage or jsfiddle that shows it happening.
