### ISSUE TITLE
startDate

### ISSUE THREAD

**Issue by cescocesco** [dangrossman/bootstrap-daterangepicker#1655]
I have two input "from" and "to". When i focus on "from" i select date range that insert startDate on "from" and endDate to "to". I want to re-open daterangepicker with range started with "from" date when i focus on "to".

```
$('#to').on('click', function () {
    $("#from").trigger('click').focus();
    $("#from").data('daterangepicker').setStartDate($("#from").val());
});
```

The daterangepicker comes up correctly but the range not start, i must click on startDate and endDate. Is there any solution?

**Comment by dangrossman** [comment]
This picker does not have that feature, so you're on your own if you want to try to create it.

**Comment by cescocesco** [comment]
@dangrossman Ok thanks

**Comment by texasinstrument** [comment]
@cescocesco I have similar use case scenario, were you able to make it work?
