### ISSUE TITLE
daterange reset selected dates after clicking apply

### ISSUE THREAD

**Issue by Psalms23** [dangrossman/bootstrap-daterangepicker#1656]
Hi. how do I reset the selected dates on daterangepicker when i click the apply button.

**Comment by dangrossman** [comment]
````
$('#yourelement').on('apply.daterangepicker', function(ev, picker) {
  picker.setStartDate(something);
  picker.setEndDate(something);
});
````

**Comment by asadalarma** [comment]
i have used the code on cancel button clicked , but i want to clear the selected dates on cancel. is there any other way to clear the calandar max and min dates ?

                          $('.daterange').on('cancel.daterangepicker', function(ev, picker) {
			        $(this).val('');
			        $('.daterange').data('daterangepicker').setStartDate(moment());
				$('.daterange').data('daterangepicker').setEndDate(moment());
			    });

**Comment by asadalarma** [comment]
how to recreate the picker with new settings ?

**Comment by dangrossman** [comment]
same way you created it the first time

**Comment by periyasamy2git** [comment]
This plugin have lot of issue totally waste of our development time.., We can look another alternative plugin that is a best way

**Comment by dangrossman** [comment]
> This plugin have lot of issue totally waste of our development time.., We can look another alternative plugin that is a best way

Goodbye
