### ISSUE TITLE
isInvalidDay (Monday Only)

### ISSUE THREAD

**Issue by JamesBuckland** [dangrossman/bootstrap-daterangepicker#1666]
I recently upgraded from an older version and one issue I've been having is that my old settings for allowing only a Monday to be selected is now not working.

My settings are as follows:
`{
                                singleDatePicker : true,
                                format : 'MM/DD/YYYY',
                                startDate : aptDate,
                                endDate : aptDate,
                                minDate: moment().startOf('week').add(1, 'day'),
                                timePicker: false,
                                showDropdowns: true,
                                opens: 'center',
                                buttonClasses: ['btn'],
                                applyClass: 'btn-primary',
                                cancelClass: 'btn-default cancel',
                                dateLimit: {day: '1'},
                                showWeekNumbers: true,
                                isInvalidDay: function(day) {
                                    if (day.day() === 1) {
                                        return false;
                                    } else {
                                        return true;
                                    }
                                }
                            }`

As you can see the isInvalidDate should return true if the day is anything other than a Monday but this does not seem to be working anymore.

Any help would be greatly appreciated.

Thanks, James.

**Comment by dangrossman** [comment]
The option is `isInvalidDate` but in your code you've written `isInvalidDay`

**Comment by JamesBuckland** [comment]
This must have changed from the older version. Thanks a lot for the help!

**Comment by dangrossman** [comment]
`isInvalidDate` was added in September 2015, v2.0.8. There was never an option named `isInvalidDay`.

**Comment by JamesBuckland** [comment]
It must have been something I added myself to the old version before it was officially added then and I forgot about it. Seems like I had the right idea at least. Fantastic component by the way, it has saved me hundreds of hours across several projects.
