### ISSUE TITLE
move Method not updating the opensright, opensleft, openscenter css classes

### ISSUE THREAD

**Issue by snassoura** [dangrossman/bootstrap-daterangepicker#1671]
If the picker is initially configured with opens = "right", but then due to scrolling of the page, we update the opens property after initialization from opens = "right" to opens = "left" the dropdown div remains with the  opensright css class. However, if the drops property is updated from "down" to "up" the dropup class is added or removed accordingly.

I traced this to the move method where this line handles the case of the change in drops property
`this.container[this.drops == 'up' ? 'addClass' : 'removeClass']('dropup');`
However, then when the opens property is checked for left, center or right, there is no code to change the applied class.

if we add 
```
this.container.removeClass("opensright");
this.container.addClass("opensleft");
```
to the if (this.opens == 'left') block for example, it will update the class correctly, and now the little "triangle" pointer on the calendar picker is in the correct place.

Similar code would need to be added to the center and right if blocks.

**Comment by dangrossman** [comment]
What do you mean by "drops property is updated"?

The only way to update any setting other than the selected dates is to recreate the picker...

**Comment by snassoura** [comment]
I am talking about line 1059, the move method adds a "dropup" css class when the this.drops = up and removes this class when the this.drops = down.

We need a similar functionality for the opens = left/center/right.

if opens was set to "right" when the picker was initialized, line 395 adds the class like so: `this.container.addClass('opens' + this.opens);`

However, i can change the value of the opens property like so: $('#mypicker').data('datarangepicker').opens = left; because the location where my picker is on the page changed due to scrolling. So i expect that when the picker is shown, it opens left and it does, however if you inspect the picker div, the css class "opensright" is still there, and therefore, the triangle pointer is in the wrong place.

I wanted to submit a pull-request with a proposed fixed but got permission denied.

if you add just these two lines below at line 1061 it would solve the problem.

```
this.container.removeClass('opensleft').removeClass('openscenter').removeClass('opensright');
this.container.addClass('opens' + this.opens);
```

**Comment by dangrossman** [comment]
> However, i can change the value of the opens property like so

This is not supported behavior. If you wish to change the setting, recreate the picker with the new value.

**Comment by snassoura** [comment]
But you are doing it for the drops = up/down, why wouldn't you do the same for the opens=left/center/right?

**Comment by dangrossman** [comment]
This is a 6 year old library that's been built through hundreds of PRs by hundreds of different people. Someone implemented the `drops` option in a way that was more robust than needed, since the property should never change. That doesn't mean we should add more code that isn't needed, and mislead people into thinking they can change properties the way you're doing. There are dozens of settings and the code does not expect them to change after creation, except in this one mistaken place.
