### ISSUE TITLE
minStartDate / maxStartDate

### ISSUE THREAD

**Issue by HugoHeneault** [dangrossman/bootstrap-daterangepicker#1672]
Hi there, 

I'm trying to find a way of forcing the start (or end) date in a range. 

My use case would be to keep the same start date but only change the end date. 

Any ideas of how it could be possible?

Related question on SO without answers:

* https://stackoverflow.com/questions/42151785/daterangepicker-change-end-date-only-but-present-default-plugin-not-allows
* https://stackoverflow.com/questions/42119294/daterangepicker-change-end-date-only-start-date-wont-change

Thanks a lot!

**Comment by dangrossman** [comment]
There is not a setting for this, you will have to program it yourself.

**Comment by HugoHeneault** [comment]
Ok. If oneday someone wants to submit a PR... 😂
