### ISSUE TITLE
opens works only if pull-right class exists

### ISSUE THREAD

**Issue by themefy** [dangrossman/bootstrap-daterangepicker#1677]
https://github.com/dangrossman/bootstrap-daterangepicker/blob/9670cb08601d0fd7d9fa39734ab6f9f1ef354e8c/daterangepicker.js#L57

Why would you bind it to a class?

**Comment by dangrossman** [comment]
This is a Bootstrap library and Bootstrap had a similar behavior, where dropdowns under something with class "pull-right" would open to the left so they'd not go off-screen
