### ISSUE TITLE
Change in range labels causes Uncaught TypeError: Cannot read property '0' of undefined at DateRangePicker.hoverRange

### ISSUE THREAD

**Issue by maurocolella** [dangrossman/bootstrap-daterangepicker#1678]
I am using range labels on an internationalized app (using React). Changes in range labels are not properly dispatched, ie. the `ranges` array is modified, but not the `label` pointer, causing the aforementioned issue on hover or on click of the labels.

**Comment by dangrossman** [comment]
> Changes in range labels are not properly

What do you mean by changes? The ranges object is set at initialization and never changes afterwards.

**Comment by maurocolella** [comment]
`on an internationalized app`. If I change language, I have to change the labels.

**Comment by dangrossman** [comment]
OK, and how are you doing that? Are you recreating the date range picker with your new options? That shouldn't ever cause an error.

**Comment by maurocolella** [comment]
It is React, so we simply update a property on JSX component. I think that, to account for compatibility with React, it would be good to expose an "update" method, or add consistency checks to the click and hover handlers in case the dataset has changed.

Currently, I am forcing react to run a full remount, but this is not ideal as the benefits of the library come with updating the least possible amount of DOM elements.

**Comment by dangrossman** [comment]
This is not a React library and I don't know anything about using or building for React; if someone makes a React port perhaps they can add whatever methods you need.

**Comment by maurocolella** [comment]
The issue is in core. There is a react port, see:
https://github.com/skratchdot/react-bootstrap-daterangepicker

But it's a wrapper around your library; the use case is not just limited to React.

If for any reason (such as internalization) anyone is forced to change the label names, they have no choice but to fully destroy, and fully rebuild a daterangepicker. That ultimately limits adoption.

**Comment by dangrossman** [comment]
Nobody else has had an issue with that in 6 years.

**Comment by maurocolella** [comment]
`Nobody else has had an issue with that in 6 years.`

Possibly because it is only now being used for large scale applications? I understand the issue with a rewrite. Perhaps a setter method (`update` or something to that effect) would be a nice middle way?
