### ISSUE TITLE
End date value shown in start date input.

### ISSUE THREAD

**Issue by ph55** [dangrossman/bootstrap-daterangepicker#1688]
In custom range.
When selecting end date in custom range, start date input becomes active and it's value set to end date's value.

You can reproduce it in demos page.

![image](https://user-images.githubusercontent.com/1386622/37252209-ecd11bb0-2525-11e8-9c54-756629e394c0.png)

**Comment by dangrossman** [comment]
As you move your mouse around the calendars, the input that represents the date you are choosing shows the date under your mouse pointer.
