### ISSUE TITLE
Input hidden on blur/select etc

### ISSUE THREAD

**Issue by quantumwebco** [dangrossman/bootstrap-daterangepicker#1690]
After selecting a date or clicking away from the datepicker the input is hidden. Something adds inline style display: none; but I can't figure out why it is happening.

**Comment by dangrossman** [comment]
There is no code which changes the appearance of your input

**Comment by quantumwebco** [comment]
@dangrossman example https://www.dvc-rental.com/index.php?option=com_dvccalc&view=resorts&item_ids[0]=1&item_ids[1]=3&item_ids[2]=4

**Comment by dangrossman** [comment]
The input in that page disappears after losing focus even if there's no date range picker attached to it

e.g. run `jQuery('#daterange').data('daterangepicker').remove();` in your console to see

You need to investigate your other code on the page, it's not this library hiding your input

**Comment by quantumwebco** [comment]
@dangrossman Thanks for that. However, when I run jQuery('#daterange').data('daterangepicker').remove(); and then focus and blur the input it remains visible as expected. Also if I add an input with no js run on it, just a plain input, it doesn't disappear either. It's only when .daterangepicker() is active on an input that it disappears on blur. Unfortunately not my site, I just made the plugin.

**Comment by dangrossman** [comment]
You made what plugin?

**Comment by dangrossman** [comment]
Write this in the console:

    jQuery('#daterange').trigger('hide');

Some other code on this page is listening for a `hide` event with no namespace and hiding whatever triggers it. That's the responsible code you need to change. That code is not part of this library.

**Comment by quantumwebco** [comment]
OK thanks a lot. Where can I donate?
