### ISSUE TITLE
Small bug when setting long custom date ranges by clicking on calendar dates

### ISSUE THREAD

**Issue by sugarfreejones** [dangrossman/bootstrap-daterangepicker#1691]
When selecting a custom date range longer than 2 months, when you selected the end date, the start date is altered. 

Try it yourself http://www.daterangepicker.com/#ex4
Choose "Custom range"
Start date: Choose Jan 1, 2018 (by clicking on date on calendar)
End date : Choose Jun 1, 2018 (by clicking on date on calendar)

Start date changes to 2/2/18 until you take focus off the calendar date (Jun 1).

**Comment by dangrossman** [comment]
The input corresponding to your next selection shows whatever date your mouse is hovering over as a preview, at all times. This is by design.
