### ISSUE TITLE
Not working under FezVrasta/bootstrap-material-design

### ISSUE THREAD

**Issue by russellhoff** [dangrossman/bootstrap-daterangepicker#1693]
I've successfully used your library in some previous projects.

Now, I've started to use [FezVrasta's Material Design Theme](https://github.com/FezVrasta/bootstrap-material-design) for Bootstrap.

I don't know whether it's an issue of your library or, otherwise, it's FezVrasta's, but I the date selection menu isn't opened when clicking the input.

This is the HTML code of the form:

```
        <form id="formBuscar" class="form-inline">
            <div class="form-group mb-2">
                <label for="formBuscarInputEmpresa" class="bmd-label-floating">Empresa</label>
                <select class="form-control" id="formBuscarInputEmpresa" style="width: 150px;   ">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>&nbsp;&nbsp;
            <div class="form-group mb-2">
                <label for="formBuscarInputFecha" class="bmd-label-floating">Fecha</label>
                <input type="text" class="form-control" id="formBuscarInputFecha" />
            </div>&nbsp;&nbsp;
            <div class="form-group mb-2">
                <label for="formBuscarInputNif" class="bmd-label-floating">NIF</label>
                <input type="text" class="form-control" id="formBuscarInputNif" pattern="[0-9]{8}[TRWAGMYFPDXBNJZSQVHLCKETtrwagmyfpdxbnjzsqvhlcket]{1}|[XYZ]{1}[0-9]{7}[TRWAGMYFPDXBNJZSQVHLCKET]{1}" />
            </div>&nbsp;&nbsp;
            <span class="form-group bmd-form-group">
                <button type="submit" class="btn btn-primary">Buscar</button>
            </span>
        </form>
```

I'm not getting any error on console.

Ask me anything else you need.

Thank you!

**Comment by russellhoff** [comment]
Found what's the issue!

To make use of FezVrasta's Material Design for Bootstrap 4 you must:
- Discard the usage of bootstrap's default stylesheet.
- Add bootstrap-material-design's stylesheet.

That way DateRangePicker's menu is shown.

**Comment by russellhoff** [comment]
Sorry for the misunderstanding. I've discovered the case in which daterangepicker menu isn't shown. So, additionally, found that it isn't compatible with that bootstrap theme. 

Could you take a look at this, please?

**Comment by dangrossman** [comment]
Take a look at what?

**Comment by russellhoff** [comment]
Datarangepicker isn't compatible with FezVrasta's Material Design Theme

**Comment by dangrossman** [comment]
That's not something it claims to be, this isn't an issue for me

**Comment by russellhoff** [comment]
Okay! Thanks

**Comment by russellhoff** [comment]
Hi. @FezVrasta doesn't provide support for third parties. How can I help you solve this problem? Seems to be visual...
