### ISSUE TITLE
Is it possible that we could use this library based on materialize css, not bootstrap?

### ISSUE THREAD

**Issue by hirokimoto** [dangrossman/bootstrap-daterangepicker#1694]
I'd like to use this library with Materialize CSS(http://materializecss.com/), not with Bootstrap.
Could you please let me know how to use this library with Materialize CSS?

**Comment by dangrossman** [comment]
> I'd like to use this library with Materialize CSS(http://materializecss.com/), not with Bootstrap.

Probably possible with a little tweaking, try it out

> Could you please let me know how to use this library with Materialize CSS?

No
