### ISSUE TITLE
I am unable to import this into Qlik Sense Nov 2017 release. what should i do ?

### ISSUE THREAD

**Issue by JoneyQuest** [dangrossman/bootstrap-daterangepicker#1696]
I am unable to import this into Qlik Sense Nov 2017 release. what should i do ?

**Comment by dangrossman** [comment]
Well, opening another issue on my repository won't help. I don't know what Qlik Sense Nov 2017 is. I've never heard of it.

**Comment by JoneyQuest** [comment]
apologies./ got it.
