### ISSUE TITLE
Show month after year

### ISSUE THREAD

**Issue by DuongNguyen3c13** [dangrossman/bootstrap-daterangepicker#1698]
Hi, Thanks for the great library!

On the calendar, I would like to display the month after year by default, is there any easy way to do this?
![image](https://user-images.githubusercontent.com/11581341/37696875-041355e8-2d0c-11e8-97e1-8132bb58503f.png)
Instead of June 2016 I would want it to be 2016.

Sincerely thanks!

**Comment by dangrossman** [comment]
There's no option for this, but you can edit it here:

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L718

**Comment by DuongNguyen3c13** [comment]
Thank you!
