### ISSUE TITLE
Single Date Picker autoApply false Doesn't Take Effect

### ISSUE THREAD

**Issue by hadiwina** [dangrossman/bootstrap-daterangepicker#1711]
Hi! 

Thanks for the great work on this plugin.

From what I can see, when we set `autoApply: false`, the calendar doesn't automatically apply and close. However, this doesn't seem to be consistently observed when `singleDatePicker: true` is set, where the calendar and `apply.daterangepicker` event is fired. This seems a bit consistent to me.

Is this something that we could change to make it consistent?

**Comment by dangrossman** [comment]
I don't know why you want to add extra buttons/steps where they're not needed, but you're free to hack the code to make it work that way, it's free open source.

**Comment by hadiwina** [comment]
We had to implement our own time picker as functionality it’s different than the timepicker that the plugin provides. We had to manually inject this, unfortunately. 

Thanks for your response, though. Let me try to find a different way for this.
