### ISSUE TITLE
How to remove current date as default date and update a new date as default date

### ISSUE THREAD

**Issue by VudugulaRamu** [dangrossman/bootstrap-daterangepicker#1712]
Hello @dangrossman, I have date range picker and used singleDatePicker as true to show only one date. Be default current date(Today's date) coming in the input box. I have another date value which is coming from another source. I just want to add this date as default date in the input box. Please help me on this

**Comment by dangrossman** [comment]
The `startDate` option specifies the date that's currently selected.
