### ISSUE TITLE
Object doesn't support property or method 'daterangepicker' only in IE 11

### ISSUE THREAD

**Issue by PAYALSHAH1210** [dangrossman/bootstrap-daterangepicker#1724]
Object doesn't support property or method 'daterangepicker' only in IE 11
 

 $('#reportrange span').daterangepicker({
        startDate: start,
        endDate: end,
        ranges: {

            'Business Year': [moment().month(9).startOf('month').subtract(1, 'year'), moment().month(9).startOf('month').subtract(1, 'days')],

            'Calendar Year': [moment().month(0).startOf('month'), moment().month(11).endOf('month')]

        }
    }, cb);
    cb(start, end);

**Comment by dangrossman** [comment]
Have you failed to load the required libraries in your webpage?

This does work on IE 11. All the demos at http://www.daterangepicker.com work
