### ISSUE TITLE
When calendars are stacked, "to" calendar is above "from" calendar

### ISSUE THREAD

**Issue by nonplus** [dangrossman/bootstrap-daterangepicker#225]
When you use the daterangepicker on a narrow page, the calendars are stacked on top of each other.  However the "starting" calendar comes **after** the "ending" calendar.

![image](https://f.cloud.github.com/assets/1023803/1958771/afcfc9d0-821f-11e3-97c9-075748d7c753.png)

FWIW, when you show the calenders with the "right" option, they are stacked correctly.

**Comment by mhenley-uk** [comment]
+1

**Comment by cnizzdotcom** [comment]
Sorry but this bug makes an otherwise wonderful plugin useless.

**Comment by vodich** [comment]
@robinfai +2 :)

**Comment by laurent1** [comment]
`.daterangepicker {
    min-width: 670px;
}`

**Comment by dangrossman** [comment]
What's that supposed to mean, @laurent1? This bug was already fixed, the calendars stack in the correct order now.

**Comment by laurent1** [comment]
@dangrossman I am using the version on npm, which points to version 1.3.10. So, I am a could of years behind. Thanks for the quick response.

**Comment by dangrossman** [comment]
This library is also published on npm, under https://www.npmjs.com/package/bootstrap-daterangepicker

**Comment by indra1** [comment]
I use daterangpicker 2.1.5 and I have this issue on one row.

![image](https://user-images.githubusercontent.com/1842674/31939247-71e55508-b8c2-11e7-91ad-330def6d0200.png)


This is how I setup the date rang picker

```
function activateDateRagePicker(field) {

        var start = moment().startOf('month');
        var end = moment().endOf('month');

        function cb(start, end) {
            field.html(start.format('DD/MM/YYYY') + ' - ' + end.format('DD/MM/YYYY'));
        }

        field.daterangepicker({
            locale: {
                format: 'DD/MM/YYYY'
            },
            startDate: start,
            endDate: end,
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'This Week': [moment().startOf('week'), moment().endOf('week')],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'This Year': [moment().startOf('year'), moment().endOf('year')],
            },
        }, cb).on('hide.daterangepicker', function (e) {
            $(e.target).val();
        }).on('cancel.daterangepicker', function (e) {
            $(e.target).val('')
        });
        cb(start, end);
    }
```

**Comment by cAstraea** [comment]
Anyone found a solution for this ? I'm on 3.0.3 and they stack vertically. 
![stacked](https://user-images.githubusercontent.com/13070662/47940447-47556c80-def3-11e8-963b-bcf645e6cbb6.png)

**Comment by hassanuos** [comment]
Can i change persian calendar to digit.?? I am using daterangepicker.

![image](https://user-images.githubusercontent.com/13483548/67632276-83c36a80-f8b2-11e9-8993-8e742f4ccd37.png)
