### ISSUE TITLE
When hit “Today” in the date selector on daterangepicker, the date selector is not changing from previous without refresh

### ISSUE THREAD

**Issue by sreekanth-reddy-ila** [dangrossman/bootstrap-daterangepicker#340]
The issue is there is https://github.com/jdorn/php-reports where they are using the following javascript.

 /**
* @version: 1.3.5
* @author: Dan Grossman http://www.dangrossman.info/
* @date: 2014-03-19
* @copyright: Copyright (c) 2012-2014 Dan Grossman. All rights reserved.
* @license: Licensed under Apache License v2.0. See http://www.apache.org/licenses/LICENSE-2.0
* @website: http://www.improvely.com/

**Comment by otisg** [comment]
@dangrossman what is the recommended way to have the date regularly update to always show e.g. "last 1 hour" vs. being fixed in time?

**Comment by dangrossman** [comment]
Either (1) periodically refresh the page, (2) periodically re-create the picker with new datetimes, or (3) read the name of the label that was clicked instead of using the date objects and implement the "last 1 hour" calculation in your code at the time of the callback.
