### ISSUE TITLE
Time picker breaks with minDate set to current date and minute selection list past.

### ISSUE THREAD

**Issue by Bhimsen** [dangrossman/bootstrap-daterangepicker#520]
**Steps to reproduce:**
1. Set minDate as current date.
2. Set minute limit to 30 minutes which is default.
3. Change hour selection during the second half of an hour(say, 5:30 to 6:00). It will break. 

**My Setting:**
$('input.date-time-picker').daterangepicker({
      timePicker: true,
      format: 'lll',
      minDate: new Date(),
      singleDatePicker: true
});

***Past minute list***
![past minute list](https://cloud.githubusercontent.com/assets/2726417/5316101/5cbfd576-7cad-11e4-8360-23735fcb0343.png)

***Exception on changing hour***
![exception on changing hour](https://cloud.githubusercontent.com/assets/2726417/5316171/41d0ace4-7cae-11e4-95f1-04a925f287b5.jpg)

**Comment by fadomire** [comment]
+1 just hited this bug today

**Comment by samarthbsb** [comment]
I am also getting this issue.
Is there any work around to prevent this? Do I have to set minDate as moment().subtract(1, 'days')?
