### ISSUE TITLE
If change event isn't fired start date time is set to mindate rather than selected time

### ISSUE THREAD

**Issue by garethbowen** [dangrossman/bootstrap-daterangepicker#528]
### Steps to reproduce

1. Open a date picker with a value earlier than the minDate
2. Click Apply

### Expected

The time should be set to the time selected in the dropdowns which is the minimum valid time based on the timePickerIncrement, eg: if minDate is 9.13 AM and you have a 30 minute timePickerIncrement then 9.30 AM is selected in the dropdowns.

### Actual

The time is set to minDate, eg: if the minDate is 9.13 AM then 9.13 AM is selected.

### Analysis

The startDate is updated when the change event is fired on the time picker selects. It also needs to be updated when the selects are initialised.

### Configuration
```
{
  singleDatePicker: true,
  timePicker: true,
  parentEl: '#edit-message-group .modal-dialog .modal-content',
  format: res.reported_date_format,
  minDate: moment()
}
```

**Comment by garethbowen** [comment]
Has this been fixed?

**Comment by dangrossman** [comment]
All PRs against v1 were closed. Version 2 was a near-complete rewrite, and does appear to have fixed this.
