### ISSUE TITLE
Not triggering change event

### ISSUE THREAD

**Issue by jfine** [dangrossman/bootstrap-daterangepicker#539]
The date range picker doesn't seem to be triggering a change event input field. Please see the example below.

http://jfine.org/misc/bootstrap-daterangepicker-change-trigger/

**Comment by jfine** [comment]
I'm using the following code so jQuery and Angular can watch for the event but just wondering if this should be built into the picker by default.

```javascript
  $('input.daterange').on('apply.daterangepicker', function() {
    $('input.daterange').trigger('change');
  });
```

**Comment by jeserkin** [comment]
My Angular wrapper knows, how to handle it.

**Comment by atentis** [comment]
@jfine I am having the exact same issue. I cannot get an ng-change or an ng-watch to work with it. 
@jeserkin Could you post yours?

**Comment by dangrossman** [comment]
The `updateInputText` function now also triggers the `change` event on the text input, if the picker is attached to one
