### ISSUE TITLE
Date Picker displaying on "apply"

### ISSUE THREAD

**Issue by PeakEmployee** [dangrossman/bootstrap-daterangepicker#541]
This is my first time using this control and I'm not sure what I'm missing here, but the picker displays by default when the page loads.

    <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 0px solid #ccc">           
            <h2 class="block-header">
                <svg><use xlink:href="#icon-calendar"></use></svg>
                <span></span>
            </h2>
    </div> 

        <script type="text/javascript">

            $(function () {

                var cb = function (start, end, label) {
                    $('#reportrange h2 span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
                }

                var optionSet = {
                    startDate: moment().subtract(30, 'days'),
                    endDate: moment(),
                    minDate: '01/01/2014',
                    maxDate: '12/31/2025',
                    opens: 'left',
                    showDropdowns: true,
                    showWeekNumbers: true,
                    ranges: {
                        'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                        'Current Month': [moment().startOf('month'), moment().endOf('month')],
                        'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                        'Last 3 Months': [moment().subtract(3, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                        'Last 6 Months': [moment().subtract(6, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                    }
                };

                $('#reportrange h2 span').html(moment().subtract(29, 'days').format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));

                $('#reportrange').daterangepicker(optionSet, cb);

                $('#reportrange').on('apply.daterangepicker', function (ev, picker) {
                    console.log("apply event fired, start/end dates are "
                      + picker.startDate.format('MMMM D, YYYY')
                      + " to "
                      + picker.endDate.format('MMMM D, YYYY')
                    );

                });

                $('#reportrange').on('cancel.daterangepicker', function (ev, picker) { console.log("cancel event fired"); });

            });
        </script>

![datepicker](https://cloud.githubusercontent.com/assets/7496310/5652785/e3f4aba0-9668-11e4-84f8-3b6be8479dd7.JPG)

**Comment by dangrossman** [comment]
That HTML does not produce that behavior for me. That points to the problem being in your stylesheet most likely.

**Comment by PeakEmployee** [comment]
Thanks Dan. In looking at the applied styles (in Chrome) and I'm not seeing where any of my custom css is interfering with the rendered markup. Here's what I have (below). Any ideas?

![datepicker2](https://cloud.githubusercontent.com/assets/7496310/5654366/17dd85b4-9677-11e4-9042-07520428690d.JPG)

**Comment by PeakEmployee** [comment]
Here's the computed styles:

-webkit-background-clip: border-box;
-webkit-background-origin: padding-box;
-webkit-background-size: auto;
-webkit-font-smoothing: antialiased;
background-attachment: scroll;
background-clip: border-box;
background-color: rgb(255, 255, 255);
background-image: none;
background-origin: padding-box;
background-size: auto;
border-bottom-color: rgb(90, 97, 102);
border-bottom-left-radius: 4px;
border-bottom-right-radius: 4px;
border-bottom-style: none;
border-bottom-width: 0px;
border-image-outset: 0px;
border-image-repeat: stretch;
border-image-slice: 100%;
border-image-source: none;
border-image-width: 1;
border-left-color: rgb(90, 97, 102);
border-left-style: none;
border-left-width: 0px;
border-right-color: rgb(90, 97, 102);
border-right-style: none;
border-right-width: 0px;
border-top-color: rgb(90, 97, 102);
border-top-left-radius: 4px;
border-top-right-radius: 4px;
border-top-style: none;
border-top-width: 0px;
box-sizing: border-box;
color: rgb(90, 97, 102);
display: block;
-- div - block user agent stylesheet
font-family: Lato;
font-size: 16.3636360168457px;
font-stretch: normal;
font-style: normal;
font-variant: normal;
font-weight: normal;
height: 382.8125px;
left: auto;
line-height: 20px;
margin-bottom: 0px;
margin-left: 0px;
margin-right: 0px;
margin-top: 1px;
max-width: none;
padding-bottom: 4px;
padding-left: 4px;
padding-right: 4px;
padding-top: 4px;
position: absolute;
right: 233.863662719727px;
top: 250.340896606445px;
vertical-align: baseline;
width: 731.931823730469px;
z-index: 3000;

**Comment by dangrossman** [comment]
Bootstrap 3's CSS says `.dropdown-menu` has `display:none`. The date range picker's outermost container has the class `dropdown-menu` which is why it's initially hidden, like other dropdowns. I dropped your HTML into a page with just Bootstrap and the stylesheet from this repo, and the picker was hidden on page load. I can't reproduce any bug.

**Comment by PeakEmployee** [comment]
Oh, that's strange. Just took a look at the daterangepicker-bs3.css (which I just downloaded from GitHub and upzipped today) and here's the style:

    /*!
    * Stylesheet for the Date Range Picker, for use with Bootstrap 3.x
   *
   * Copyright 2013 Dan Grossman ( http://www.dangrossman.info )
   * Licensed under the Apache License v2.0
   * http://www.apache.org/licenses/LICENSE-2.0
   *
   * Built for http://www.improvely.com
   */

  .daterangepicker.dropdown-menu {
      max-width: none;
      z-index: 3000;
    }

I added "display:none" to it and now it's working.

**Comment by dangrossman** [comment]
I'm talking about the Bootstrap stylesheet, not the one provided by this library. That is where the `display:none` appears for `.dropdown-menu`.
