### ISSUE TITLE
Should make use of Dropup

### ISSUE THREAD

**Issue by jeserkin** [dangrossman/bootstrap-daterangepicker#542]
Found quite few times myself in a pickle with this option missing. This is normal if the field, that uses daterangepicker is at the bottom of the page and for example app has sticky footer in use, then it will be broken(probably).

Would be nice, to see, that this plugin can calc. the probability of it fiting and if not, then use "[Bootstrap Dropup](http://getbootstrap.com/components/#btn-dropdowns-dropup)"

**PS.**
I would probably say, that same goes for existing `opens` property as well, but this more or less doable.

**Comment by tjagusz** [comment]
:+1:

**Comment by shekky** [comment]
+1

**Comment by dangrossman** [comment]
"Dropping up" is available as an option now.

**Comment by shekky** [comment]
The drops "up" option still shows the arrow on the top side of the popup instead of the bottom.

**Comment by shekky** [comment]
Nevermind, I forgot to update the css file as well as the js.

**Comment by jeserkin** [comment]
@dangrossman, as I understand it still needs manual setup. My initial idea was regarding popup to know itself when to open up and when down.

**Comment by Mudasty** [comment]
There is any improvement with the drops "auto"?
Keep with great work!
