### ISSUE TITLE
Deprecation warning: moment().zone is deprecated

### ISSUE THREAD

**Issue by Rudolph-Miller** [dangrossman/bootstrap-daterangepicker#544]
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. moment/moment#1779

**Comment by toncid** [comment]
+1

**Comment by YidingW** [comment]
+1

**Comment by vnen** [comment]
+1

**Comment by mattholtom** [comment]
+1

**Comment by johnedo1234** [comment]
+1

**Comment by Rudolph-Miller** [comment]
Thanks @YidingW
ref https://github.com/dangrossman/bootstrap-daterangepicker/pull/568

**Comment by johnedo1234** [comment]
Sweet! Thanks guys!!!

**Comment by hiperjp** [comment]
+1!

**Comment by dangrossman** [comment]
+1 to what? This was fixed a year ago, and now the code base contains neither.

**Comment by hiperjp** [comment]
I'm sorry Dan, searching for last version (I'd face this issue today)

**Comment by jexneedls** [comment]
+1

**Comment by dangrossman** [comment]
@jexneedls Read

**Comment by fabiohbarbosa** [comment]
+1

**Comment by dangrossman** [comment]
@fabiohbarbosa You can't +1 an issue that hasn't existed in over a year.
