### ISSUE TITLE
How to translate or set local on the ranges  

### ISSUE THREAD

**Issue by almogdesign** [dangrossman/bootstrap-daterangepicker#550]
I tried the following but it's not working 

todayLabel:  TAPi18n.__('customRangeLabel'),
today:  TAPi18n.__('customRangeLabel'),
Today:  TAPi18n.__('customRangeLabel'),

**Comment by dangrossman** [comment]
I don't know what TAPi18n is or how to use it, but I can tell you that "Today" would be the word you're trying to localize, not the date objects it's connected to.

    $('#something').daterangepicker({
      ranges: {
        TAPi18n.__('Today'): [moment(), moment()],
        TAPi18n.__('Yesterday'): [moment().subtract('days', 1), moment().subtract('days', 1)]
        ...
      }
    });

**Comment by almogdesign** [comment]
no that just calls the correct json value it can be anything 

If I do what you suggest I get  Unexpected token .

ranges: {
            TAPi18n.__('apply'): [moment(), moment()], 
}

this throws an error  TAPi18n.__('Today'):

**Comment by dangrossman** [comment]
Yeah, you can't use that as the key to an array, my bad. Nothing to do with the date range picker though.

**Comment by almogdesign** [comment]
So there is no way to translate the ranges as it always expects a string 

This works great 

locale: {
            applyLabel: TAPi18n.__('apply'),
            cancelLabel:  TAPi18n.__('cancel'),
            fromLabel:  TAPi18n.__('fromLabel'),
            toLabel:  TAPi18n.__('toLabel'),
            customRangeLabel:  TAPi18n.__('customRangeLabel')

        }

**Comment by almogdesign** [comment]
Ok found a way 

 var today = TAPi18n.__('today');
    var yesterday = TAPi18n.__('yesterday');
    var last7Days = TAPi18n.__('last7Days');
    var last30Days = TAPi18n.__('last30Days');

and then 
today: [moment(), moment()],
            yesterday: [moment().subtract(1, 'days'), moment().subtract(1, 'days')],

**Comment by almogdesign** [comment]
Ok this does not work, you can't translate the ranges

**Comment by jbwl** [comment]
+1 feature request - please let us translate the ranges, especially needed when creating custom ranges through the ranges: attribute.

**Comment by dangrossman** [comment]
You can translate the ranges! The ranges option is an object with labels as keys and an array of date/moment objects as values. You provide the keys in whatever language you want. There is nothing hardcoded in any language here. There aren't even defaults.

**Comment by oriceon** [comment]
ES2015:

If you're able to use ES6 JavaScript features, you can use Computed Property Names to handle this very easily:

```
var key = 'DYNAMIC_KEY',
    obj = {
        [key]: 'ES6!'
    };

console.log(obj);
// > { 'DYNAMIC_KEY': 'ES6!' }
```

so

```
$('#defaultrange').daterangepicker({
            ranges: {
                [your_translated_variable_here]    : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           },
   .....
});
```

**Comment by isasantossi** [comment]
When use  TAPi18n my project return this error , how  i do ?? 
[ts] Não é possível encontrar o nome 'TAPi18n'.
any 
I need do translate daterangepicker

**Comment by isasantossi** [comment]
When use  TAPi18n my project return this error , how  i do ?? 
[ts] Não é possível encontrar o nome 'TAPi18n'.
any 
I need do translate daterangepicker

**Comment by isasantossi** [comment]
When use  TAPi18n my project return this error , how  i do ?? 
[ts] Não é possível encontrar o nome 'TAPi18n'.
any 
I need do translate daterangepicker

**Comment by purethemes** [comment]
+1 as you can't use wp_localize_script with that as it always expects a string as a key

**Comment by saionachi** [comment]
How about localizing the label "Custom Range"? it is not defined in 'ranges' therefore can't find any way to localize that label..

**Comment by dangrossman** [comment]
> How about localizing the label "Custom Range"? it is not defined in 'ranges' therefore can't find any way to localize that label..

````
$('#yourinput').daterangepicker({
  locale: { 
    customRangeLabel: 'Something Localized'
  }
});
````

Check off "locale (example settings)" in the configuration generator at http://www.daterangepicker.com/#config

**Comment by bileloues** [comment]
I tried to create an object to translate data, it's work for me

var ranges = new Object();
        ranges[Tygh.tr('date_range_picker_today')] = [moment(), moment()];
        ranges[Tygh.tr('date_range_picker_yesterday')] = [moment().subtract(1, 'days'), moment().subtract(1, 'days')];
        ranges[Tygh.tr('date_range_picker_last_seven_days')] = [moment().subtract(6, 'days'), moment()];
        ranges[Tygh.tr('date_range_picker_thirty_days')] = [moment().subtract(29, 'days'), moment()];
        ranges[Tygh.tr('date_range_picker_this_month')] = [moment().startOf('month'), moment().endOf('month')];
        ranges[Tygh.tr('date_range_picker_this_year')] = [moment().startOf('year'), moment().endOf('year')];
