### ISSUE TITLE
Start Date >= End Date Error

### ISSUE THREAD

**Issue by Azores83** [dangrossman/bootstrap-daterangepicker#556]
When selecting a date greater than or equal beginning that the end date can not choose a date in the second calendar. Can anyone help ?

![preview](https://cloud.githubusercontent.com/assets/10707556/5899114/0be4554e-a54f-11e4-97c8-1b150097d5ca.png)

**Comment by dangrossman** [comment]
I can't reproduce that. I suspect you have some other options set that may be contributing to this...

**Comment by Azores83** [comment]
['datepickerOptions'] = array(
			"dateFormat" => "YYYY-MM-DD",
			"minDate" => $min_date,
			"maxDate" => $max_date
		);

**Comment by dangrossman** [comment]
What are $min_date and $max_date? And why are they not in quotes?

**Comment by Azores83** [comment]
php variables

**Comment by dangrossman** [comment]
Obviously. I wanted to know what's in them. I want to know what options you're passing to the date range picker so that I can reproduce your bug and help fix it for you. If you're not going to cooperate, you're not going to get help.

**Comment by Azores83** [comment]
These values ​​are passed to draw the graph , but the problem is in the selection of dates. The choice is limited to the present day ( max_date ) . The value simply passes max_date that set 
![teste2](https://cloud.githubusercontent.com/assets/10707556/5899642/8d09af50-a556-11e4-92c6-eef648e30bd8.png)

**Comment by dangrossman** [comment]
You're not going to give me the JavaScript options used to create this picker, so I can't reproduce this bug and try to help. You'll have to work on it yourself.

**Comment by Azores83** [comment]
<script type="text/javascript">

		var beforeOneWeek = new Date(new Date().getTime() - 60 * 60 * 24 * 7 * 1000),
			day = beforeOneWeek.getDay(),
			diffToMonday = beforeOneWeek.getDate() - day + (day === 0 ? -6 : 1),
			lastMonday = new Date(beforeOneWeek.setDate(diffToMonday)),
			lastSunday = new Date(beforeOneWeek.setDate(diffToMonday + 6));

			$('#panel_period).daterangepicker(
				{
					parentEl: ".body-scroller",
					locale: {
						applyLabel: "Aplicar",
						cancelLabel: "Cancelar",
						fromLabel: "Desde",
						toLabel: "Até",
						customRangeLabel: "Intervalo de datas",
						daysOfWeek:['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex','Sáb'],
						monthNames:['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']
					},
					startDate: '2015-01-01 00:00:00',
					endDate: '2015-01-26',
					minDate: '2009-07-01',
					maxDate: '2015-01-26',
					dateLimit: '2015-01-26',
					format: 'YYYY-MM-DD',
					showDropdowns: true
					ranges: {
						'Hoje': [Date.today(), Date.today()],
						'Ontem': [Date.today().add({ days: -1 }), Date.today().add({ days: -1 })],
						'Últimos 7 dias': [Date.today().add({ days: -6 }), Date.today()],
						'Últimos 30 dias': [Date.today().add({ days: -29 }), Date.today()],
						'Semana actual': [Date.today().last().monday(), Date.today().next().sunday()],
						'Última semana': [lastMonday, lastSunday],
						'Mês actual': [Date.today().moveToFirstDayOfMonth(), Date.today().moveToLastDayOfMonth()],
						'Último mês': [Date.today().moveToFirstDayOfMonth().add({ months: -1 }), Date.today().moveToFirstDayOfMonth().add({ days: -1 })],
						'Últimos três meses': [Date.today().moveToFirstDayOfMonth().add({ months: -3 }), Date.today().moveToFirstDayOfMonth().add({ days: -1 })]
					},
					opens: 'left'
				},
				function(start, end) {
					$('#panel_period span').html(start.format('YYYY-MM-DD') + ' - ' + end.format('YYYY-MM-DD'));

					start_date = start.format('YYYY-MM-DD');
					end_date = end.format('YYYY-MM-DD');

				}
			);

		</script>

**Comment by dangrossman** [comment]
I wouldn't think Date.js and moment.js would play well together, but I guess they do. That code works fine even though the `dateLimit` option is not supposed to be a date.

![ok2](https://cloud.githubusercontent.com/assets/407706/5899845/7e5c51b4-a52f-11e4-8a52-0e90ea183e6c.png)

**Comment by Azores83** [comment]
dateLimit is a boolean value?

**Comment by vitorhsb** [comment]
I have come across this issue as well and delivered a patch. Could you reopen this issue so I could make a pull request?
It happens when having a max date configured and a custom start date is chosen. The difference between previous start and end dates, added to the current end date could end up being bigger than the max date defined.
