### ISSUE TITLE
With Bootstrap 3, I am having a display issue

### ISSUE THREAD

**Issue by adgfx** [dangrossman/bootstrap-daterangepicker#558]
If i try to display the control on the right side on screen, the control display is messed up a bit. I tried to resize my window down and see what happens. My screen is 1920x1080. Its IE latest.

![daterangepicker_issue](https://cloud.githubusercontent.com/assets/6965294/5916172/ab0b71d8-a627-11e4-9945-3a4e29024572.jpg)

**Comment by dangrossman** [comment]
$('#el').daterangepicker({
      opens: 'left'
    });

Refer to README and examples.html

**Comment by adgfx** [comment]
OOps!! My bad... thank you Sir.
