### ISSUE TITLE
timePicker sometimes go wrong

### ISSUE THREAD

**Issue by shuax** [dangrossman/bootstrap-daterangepicker#559]
My setting is that
```javascript
timePicker: true,
timePicker12Hour: false,
timePickerIncrement: 10,
timePickerSeconds: false,
```
If the current time is 16:53:32, then all class="minuteselect" are disabled.
In the `updateTime` function here
```javascript
var minute = parseInt(cal.find('.minuteselect').val(), 10);
```
will get NaN.

Please apologize my poor English

**Comment by hjansen** [comment]
I can confirm that. When the time is in the range from arround xx:55:00 to xx:59:00 the datepicker goes nuts and the datepicker will show invalid date and NaN as dates everywhere.

**Comment by jaketoolson** [comment]
Same thing happens to me.

![screenshot 2015-03-19 11 51 46](https://cloud.githubusercontent.com/assets/612332/6738300/618497c2-ce2e-11e4-8cdf-efdf6be04870.png)

**Comment by andymrussell** [comment]
when you construct the min date, just make sure the time is start of day.
You can do this with moment like so:

moment().subtract(29, 'days').startOf('day')
