### ISSUE TITLE
How to disbale dateranges on calendar show

### ISSUE THREAD

**Issue by lgt** [dangrossman/bootstrap-daterangepicker#563]
I still desperatly search  a way to disable date ranges when a user choses date intervals. I have a reservation system where users gives check in and check out times. I save this in database.

than I try to disable this days between on new datrangepicker init

```$('#reservation').daterangepicker();
$('#reservation').on('show.daterangepicker', function(ev, picker) {
       //Ajax method to return all booked intervals for actual property , which returns from and to dates as JSON
        $.request('onAvability', {
            data:{id : $("input[name=property_id]").val()}
        });
    });
});
```

I have the ajax response with all `from` and `to` dates, which should repopulate the calender and disable the days between.

How do I do this?

**Comment by dangrossman** [comment]
You cannot do this. This date picker does not have a feature to disable specific dates. You'll want to use something else for a reservation system.

**Comment by lgt** [comment]
hm would be possible to implement in the future such an extension to the plugin?
