### ISSUE TITLE
I required two functionality to be implemented ( 1.Without apply button | 2.Two consecutive months to be loaded initially)

### ISSUE THREAD

**Issue by vanabharathiraja** [dangrossman/bootstrap-daterangepicker#564]
Hi,

I required two functionality to be implemented top of this plugin.

1. On click of "second/To date picker",  the selected value needs to be populated on text box ( without clicking apply button )
2. Two consecutive months have to be loaded initially. for eg., if "From date picker" shows Current month(Feb) means the "To/second date picker" should be loaded as March.

How can I achieve this ? Does it having inbuilt functionality?  

Thanks,
Bharathi

**Comment by dangrossman** [comment]
You'll be custom programming all of that. It's not built in.
