### ISSUE TITLE
Date ranges

### ISSUE THREAD

**Issue by Azores83** [dangrossman/bootstrap-daterangepicker#565]
When selected a start date for example November 1, 2014 and if we have the date of the order selected with February 2, 2015 and move to 2014 he assumes the month as February and the 2014 which can not be because the start date is November 2014.

![ranges](https://cloud.githubusercontent.com/assets/10707556/6002141/b42b7f22-aae8-11e4-93ad-b26a782f0ca6.png)

**Comment by olgaSkobeleva** [comment]
Hi! I have the same issue

**Comment by vitorhsb** [comment]
I have made a pull request that discusses and resolves this issue. https://github.com/dangrossman/bootstrap-daterangepicker/pull/570

Hope it will get accepted or at least point out the directions to acknowledge the issue.

**Comment by dangrossman** [comment]
Merged PR #570
