### ISSUE TITLE
How to force the datepicker to close?

### ISSUE THREAD

**Issue by airomero** [dangrossman/bootstrap-daterangepicker#567]
Hello, i wanted to know how can i force the datepicker to close programatically without destroying it.

Thanks!!

**Comment by dangrossman** [comment]
`$('#yourelement').data('daterangepicker').hide();` should do it

**Comment by airomero** [comment]
Dan, it worked. But not the way i wanted, i'm trying to close the calendar when the element loses focus.  When i executed the line of code you showed me before it hides the calendar when i press the "tab" on the element, but when the calendar is open and i click on a date, the date never is showed on the input. Is there a way to close the calendar when the input loses focus with a "tab" as it does when you click out of the input?

Thanks!

**Comment by dangrossman** [comment]
It doesn't work like that, sorry. You have to click the apply button (or a predefined range) to have the chosen dates change. Simply clicking on a date and pressing tab won't do it.
