### ISSUE TITLE
New Feture: Set "startDate" and "endDate" reset to null

### ISSUE THREAD

**Issue by ramprakash-ravi** [dangrossman/bootstrap-daterangepicker#569]
Is there a possibility to set back startDate and endDate to null after a date is set, 
like Apply and Cancel button one more button for a reset in picker to make it happen and make text box empty.

**Comment by dangrossman** [comment]
No. You can make the text box empty inside an event listener or your custom callback function. The start and end date of the picker can never be null, however.
