### ISSUE TITLE
Rendering issue in Firefox 35.0.1

### ISSUE THREAD

**Issue by dylantmarsh** [dangrossman/bootstrap-daterangepicker#571]
![screen shot 2015-02-06 at 3 03 15 pm](https://cloud.githubusercontent.com/assets/10099657/6086615/4a8c2e78-ae11-11e4-8059-17f97645e5c2.png)

This was fixed by setting the max width on `.daterangepicker .calendar` to `370px`. I also needed to add a padding of `8px` on `.daterangepicker .calendar-date` to get a consistent look across both latest Chrome and FF.

Not sure if this is an issue with the library itself or a style conflict in our projects. This is the second project we have integrated a stock version of daterangepicker and had to make tweaks on FF.

If anyone else comes across this, here is my fix.

```
.daterangepicker .calendar {
    max-width:370px;
}

.daterangepicker .calendar-date {
    padding:8px;
}
```

**Comment by dangrossman** [comment]
The calendar boxes are squares. In your screenshot, they're wide rectangles. This is your own stylesheet at work, probably adding extra left/right padding, not the library.
