### ISSUE TITLE
Should not allow user to edit start date and end date in input text box

### ISSUE THREAD

**Issue by ramprakash-ravi** [dangrossman/bootstrap-daterangepicker#572]
How can we make input box of start and end date to be readonly ?

**Comment by dangrossman** [comment]
http://www.w3schools.com/tags/att_input_readonly.asp

http://www.w3schools.com/tags/att_input_disabled.asp

**Comment by RomkaLTU** [comment]
That's not what OP wanted to know. `$dates_input_selector.daterangepicker()` will not work if input field is disabled or read-only.
