### ISSUE TITLE
What the way to set only start date or end date in daterange?

### ISSUE THREAD

**Issue by akvasov** [dangrossman/bootstrap-daterangepicker#575]
I want to set either start date or end date or start & end date. When I set only one date, the other date will be openned. For example, start date 11.02.2015 and end date - any date in future. But now, when I set start date, end date have set automatically equals to start date.

**Comment by dangrossman** [comment]
That ability does not exist right now. There is no feature where you can lock one date and only allow the user to select the other.

**Comment by akvasov** [comment]
Do you want to do this feature in next time? It can be a configurate parametr to allow open period?

**Comment by dangrossman** [comment]
If a user only has to select one date, they probably only need one calendar, right? So you wouldn't need a date range picker for this purpose, just a date picker, of which there are many to choose from.

**Comment by akvasov** [comment]
No, I will have a date range picker which can allow a closed period (from start date to end date) and openeed period (from start date to any date in future or from any date in past to end date).

**Comment by akvasov** [comment]
If shut down function which automatically set other date, we can solve this issue.

**Comment by ConneXNL** [comment]
Sad to see this closed :(

**Comment by NeilSchneider** [comment]
This would be a nice feature. I can think of a lot of cases where a users may want to change only the start or end date of a range, and then click apply.

**Comment by dangrossman** [comment]
Once again, entirely possible, using a single date picker. That's how at least half the largest travel sites work when choosing reservation dates. Two input boxes, one for the checkin/departure date, one for the checkout/arrival date. Each one opens a single calendar to choose a single date.

**Comment by DonghuaLau** [comment]
Showing tips that it can not set start date or end date and don't change the date values in the callback function. It works for me, hope this can help someone.

**Comment by cornelRaiu** [comment]
Add this to the in the library somewhere in the `DateRangePicker.prototype`. I added it just above `clickApply: function(e)`

    clearEndDate: function(e) {
        this.endDate = null;
        this.updateView();

        e.stopPropagation();
    },

It will just clear the end date and works like if you just selected the startDate by using the normal flow.

Usage example:

    $picker.on('show.daterangepicker', function( ev, picker ) {
        $('#my-field').off('click.clearDateEvent').on('click.clearDateEvent', function(){
            if(picker.startDate.format('DD MMM') !== picker.endDate.format('DD MMM')) {
                picker.clearEndDate();
            }
        })
    })

I did not bother making a pull request with this because it will never be accepted as it is definitely not in line with Dan's view of how this library should be used
