### ISSUE TITLE
Always make date range picker visible?

### ISSUE THREAD

**Issue by musicist288** [dangrossman/bootstrap-daterangepicker#576]
I'm looking for a bit of advice on using this plug-in without the show/hide functionality.  I want to nest the date range picker inside container that is always visible. Currently it's a bit inconvenient to 
have to work around the events handling showing and hiding the picker. Is this easy to achieve with the current implementation? If not, is this something you're interested in adding to this component?

**Comment by dangrossman** [comment]
This is not something I'm interested in adding.

I suggest you comment out the one line of code that hides the picker in your copy.

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L639

**Comment by musicist288** [comment]
Thanks.

**Comment by loostro** [comment]
I've created a PR for this #587.

**Comment by arturoromero** [comment]
Hello,
Nice plugin I really like it!
Is there a way to show the calendar without clicking on the input .?
I don't want to trigger("click") because there are some Jquery UI errors that appear when doing so.

Thank you

**Comment by Triplecorpse** [comment]
.toggle() function worked for me, run on daterangepicker element

**Comment by HansSchouten** [comment]
I had the same requirement and made a simple solution since an embedded daterangepicker is currently still not supported: https://jsfiddle.net/9m63neo2/

**Comment by ahmadzahabi1** [comment]
just reorder the last two line in daterangepicker.js into hide function:

        this.element.trigger('hide.daterangepicker', this);
        this.isShowing = false;
To

        this.isShowing = false;
        this.element.trigger('hide.daterangepicker', this);
And then

$('#daterange-btn').on('hide.daterangepicker', function(ev, picker) {
    $('#daterange-btn').click();
});

$('#daterange-btn').click();

**Comment by exoliveira** [comment]
> I had the same requirement and made a simple solution since an embedded daterangepicker is currently still not supported: https://jsfiddle.net/9m63neo2/

Worked very well, dear. Congratulations!
