### ISSUE TITLE
Should allow the disabling of days

### ISSUE THREAD

**Issue by jojovem** [dangrossman/bootstrap-daterangepicker#578]
It would be really nice to have a way to disable certain days.

Ex: Disable all weekends. Disable all mondays. Etc..

I really believe this is a must-have.

Thank you !

**Comment by dangrossman** [comment]
Yes, that would be nice.

**Comment by adgfx** [comment]
Similarly I have another requirement, Eaxctly like this (stackoverflow.com/questions/15400775/jquery-ui-datepicker-disable-array-of-dates). To block certain days. We are using the picker in a photo request form (for our photography desk), here certain events/dates each year have to be pre-reserved or blocked. So nobody allocate them accidently.
