### ISSUE TITLE
Auto-close & update

### ISSUE THREAD

**Issue by claudiu-cristea** [dangrossman/bootstrap-daterangepicker#583]
My picker is linked to a text input. I would like to hide the Apply/Cancel area (keep only calendars) and update my form element (the text input) automatically when I'm leaving the calendars area with the mouse (including over form element). 

Is there a way to workaround?

**Comment by dangrossman** [comment]
It's open source. I gave, you take. You can edit it to work however you want for your own website. Doing so is entirely on you.

**Comment by holtkamp** [comment]
@claudiu-cristea you found a way to do this? Setting the button classes to a CSS class that is ```hidden``` already hides the buttons...

**Comment by dangrossman** [comment]
There's an `autoApply` option you can set now that'll hide the buttons, and immediately apply the date range once selected. You can try it out using the configuration builder:

http://www.daterangepicker.com/#config

**Comment by holtkamp** [comment]
Yeah, found that out when disabling the TimePickers. When TimePickers are enabled it makes sense that AutoApply is not an option...
