### ISSUE TITLE
Blocked days

### ISSUE THREAD

**Issue by adgfx** [dangrossman/bootstrap-daterangepicker#586]
Like #578  I have a requirement, Eaxctly like this (stackoverflow.com/questions/15400775/jquery-ui-datepicker-disable-array-of-dates). To block certain days. We are using the picker in a photo request form (for our photography desk), here certain events/dates each year have to be pre-reserved or blocked. So nobody allocate them accidently.

**Comment by dangrossman** [comment]
I understand you'd like this feature. It does not currently exist.

**Comment by adgfx** [comment]
No worries, how easy is to highlight some dates, maybe we add a background color or css class to certain dates matching our array?

**Comment by adgfx** [comment]
added a lot of custom scripts already, how easy is to set the end time, when the start date and time is selected, we want the end time to be set to +2H...
