### ISSUE TITLE
Chrome crash

### ISSUE THREAD

**Issue by bricss** [dangrossman/bootstrap-daterangepicker#588]
Chrome ran out of memory ("He's dead, Jim!" or "Aw, Snap" screens), while switching month or year in dropdown's. Using Chrome v42 (dev).

**Comment by dangrossman** [comment]
That's weird...?

**Comment by bricss** [comment]
Yep, little bit weird... I tried to figure out today where is a problem but couldn't find it. Just tried to reproduce it in your blog post http://www.dangrossman.info/2012/08/20/a-date-range-picker-for-twitter-bootstrap/ while trying to change time I getting dead screen.

**Comment by dangrossman** [comment]
That's even an older copy of the date picker that's probably had hundreds of downloads since then. Sounds like a Chrome bug.

**Comment by fadomire** [comment]
+1 on this one, switching any dropdown : month / year / time crash chrome
