### ISSUE TITLE
How to retreive selected dates

### ISSUE THREAD

**Issue by rickszyr** [dangrossman/bootstrap-daterangepicker#589]
Hi!

Is there a way to retrieve the selected dates?

**Comment by dangrossman** [comment]
Yes. Multiple ways, including properties or a callback function that's passed the selected dates. Please read the README on the front of this repo and the examples.html file.

**Comment by rickszyr** [comment]
Got it. Thanks, I wasn't sure how to retreive the properties.

In case anyone has the same doubt I do: $datePicker.data('daterangepicker') contains everything. Wasn't so obvious to me! :smile:
