### ISSUE TITLE
No Unique ID?

### ISSUE THREAD

**Issue by rodrigograca31** [dangrossman/bootstrap-daterangepicker#591]
Hi.

**Problem:**
If I have multiple daterangepicker's and I want to do something with one of them and not the other is not possible, because they do not have an unique ID, and they are near the `</body>` tag instead of the element where they appear...

For example, I wanted to hide the element with "range_inputs" class of one daterangepicker and was not able to to it.... (No way to identify it uniquely)

**Temporary solution:**
I used "buttonClasses" option to apply a unique class that I used to go up (.parent) and hide the ".range_inputs" element....

Please add an unique ID to the element.

Thanks.

**Comment by dangrossman** [comment]
This might help.

    $('#element').daterangepicker();
    var picker = $('#element').data('daterangepicker');
    //hide the range inputs only on this specific date range picker
    picker.container.find('.range_inputs').hide();

**Comment by rodrigograca31** [comment]
@dangrossman Nope, that does not help...

Why? Because I need to be able to reference it from "other scripts", in another words, that code will only work inside the "scope" where I created the picker ...

**Comment by dangrossman** [comment]
Interesting. You can add a unique ID to your copy to meet your requirement :)
