### ISSUE TITLE
Removing custom range from date picker

### ISSUE THREAD

**Issue by kiempoturner** [dangrossman/bootstrap-daterangepicker#594]
(day 2)

Still finding a way to remove(hide) the custom range option. Would only love to use the ranges except for Custom Ranges option.

Thanks!

**Comment by dangrossman** [comment]
Remove this line from your copy of the code:

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L370

Or write some CSS to make the last element of the list hidden. 

What do you mean "day 2"? Did you pay someone for customer support with a response time guarantee?

**Comment by kiempoturner** [comment]
Thanks man. haha sorry if I offended you, "day 2" is about me trying to alter it before calling for help here.
