### ISSUE TITLE
Single date input selection off by one day between 31 Mar and 26 Oct

### ISSUE THREAD

**Issue by kkulmala** [dangrossman/bootstrap-daterangepicker#595]
When certain dates are inputted to the field, daterangepicker selects the previous day:

![screenshot_3_17_15 _9_41_am](https://cloud.githubusercontent.com/assets/5467252/6683087/df1f0394-cc89-11e4-8289-4e43200b8be6.png)

This repeats on dates between 31 Mar - 26 Oct in both 2014 and 2015. Other dates get selected right based on the user input.

The component initialization:

 $('#date_paid').daterangepicker({
        format: 'DD MMM YYYY',
        singleDatePicker: true
    });

Input field value initialization:
Date.today.strftime('%d %b %Y') 

I assume this must be related to component init, but wasn't able to find out the reason. 

When I used format: 'YYYY-MM-DD' and kept the old initialization (which then was invalid, making the component to jump to year 0017), I was able to get the component to pick the right dates based on input.

But when I updated the initialization to match the format (Date.today.strftime('%Y-%m-%d')) it stopped working again. When I removed the initialization, it didn't work either. 

The date range with problems matches the daylight savings time period. I'm in EET, UTC +2, but I have customers being able to reproduce the problem from UTC +8.

**Comment by MysterAitch** [comment]
I believe that this is related to moment's handling of daylight savings, having had similar issues recently. 

The only workaround I've found is to use UTC (stops the time offset changing), and then input it to a local timezone.
