### ISSUE TITLE
"singleDatePicker: true" with time-range

### ISSUE THREAD

**Issue by nadeemja** [dangrossman/bootstrap-daterangepicker#597]
Hi,

I would like the user to be able to pick one date, but a timerange for that date. 
To achieve this, I've set "dateLimit: { days: 0 }", which gives the desired functionality, but still shows to calendars. 

Any and all help appreciated :)

**Comment by dangrossman** [comment]
That's how it works. It's a date range picker, and no set of options will make it great for picking only a time range. You'll probably want to use something else.
