### ISSUE TITLE
Translate calendar and special characters

### ISSUE THREAD

**Issue by martingithu** [dangrossman/bootstrap-daterangepicker#598]
Hello and thank you for a very nice product.
Is it possible to use special characters in the day/month names?
In Norwegian, we have the charater "Ø" included in the name for "Saturday" and "Sunday".
When setting these, I'm getting troubles with the button click event.
Is it possible to use these characters? (LØ instead of SA and SØ instead of SU)

Best regards,
Martin

**Comment by dangrossman** [comment]
What button are you having trouble with? I put in those custom day names and didn't see anything strange...

![ss](https://cloud.githubusercontent.com/assets/407706/6780875/36524f2c-d13f-11e4-8f8f-24fcdc19a88e.png)

**Comment by martingithu** [comment]
Thank you very much for you're fast reply.
I've got everything to work now. Thank again!
