### ISSUE TITLE
singleDatePicker triggers date range picker too

### ISSUE THREAD

**Issue by sumityadav** [dangrossman/bootstrap-daterangepicker#599]
When adding singleDatePicker and date range picker. When we click the date picker, it also shows the date range picker too.
JSFiddle: http://jsfiddle.net/sumityadav/u0m61ere/

**Comment by dangrossman** [comment]
I do not see that behavior in your fiddle. I tried Chrome, Firefox and IE.

**Comment by sumityadav** [comment]
Please see this screencast showing the behavior. http://screencast.com/t/Py1qje8YJiCk

It was happening in my dev machine, then I went ahead and tried in jsfiddle and it was showing the same behavior.

**Comment by dangrossman** [comment]
I would suggest not giving your text input a class of "daterangepicker" since that is the class name of the actual widget this library creates. That's probably the source of your issue.
