### ISSUE TITLE
Close when blur (using tab)

### ISSUE THREAD

**Issue by joelmora** [dangrossman/bootstrap-daterangepicker#600]
I Think there is a problem when you are pressing tab to move between inputs, the picker doesn't close when blur. The only way close it is clicking outside the input.

I removed the line: ` e.type == "focusin" || ` and it works ok, but I don't know if affects other thing

```javascript
outsideClick: function (e) {
            var target = $(e.target);
            // if the page is clicked anywhere except within the daterangerpicker/button
            // itself then call this.hide()
            if (
                // ie modal dialog fix
                e.type == "focusin" || // ---------------------> without this line works OK
                target.closest(this.element).length ||
                target.closest(this.container).length ||
                target.closest('.calendar-date').length
                ) return;
            this.hide();
        },
```

**Comment by defsprite** [comment]
Same issue here. The opened dialog also breaks automated (selenium, poltergeist etc.) specs by obscuring other elements.

Seems to be a regression of https://github.com/dangrossman/bootstrap-daterangepicker/pull/509

Maybe limiting to IE would help, but there seems to be a deeper issue here.

**Comment by dangrossman** [comment]
Someone has submitted a PR that closes the picker on tab
