### ISSUE TITLE
Ability to select fixed weeks

### ISSUE THREAD

**Issue by mohitkumat** [dangrossman/bootstrap-daterangepicker#601]
Do we have the ability to pick the entire week on click of any day from that week.
Like this: [Fiddle](http://jsfiddle.net/manishma/AVZJh/light/)

**Comment by dangrossman** [comment]
No

**Comment by mohitkumat** [comment]
No problem, did it myself.
Thanks.

**Comment by odecharette** [comment]
Hi,
I'd like the same functionnality, could you share your code ?

Thanks !

**Comment by odecharette** [comment]
OK I found so I share : https://jsfiddle.net/skfw0k53/
