### ISSUE TITLE
Changing Locale Does Not Update All of UI

### ISSUE THREAD

**Issue by pixelshaded** [dangrossman/bootstrap-daterangepicker#602]
Version 1.3.19

The following locale properties are only being rendered to the UI in the constructor:
fromLabel
toLabel
applyLabel
cancelLabel

If I initialize daterangepicker without locale settings, but then call setOptions later with locale settings, those labels do not get updated.

**Comment by metz0r** [comment]
Would love to see a fix for this!

**Comment by dangrossman** [comment]
Fastest way for that to happen is for you to write the fix ;)

**Comment by pixelshaded** [comment]
https://github.com/dangrossman/bootstrap-daterangepicker/pull/604

**Comment by pixelshaded** [comment]
bump

**Comment by dangrossman** [comment]
Thanks for submitting your improvement. I'll review the PR when I have a free day. Please don't "bump" things, it only makes me busier.
