### ISSUE TITLE
'Yesterday' returns 2 different days for start and end date values instead of one. 

### ISSUE THREAD

**Issue by anandvc** [dangrossman/bootstrap-daterangepicker#603]
I see a bug when selecting "Yesterday" from the example script: The input on the page correctly shows the same date as yesterday's, but in the console, the start and end values returned from the function show two different values. It seems like "yesterday" selects a range of 2 days instead of one. Please see this screencast showing the same bug on daterangepicker.com:

https://www.dropbox.com/s/5jehxa4r9eh8pk3/daterangepicker-bug.gif?dl=0

**Comment by dangrossman** [comment]
In *your local time zone*, that's March 26th 00:00:00 to March 26th 23:59:59, which corresponds to the date range of "yesterday".

It just looks odd because you're looking at that one day in UTC time because that callback outputs an ISO date string.
