### ISSUE TITLE
Custom Range and Single Date

### ISSUE THREAD

**Issue by Johnb21** [dangrossman/bootstrap-daterangepicker#609]
It would be awesome if there was the ability to use both the Custom Range and Single date (multiple calendars) in a single call. I tried to set a range to a custom object:

    ranges: {
       'Specific Day': { 
            singleDatePicker:true
        }
    }

That did not work. I also tried adding two objects to locale:

    locale: [
        {
            singleDateLabel: 'Specific Day',
            singleDatePicker:true
        },
        {
             customRangeLabel: 'Custom Range',
            ... rest of custom range options
        }
    ]

That also did not work. Is there currently any way to mix Single Date and Custom range into the same picker as separate options/selections?

**Comment by dangrossman** [comment]
There is no option that will turn a date range picker into a date picker when you click a range.

**Comment by Johnb21** [comment]
I was not referring to turning a date range picker into a date picker when you select a range. Think of one drop down such as the one used in the 'All Options' example. If I had these labels:

Yesterday
Last 7 Days
Last 30 Days
This Year
Last Year
Specific Day
Custom Range

As you can see from that list of options in the drop down, the bottom two would require the datepicker functionality. I was simply asking if there was a way to incorporate (co-mingle) the two Custom Range and Single Date Picker into the same drop down so when 'Specific Day' is clicked, the single date picker comes up. When 'Custom Range' is clicked, the Custom range selector would come up

**Comment by dangrossman** [comment]
> I was not referring to turning a date range picker into a date picker when you select a range.

> so when 'Specific Day' is clicked, the single date picker comes up

I don't understand.

**Comment by gilhanan** [comment]
@Johnb21  I need something like your needs, can you share please which solution did you choose?
