### ISSUE TITLE
Show range name in element.val

### ISSUE THREAD

**Issue by park896** [dangrossman/bootstrap-daterangepicker#610]
It would be nice if there was an option to set the `element.val()` text to the name of the range selected by the user. So the input value would be 'Today' or 'Tomorrow' instead of 'startDate - endDate'. If a custom date range was entered then the default display format would be used. Here is an example that worked in my specific case, but doesnt support all the features of daterangepicker.

    drp.updateInputText = function() {
                               var val;
                                if (this.chosenLabel === 'Custom') {
                                    val = this.startDate.format(this.format) + this.separator + this.endDate.format(this.format);
                                } else {
                                    val = this.chosenLabel;
                                }
                                this.element.val(val);
                                this.element.trigger('change');
                            };

The only problem with this was that the `updateFromControl` method was running very slowly if i tried to type. so i ended up disabling this event, but this code did work just slowly.

                            var oldUpdateFromControl = $.proxy(drp.updateFromControl, drp);
                            input.off('keyup.daterangepicker', oldUpdateFromControl);
                            drp.updateFromControl = function() {
                                var val = this.element.val();
                                if (val) {
                                    if (this.ranges[val]) {
                                        this.chosenLabel = val;

                                        var start = this.ranges[val][0];
                                        var end = this.ranges[val][1];

                                        this.oldStartDate = this.startDate.clone();
                                        this.oldEndDate = this.endDate.clone();

                                        this.startDate = start;
                                        this.endDate = end;

                                        if (!this.startDate.isSame(this.oldStartDate) || !this.endDate.isSame(this.oldEndDate))
                                            this.notify();

                                        this.leftCalendar.month.month(this.startDate.month()).year(this.startDate.year()).hour(this.startDate.hour()).minute(this.startDate.minute());
                                        this.rightCalendar.month.month(this.endDate.month()).year(this.endDate.year()).hour(this.endDate.hour()).minute(this.endDate.minute());

                                        this.updateCalendars();
                                    } else {
                                        oldUpdateFromControl();
                                    }
                                }
                            };
                            input.on('keyup.daterangepicker', $.proxy(drp.updateFromControl, drp));

**Comment by dangrossman** [comment]
$('#element').daterangepicker({}, function(start, end, label) {
      if (label != '') 
        $('#element').val(label);
    });

**Comment by Nadeermalangadan** [comment]
How can i set the label while setting input as date-piker
