### ISSUE TITLE
Using ranges hides the calendar

### ISSUE THREAD

**Issue by eskimoblood** [dangrossman/bootstrap-daterangepicker#615]
When I have a {{ranges}} section in my settings the calendar is not shown.
 I think its because of this [line](https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L952), Is it a bug, that the `this.showCalendars()` is inside the `if` statement?

**Comment by dangrossman** [comment]
This is the intended behavior. The calendars are not needed unless the visitor clicks on "Custom Range", which displays them.
