### ISSUE TITLE
Displaying Same Month for Start and End Months

### ISSUE THREAD

**Issue by wesbeyrent** [dangrossman/bootstrap-daterangepicker#617]
From a usability perspective, the 2nd month displayed should not be the same as the first month.  For example, If I choose a range within January, I should not see a duplicate January calendar for the end date.  The range should be shown in one calendar. The second calendar should be February, regardless of whether my range extends into February.

The current functionality makes it look like a 30 day range is actually a two month span.
![daterangepicker_issue](https://cloud.githubusercontent.com/assets/409970/7031642/043573ea-dd3b-11e4-9a3c-0c5482d3f9c3.png)

**Comment by dangrossman** [comment]
The first calendar selects the "from" date, and the second calendar selects the "to" date. You can't select two dates within the same month without two calendars showing the same month. I understand there are other date range picker widgets where it doesn't work like that, but this isn't one of them and it's not going to fundamentally change now, years later.

**Comment by chamnap** [comment]
@dangrossman, I just upgrade to the latest version. Previously, the first and second calendar shows the same month. Right now, they show sequentially (Jan and Feb). Is it possible to make them show the same month as before? I have gone through all options, and I can't find any.

I already set `linkedCalendars` to false already, but doesn't work.

**Comment by dangrossman** [comment]
<img width="300" alt="ss" src="https://cloud.githubusercontent.com/assets/407706/16216406/7d41aada-3738-11e6-9f82-f183f448fd2b.png">

**Comment by chamnap** [comment]
I'm unable to get the same result as yours. I already unchecked `linkedCalendars`. The calendar doesn't show up as the same month.

<img width="896" alt="screen shot 2016-06-21 at 9 50 37 am" src="https://cloud.githubusercontent.com/assets/407708/16216574/f99d94ec-3795-11e6-8a68-4c7ccda36401.png">

**Comment by dangrossman** [comment]
You would click the left arrow next to "Jul 2016" to scroll to June. If you want to change what months are shown initially, I pointed you to the code.

**Comment by chamnap** [comment]
Yeah, I need to show them initially. Please point me to the code. Thanks a lot for your help.

**Comment by dangrossman** [comment]
https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L541

**Comment by chamnap** [comment]
I got it working now.

```javascript
   $registrationPeriods.on('show.daterangepicker', function (event, picker) {
      let rightDate   = endDate || new Date();
      let rightMoment = moment(rightDate);

      picker.rightCalendar.month = rightMoment;
      picker.renderCalendar('right');
    });
```

**Comment by kamalKpUi** [comment]
> From a usability perspective, the 2nd month displayed should not be the same as the first month. For example, If I choose a range within January, I should not see a duplicate January calendar for the end date. The range should be shown in one calendar. The second calendar should be February, regardless of whether my range extends into February.
> 
> The current functionality makes it look like a 30 day range is actually a two month span.
> ![daterangepicker_issue](https://cloud.githubusercontent.com/assets/409970/7031642/043573ea-dd3b-11e4-9a3c-0c5482d3f9c3.png)

How did you get the from and to section from the left panel above the apply button. what option/property did you use?

**Comment by dangrossman** [comment]
That screenshot is of a the original version of this library from 2012 or around there. If you want it to look like that, you can go to "Releases" and download one of the 1.x releases from years ago.

**Comment by kamalKpUi** [comment]
> That screenshot is of a the original version of this library from 2012 or around there. If you want it to look like that, you can go to "Releases" and download one of the 1.x releases from years ago. You'll also need an equally old version of the Bootstrap stylesheet to go along with it, as that used to be a dependency.

Thanks for the quick reply. is there any way of having end date still focused when only changing start date or vise versa ? something like this http://boolie.github.io/daterangepicker.html.

**Comment by dangrossman** [comment]
There are no start and end date inputs to have focus in this library any more.

**Comment by RobertRajcool** [comment]
> I got it working now.
> 
> ```js
>    $registrationPeriods.on('show.daterangepicker', function (event, picker) {
>       let rightDate   = endDate || new Date();
>       let rightMoment = moment(rightDate);
> 
>       picker.rightCalendar.month = rightMoment;
>       picker.renderCalendar('right');
>     });
> ```

How you register this function ??
