### ISSUE TITLE
Disable specific dates

### ISSUE THREAD

**Issue by iMasterAle** [dangrossman/bootstrap-daterangepicker#618]
Hi guys,
Can i disable specific dates range load to JSON data?

Ex: booking for the hotel...

Thanks!

**Comment by dangrossman** [comment]
No you cannot. You'll have to program this yourself, or use a different widget that has that ability.

**Comment by WalterBernard** [comment]
is it possible if i use iteration methods to  disable specific dates range load from JSON data ?
