### ISSUE TITLE
Multiple ranges can be active at once

### ISSUE THREAD

**Issue by nordfjord** [dangrossman/bootstrap-daterangepicker#621]
Hi,
in my usage of daterangepicker I have two ranges which can end up being the same (last 7 days, and this week). It is a UX nightmare that both are active at once. I recommend it be changed so that only the first match is active.

**Comment by dangrossman** [comment]
You can probably add a `break` after here:

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L964

and here: 

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L971

In your copy, for now.
