### ISSUE TITLE
Custome range fixed intervals

### ISSUE THREAD

**Issue by dolson911** [dangrossman/bootstrap-daterangepicker#625]
I've had this stuffed on a site for a few years (it's updated to the latest), but I finally had someone hit something weird.

We preset it with the past 30 days since most of our queries are in that timeframe. Today someone wanted to do a custom range of more than 30 days. What's happening is we can select a starting date, then an end date. Fine. Select a new starting date on a different month, and the end date moves based on the interval of the past selection. Even if they now go and chose the right ending date, the starting date will move based on the previous interval.

Keep doing it and the intervals start to get more arbitrary, though usually minus 1 day.

Is it possible that my initializing it with a 30 window is setting some state that it shouldn't?

-David-

**Comment by dangrossman** [comment]
I'm not able to reproduce that from this description.

**Comment by dolson911** [comment]
Yeah. I figured that would be the case. So here are my steps:
1) daterangepicker gets set with start date (today-30) and end date (today)
2) Select custom range from the dropdown
3) Pick March 1 as start. Cool no problem.
4) Now pick move start month back to January and pick the 1st
5) End date magically moves to March 2nd where it should have stayed fixed to today.

Strange. Though I think the root of the problem is how I'm setting the initial dates by variable assignment in the PHP code. That would, of course, remain static since the page isn't being refreshed with the calendar is changing. I don't reset those dates until we repost with the selected dates.

-David-

**Comment by dangrossman** [comment]
I'm not seeing that either, following those steps. It *sounds* like you have the option `dateLimit: { days: 60 }` in there (which is in several of the usage examples) which would automatically move the end date to March 2nd because that's 60 days after January 1st. Are you using the `dateLimit` option and forgot about it?

**Comment by dolson911** [comment]
Bingo. That was it - buried deep in a PHP string.

Thanks Dan!
