### ISSUE TITLE
momentum object from manual selected start date (by datepicker) has a date/time in UTC (isUtc()==true)

### ISSUE THREAD

**Issue by tzahari** [dangrossman/bootstrap-daterangepicker#626]
Hi,
I detected a issue with the component.

It is possibile to set the date range by three methods:
- predefined ranges (today, yesterday...)
- entered into the input field
- selected by date picker

I found out, that the start date momentum object from date picker is in UTC. In the other methods not.
Therefore a formatting with AngularJS is showing a date a day before of the selected date (cause of the Timezone offset). 
As I read is if you use any .utc* Method the momentum object switches to UCT mode.
http://momentjs.com/docs/#/parsing/utc/

I detected another issue with the TimeZone setting: if the selected date is in another DST (daylight saving) then the momentum objects get a wrong date / time.
- currently we have a offset of 120 minutes. 
- the 01/03/15 has a offset of 60 minutes
But the component sets the date with a offset of 120 minutes.

We fixed it temporarily by our own by setting the offset back to 0 in case of if !start.isLocal().
```javascript
if (!start.isLocal()) {
  start.utcOffset(0, true);
};
```
I hope the issues are clear otherwise please reply.
Best Regards
Thomas

**Comment by zhenyi2697** [comment]
I have the same issue here. When user manually type the start/end date, the calendar displays date with -1 day offset. I've set the timezone of the daterangpicker as timezone: '02:00'
Hopes that this will be fixed shortly.

**Comment by tzahari** [comment]
Hi, 
we detected that our first fix is not working if the time is also used (not only dates).
The start date still had a time difference of the timezone offset.
With the commit tzahari@20b2a5520968562223a69a194003f65af51d8844 I fixed this issue at our side.
But I am not 100% sure if this works in all cases.
Best Regards
Thomas

**Comment by devcollectief** [comment]
:+1:
