### ISSUE TITLE
How to select a label programmatically, is there a inbuilt method?

### ISSUE THREAD

**Issue by mohammadwali** [dangrossman/bootstrap-daterangepicker#628]
Hi, i am trying to find an in built method where i can select the labels i added at the time of initialization, i tried to use  the below while initializing -
```javascript
 ranges: {
             'All': [moment(), moment().add(22, 'years')],
             'Only Today': [moment(), moment()],
             'Next 48 hours': [moment(), moment().add(2, 'days')],
             'Next 7 Days': [moment(), moment().add(7, 'days')],
             'Next 30 Days': [moment(), moment().add(30, 'days')]
         },
```
and below to choose the first label which is named as All -
```javascript
$('#search_date').data('daterangepicker').setStartDate(moment().add(22, 'years'));
$('#search_date').data('daterangepicker').setEndDate(moment()); 
```
It worked fine but chooses the option as custom range. anyway i can update it ?

**Comment by dangrossman** [comment]
For 'All', the start date is `moment()`, and the end date is `moment().add(22, 'years')`. You flipped the start and end dates when you tried to select that range.

**Comment by mohammadwali** [comment]
LOL thanks :) :+1:
