### ISSUE TITLE
TimeZone is not applying the local time

### ISSUE THREAD

**Issue by ewamarciniak** [dangrossman/bootstrap-daterangepicker#629]
I need the datetimepicker to allow user select their local time, which is supposed to be then converted based on the timezone and sent to the backend as UTC. I thought that timeZone option is supposed to deal with this but it doesn't seem to be working correctly. When a user selects 3pm the time sent to the database is still saved as 3pm utc depsite of me setting the timeZone option as "01:00".

I would greatly appreciate if you could have a look into this and correct me if I am misinterpretting the purpose of TimeZone option.

Best regards,

Ewa

**Comment by dangrossman** [comment]
I honestly have NFC exactly how the time zone option works. People demanded it, said it was absolutely necessary, and someone added it.

**Comment by ReinierGielen** [comment]
I have the opposite problem. For me everything is displayed in local time, even if it is stored in UTC and supplied to the widget in UTC. If I format the date in the widget as an epoch I can see it is the correct UTC time, but it is displayed as local time.

This might work  form most people but not in our app.

We have globally gathered data with a timestamp
And now the user has to select a timeperiod to select from this database from whatever country on the world.

To keep things understandable for the customers they need to select the period in UTC time, so they have to see UTC time. 

This is what I am struggeling with. If if feed epoch 1421550000000 which is Sun, 18 Jan 2015 03:00:00 GMT to the widget it is shown as 1/18/2015 4:00:00 AM GMT+1:00 and when the user in the widget changes the time to 05:00 it is shown as 1/18/2015 5:00:00 AM GMT+1:00 but stored as  Sun, 18 Jan 2015 04:00:00 GMT.

I need the stored value to be the SAME as the displayed value ( UTC ) and I am not clear on how to handle that. The timezone option does not seem to have an effect.

**Comment by ReinierGielen** [comment]
UPDATE: for MY problem found a work around.
I replaced all statements:   moment.(. . .     by  moment.utc(. . .
This way the entire widget works and displays dates as UTC-date ( exactly what I want )

And as I work in Angularjs I did this also in the angular directive angular-daterangepicker.
