### ISSUE TITLE
Wrong dates selection when the range in one month

### ISSUE THREAD

**Issue by Victori0us** [dangrossman/bootstrap-daterangepicker#631]
Steps to reproduce:
1. Click on date input
2. Click on Yesterday, Today or Last 7 days
3. Then click again on date input
4. Click on Custom
5. Two calendars should contain something like on attached screen.

Selected range is 18 - 24 of April. The second calendar selected 17 - 24 of April. 
In case of Today or Yesterday that calendar selects two days.

![screenshot from 2015-04-24 10 42 13](https://cloud.githubusercontent.com/assets/4447685/7314730/ed4f457e-ea6f-11e4-8244-490230f0d301.png)
![screenshot from 2015-04-24 10 55 09](https://cloud.githubusercontent.com/assets/4447685/7314796/799855f2-ea70-11e4-8d54-1e6364934b40.png)

**Comment by dangrossman** [comment]
Was it near midnight when you made those screenshots? It sounds like a time zone bug.

**Comment by Victori0us** [comment]
No! screenshot from 2015-04-24 10 42 13

**Comment by dangrossman** [comment]
What's wrong in that screenshot?

**Comment by mikehoh** [comment]
@dangrossman 
On the first calendar selected range is 18-24.
On the second it's 17-24.
The second calendar contains bug, it mustn't to highlight the day of 17.

**Comment by dangrossman** [comment]
OK. It doesn't do that for me. The correct dates are highlighted. I don't know what's causing that.

**Comment by mikehoh** [comment]
All became fine after update from version .17 to .21
Fixed.
