### ISSUE TITLE
Display bug after setOptions

### ISSUE THREAD

**Issue by chaudeco** [dangrossman/bootstrap-daterangepicker#632]
A bug appears in this case :

1) setOptions({singleDatePicker: true})
![capture d ecran 2015-04-24 a 18 55 54](https://cloud.githubusercontent.com/assets/1297719/7324097/aa5b9418-eab3-11e4-8050-84067b793029.png)

2) setOptions({singleDatePicker: false})
![capture d ecran 2015-04-24 a 18 54 56](https://cloud.githubusercontent.com/assets/1297719/7324104/b20fe6b4-eab3-11e4-9c9a-d8fcdc780ec8.png)

One of the calendars stays hidden.

Should display :
![capture d ecran 2015-04-24 a 18 55 36](https://cloud.githubusercontent.com/assets/1297719/7324114/bf454054-eab3-11e4-9ba3-27ff3edff229.png)

**Comment by chaudeco** [comment]
Also, on the last screenshot, the left calendar should be the right one and the right calendar should be the left one (opens = "right").

**Comment by CYCTina** [comment]
Is this fix? I just ran into this bug and here is my quick fix: 

```
var updatedOption = { singleDatePicker: isNotRange }
                var secondCalendarDisplay = (isNotRange) ? 'none' : 'block';
                console.info('set new option', updatedOption);
                $('input[name="daterange"]').data('daterangepicker').setOptions(updatedOption, datePickerApplyCallback);
                //have to override the display css property of the second date picker and set the callback function again --> this is a bug
                $('.daterangepicker .calendar.second').css('display', secondCalendarDisplay);
```

**Comment by cassus** [comment]
+1
