### ISSUE TITLE
DateLimit exceeds endDate 

### ISSUE THREAD

**Issue by tusharughade** [dangrossman/bootstrap-daterangepicker#639]
Hello,
I need your help in fixing one issue which I am facing in the Date range picker.

I have endDate: moment(), and dateLimit: {days: 90},
Date Range picker works absolutely fine.
Now I don't want user to select future date's so I set  "endDate" as today's date.
But as the dateLimit is 90 days it picks further date if I select toady's date or previous dates.

1. Go to date picker , select From date = 1 Dec 2014
2. Then again select From date = 28 April 2015 (Today's date) and click on apply button.

Expected behavior : Date should not be greater than Today's date

Unexpected behavior : Date should be seen greater than Today's date
*
---------------------------------------------------------------------------------------------------------------------------
Code:
              format: 'YYYY-MM-DD',
              separator: ' to ',
              startDate: moment().subtract(6, 'days'),
              endDate: moment(),
              showWeekNumbers: false,
              maxDate: moment(),
              dateLimit : {days: 90},
*
-----------------------------------------------------------------------------------------------------------------------------

![datelimit](https://cloud.githubusercontent.com/assets/9526673/7410004/a825e95c-ef48-11e4-8bbc-e9c427ea2d58.jpg)

**Comment by tusharughade** [comment]
Any Solution on the above query?

**Comment by dangrossman** [comment]
I could not replicate the bug using your settings and instructions. When I do them exactly, I am left with today's date as the selected end date.

**Comment by tusharughade** [comment]
Hello,
Thanks for the reply.

Please find the jsfiddle link below
http://jsfiddle.net/nq522uj3/1/

Steps to produce the Issue:
1) Click on "Apply Option Set 2" button
2) Click on range date picker by default 7 days range is selected.
3) Now select 1st Jan 2015 and submit you will get January 1, 2015 - April 1, 2015 which is correct
4) Now go back and select 5th May 2015 you will get May 5, 2015 - August 3, 2015
the result should be May 5, 2015 - May 5, 2015 and not August 3, 2015

in jsfiddle my javascript code is on line no 4112 to 4116

**Comment by tusharughade** [comment]
What would be the Solution any Idea on this?

**Comment by tusharughade** [comment]
Any Solution on the above query?

**Comment by dangrossman** [comment]
There probably won't be a solution unless you write one. Nobody is paid to fix bugs on this 3-year-old free widget.

**Comment by cxytomo** [comment]
@tusharughade I use daterangepicker 1.3.21. It works fine.
