### ISSUE TITLE
Issue with moment timezone

### ISSUE THREAD

**Issue by kesavkolla** [dangrossman/bootstrap-daterangepicker#642]
In my application I'd to use moment with timezone.  In my application I set default timezone to my application specific one.

Example:  moment.tz.setTimezone('US/Hawaii');

After I set this the daterangepicker doesn't work.  I select some date and it displays random date.  Some months it shows Invalidate as label.

I also tried to set dateRangeOptions.timezone = 'US/Hawaii';  Still doesn't work.

Looks like moment timezone is breaking daterangepicker.

**Comment by clouchtibat** [comment]
I also set a default timezone with moment and I have the same problem.
After investigation it seems that OS timezone has still an impact on daterangepicker: I tried different timezones in OS settings and daterangepicker worked for some of them and bugged for some others.

**Comment by kesavkolla** [comment]
I've re-implemented this using appropriate timezone calls.  If you want you can take changes from my fork.  https://github.com/kesavkolla/bootstrap-daterangepicker

**Comment by clouchtibat** [comment]
Great work! Thank you for your help.
