### ISSUE TITLE
Default hide calendar

### ISSUE THREAD

**Issue by frlinw** [dangrossman/bootstrap-daterangepicker#643]
Hi,

I'm using daterangepicker for a search engine, I don't want to select any default date but it's not possible so I chose a date which is never selected (first sunday of the current month).
Problem is, if I choose a custom range like that, calendars are shown when I click on the input for the first time

Questions : 
1 - Is it possible to have empty inputs (for startDate and endDate) and calendars positioned on the current month ?
2 - If not, is it possible to hide calendars (by default) if the default startDate and endDate are a custom range ?

Thanks!

**Comment by dangrossman** [comment]
There is no option that will make it work like that. You need to customize your copy for your needs.
