### ISSUE TITLE
Different parse and display format

### ISSUE THREAD

**Issue by brauliobo** [dangrossman/bootstrap-daterangepicker#647]
It is particulary easy to parse a ISO date from date and then use a different format to display. So it might be interesting to be able to specify both formats

**Comment by brauliobo** [comment]
I would call them: `valueFormat` and `displayFormat`, and the date will be read/write from/to the `value` attribute.

**Comment by brauliobo** [comment]
I'm using the format `LLLL`, and inside the dropdown the `from` and `to` inputs' widths are not enough to fit them. So, a `shortDisplayFormat` option would also be very useful.

**Comment by dangrossman** [comment]
Hi Bráulio. There is no need for a `valueFormat`. The current start and end dates for the picker are moment date objects. You always have access to the moment objects. There is never a need to parse a formatted string. If you want the start and end dates in ISO format, you can always get them. You can access the dates a user selects by providing a callback function, which is passed the two moment objects every time the selected range changes. You can have your callback populate a hidden input with the ISO formatted string if you so wish (`$('#hidden').val(start.format());`). You can also access the start/end date through the picker object anywhere in your code: `var start = $('#container').data('daterangepicker').startDate;`.

**Comment by brauliobo** [comment]
@dangrossman right, got it. Still `shortDisplayFormat` is necessary.
