### ISSUE TITLE
Increase endDate by 1

### ISSUE THREAD

**Issue by yashwanthbabu** [dangrossman/bootstrap-daterangepicker#649]
Hi. I am using daterangepicker and I loved it. 

My question is, after clicking on the textbox the calendar be opened. In that the startDate be shown as present day date. And the endDate should be shown as tomorrow's date by default. Right now both startDate and endDate are showing as the present day dates.

How can I do this??

**Comment by dangrossman** [comment]
$('#element').daterangepicker(
      { 
        startDate: moment(),
        endDate: moment().add(1, 'days')
      }
    );
