### ISSUE TITLE
Missing Bootstrap as dependency in bower.json

### ISSUE THREAD

**Issue by vmariano** [dangrossman/bootstrap-daterangepicker#651]
yeah, that. What version should be compatible?

**Comment by dangrossman** [comment]
It's not actually a dependency, except insofar as the date range picker is made to work well with their stylesheet. It's compatible with any version (2.x or 3.x).

**Comment by vmariano** [comment]
I see, my bad. I think was weird after do `bower install`, and  didn´t complete the starter example.

maybe you can add a default version in your bower install with the note of is compatible with 3.x

**Comment by dangrossman** [comment]
It's compatible with 2.x too.
