### ISSUE TITLE
Time selection is reset when a new day is selected

### ISSUE THREAD

**Issue by zackperdue** [dangrossman/bootstrap-daterangepicker#654]
This is bad functionality especially since I have a plugin trying to hijack the select dropdown menus for the hours:minutes:am/pm. I'm using select2.

Is there a better callback on can use to init this plugin when it changes? If not, can we get functionality that leaves the time pickers alone when day changes?

Thanks

**Comment by dangrossman** [comment]
No and no, sorry 'bout that.
