### ISSUE TITLE
Is not possible using custom html in range key.

### ISSUE THREAD

**Issue by vmariano** [dangrossman/bootstrap-daterangepicker#656]
Hi, I'm trying to add a custom range, with a custom message in locale lang:
```javascript
'Este a&ntilde;o': [moment().startOf('year'), moment().endOf("year")],
```
Inside of the key, is not possible using custom html.

A possible wk, could be add a more complex notation in range. Instead of using a simple key/value, using something like:
```javascript
 range: {
   'aKey' : {
        dateRange:  [moment().startOf('year'), moment().endOf("year")],
        menuText:  'an <blink>html</blink> compatible text',
    }
 }
```

What do you think?

**Comment by dangrossman** [comment]
I think you can certainly program something like that for your application.

**Comment by vmariano** [comment]
Are you sure you want to discard this issue? I think will be hard internationalize menu texts.

**Comment by dangrossman** [comment]
There's nobody here that will look at your issue and go write new code, so there's no point having the issue.
