### ISSUE TITLE
"Cancel" doesn't work after hiding without applying

### ISSUE THREAD

**Issue by komaval** [dangrossman/bootstrap-daterangepicker#663]
How to reproduce:
1. Go to http://www.daterangepicker.com/
2. Open any picker and select range (don't click "Apply" or "Cancel"!)
3. Click outside picker to close it.
4. Open picker again - you'll see previously selected range.
5. Try to click "Cancel" - nothing happens

Is it correct behaviour?
We haven't done any action ("Apply" or "Cancel"), but "history" is erased.

Expected behaviour: "Cancel" has to work

Am I right?

**Comment by dangrossman** [comment]
That's perhaps a reasonable expectation. "Cancel" does result in no changes being applied to the input nor a callback being called.

**Comment by komaval** [comment]
Thank you for the answer, but would you clarify it, please?:)
"Cancel" has to work,
or current behaviour is correct and expected.

> That's perhaps a reasonable expectation

I mean, what is "That's"?
