### ISSUE TITLE
Time-only Picker?

### ISSUE THREAD

**Issue by gregheidorn** [dangrossman/bootstrap-daterangepicker#668]
I am having trouble figuring out if it's possible to render an input as a single time-only picker.  Is that an option or configuration of options?

**Comment by dangrossman** [comment]
No. Why would you want to use a date range picker to pick a single time? There are plenty of time picker widgets out there, or you can just use two `select`s.

**Comment by gregheidorn** [comment]
Just to reduce the number of libs in my app, that's all.  Thanks for the quick reply!

**Comment by umutm** [comment]
I was in the same need.

And, also to display a similar interface for all options (date-picking, date-time picking and time-picking).
