### ISSUE TITLE
Can't select a range spanning more than one year when showDropdowns = true

### ISSUE THREAD

**Issue by gdemartini** [dangrossman/bootstrap-daterangepicker#671]
When I change the year on the start date (or end date) and click on a date, it applies the same year to the end date (or start date).
Steps to reproduce:
- Go to http://www.daterangepicker.com/
- Scroll down to the "All options" example (or click the "All options" menu item)
- Open the date range picker and change the year to 2012 on either one of the dropdowns, then click on a date
- Notice the year changes on the other year dropdown

**Comment by dangrossman** [comment]
That's because the "all options" example has the `dateLimit: { days: 60 }` option, which says the start and end date can't be more than 60 days apart. It is adjusting your end date to be within 60 days of the newly selected start date. That is the correct functionality.

**Comment by gdemartini** [comment]
Thanks for the quick reply and sorry for the blunder.
