### ISSUE TITLE
Non-documented API

### ISSUE THREAD

**Issue by BlaMaeda** [dangrossman/bootstrap-daterangepicker#674]
Hello, in the readme there are some functions that can be called on the picker (setOptions, setStartDate, setEndDate), but these are not the only public functions on it. In my case, I want to show the picker programatically, and peeking at the code I see that there is a show function. I tested it and it seemed to work fine (it also triggers the proper event, for example).

My question is, are these other functions not supposed to be used, or just not documented?

Thanks.

**Comment by dangrossman** [comment]
I guess just not documented? Nobody's going to shoot me if I break the API, documented or not... not that I plan to. It's just a little JavaScript widget; your copy of it will never change.

**Comment by BlaMaeda** [comment]
Great, thanks. Would you accept a PR adding that to the documentation?
