### ISSUE TITLE
Would suggest validating element value to moment conversation via strict argument

### ISSUE THREAD

**Issue by jeserkin** [dangrossman/bootstrap-daterangepicker#677]
i.e.

`input.val() => '16.05.201' ==> moment conversion => '16.05.0201'`

and with `strict` check

`input.val() => '16.05.201' ==> moment strict conversion => 'Invalid date'`

**Comment by jeserkin** [comment]
Closed?

**Comment by dangrossman** [comment]
All issues and PRs against v1 were closed when v2 was released.
