### ISSUE TITLE
datepicker hidden after event

### ISSUE THREAD

**Issue by ron0** [dangrossman/bootstrap-daterangepicker#678]
Great work, Dan!

I'm starting with your All Options example.  After receiving an event and setting the value of the span in your sample callback, the datepicker div display gets set to none.

    $('#reportrange span').html(moment().subtract(29, 'days').format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));
 
    $('#reportrange').daterangepicker({
        format: 'MM/DD/YYYY',
        startDate: moment().subtract(29, 'days'),
        endDate: moment(),
        dateLimit: { days: 60 },
        showDropdowns: true,
        showWeekNumbers: true,
        timePicker: false,
        timePickerIncrement: 1,
        timePicker12Hour: true,
        ranges: {
           'Today': [moment(), moment()],
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Last 7 Days': [moment().subtract(6, 'days'), moment()],
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        opens: 'left',
        drops: 'down',
        buttonClasses: ['btn', 'btn-sm'],
        applyClass: 'btn-primary',
        cancelClass: 'btn-default',
        separator: ' to ',
        locale: {
            applyLabel: 'Submit',
            cancelLabel: 'All',
            fromLabel: 'From',
            toLabel: 'To',
            customRangeLabel: 'Custom',
            daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr','Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            firstDay: 1
        }
    }, function(start, end, label) {
        console.log(start.toISOString(), end.toISOString(), label);
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        start.startOf('day');
        end.endOf('day');
        $('#startDate').val(start.format("MM/DD/YYYY hh:mm a"));
        $('#endDate').val(end.format("MM/DD/YYYY hh:mm a"));
        $('#reportrange').css('display', 'inline-block');
        console.log('passed change');
    });

    $('#reportrange').on('cancel.daterangepicker', function(ev, picker) {
    	  //do something, like clearing an input
    	  $('#reportrange').val('');
    	});

    $(document).ready(function() {
    	var drp = $('#reportrange').data('daterangepicker');
        $('#startDate').val(drp.startDate.format("MM/DD/YYYY hh:mm a"));
        $('#endDate').val(drp.endDate.format("MM/DD/YYYY hh:mm a"));    	
    });

**Comment by dangrossman** [comment]
The date range picker is hidden after you've selected your date range. That's the expected behavior.

**Comment by ron0** [comment]
My mistake - it was a conflict with another javascript module.

Ron Cass
BigRiver - Increase Online Giving
c: 216-832-6444
http://www.gobigriver.com

Big River helps nonprofit organizations raise more money by engaging donors through personally relevant appeals, promotions, data mining and social marketing.  The cloud-based solution is easy to use, affordable and integrates with existing donor management products.
