### ISSUE TITLE
setEndDate as setStartDate

### ISSUE THREAD

**Issue by umesh-naik** [dangrossman/bootstrap-daterangepicker#679]
Hi,
I'm working on an application in which, when I select a date in setStartDate, it also has to become my setEndDate. One can say that, set it to moment(). But, the problem is, suppose I select my startDate in future, then I can't have my endDate to be back. So, it should move along with the startDate. Suggestions please.

**Comment by dangrossman** [comment]
Call `setEndDate` whenever you call `setStartDate`.

**Comment by umesh-naik** [comment]
Exactly.. but do I have any methods to do so? As you have suggested, I can set my endDate as my startDate but I don't want that. I want my endDate change dynamically when I select my startDate (mainly when I select my startDate in future)

**Comment by umesh-naik** [comment]
Let me explain this with an example.
Suppose I have an mail to be sent. I want to send my mail after two days from today. And since my end date starts from today, I want that to start after two days.

**Comment by dangrossman** [comment]
Scheduling a mail to be sent in two days requires a date picker, not a date range picker. This is not the right user interface widget for your needs.

**Comment by umesh-naik** [comment]
Do I have any way to get the result I want? Because the application exactly needs daterangepicker plugin.

Or can I integrate datepicker in daterangepicker so that my task gets done? If yes, then can you please specify how the configuration should be done.

**Comment by dangrossman** [comment]
I have no idea what you're asking for. Sending a mail two days from today does not involve a date range, just a date (June 24). You don't need a date **range** picker to select a single date.
