### ISSUE TITLE
When selecting preset range of 'This Month' calendar gets set to Wed, Dec 31st 1969

### ISSUE THREAD

**Issue by sferoze** [dangrossman/bootstrap-daterangepicker#681]
I have setup custom ranges like so

```
t.$('input[name="daterange"]').daterangepicker
    startDate: moment().startOf('day')
    endDate: moment().endOf('day')
    format: 'ddd, MMM D'
    #minDate: '01/01/2015'
    ranges:
      'Today': [
        moment().startOf('day')
        moment().endOf('day')
      ]
      'Next 7 Days': [
        moment()
        moment().add(6, 'days')
      ]
      'Next 30 Days': [
        moment()
        moment().add(29, 'days')
      ]
      'This Month': [
        moment().startOf('month')
        moment().endOf('month')
      ]
    opens: 'right'
    separator: ' to '
    # locale: 
    #   cancelLabel: 'Clear'
  , cbChooseDate
```

Whenever I select this month, the calendar seems to be setting the correct date internally but the display shows 'Wed, Dec 31 to Wed, Dec 31' and the calendar shows December 31st 2015. But it logs out this month June1st, and June 30th in the callback. 

Also in my console I am getting this error: 

```
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
```

Any idea how to fix this issue?

**Comment by dangrossman** [comment]
I think the problem's in your callback or something else in your application. I can't reproduce that bug with those options, neither with the bundled version of moment nor the latest.

**Comment by sferoze** [comment]
@dangrossman your right. I figured out the mistake was in my callback setting the date of the calendar to null accidentally. Sorry and thanks!
