### ISSUE TITLE
Add more columns for ranges

### ISSUE THREAD

**Issue by Skipper565** [dangrossman/bootstrap-daterangepicker#687]
There is only one column list of ranges.
When there are more than five ranges height of modal window is too big.
It'll be better to add array of ranges for more columns.

Add "for" cycle (lines 342 - 372).
Example definition of ranges could be something like this:

`ranges = [{`
`'firstColumnFirstRange': [moment(), moment()],`
`'firstColumnSecondRange': [moment(), moment()]`
`}, {`
`'secondColumnFirstRange': [moment(), moment()],`
`'secondColumnSecondRange': [moment(), moment()],`
`}];`

![vystrizek](https://cloud.githubusercontent.com/assets/12514488/8409717/fbb33790-1e79-11e5-8ea1-c5cdb70563aa.JPG)

**Comment by dangrossman** [comment]
This seems like a an uncommon use case, and not a good reason for making use more complex for everyone else. You are free to make this modification to your copy.

**Comment by Skipper565** [comment]
And could you please merge this improvement to main if i made it?

**Comment by dangrossman** [comment]
No, I would not consider this an improvement.
