### ISSUE TITLE
Need option to disable submitting

### ISSUE THREAD

**Issue by DenianShades** [dangrossman/bootstrap-daterangepicker#691]
When clicking "apply", the date range is automatically submitted (using value names I *never* used *anywhere*). This happens whenever the "parentEL" parameter is set to render the picker inside a form; I really need the option to disable this behaviour, because I need to handle the submits differently.

**Comment by dangrossman** [comment]
Update to the latest version of this library. "type=button" was already added to the buttons to avoid unintentional form submits.
