### ISSUE TITLE
Request: Options to change UI

### ISSUE THREAD

**Issue by anshbansal** [dangrossman/bootstrap-daterangepicker#692]
Hi @dangrossman 

Can you add options to change the UI? For example
* Location of ranges - top, bottom
* Adding headings to the calendars shown. e.g. "From", "to" or "Event Start" and "Event end"
* Applying some separators between ranges and calendars, between calendars.

I checked the examples and this datepicker seems to be a very good. But some UI changes might be necessary sometimes to meet the UI look and feel.

**Comment by dangrossman** [comment]
No. This isn't the kind of thing that's going to be changed through a set of options, and it would add enormous complexity to the code. If you want to change the location of things, add headings, add separators, then you need to edit the HTML of your copy of the code.
