### ISSUE TITLE
"this" in callback function

### ISSUE THREAD

**Issue by DenianShades** [dangrossman/bootstrap-daterangepicker#693]
Where exactly does "this" point to in the supplied callback function? Which element is it attached to?

I ask because I'm trying to attach daterange pickers to multiple (dynamically placed) elements by class, not by ID. I need to change the values of two hidden inputs placed in the same container as the element the picker is attached to. So I have the following structure:

* div class="dateRange"
  * input type="text" class="dateRangePicker"
  * input type="hidden" class="dateRangeMin"
  * input type="hidden" class="dateRangeMax"

This occurs multiple times throughout the document, and the range should only be set for the siblings of the *specific* text input that was used. I can't access those elements using $(this).siblings('.dateRangeMin').val(), $(this).parents('.dateRange').children('.dateRangeMin').val() or anything similar. The "parentEl" option is set to '.dateRange'.

Where does "this" point to? Is there some other way of accessing the element the picker is attached to?

**Comment by dangrossman** [comment]
`this` is the DateRangePicker object. The DOM element it's attached to is in `this.element`.
