### ISSUE TITLE
Can someone bundle latest moment.js 2.10.3

### ISSUE THREAD

**Issue by baskarsugumar** [dangrossman/bootstrap-daterangepicker#702]
Every time I instal daterangepicker, I was asked for confirmation as my project uses latest moment.js. Can someone help me getting latest moment.js bundled with bootstrap-daterangepicker

Thanks,
Baskar S

**Comment by dangrossman** [comment]
This would not be a long-term fix for whatever issue you have in your process. I do not monitor the momentjs repo on a daily basis, so the bundled copy will fall behind the latest version for some time every time it's updated.
