### ISSUE TITLE
Set the year range in Single Date Picker

### ISSUE THREAD

**Issue by dangelion** [dangrossman/bootstrap-daterangepicker#703]
I'm using your awesome plugin as Single Date Picker. How can set the year range in the select?
I'd like to set a range like: from "10 years ago from now" to "current year". 
Or from "2005" to "current year". 

Thanks

**Comment by dangrossman** [comment]
Use the `minDate` and `maxDate` options.

January 1 2015 to December 31 2015 is the same as "2005 to current year".
