### ISSUE TITLE
Date and Time Picker - To Time change through input textbox not working

### ISSUE THREAD

**Issue by dharmesh019** [dangrossman/bootstrap-daterangepicker#704]
Hi,
 i have found strange issue of "To datetime input textbox" is not applying entered time to combined display daterange textbox when user hit enter after changing time section of "To" datetime.

Otherside, same thing is working fine with "From" datetime where user can change the time section and hit enter and it changes the main daterange textbox and time seleciton dropboxes correctly.

it is happening with live example shown for Date and Time Picker. Would you please advise or address the issue 
![image](https://cloud.githubusercontent.com/assets/2424276/8643877/a86fda08-297c-11e5-8b3a-e0f5a6520194.png)

**Comment by dangrossman** [comment]
The same bug exists in both text boxes: you can type a time that isn't valid under the current `timePickerIncrement` setting, which is 30 in that example. Only times ending in 00 or 30 should be valid.

**Comment by dharmesh019** [comment]
I know that issue but here i am trying to explain different issue which does not exists in From inputbox. for example, if you type 04:00 AM in from time section and then press enter then it reflect the change immediately to dropdown selection and main daterange inputbox but it is not happening with To datetime inputbox. if you enter different time like 08:00 and press enter then it changes to 11:59 PM in textbox and also in main daterange box and dropdown select 11:00 PM.

**Comment by dangrossman** [comment]
Yes, a separate bug. On line 727, the date is set to `date.endOf('day')` without checking if the `timePicker` option is enabled.

**Comment by dharmesh019** [comment]
This bug is resolved or it will be address in next release. Can i find the solution for it?

**Comment by dangrossman** [comment]
See my comment above for a solution.

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L727

**Comment by dharmesh019** [comment]
Should i need to change the line to check timepicker option enabled or not to make it work?

**Comment by dangrossman** [comment]
It's almost 3AM here, I have to be up in the morning. I gave you a quick fix. A more complete fix for these two bugs will have to wait.

**Comment by dharmesh019** [comment]
ok thanks . i will fix it for me .Thanks for your prompt support.
