### ISSUE TITLE
Fire apply on date selected

### ISSUE THREAD

**Issue by closca** [dangrossman/bootstrap-daterangepicker#705]
Is there posible to fire apply when a date is clicked or a custom range from the side is chosen?

**Comment by dangrossman** [comment]
The apply event is fired when a predefined range is clicked or when the apply button is clicked.

**Comment by alanhamlett** [comment]
This looks like it's no longer firing the apply event. I had code using it and after upgrading to 2.0.4 my apply.daterangepicker callback is no longer being called.

**Comment by alanhamlett** [comment]
After upgrading to master it's fixed, so looks like a problem in latest 2.0.4 release.
