### ISSUE TITLE
Auto apply when dates are selected. or add an event when user selects start date and end date

### ISSUE THREAD

**Issue by fatbotdesigns** [dangrossman/bootstrap-daterangepicker#709]
Hi,

Can you please add a custom event for when a user selects a date range. So that it's possible to auto-apply the date range when selected.

**Comment by Liaohuanle** [comment]
Maybe the dateRP has the reletaive API

**Comment by nlagdhir** [comment]
You can use autoApply option.

autoApply: (boolean) Hide the apply and cancel buttons, and automatically apply a new date range as soon as two dates or a predefined range is selected
