### ISSUE TITLE
bower.json moment.js version update

### ISSUE THREAD

**Issue by 719media** [dangrossman/bootstrap-daterangepicker#713]
Awesome plugin, Ive been using it for awhile and happy to see all the recent work you've done it. Thanks!

If you could update the bower.json external reference to have the newer version of moment, that would be great!

Thanks again!

**Comment by dangrossman** [comment]
A pull request is the best way to make this happen. I don't actually use any of these package managers myself, which makes editing the metadata correctly challenging.
