### ISSUE TITLE
Only timepicker? 

### ISSUE THREAD

**Issue by naveed-ahmad** [dangrossman/bootstrap-daterangepicker#716]
Is there any configuration to show only timepicker? Really don't want to use two plugin for picking date ranges and sometime only the time.

Great plugin, loving this so far :heart: 

Also how about adding inline rendering option?

**Comment by dangrossman** [comment]
There's no configuration to show only a time picker, sorry. I've personally never come across a website that created/used some kind of special widget for choosing times: I don't understand the need for a "time picker" to exist. Just some `<select>` lists seems adequate? Maybe you could point me to an example, just out of curiosity.

**Comment by mpetris** [comment]
(2) I've a use case where the user is supposed to input date ranges quickly and there is plenty of page space available. So it would be nice to have an inline date range picker to save the user an extra click. Also the user can see the date range faster if the calendars are always visible, the visualization is more powerful. Actually I would go so far as to skip the input box altogether and just display the calendars. So +1 for this feature. In any case thanks for this very useful component!

**Comment by dangrossman** [comment]
I'll need more than a "this would be useful". Like an actual screenshot of a UI that includes an inline date range picker.

**Comment by naveed-ahmad** [comment]
@dangrossman sorry for delays, was busy in a family medical emergency. I can see your point, the biggest issue with open source( and free ) work is everyone want his own dam customization :) 

Inline calendar view and time picker are popular in web apps. You can see an example of Runkeeper.com

![selection_037](https://cloud.githubusercontent.com/assets/701567/8894297/3b55e31a-33ca-11e5-8558-96549eaa4435.png) 

Click on date and you'll see logs data for that date or create new log, simple and effective. 

Issue with select field for time is lot of clicks, text field would need validation, see invalid 555 value for both hours and minutes field in above screenshot which result is 500 error on submitting the form.
![selection_038](https://cloud.githubusercontent.com/assets/701567/8894307/b48eadb6-33ca-11e5-918b-0c956e43e7e2.png)

We already have lot of date and time-picker : 
https://github.com/jdewit/bootstrap-timepicker ( 979 frocks )
https://github.com/Eonasdan/bootstrap-datetimepicker ( date + time picker. 1781 frocks )

Now issue with using multiple plugins for picking time, date( inline calendar ) and daterange is conflicts, page load time, development time, this even goes worst when upgrading bootstrap's version etc. Few more bytes can add inline calendar view, and time-picker in this awesome plugin.

Ill love to contribute if adding them makes sense now.

**Comment by alandball** [comment]
It is useful in the case where I select a date range for setting up repeating of events, and what time each event will happen in the day. I have a list of checkboxes for days o the week on which a repeat should happen. The date range picker is used to select range(e.g. Jan to end Jun). And another date range picker to say each event will happen from 13:05 until 14:00 (building a timetable for lectures at a college).

Two dropdowns will do in this scenario, but now I am not using the helper I built for C# Razor which automatically adds the control groups, inputs. I don't mind building a timepicker helper, I was just hoping there is an option I can set for it.

**Comment by jonalxh** [comment]
This code is working for me, I hope it helps someone:
```html
<input type="text" class="input-timepicker">
```


```javascript
    $('.input-timepicker').daterangepicker({
        timePicker: true,
        timePickerIncrement: 60,
        locale: {
            format: 'hh:mm'
        }
    }, function (start, end, label) { //callback
        start_time = start.format('HH:mm');
        end_time = end.format('HH:mm');
        console.log(start_time, end_time);
    }).on('show.daterangepicker', function (ev, picker) {
        picker.container.find(".calendar-table").hide(); //Hide calendar
    });
```
