### ISSUE TITLE
Can someone bundle latest moment.js 2.10.3

### ISSUE THREAD

**Issue by baskarsugumar** [dangrossman/bootstrap-daterangepicker#717]
Can someone help me in bundling latest moment.js

Regards,
Baskar S

**Comment by dangrossman** [comment]
That's already the version included in this repository.

**Comment by baskarsugumar** [comment]
Sorry, I see only 2.9.0 bundled and not 2.10.3. Can you please check that.

**Comment by dangrossman** [comment]
https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/moment.js#L2

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/moment.min.js#L2

**Comment by baskarsugumar** [comment]
Thank you for the info @dangrossman
