### ISSUE TITLE
Month/Year expand calendar

### ISSUE THREAD

**Issue by tsmgeek** [dangrossman/bootstrap-daterangepicker#718]
It would be nifty to have the ability to click on the Month/Year headings on the calendar and it open up and show all the months for that year, the title changes to year, if you then click on the year it will expand out to show the last 12 years etc etc..

**Comment by dangrossman** [comment]
That might be nifty but it's not a feature that exists. I use this issue tracker for bug reports. There are no developers that implement feature suggestions here.
