### ISSUE TITLE
custom date-picker in date range picker shows reversed timestamps!

### ISSUE THREAD

**Issue by simkeyur** [dangrossman/bootstrap-daterangepicker#720]
problem is when I select from the custom date picker, it somehows shows me reversed from and start dates, I am adding pictures to get better idea what I am talking about.

Can you help me locate the code in js file?

Thanks
<img width="923" alt="img1" src="https://cloud.githubusercontent.com/assets/3363966/8785658/fc2a052a-2eee-11e5-9856-5bd56a857881.png">
<img width="611" alt="img2" src="https://cloud.githubusercontent.com/assets/3363966/8785661/ff9a5bec-2eee-11e5-9b18-70d256835659.png">

**Comment by dangrossman** [comment]
I can't help debug something from a screenshot, and that is an old version of the date range picker
