### ISSUE TITLE
Possible regression in 1.3.22 release around "in-range" styling

### ISSUE THREAD

**Issue by swanson** [dangrossman/bootstrap-daterangepicker#722]
```js
$('#reportrange').daterangepicker({
   timezone: 0,
   startDate: moment.utc('2015-07-15').startOf('day'),
   endDate: moment.utc('2015-07-20').endOf('day')
});
```

# Previous behavior
http://jsfiddle.net/wda3kpwm/ Test case for v1.3.21

![image](https://cloud.githubusercontent.com/assets/56947/8807921/78807d7a-2fad-11e5-8528-023edd069c18.png)

# New behavior
http://jsfiddle.net/zqkq07ga/ Test case for v1.3.23

Notice that July 14 (outside the range) on the right calendar is styled as if it were included in the range.

![image](https://cloud.githubusercontent.com/assets/56947/8807898/5ae83c6c-2fad-11e5-8cac-43fe8a92178b.png)

I believe that [this commit](https://github.com/dangrossman/bootstrap-daterangepicker/commit/61ac1dccd183711c5167f8ed2060aa4f29afee16) introduced the change in behavior.

When checking if the current cell is included in the range (see [this conditional](https://github.com/dangrossman/bootstrap-daterangepicker/blob/v1.3.23/daterangepicker.js#L1178-L1182) in `renderCalendars`), the start and end date are in UTC, while the date associated with the table cell is not set to the user-defined timezone. This causes the comparison to incorrectly mark a date outside the range as `in-range`.

We've forked this repo locally and reverted https://github.com/dangrossman/bootstrap-daterangepicker/commit/61ac1dccd183711c5167f8ed2060aa4f29afee16 as a temporary work-around. I don't know the full context of the behavior that this commit attempted to address, but the comment of "possible fix" above the change leads me to believe that this was perhaps not a long-term solution.

Can you confirm if this is a regression? Or intended behavior?

**Comment by dangrossman** [comment]
Hi Matt. Highlighting the wrong dates is not intended behavior.

**Comment by swanson** [comment]
@dangrossman thanks Dan - I can open a PR that reverts that commit if that is helpful. Let me know how I can assist.

**Comment by dangrossman** [comment]
Reverting that commit will re-introduce other bugs. I really do hate this feature; configurable time zone support has been a headache and I still don't see its purpose, but I'm badgered by requests for it if it's not there.

**Comment by swanson** [comment]
Understandable - we will continue with our fork for now then. Are you open to an alternative fix for https://github.com/dangrossman/bootstrap-daterangepicker/issues/626 if I can come up with one?

I can say that our use-case for configurable timezones involves a server-side, user specific "Display Timezone" preference. Our application allows users to manage assets that located in other timezones or countries, so there is the desire to use a different timezone than the browser's local timezone. Definitely a headache when timezones are involved :)

**Comment by dangrossman** [comment]
It's a fancy interface for picking two [year, month, day, hour and minute]. What time zone those will correspond to doesn't matter for the picking part. You can construct a datetime object in your application in any time zone with that information. That's why I don't understand why the picker needs to be time zone aware.

Improvely has user configurable display timezones as well. It's used this picker for years before the time zone setting was added. I just converted the selection from the user's time zone to GMT *after* they chose the dates.

**Comment by swanson** [comment]
Thanks - I will definitely think about your approach and re-evaluate if we are solving our users needs in the simplest way.

Appreciate the quick response, have a great week :)

**Comment by dangrossman** [comment]
I ended up reverting that old commit, and nobody's complained about it yet. Perhaps more consistent use of `utcOffset` on inputs eliminated the need for the hack there, and this is 'fixed' for now?

**Comment by swanson** [comment]
I'll close for now - can always re-open if I still have issues after updating. Thanks Dan :)
