### ISSUE TITLE
Can't leave the field blank

### ISSUE THREAD

**Issue by sb4m** [dangrossman/bootstrap-daterangepicker#724]
Hi, 
Since I update this gem, my input are autofill with the current date. 
I have to leave this input blank when my people dont want to filter my results in a range
How can I do this, maybe I miss an option

Edit:
just add the pull request
https://github.com/dangrossman/bootstrap-daterangepicker/pull/725

**Comment by dangrossman** [comment]
$('#el').daterangepicker();
    $('#el').val('');

**Comment by sb4m** [comment]
Why not but I want to be able to :
- populate or not the field at loading
- clear the field after a select

**Comment by dangrossman** [comment]
`$('#el').val('');` clears the field.

You can do this when you create the picker, when the cancel button is clicked, after a specific range is chosen...
