### ISSUE TITLE
How to handle short time ranges 

### ISSUE THREAD

**Issue by eskimoblood** [dangrossman/bootstrap-daterangepicker#726]
Lets say I want to have something like `last 5 minutes`. As the ranges are set when initialising the date picker, after some minutes the range is out dated. Is there a way to set the ranges when the date picker is opening?

**Comment by dangrossman** [comment]
This isn't possible.

However, the label of the chosen predefined range is provided to your callback function, so you can re-calculate the dates there.

**Comment by eskimoblood** [comment]
Ok, but would it be possible to change the ranges on `showCalendar`?

**Comment by dangrossman** [comment]
No, it's not possible. What you're passing in are essentially timestamps, not descriptions of how to build timestamps. They're fixed points in time as soon as the code where you create the date/moment object is executed, which is before the date range picker is even created.

**Comment by dangrossman** [comment]
It's not.

**Comment by eskimoblood** [comment]
Ok, than I'll use the `chosenLabel` field and recalculate the duration, thanks
