### ISSUE TITLE
Bower installing 1.3.23

### ISSUE THREAD

**Issue by bcruddy** [dangrossman/bootstrap-daterangepicker#729]
Installing with bower installs version 1.3.22 instead of 2.x

**Comment by dangrossman** [comment]
Isn't it your own project's bower.json file that determines which version of dependencies get installed?

**Comment by bcruddy** [comment]
Must have been a bower caching issue, I did a bower install in a temp directory just to grab the dist files and it installed 1.3.23 a couple hours ago, just tried again and it installed 2.0.4.
