### ISSUE TITLE
problem with loop structure

### ISSUE THREAD

**Issue by baskarsugumar** [dangrossman/bootstrap-daterangepicker#736]
I using bootstrap-daterangepicker in an ember-cli application. Since it compresses all the js files, there seems to be problem with the following line.
for (var i in classes) {
                        cname += classes[i] + ' ';
                        if (classes[i] == 'disabled')
                            disabled = true;
                    }

there are so many variables by default with the name classes and hence, the td's class attribute is assigned with a large javascript function. Since the variable classes is an array, I tried writting it as 

for(var i=0; i<classes.length; i++) instead of for (var i in classes) and it worked. Can some thing be done on this.

Thanks,
Baskar S

**Comment by dangrossman** [comment]
Yes, this has already been patched.

https://github.com/dangrossman/bootstrap-daterangepicker/commit/3cfe4bb8c738efc3192a2d079c783bf33b744bbe

**Comment by baskarsugumar** [comment]
I am just installing it as bower component and how can I get to install the patched one or Will it be available at the top.

Regards,
Baskar S

**Comment by SamvelRaja** [comment]
@baskarsugumar 

add this in your **bower.json** file

```js
   "bootstrap-daterangepicker" : "https://github.com/dangrossman/bootstrap-daterangepicker.git#3cfe4bb8c738efc3192a2d079c783bf33b744bbe"

```
To download it from the particulat commit hash.
