### ISSUE TITLE
How to ?

### ISSUE THREAD

**Issue by baskarsugumar** [dangrossman/bootstrap-daterangepicker#737]
Sorry to ask it here, since I don't see proper document, I have no other option.

I am using daterange picker in an ember application, and it will be really helpful if anyone can guide me on how to

1. get the selected date range - in all cases, ie, even when setting default date
2. localize, ie, need to i18n all the strings via ember-i8n.

Thanks,
Baskar S

**Comment by SamvelRaja** [comment]
You can make it as an `ember.component` 

Two way binding property of ember will help you with this.

```js

$('#config-demo').daterangepicker({
    "timePickerIncrement": 1,
    "startDate": "07/01/2015",
    "endDate": "07/15/2015",
    "opens": "left",
    "drops": "down",
    "buttonClasses": "btn btn-sm",
    "applyClass": "btn-success",
    "cancelClass": "btn-default"
}, function(start, end, label) {
    //Here set it up to the binded component attribute.
});
```

Also,
[options](http://www.daterangepicker.com/#options) has the `locale` feature to handle the i18n.

**Comment by dangrossman** [comment]
Thanks for the help Samvel

**Comment by SamvelRaja** [comment]
(Y)

**Comment by baskarsugumar** [comment]
Thanks @SamvelRaja , But still I feel the options for locale is not helping me, can explain it with an example ?

**Comment by SamvelRaja** [comment]
@baskarsugumar  check these ember addons

[ember-bootstrap-daterange](https://www.npmjs.com/package/ember-bootstrap-daterange)
[ember-cli-daterange](https://www.npmjs.com/package/ember-cli-daterangepicker)

Both are easy to use.

Make a try.

Even i have the idea of creating my own version. Will update this thread once done
