### ISSUE TITLE
I found a bug and fixed it.(version: 2.0.2)

### ISSUE THREAD

**Issue by journey191** [dangrossman/bootstrap-daterangepicker#738]
Issue description：
1.I initialized daterangepicker and set the startDate and endDate:
![date1](https://cloud.githubusercontent.com/assets/11626700/8953931/a546824c-3614-11e5-919c-76deb96aec17.png)

2.Then I want to change the time:(I set the start time to 13:00,then the end time auto setted to 13:00,but all the minute select option became disabled.)
![date2](https://cloud.githubusercontent.com/assets/11626700/8954081/c87f1188-3615-11e5-8090-d77bb4dad941.png)
![date3](https://cloud.githubusercontent.com/assets/11626700/8954086/cfb31026-3615-11e5-9a4e-8b1d268c3025.png)

3.I set the end hour to 14 then:
![date4](https://cloud.githubusercontent.com/assets/11626700/8954087/d0103a94-3615-11e5-8807-e5ed4525ef10.png)

Then I read the js code and found what this problem was.And I fixed it with the code:
(Modified the function: renderTimePicker)

renderTimePicker: function (side) {
            var selected, minDate, maxDate = this.maxDate;
            if (this.dateLimit && (!this.maxDate || this.startDate.clone().add(this.dateLimit).isAfter(this.maxDate)))
                maxDate = this.startDate.clone().add(this.dateLimit);

            if (side == 'left') {
                selected = this.startDate.clone();
                minDate = this.minDate;
            } else if (side == 'right') {
                selected = this.endDate ? this.endDate.clone() : this.startDate.clone();
                minDate = this.startDate;
                /*  原插件Bug:
                *       在开启时间选择的情况下，如果本次更改的左边时间大于上次选择的右边时间，
                *       会导致右边的分钟minute全部被disable掉，render时右边时间和日期都会变成NaN。
                *   修改方案：
                *       如果右边时间不在最小时间之后，则将右边的时间设置为minDate 加 timePickerIncrement
                *   张政权修改 2015-07-29 start
                */
                if (!selected.isAfter(minDate)) {
                    selected = minDate.clone().add(this.timePickerIncrement, this.timePickerSeconds ? 'seconds' : 'minutes');
                    this.setEndDate(selected);
                }
                /*
                * 张政权修改 2015-07-29 end
                */
            }

            //
            // hours
            //

            html = '<select class="hourselect">';

            var start = this.timePicker24Hour ? 0 : 1;
            var end = this.timePicker24Hour ? 23 : 12;

            for (var i = start; i <= end; i++) {
                var i_in_24 = i;
                if (!this.timePicker24Hour)
                    i_in_24 = selected.hour() >= 12 ? (i == 12 ? 12 : i + 12) : (i == 12 ? 0 : i);

                var time = selected.clone().hour(i_in_24);
                var disabled = false;
                if (minDate && time.minute(59).isBefore(minDate))
                    disabled = true;
                if (maxDate && time.minute(0).isAfter(maxDate))
                    disabled = true;

                if (i_in_24 == selected.hour() && !disabled) {
                    html += '<option value="' + i + '" selected="selected">' + i + '</option>';
                } else if (disabled) {
                    html += '<option value="' + i + '" disabled="disabled" class="disabled">' + i + '</option>';
                } else {
                    html += '<option value="' + i + '">' + i + '</option>';
                }
            }

            html += '</select> ';

            //
            // minutes
            //

            html += ': <select class="minuteselect">';

            for (var i = 0; i < 60; i += this.timePickerIncrement) {
                var padded = i < 10 ? '0' + i : i;
                var time = selected.clone().minute(i);

                var disabled = false;
                
                //to make sure end time after start 2015-07-29 
                if (minDate && time.subtract(1,'minutes').second(59).isBefore(minDate))
                    disabled = true;
                if (maxDate && time.add(2, 'minutes').second(0).isAfter(maxDate))
                    disabled = true;

                if (selected.minute() == i && !disabled) {
                    html += '<option value="' + i + '" selected="selected">' + padded + '</option>';
                } else if (disabled) {
                    html += '<option value="' + i + '" disabled="disabled" class="disabled">' + padded + '</option>';
                } else {
                    html += '<option value="' + i + '">' + padded + '</option>';
                }
            }

            html += '</select> ';

            //
            // seconds
            //

            if (this.timePickerSeconds) {
                html += ': <select class="secondselect">';

                for (var i = 0; i < 60; i++) {
                    var padded = i < 10 ? '0' + i : i;
                    var time = selected.clone().second(i);

                    var disabled = false;
                    if (minDate && time.isBefore(minDate))
                        disabled = true;
                    if (maxDate && time.isAfter(maxDate))
                        disabled = true;

                    if (selected.second() == i && !disabled) {
                        html += '<option value="' + i + '" selected="selected">' + padded + '</option>';
                    } else if (disabled) {
                        html += '<option value="' + i + '" disabled="disabled" class="disabled">' + padded + '</option>';
                    } else {
                        html += '<option value="' + i + '">' + padded + '</option>';
                    }
                }

                html += '</select> ';
            }

            //
            // AM/PM
            //

            if (!this.timePicker24Hour) {
                html += '<select class="ampmselect">';

                var am_html = '';
                var pm_html = '';

                if (minDate && selected.clone().hour(12).minute(0).second(0).isBefore(minDate))
                    am_html = ' disabled="disabled" class="disabled"';

                if (maxDate && selected.clone().hour(0).minute(0).second(0).isAfter(maxDate))
                    pm_html = ' disabled="disabled" class="disabled"';

                if (selected.hour() >= 12) {
                    html += '<option value="AM"' + am_html + '>AM</option><option value="PM" selected="selected"' + pm_html + '>PM</option>';
                } else {
                    html += '<option value="AM" selected="selected"' + am_html + '>AM</option><option value="PM"' + pm_html + '>PM</option>';
                }

                html += '</select>';
            }

            this.container.find('.calendar.' + side + ' .calendar-time div').html(html);

        }

**Comment by amigrave** [comment]
I experienced a similar bug. I guess you might have better chance to make a merge proposal with english comments in the code.
