### ISSUE TITLE
setStartDate method is not working

### ISSUE THREAD

**Issue by matiishyn** [dangrossman/bootstrap-daterangepicker#739]
I need to update start date after init.

So, I have this bootstrap-daterangepicker which has default start date ( e.g. `'01/01/2000'`) and I'm doing this in Chrome console
```javascript
$($0).data('daterangepicker').setStartDate('01/01/1990');
```
nothing happened with the filed itself - I still can see previously defined startDate ('01/01/2000'), not that I've just tried to set ('01/01/1990').

But, when I click on field then in datepicker is expanded with the new date ('01/01/1990'). Then I can click somewhere else and correct startDate is set.

I've also tried similar in example page, just to make sure it was not about my app and issue is there as well

**Comment by dangrossman** [comment]
The `setDate` method changes the current start date chosen by the picker. It does not update anything else on your webpage.

**Comment by matiishyn** [comment]
Then help me please. How can I update field with JS ?

**Comment by dangrossman** [comment]
`$(field).val('text');`

**Comment by matiishyn** [comment]
but then when you focus on input and blur another values are set (startDate and endDate). Is it correct behavior?

**Comment by dangrossman** [comment]
Yes.

**Comment by matiishyn** [comment]
thanks for help
