### ISSUE TITLE
minDate field broken when using moment()

### ISSUE THREAD

**Issue by Sheepzez** [dangrossman/bootstrap-daterangepicker#740]
If minDate is set using a string, it works fine, but using moment() breaks it.

Fiddle exhibiting behaviour available here: http://jsfiddle.net/Sheepzez/zxban2wv/1/

The only difference between the two date pickers is that "minDate: moment()" is commented out in the second one.

Edit: Did some further testing, whether or not you set a startDate seems to affect the behaviour. startDate using string seems to fail, but startDate using moment() works?

It also appears that autoApply no longer hides the "Apply" and "Cancel" buttons. They seem to show no matter what.

It also appears to ignore the format field, and seems to always set the value of the text field to the "DD/MM/YYYY" format, ignoring the fact I want ""DD/MM/YYYY HH:mm", even if that's set using jQuery in the given function. 

I have it working using version 1.3.22 (version first used when I started working on my project), but the 24 hour time picker doesn't work in that version, hence me trying to update.

**Comment by dangrossman** [comment]
I'm looking into the `minDate` issue

`autoApply` has no effect if the time picker is enabled because people tend to choose the date before the time, meaning with `autoApply` on the picker would close before they're done making the selection. 

`format` was moved into the locale object in v2, so you're essentially not setting that option

**Comment by dangrossman** [comment]
The "NaN" issue appears when you specify a `minDate` that is before the `startDate`. 

In your example: `minDate: moment()` is today, while 07/01/2015 is either January 7th or July 1st, either of which is before today.

This is a bad set of settings (why do you want to set the selected start date to before the minimum selectable date?), so I'm not sure if I should take the time to do something about it.

**Comment by Sheepzez** [comment]
Apologies, I'm not sure what I was thinking this morning! I took a second look, changed over the format to be inside the locale object, and it seems to work good.

The only thing I can't seem to get right is for there to be no start date. I want my text box to be blank when the page loads in. If I don't specify the startDate then it seems to default to the minDate, and if I set it to the null then everything is NaN. Is there a proper way to do this? Or should I maybe just wipe the text box after the daterangepicker has loaded?

Thanks for taking a look at my mistakes!

**Comment by dangrossman** [comment]
The concept of there being no start date isn't supported. There's always a start and end date selected internally. If you want the text box to be blank, then yes, you'll want to make it blank explicitly.

   $('#DropOffDateTime1').daterangepicker( ... ).val('');
