### ISSUE TITLE
How to remove the default startDate?

### ISSUE THREAD

**Issue by archie18** [dangrossman/bootstrap-daterangepicker#741]
Hello,

   It seems that daterangepicker always sets a default startDate. If none is given via the options, today's date is used. I would need the calender to initialize without any date selected by default. But I still need an option to set the default starting month and year shown on initialization of the calender. I had a look at the code, but it seems there is no separation between the currently selected date and the currently shown calendar month/year.

Our use case is simple: A date input fields starts blank. Clicking it should open the calendar at a provided month/year (20 years ago), but the calendar should not automatically force the user to apply any date, unless the user explicitly selects one.

In the current implementation of the calendar, a date is always selected by default. This can possible lead to incorrect dates being entered by the user. Hiding the calendar will update the value of the input field with this default date, although the user never selected it.

Best,
Andreas

**Comment by dangrossman** [comment]
You cannot remove the default startDate. This date range picker does not meet your requirements.

**Comment by nicomollet** [comment]
I need this too, being able to provide a default month, without having to initialize startDate.

**Comment by wreardan** [comment]
I also would like this functionality.  We are using this as a date filter dropdown and initially there is no date range filter selected.  If something is pre-selected, then the user is unable to click on that date range option to filter the table.

**Comment by dexterpeters** [comment]
I would also like this functionality, if a user opens the datepicker and closes it without selecting a date the current date is selected for them.

**Comment by hbadri1** [comment]
Me too, yeah. As a workaround I clear the input manually. It seems that the whole calendar depends on start and end dates
