### ISSUE TITLE
Provide a minimized version.

### ISSUE THREAD

**Issue by StarpTech** [dangrossman/bootstrap-daterangepicker#742]

**Comment by StarpTech** [comment]
Why did you close this issue with no comment?

**Comment by dangrossman** [comment]
I use the issue tracker for bug reports, not feature requests.

**Comment by StarpTech** [comment]
This is no feature. If you provide your project via bower a minified version is essential otherwise the people who like your work have to fork it and this cannot be in the interests of you.

**Comment by dangrossman** [comment]
That's a little hyperbolic. I can do that too. This project is 3 years old with hundreds of daily clones/downloads. It's been viewed over a million times, and you're only the second person to ask for a minified version. I have a feeling most people that *have* a build process involving bower or some other package manager, can and have put bundling/minifying into their own build process.

**Comment by StarpTech** [comment]
I also have a build system which can minified such deps but I have to adapt it for this special case because I lazy load the single file. All my bower plugins delivers a minified version. I think it is more comfortable for users to have both but when it is too difficult for you then forget it. Thanks.

**Comment by chennighan** [comment]
I agree with this... It's standard practice to provide a minified version for package management systems...
