### ISSUE TITLE
show predefined range's text in the input field instead of dates

### ISSUE THREAD

**Issue by flc** [dangrossman/bootstrap-daterangepicker#745]
Hi, is it possible to show the selected predefined range in the input field instead of the dates?
For example if I have a range 'This Month' I would like to see this text in the input field instead of something like August 1, 2015 - August 31, 2015.

**Comment by dangrossman** [comment]
The name of the range clicked is one of the things passed to your callback function. That would be a good place to update your input to contain that name instead of the dates.
