### ISSUE TITLE
Using setStartDate or setEndDate does not update input field

### ISSUE THREAD

**Issue by abzainuddin** [dangrossman/bootstrap-daterangepicker#746]
When you programmatically set the start or end date using `setStartDate` or `setEndDate`, the input field will not be updated. Version 1.3.23 is the latest version where it still worked, v2.0.0 it doesn't work anymore.

In v1.3.23 in both `setStartDate` and `setEndDate` the `updateInputText` is called. It seems that in v2.0.0 this function is gone. Perhaps re-introduce `updateInputText`?

**Comment by navinova** [comment]
Set start date and set end date dont call updateInputText, how can i solve this problem?

**Comment by dangrossman** [comment]
A lot of behavior changed between v1 and v2, yes. It's not broken, it's different, and makes fewer assumptions about how your webpage is using this picker, like not assuming you want an input updated when you programmatically change the internal dates of the picker. 

Instead of `$('#el').data('daterangepicker').updateInputText()`, write `$('#el').val(start . ' - ' . end);` when you're updating the start or end date?

**Comment by abzainuddin** [comment]
I agree that fewer assumptions on how it will be used is a good thing.

It is possible to update the input element when updating the internal dates using `setStartDate` and `setEndDate` by directly editing the input element. But then again this is why `updateInputText` is quite useful. Then I can do:

```
datepicker.setStartDate(date);
datepicker.updateInputText();
```

Instead of:

```
datepicker.setStartDate(date);
$('#el').val(start.format(datepicker.locale.format) . ' - ' . end.format(datepicker.locale.format));
```

The first one is much cleaner and the second one specific internal stuff like `locale.format` is being used. Since `updateInputText` can be a public function, the internals of how the formatting and where the format is stored is abstracted away from the user. Internally Daterangepicker will also be more consistent, since there is now code duplication in the `hide` function and in the `constructor`:

```
if (this.element.is('input') && !this.singleDatePicker) {
            this.element.val(this.startDate.format(this.locale.format) + this.locale.separator + this.endDate.format(this.locale.format));
            this.element.trigger('change');
        } else if (this.element.is('input')) {
            this.element.val(this.startDate.format(this.locale.format));
            this.element.trigger('change');
        }
```

Re-add updateInputText does not make Daterangepicker assume more about how it is used, but gives it more flexibility. Can you please reconsider?
