### ISSUE TITLE
No default dates

### ISSUE THREAD

**Issue by jacksoncharles** [dangrossman/bootstrap-daterangepicker#747]
Not sure if I bug or a lack of knowledge but I am struggling to create an instance of the date range picker without populating the input fields with default values. Tried setting the input values to "" to no avail. If am I missing something I apologise if it's simply not a feature then it would be +1 from me. Stopping me from using your otherwise excellent plugin.

**Comment by dangrossman** [comment]
This works fine:

    $('#element').daterangepicker();
    $('#element').val('');
