### ISSUE TITLE
Bug: Can't properly select date range in same month

### ISSUE THREAD

**Issue by thedeeno** [dangrossman/bootstrap-daterangepicker#748]
1) On the demo page open the first example
2) Set start/end calendar to the same month
3) Select a start date on the left calendar
4) Select an end date on the right calendar
5) Observe the right calendar switch to the next month and the range only show on the left calendar.

I'm assuming this is a bug. It looks like this bug was introduced in v2 since v1 doesn't appear to have this problem. Any thoughts on what part of the codebase might be causing this issue? I can investigate.

**Comment by dangrossman** [comment]
This is not a bug.

**Comment by thedeeno** [comment]
Hmm, I watched a couple of users fumble around this morning with this behavior. The surprise could probably be alleviated by preventing a user from selecting the same month for the left/right calendar.

Are there hooks I can leverage to implement this in my app? Looking at the docs I don't see any events triggered when a month is changed.

Thanks for you work on this library!

**Comment by dangrossman** [comment]
No there are no hooks. You have the code, you can make it work however you'd like.

**Comment by thedeeno** [comment]
Should I consider rolling my extensions into a PR? Or are these hooks not worth it?

**Comment by christophior** [comment]
Would you mind sharing your extension for selecting dates in the same month @thedeeno? Thanks!
