### ISSUE TITLE
Bug: Can't select range when starting from right calendar

### ISSUE THREAD

**Issue by thedeeno** [dangrossman/bootstrap-daterangepicker#749]
1) On the demo page, open the first example
2) Select a date on the right calendar
3) Select a data on the left calendar

Expected:
A range to be selected using the left/right as start/end

Actual:
The end date is deselected, the range is reset, and only the start date is selected.

**Comment by dangrossman** [comment]
Your expected result differs from how the date range pickers at all major travel sites and reporting systems works. The first click selects the start date. The second click selects the end date. If your second click is on an earlier date than your first click, the start date gets moved to that selection.
