### ISSUE TITLE
Question: Event fired when click on and then off

### ISSUE THREAD

**Issue by Sheepzez** [dangrossman/bootstrap-daterangepicker#750]
JSFiddle example of behaviour: http://jsfiddle.net/L0Lu5e1b/1/

I start off with a daterangepicker, and I click on it, then I click off it. The input gets set to the specified format, but no event is triggered. Is there any way I can control this behaviour?

Ideally I want the daterangepicker to not do anything if nothing is explicitly chosen, but if I can use an event handler to control it then that's fine too.

What are my options here?

Many thanks!

**Comment by dangrossman** [comment]
You can use the hide event.

http://www.daterangepicker.com/#events
