### ISSUE TITLE
hour limit

### ISSUE THREAD

**Issue by Zane-XY** [dangrossman/bootstrap-daterangepicker#751]
Is there a way to limit the selectable hours in Timepicker? I only want the user to be able to select a few specific hours, how should I do that?

**Comment by dangrossman** [comment]
There is not a way to limit the selectable hours. You'll have to make that customization yourself.

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L798

**Comment by Zane-XY** [comment]
would it cause any problems if I remove those options from the hourselect using jquery?

**Comment by dangrossman** [comment]
No, but I don't think that would be an effective solution. The UI is re-rendered often as the user interacts with it.

**Comment by Zane-XY** [comment]
Is there a render event I can listen to?

**Comment by Zane-XY** [comment]
created pull request: https://github.com/dangrossman/bootstrap-daterangepicker/pull/752
