### ISSUE TITLE
Hour 0 changes to 12 for timePicker24Hour

### ISSUE THREAD

**Issue by enumag** [dangrossman/bootstrap-daterangepicker#754]
Steps to reproduce:

1) Go to the [Configuration Generator](http://www.daterangepicker.com/#config)

2) Put this configuration to the text area:

```js
$('#config-demo').daterangepicker({
    "singleDatePicker": true,
    "timePicker": true,
    "timePicker24Hour": true,
    "locale": {
        "format": "MM/DD/YYYY hh:mm",
    }
});
```

3) Select hour 0 and click "Apply".

The time in the input has hour 12 instead of 0.

**Comment by dangrossman** [comment]
That's correct according to the date format you requested. "hh" is 12 hour time.

**Comment by enumag** [comment]
Interesting, thanks for your help. Where can I find documentation about format though?

**Comment by enumag** [comment]
Never mind, foung it in the documentation of moment.js.
