### ISSUE TITLE
Selection of a period is confusing

### ISSUE THREAD

**Issue by ReinierGielen** [dangrossman/bootstrap-daterangepicker#756]
When I select a start date all is fine.
Then I select a end date in the second calendar. The period is colored light blue. All Fine.

Then I decided to change my start date e.g. with 1 day. So I click that date in the left calendar.

What happens is that it selects the new startdate and it deselects the enddate. So I have to reselect the enddate. That is not very user friendly.

The same happens when I change the enddate.

**Comment by dangrossman** [comment]
This is how all the other date range pickers I could find work. First click selects the start of the range, second click selects the end.

**Comment by ReinierGielen** [comment]
Well yes that is logical.
But does that need to be that a third click resets all ?

The previous versions 1.3.x etc did not work like that.
There a click in the left calendar selected the start and a click in the right calendar selected the end.
Very simple, very nice.

Why did it have to change ?

**Comment by dangrossman** [comment]
It changed because that was inconsistent with all the other date range pickers on the web. What matters is what will confuse end users, not what will confuse developers that used DRP 1.x when it was confusing.

**Comment by ReinierGielen** [comment]
True.

**Comment by ReinierGielen** [comment]
I'll put it to the user then.

**Comment by dangrossman** [comment]
You can always still use 1.3 if you prefer. Call it the "stable branch" if necessary ;)
