### ISSUE TITLE
Dateformat MMM doesnt work in 2.0.7

### ISSUE THREAD

**Issue by rfinquiron** [dangrossman/bootstrap-daterangepicker#761]
Dateformat MMM doesnot work in this version.
I want to show "09 Aug 2015"
I had version 1.2 and it worked well, but it doesnt work for version 2.0.7
    format: 'DD MMM YYYY',

**Comment by dangrossman** [comment]
The format option is part of the locale object in v2.

**Comment by dangrossman** [comment]
https://gist.github.com/dangrossman/89a40223f5a8a892fbf1#file-drp-example-2-js

**Comment by rfinquiron** [comment]
Thanks
