### ISSUE TITLE
latest version not reflecting programmatic update to start/end values

### ISSUE THREAD

**Issue by daimeng** [dangrossman/bootstrap-daterangepicker#764]
upgraded from 1.3 to 2.0.8, because of month arrow bugs. Setting start and end date after init is no longer reflecting in text fields. The val() of the text field is only updated once on creation and when hiding calendar, so now I am wrapping my setStartDate and setEndDate with a picker.isShowing = true followed by picker.hide().

**Comment by dangrossman** [comment]
That's one option. You can also update your input box in the same code where you update the start and end date.
