### ISSUE TITLE
single datepicker and date format issue

### ISSUE THREAD

**Issue by dharmesh019** [dangrossman/bootstrap-daterangepicker#765]
Hi,
I was just using dateformat 'DD/MM/YYYY'  instead of MM/DD/YYYY as below but it does not work when i try to enter the date directly in textbox instead of selecting the date from datepicker. it is selecting wrong date in datepicker.

 $('input[name="daterangeForOverlay"]').daterangepicker({
            singleDatePicker: true,
            showDropdowns: true,
            locale: {
                format: 'DD/MM/YYYY'
            }
        },
    function (start, end, label) {
        var years = moment().diff(start, 'years');
        //  alert("You are " + years + " years old.");
    });
please see attached screenshot.
![image](https://cloud.githubusercontent.com/assets/2424276/9186584/cba50d4c-4009-11e5-968e-9ad18c624446.png)

**Comment by Shorang** [comment]
I think think this code need to be fixed: 
```java
if (this.singleDatePicker || start === null || end === null) {
    start = moment(this.element.val(), this.locale.format).utcOffset(this.timeZone);
    end = start;
}
```
The `utcOffset` is pushing the more timezones than the original. `this.timeZone` is pointing to the default offset timeZone and the `moment(this.element.val(), this.locale.format)` points to another offset.

In my case was: 
`this.timeZone = -180` (standard daylight savings)
`moment(this.element.val(), this.locale.format) = -120` (Summer Daylight Saving)

you need to test if the date is UTC time
```java
if (this.singleDatePicker || start === null || end === null) {
    var offset = 0;
    start = moment(this.element.val(), this.locale.format);
    if(start.isUTC()){
        start = start.utcOffset(this.timeZone);
    }
   end = start;
}
```

PS.: I'm setting my default momento.js locale to pt-br
`moment().locale('pt-br');`

**Comment by dangrossman** [comment]
Does the bug exist when you don't have a locale set on the moment object? `utcOffset` is called any time user input is parsed, and AFAIK this is the first bug report of that causing trouble. I'd like to know if there's something more to it, or maybe it's just that few people use the timezone setting.

**Comment by Shorang** [comment]
Yes, 
Try on http://www.daterangepicker.com/ go to Configuration Generator, then check singleDatePicker

type the date 11/11/2013 --> hit tab --> hit shift+tab --> hit tab

**Comment by dangrossman** [comment]
Those steps don't produce any bug for me; only the typed date is highlighted.

**Comment by Shorang** [comment]
![daterangepicker](https://cloud.githubusercontent.com/assets/2739881/9473974/2686425a-4b34-11e5-9145-bb5f95e60597.gif)

**Comment by dangrossman** [comment]
I see it, but it doesn't do that in my browser...

**Comment by Shorang** [comment]
The problem is the timezone. I changed it to Seattle's timezone and the problem disappeared. 
Try your timezone to GMT -3

**Comment by herlon214** [comment]
@Shorang , can you show me the final code?

I'm with the same problem, here is the code:
```javascript
// Date time picker
    $('.datetime-picker').daterangepicker({
      singleDatePicker: true,
      "showDropdowns": true,
      showDropdowns: true,
      "timePickerSeconds": true,
      "timePicker": true,
      timePicker24Hour: true,
      "locale": {
        "format": "YYYY/MM/DD",
        "separator": "-",
      }
    });
```

**Comment by dangrossman** [comment]
"Fixed" by removing the `utcOffset` calls everywhere. If someone wants everything in a different time zone than the user's computer, you can set a time zone globally on the moment object rather than through this date picker. Or, as Improvely does, handle time zone offsets entirely server-side.

**Comment by itsazzad** [comment]
Is that problem again arising? I am having issue with the format. Its always MM/DD/YYYY although I want DD/MM/YYYY

**Comment by itsazzad** [comment]
After updating to the latest its working now :+1:

**Comment by newshagithub** [comment]
i want to have a year range picker. i mean just year. any idea?

**Comment by sydjaff** [comment]
is there any possibility to show only months and year in daterangepicker.
I'm stuck in this scenario
