### ISSUE TITLE
AM/PM error

### ISSUE THREAD

**Issue by FlorisMoriceau** [dangrossman/bootstrap-daterangepicker#767]
Hi folks, 

I'm using daterangepicker in a French project.
We don't use AM / PM in our time notation, and I need hours and minutes in my range.
So I set my time format this way : 'DD/MM/YYYY hh:mm',

Here is the issue : 
When I select a date, combined with a timePicker (timePicker24Hour set as true) and select for instance "10/08/2015 18:00", the input field (left and/or right sides) rewrite this date as 10/08/2015 6:00.

I tried to debug each of the functions called in the file, but I can't figure out where this rewriting is done.

Here is the code : 

```javascript
$(function(){
	$('#daterange').daterangepicker({
		showDropdowns:			false,
		timePicker:				true,
		timePicker24Hour:		true,
		timePickerIncrement:	15,
		locale:	{	firstDay:		1,
					separator:		' - ',
					format:			'DD/MM/YYYY hh:mm',
					applyLabel:		'OK',
					cancelLabel:	'Annuler',
					fromLabel:		'De',
					toLabel:		'à',
					daysOfWeek: [	'Dim','Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
					monthNames: [	'Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'	]	},
		minDate:				'01/07/2015 00:00',
		maxDate:				'01/07/2016 00:00',
		buttonClasses:			'btn btn-sm',
		applyClass:				'btn-success',
		cancelClass:			'btn-default',
		drops:					'down',
		opens:					'left'
	});
});
```

Is that a real bug ? Or did I miss a config option ?

Thx

**Comment by dangrossman** [comment]
"hh" is the format token for 12 hour time. You want "HH".

http://momentjs.com/docs/#/parsing/string-format/

**Comment by FlorisMoriceau** [comment]
Gosh...

You saved my life.
