### ISSUE TITLE
Predefined Ranges DateRangePicker Model ,select 'today' not change

### ISSUE THREAD

**Issue by jiao34367** [dangrossman/bootstrap-daterangepicker#769]
Hello,
I am using daterangepicker and feedback a question:
### and ,the first time open the dropMenu,choose 'Today'

![daterangepicker1](https://cloud.githubusercontent.com/assets/8828117/9268688/542dca78-4294-11e5-9490-534a7ed63cf8.jpg)
## after click,the show is not change :
![daterangepicker3](https://cloud.githubusercontent.com/assets/8828117/9268790/087c4ebe-4295-11e5-9587-00aed776095d.jpg)

**Comment by dangrossman** [comment]
Because no `startDate` or `endDate` settings were specified, they default to "today". Opening and closing the date range picker without changing the selected dates will not trigger the callback function to fire.
