### ISSUE TITLE
Datepicker don't allowing empty values

### ISSUE THREAD

**Issue by Shorang** [dangrossman/bootstrap-daterangepicker#771]
Sometimes, when you have some optional date fields, you need to leave the field blank, but the single datepicker aways fill the values.

How to reproduce: 

Go to the single date picker example on http://www.daterangepicker.com/ 
erase the value, hit tab.

**Comment by lennyk** [comment]
I ran into this problem today as well. I found the author has previously suggested to [clear the value on init](https://github.com/dangrossman/bootstrap-daterangepicker/issues/724#issuecomment-123809298).

**Comment by dangrossman** [comment]
You can now set `autoUpdateInput: false` in your settings to manually handle updating your input when dates cahnge, so that it can be cleared.

**Comment by richard-rhsr** [comment]
Well, that does not address the problem, it only makes the plugin almost useless: the user can then throw any invalid data on the input.

What would be nice is an option allowEmpty: true, to allow either for valid dates or an empty string to be considered valid data. 
I'm currently trying to workaround the internal event handling and related internal state modifying methods to allow for this possibility.

**Comment by dangrossman** [comment]
The user can put invalid data in the input no matter what javascript code you write. Thanks for calling the plugin almost useless, feels great. BTW, have you considered following the "input initially empty" example from the site, and adding a change event to the text input and validating what's in there yourself as well?

**Comment by richard-rhsr** [comment]
Whoa, re-reading my comment, it actually can be interpreted as if I'm calling the plugin "almost useless". Sorry!
I was actually referring to setting `autoUpdateInput: false`, which really diminishes the plugin functionality. Sure, the user can turn off JS or hack the plugin functionality, no front-end validation can be relied upon as a security measure. But this plugin does indeed a really nice job in only allowing valid dates in the the form field, preventing typos and manifold date formats.

Yes, I checked the example "input initially empty", but it didn't address the possibility of allowing deleting the date in the field (in the case of an optional field that I don't want filled anymore).

And yes, I'm currently messing with the event handlers to allow this kind behavior, trying to fallback into default behavior whenever there is some data in the text field. I will try to format this functionality internally to the plugin, allowing it through a `allowEmpty: true` flag, and send this as a PR, if you don't mind.
Again, sorry for my bad tone, in no way I was calling this repo useless at all.

**Comment by dangrossman** [comment]
> Yes, I checked the example "input initially empty", but it didn't address the possibility of allowing deleting the date in the field (in the case of an optional field that I don't want filled anymore).

That example actually adds a "clear" button to the dropdown which deletes the date in the field. You can also delete whatever's in the field manually and it stays empty.

**Comment by rodiojp** [comment]
if input value is "", daterangepicker can be initialized with an empty value this way:

`    var $dateFrom = $('#dateFrom');
    var dateFromVal = $dateFrom.val();
    $dateFrom.daterangepicker({
        // autoUpdateInput: false,
        singleDatePicker: true
    });
    $dateFrom.val(dateFromVal);`

**Comment by Roman86** [comment]
here's how I solved it in 3 steps:
(in the code below I assume `$inp` is our daterangepicker input, jquery object)
1. in the value change callback (cb argument, which goes right after options) we reset the flag:
```
$inp.daterangepicker({}, function(start, end, label){
    $inp.data('drp_empty', false); // means value was SET
});
```
2. add event handler for "change", "input", "keyup" (whatever else makes sense when you adjust/reset the value manually). In this handler you check if value *erased* and remember it (one way):
```
        $inp.on('change input keyup', function() {
            if (!$inp.val()) { // only if empty. Means value ERASED. If there is any value - we ignore it
                $(this).data('drp_empty', true); // remember our empty state (until reset again in cb)
            }
        });
```
3. add handler for "blur" event
```
        $inp.on('blur', function() {
            if ($inp.data('drp_empty')) { // means we were erasing it
                $(this).val(''); // so we force erasing it
            }
        });
```
