### ISSUE TITLE
[Feature request] left calendar for startDate and right calendar for endDate

### ISSUE THREAD

**Issue by levinzz** [dangrossman/bootstrap-daterangepicker#773]
Sorry if this was asked already, I couldn't find any similar request.

I'd like to have the left calendar be used for selecting only the start of the range and the right calendar be used only for the end of the range.

When you click on a date in the left calendar, it always updates the startDate no matter if a startDate is already selected or not. (The same applies to the right calendar with endDate)

I know this could be achieved with two separate datepickers but then I don't get all the bells and whistles that you implemented in this one (buttons, timepickers, range highlighting, ...)

Is there a way to make it work like that ?

**Comment by dangrossman** [comment]
Download v1

https://github.com/dangrossman/bootstrap-daterangepicker/releases/tag/v1.3.23
