### ISSUE TITLE
what's new in v2?

### ISSUE THREAD

**Issue by epikhighs** [dangrossman/bootstrap-daterangepicker#775]
Hi,

I can't seem to find a changelog or what the breaking changes are in v2.  Anything I should know before upgrading from 1.3.x?

Thanks.

**Comment by dangrossman** [comment]
Some of the option names and defaults changed. The format option moved into the locale object. If attached to a text input, the input is filled in when you create the date picker. The setOptions method is gone. Setting the start/end date is no longer accomplished by clicking on the left versus right calendar, but by what order you click on dates in either calendar. The selected date range is highlighted. Bootstrap 2.x support was dropped. Many bugs were fixed. The code was completely rewritten. The widget looks different with elements in different places than before. There's a new configuration generator. That's all I can remember off the top of my head.

**Comment by epikhighs** [comment]
nice.  thanks!

**Comment by jwhitmarsh** [comment]
What should we use in place of `setOptions` if we need to?

**Comment by dangrossman** [comment]
Call `$.daterangepicker(options)` again with your new options

**Comment by jwhitmarsh** [comment]
:+1: thank you :)
