### ISSUE TITLE
No clock icon on singleDatePicker and timePicker

### ISSUE THREAD

**Issue by levinzz** [dangrossman/bootstrap-daterangepicker#779]
![image](https://cloud.githubusercontent.com/assets/10078646/9438371/7e9cc702-4a5d-11e5-8639-548ad0b743e5.png)

As you can see in the screenshot, the clock icon is missing when selecting the options "singleDatePicker" and "timePicker"

**Comment by dangrossman** [comment]
That's true. I'm probably not going to do anything about it personally... there was never a clock icon in v1 anyway.
