### ISSUE TITLE
Automatically publish Meteor package

### ISSUE THREAD

**Issue by oskarszoon** [dangrossman/bootstrap-daterangepicker#780]
Hi there,

Could you setup something to automatically (or manually) publish the latest version of your package for Meteor?

Thanks in advance

**Comment by dangrossman** [comment]
I don't know anything about Meteor or publishing packages.

**Comment by oskarszoon** [comment]
@dangrossman Oh sorry, I assumed you were publishing these because they are published under your name, sorry about that. I'll try and find the right person
