### ISSUE TITLE
When selecting the end date the calendars go back to the start date

### ISSUE THREAD

**Issue by pedrocatre** [dangrossman/bootstrap-daterangepicker#781]
Maybe this is an intended behaviour but I would like to understand why it happens because to me it is confusing and I believe it can be confusing for users as well. The user chooses the start date then he moves the second calendar to pick the end date (to see this it you can't have consecutive months, the interval needs to be bigger), when he clicks on the end date everything is correctly selected but the view on the calendars jumps back to show him the start date. When that happens the user needs to check the top inputs to make sure he selected the correct end date which is not very intuitive and harder than just looking at what he just selected for the end date.

Is this behaviour intended? Would it not be better to not have this jump in the calendars and just leave the user in the month of the end date when he selects it?

**Comment by dangrossman** [comment]
The behavior is intended. For another date range picker that also jumps back to display your start date like that, check https://www.google.com/flights or http://www.hotels.com. It might be less jarring if you enable `autoApply` so that the picker closes after you've selected a range.
