### ISSUE TITLE
Time only support

### ISSUE THREAD

**Issue by rmeschian** [dangrossman/bootstrap-daterangepicker#782]
I noticed the plugin has the ability to select time and date, or date only, but I didn't notice a way to do time only.  I want to use this same plugin to do time selection as single and range values.

Seems like it's just a matter of shutting off the date UI with some if statements.  What do you think?

Thanks for a great plugin.

**Comment by dangrossman** [comment]
I think it's quite a bit more than just hiding UI. The code would be strewn with new conditionals to handle this new mode. You have to think about its interaction with all possible values of the other 25 settings, everywhere in the code. Tons of extra complexity to maintain something that doesn't even resemble the original purpose of this widget. And the UI won't look like anything you want on your site if you simply hide the calendar portion. This isn't something I want to maintain. Do what 99% of sites do and use two `<select>`s to choose time, or load a separate time picker thing.
