### ISSUE TITLE
There is no way to have no date selected in the range picker

### ISSUE THREAD

**Issue by pedrocatre** [dangrossman/bootstrap-daterangepicker#783]
As far as I can tell the date range picker always needs to have a date selected, if we provide none it will just provide its own. This makes it unsuitable for certain use cases.

Example if the date range picker is a filter that can be applied, then before it is applied it should have no value and just say "Select range" or something like that.

Does this make sense?

**Comment by dangrossman** [comment]
There is always a date range selected internally to the date range picker widget, yes.

That doesn't mean your own application needs to always have a date range selected.

You can write "Select range" wherever you want. If you're attaching the daterangepicker to a text input and don't want it automatically filled in with a date range, use the `autoUpdateInput: false` option and handle changes in your callback function.

**Comment by pedrocatre** [comment]
I could do that sure. But when the user opens the date range picker in that case he will see a date range pre selected which is wrong and confusing.

**Comment by melgish** [comment]
Came here looking for similar options. In my case I need 4 possible conditions

a discrete date range: 
   i.e. start = 1/28/1969, end = 2/13/1969
from start date until the end of time:
   i.e. start = 1/28/1969, end = null
from beginning of time until end date:
   i.e. start = null, end = 2/13/1969
all of eternity:
   i.e. start = null, end = null

**Comment by dangrossman** [comment]
Unfortunately this is not the widget for you.

**Comment by tcs-apeters** [comment]
In an earlier version it was possible to have "no date". Our initial values are always null and it must be possible to reset them to null again. Now, the initial value is always set to now(). We are using the daterangepicker with the setting singleDatePicker:true. To have a possible "null" value back would be great.

Also, maybe it is possible to change the default local.format setting to:
 this.locale = {
            format: moment.localeData()._longDateFormat.L,
}

**Comment by dangrossman** [comment]
Hi @tcs-apeters, did you read the first reply in this thread? Set `autoUpdateInput: false` in your options and your text box can remain empty. Nothing changed internally (there was *always* a start and end date selected, back to the very first release).

**Comment by tcs-apeters** [comment]
Thanks for your quick response. Yes, I am using autoUpdate: false and the event 'apply.daterangepicker' now, which solved my problem.

**Comment by CassianoViana** [comment]
Hi, 
In my case I wanna have no range selected. How you can see the "Hoje" == "Today" word is selected. autoUpdate: false does not work for me. Im done something wrong way? Thanks!

![screenshot from 2017-05-31 14-48-00](https://cloud.githubusercontent.com/assets/6260991/26645932/3058af4c-4610-11e7-80cb-1d09d8388724.png)

**Comment by dangrossman** [comment]
The comments above that you replied to are very clear. There is always a date range selected internally. If you don't provide one, it'll be today to today.
