### ISSUE TITLE
Allow to pass the callback function as a configuration parameter

### ISSUE THREAD

**Issue by Radagaisus** [dangrossman/bootstrap-daterangepicker#784]
Doing so would allow a cleaner syntax for long configuration options:

```javascript
$('#date-range').daterangepicker({
  callback: this.render,
  showDropdowns: true,
  autoApply: true,
  linkedCalendars: false,
  parentEl: '.stage',
  opens: 'center',
  startDate: this.options.start_date,
  endDate: this.options.end_date,
  maxDate: moment(),
  ranges: {
    'Today': [moment(), moment()],
    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
    'Last 7 Days': [moment().subtract(6, 'days'), moment()],
    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
    'This Month': [moment().startOf('month'), moment().endOf('month')]
  }
});
```

**Comment by dangrossman** [comment]
What's "cleaner" about that? All it does is add 10 additional characters.

$('#date-range').daterangepicker({
      callback: this.render,
      showDropdowns: true,
      autoApply: true,
      linkedCalendars: false,
      parentEl: '.stage',
      opens: 'center',
      startDate: this.options.start_date,
      endDate: this.options.end_date,
      maxDate: moment(),
      ranges: {
        'Today': [moment(), moment()],
        'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
        'Last 7 Days': [moment().subtract(6, 'days'), moment()],
        'Last 30 Days': [moment().subtract(29, 'days'), moment()],
        'This Month': [moment().startOf('month'), moment().endOf('month')]
      }
    }, this.render);

**Comment by Radagaisus** [comment]
@dangrossman 

- This library exposes a lot of configuration options, which is great, and allows it to meet demands of different applications. Usually though, end-developers need their own set of "global" default configuration options they want to share through all their date range pickers, and they end up writing their own wrapper or factory methods to help with that. In this case, putting all configuration options, including the callback method, in just one options object is beneficial. (Another approach is to offer a global singleton defaults object).

- If there are several callback methods (say, callbacks for all events), it will look much clearer and easier to manage if all of them will be part of the configuration object.

- It will look much clearer, aesthetically, in CoffeeScript, where callback functions after a long options object look like floating eels.
