### ISSUE TITLE
Start date and end date in seperate calendars

### ISSUE THREAD

**Issue by rolandsusans** [dangrossman/bootstrap-daterangepicker#785]
Hi, 
I was confused by how date picker acts : 
![dc906c74eed4a3cd8195aa7c40db90f02](https://cloud.githubusercontent.com/assets/6154604/9514695/00a5beae-4ca5-11e5-849d-171b57164911.png)

Even more when i tried to look at choices available in right calendar i got: 
![2a3d0360d60794e9d345e03e96789aed](https://cloud.githubusercontent.com/assets/6154604/9514782/a30964fc-4ca5-11e5-85a2-34b880480606.png)

I expected to choose startDate in leftCalendar, and endDate in right calendar, like in this example:
![ca6a8c88607850c7a4d7b697c7c464eb](https://cloud.githubusercontent.com/assets/6154604/9514734/498538e8-4ca5-11e5-9c24-b70e92c707a8.png)

Is there a way to force DateRangePicker to expect startDate selection in left calendar, and endDate right calendar? 

btw i'm using [react wrapper](https://github.com/quri/react-bootstrap-datetimepicker) with following code:
```javascript
 <DateRangePicker className={'datePicker'}
                                     onEvent={this.handleDate}
                                     startDate={this.state.startDate}
                                     endDate={this.state.endDate}
                                     minDate={this.state.minDate}
                                     maxDate={this.state.maxDate}
                                     ranges={this.state.ranges}
                                     timePicker={true}
                                     linkedCalendars={false}
                                     timePicker24Hour={true}
                                     showWeekNumbers={true}
                                     locale={this.state.localTranslations}
                                     opens={'right'}
                        >
```
For me looks like this behavior comes from this library, because at [daterangepicker.com](http://www.daterangepicker.com/), you can see the same:
![aa](https://cloud.githubusercontent.com/assets/6154604/9514952/c036a958-4ca6-11e5-85e0-bdec0db522db.png)

Is that normal behavior, of daterangepicker.com ? Maybe i'm missing some param ?

**Comment by dangrossman** [comment]
Yes, this is normal behavior. This is how most date range pickers on the web work. If you want the start and end dates to be chosen on different calendars, then I suggest using two inputs and a single date picker attached to each.

**Comment by janetwu** [comment]
I find out that version 1.3.21 of daterangepicker.js works,so I have to choose the old version instead of the latest one.

**Comment by dedanirungu** [comment]
Why can this be a setting for all new version so that if someone prefer to separate the calendars they can can do so by changing setting.

**Comment by dedanirungu** [comment]
I am forced to use an older version (1.3.21) in order to achieve this behaviour.
