### ISSUE TITLE
autoUpdateInput issue

### ISSUE THREAD

**Issue by Toccata6767** [dangrossman/bootstrap-daterangepicker#788]
I'm trying to implement a single date picker.

With autoUpdateInput set to true (default behavior), the textbox will always have a date. You can change the date with manual entry or via the calendar and it automatically populates the textbox. There is no way to make it a blank value. By default it loads the current date.

With autoUpdateInput set to false, the textbox can be blank, but selecting a date from the calendar no longer works. Only manual entry will put a date into the field.

I don't think that is the intended behavior is it? I think the page should be able to load with a blank value and then allow entry either manually or from the calendar, unless I'm mistaken.

**Comment by dangrossman** [comment]
This is the intended behavior. When you set `autoUpdateInput` to false, your input will not be automatically updated. You have to update it yourself, which you can do in a callback function. Your callback is invoked any time the selected date changes. 

Examples:
http://www.daterangepicker.com/#usage
http://www.daterangepicker.com/#ex3
