### ISSUE TITLE
Date format localisation.

### ISSUE THREAD

**Issue by ipbebnev** [dangrossman/bootstrap-daterangepicker#789]
Hello. Can you write resolving the problem? I use such the format of date:
      locale: {
       format: 'DD MMMM YYYY'
      }

But i'm from Russia and my months named that:

if ($d=="Jan") echo "Январь";
if ($d=="Feb") echo "Февраль";
if ($d=="Mar") echo "Март";
if ($d=="Apr") echo "Апрель";
if ($d=="May") echo "Май";
if ($d=="Jun") echo "Июнь";
if ($d=="Jul") echo "Июль";
if ($d=="Aug") echo "Август";
if ($d=="Sep") echo "Сентябрь";
if ($d=="Oct") echo "Октябрь";
if ($d=="Nov") echo "Ноябрь";
if ($d=="Dec") echo "Декабрь";

$d means month (MMMM in format)

How i can translate MMMM to my Russia format across the callback function? Thanks.

**Comment by ipbebnev** [comment]
Also, there are have a some method to translate it all the interface to other language?

**Comment by dangrossman** [comment]
Check out the configuration builder:

http://www.daterangepicker.com/#config

Check off "Locale (with example settings)" to see how to translate all text in the interface.

**Comment by ipbebnev** [comment]
Thanks
