### ISSUE TITLE
Select year and month not working on FF

### ISSUE THREAD

**Issue by looc** [dangrossman/bootstrap-daterangepicker#790]
When placing a textbox inside a modular windows (bootstrap3-dialog) and binding daterangepicker to it year and month select will not show on FF (40.0.3) , IE and chrome works fine.

https://github.com/nakupanda/bootstrap3-dialog

**Comment by dangrossman** [comment]
Feel free to submit a PR with a fix. I will not be investigating this. Currently on vacation, and won't have the time when I get back either.
