### ISSUE TITLE
Bootstrap Popover - Position not correct

### ISSUE THREAD

**Issue by tcs-apeters** [dangrossman/bootstrap-daterangepicker#791]
I am using the daterangepicker within a Bootstrap Popover, but I cannot get the correct position of the daterangepicker. When I use the 'body' as parentEL and I scroll to the right, the daterangepicker is out of the popover dialog. When I use a custom parentEL the position is not correct as well. The top, left and right attributes are not calculated correct. In version 1.3.18 I did not have this problem. Any idea or hint for me?

**Comment by dangrossman** [comment]
No, I have no idea.
