### ISSUE TITLE
Empty date

### ISSUE THREAD

**Issue by ehhc** [dangrossman/bootstrap-daterangepicker#793]
It would be nice to have the possibility to not select a date at all. Especially if a single date picker is used there are different use cases where it would be useful to give the user the possibility not to select a date (e.g. if the date represents the date of an event that might not happened yet).

**Comment by chillyistkult** [comment]
Yes that would be really nice. The "Clear" button hack described in the docs isn't a good solution.

**Comment by superdummy** [comment]
+1: Just searched exactly for this feature. Would be really great to have this feature. There are alot of use cases where this makes sense. Thanks very much!

**Comment by ehhc** [comment]
Yes, as i said, i think this would be a nice and usefull feature too.
As you see i've commited a fix for this problem and i hope @dangrossman  will accept my pull request and merge my changes (or an other solution) into the official code base.
Until then you're welcome to use my fork.

**Comment by pascalmartin** [comment]
+1: I also need this functionality

**Comment by legrego** [comment]
+1: this would be great

**Comment by dangrossman** [comment]
This date picker appears to support no date selected. This one seems a better fit for your needs:

http://eternicode.github.io/bootstrap-datepicker

**Comment by chillyistkult** [comment]
@dangrossman it's not really helpful to just point to another repository. There are dozens of other datepickers that support this feature, but we bring it up here for a reason.

**Comment by superdummy** [comment]
Hello @dangrossman

I spend considerably amount of time trying to find and evaluate all (bootstrap/jqurey compatible) date and time(!) pickers and ended up with yours.
I am not Gartner, but you are in the magic quadrant on the top right corner! Leader in functionality and(!) UX. I know the other pickers but they all had major lack in functionality (time picker) or a bad UX. And take this as a big kudos! Your coding and UX skills are the best! 

Everone who +1 and also the first poster who even wrote a patch, showed interest in making your cool plugin even more cooler. And the Number of +1 in such a short amount of time shows how important this feature is. From an UX standpoint for a Single Date Picker this is one of the most fundamental UX-Patterns, as empty means, you as a user,  have to do something...  

Please think about it, it will make your plugin even more better and the world too.

**Comment by alexdd55** [comment]
:+1:

**Comment by uniteddevelopers** [comment]
@alexdd55 and all that are coming to this ticket: Very good news. DateRangePicker now supports empty Dates. See this ticket and the answers from dangrossmann: 
https://github.com/dangrossman/bootstrap-daterangepicker/issues/815

**Comment by ehhc** [comment]
@uniteddevelopers  thank you for sharing your solution. But i do not believe this to be very intuitive. For me it seems to be a hack. My "patch" uses nearly the same solution but uses a own option to initialize it so that the behaviour of the datepicker is understandable for people who might maintain my code. 
I do not understand why @dangrossman says my solution is a "hack" and then uses a similar but not intuitive solution...
