### ISSUE TITLE
Input text is not updated 

### ISSUE THREAD

**Issue by kobalka** [dangrossman/bootstrap-daterangepicker#795]
Input text is not updated when dates are change programmatically by calling setStartDate/setEndDate.  

This is because the code which updates input text is executed if and only if the dialog becomes hidden  

```javascript 
hide: function(e) { ...

//if picker is attached to a text input, update it
if (this.element.is('input') && !this.singleDatePicker && this.autoUpdateInput) {
	this.element.val(this.startDate.format(this.locale.format) + this.locale.separator + this.endDate.format(this.locale.format));
	this.element.trigger('change');
} else if (this.element.is('input') && this.autoUpdateInput) {
	this.element.val(this.startDate.format(this.locale.format));
	this.element.trigger('change');
}
...
}
```

Plugin should expose a method to update text input or should update input text after each change.

**Comment by dangrossman** [comment]
I'm not sure if I agree. I'll consider it next time I have a chance to work on this thing. Regardless, wherever you're calling `setStartDate`/`setEndDate`, you can also update your input if you wish. `$('#yourelement').val('your text')`...

**Comment by kobalka** [comment]
I did a pull request for that, have a look.

**Comment by hemavidal** [comment]
For input tag is ok but for a div, like in example, is not refreshing the text.

<div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%">
    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
    <span></span> <b class="caret"></b>
</div>

<script type="text/javascript">
$(function() {

    function cb(start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    }
    cb(moment().subtract(29, 'days'), moment());

    $('#reportrange').daterangepicker({
        ranges: {
           'Today': [moment(), moment()],
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Last 7 Days': [moment().subtract(6, 'days'), moment()],
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
    }, cb);

});
</script>

**Comment by dangrossman** [comment]
That's never going to be automatic. There's no way for the picker to know you want to replace the contents of some arbitrary HTML element with a date. When it's not attached to an input element, most of the time it's attached to something more complex than a div with nothing in it but text.

**Comment by hemavidal** [comment]
OK, 
i will try with a input tag! 
Thanks!

**Comment by hemavidal** [comment]
Its done,

the text is the span tag which is updated in cb function :

function cb(start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    }

I just called "cb" to change the text of the dateRangePicker!
