### ISSUE TITLE
By default selection is always Today!

### ISSUE THREAD

**Issue by saubi1993** [dangrossman/bootstrap-daterangepicker#797]
How to change by default selection when pop up opens?

**Comment by dangrossman** [comment]
Set the `startDate` and `endDate` options.

http://www.daterangepicker.com/#usage

**Comment by clod81** [comment]
In relation to this, looking at this example as well: http://www.daterangepicker.com/#ex4 , when I click on "today", which is the default selected option, doesn't set the start and end date to today. 
If I choose another option, and then click back again on today, seems to set them properly.

**Comment by dangrossman** [comment]
That's because "today" is already selected in that example.

**Comment by clod81** [comment]
thanks for the quick reply :+1:
