### ISSUE TITLE
Bower is not installing the latest version

### ISSUE THREAD

**Issue by vlados** [dangrossman/bootstrap-daterangepicker#798]
If I try to install the latest version (2.09), Bower is getting without commit https://github.com/dangrossman/bootstrap-daterangepicker/commit/93b7883c3d450b177a2e4f31b0bee1e199ffff35

I think the problem is that the commit is not tagged

**Comment by dangrossman** [comment]
I add multiple changes to `master` before making a new release. I don't think that is uncommon. 

http://stackoverflow.com/questions/16949173/how-to-install-latest-untagged-state-of-a-repo-using-bower
