### ISSUE TITLE
Trigger event on date click

### ISSUE THREAD

**Issue by clouchtibat** [dangrossman/bootstrap-daterangepicker#800]
I need to set dates hours depending on custom range chosen by user, but I can't properly detect if user set a custom range (means he manually chose dates in calendar) with the events currently available.
The only way I found to do so was to update daterangepicker.js by triggering a custom event at the end of the clickDate method:
```javascript
this.element.trigger('dateClick.daterangepicker', this);
```
Would it be relevant to add it permanently to your plugin?

I use your meteor package which embeds the 1.3.21 version of your plugin.

**Comment by dangrossman** [comment]
When creating the daterangepicker, you can provide a callback function that is triggered every time a new date range is selected. The third parameter passed to your callback is the name of the predefined range label chosen. That's how you can detect if a custom range was chosen from the calendars or not.

http://www.daterangepicker.com/#usage

**Comment by seutje** [comment]
For custom ranges, this only seems to fire one the "apply" button is pressed, whereas for other ranges, it fires as soon as the range is selected.

**Comment by dangrossman** [comment]
That is not the case. Easily demonstrated using the Configuration Generator at http://www.daterangepicker.com/#config. Please open your own issue with a working webpage/fiddle showing your problem if you'd like help.
