### ISSUE TITLE
Inline and block days in daterangepicker

### ISSUE THREAD

**Issue by ApuRed** [dangrossman/bootstrap-daterangepicker#801]
I need to know if you can lock datepicker days and if you can put on without the popup window ...

**Comment by dangrossman** [comment]
You can use the `isInvalidDate` option to block days

Ex: https://github.com/dangrossman/bootstrap-daterangepicker/pull/759

There is no inline mode. I can't imagine a website with an inline two-calendar date range picker. I've never seen such a thing.
