### ISSUE TITLE
publish releases on npm

### ISSUE THREAD

**Issue by mshwery** [dangrossman/bootstrap-daterangepicker#802]
currently npm only has v0.0.3

**Comment by dangrossman** [comment]
That's because I did not ever create an npm package. It looks like whoever did added one of my emails as a maintainer though, so I'll try to publish the current version now.

**Comment by dangrossman** [comment]
Also, you're looking at the wrong package. bootstrap-daterangepicker, not daterangepicker.

**Comment by mshwery** [comment]
Actually it links to this repository:
https://www.npmjs.com/package/daterangepicker

**Comment by dangrossman** [comment]
What is "it"? Nothing here links there.

https://www.npmjs.com/package/bootstrap-daterangepicker

**Comment by mshwery** [comment]
Sorry, I should clarify.

That npm package downloads your package at version 0.0.3.

That package.json points to your github bootstrap-daterangepicker even
though the published npm package is called just daterangepicker.

You'll also see on the npm package details page that the "github" link (in
the sidebar) is to this github repository.

Looks like you didn't publish, but someone else did.

I actually found this repository by way of searching npm. It's a pretty
useful lib and most of the other ones out there are fairly bloated with
jquery ui. It'd be great to have the latest version available on npm either
way!

**Comment by dangrossman** [comment]
I did not publish "daterangepicker". There is no such thing as a version 0.0.3 either. Someone else published an old version (1.x) and gave it that name. I can't do anything about it. Anyone can publish a package to npm with any name, then they own it.

There is a "bootstrap-daterangepicker" package on npm. If you search npm, you'll find that repository as well. It's up to date.

If you want "daterangepicker" to also be up to date, then you need to find and talk to the person that published it.

**Comment by mshwery** [comment]
Ah, cool. Didn't realize it'd be locked to the original publisher, but that makes sense.

I'll look for your actual npm package. Thanks!
