### ISSUE TITLE
Date picker locks to page scroll position instead of element position

### ISSUE THREAD

**Issue by TimoSolo** [dangrossman/bootstrap-daterangepicker#803]
If you have a scrollable div, the datepicker doesn't scroll in sync with the element that opened it.

Eg: http://codepen.io/timosolo/pen/eppZbv

**Comment by TimoSolo** [comment]
OK, not a bug -  I found out you have to use the "parentEl" setting. Now it does stick to the element, but is there a way to lock the position to an element but make the width use the body width? see the update codepen for the issue.

**Comment by mikecabana** [comment]
That's good to know...would have been nice if you left your solution as a reference.
