### ISSUE TITLE
Google Closure compability

### ISSUE THREAD

**Issue by aleksandersumowski** [dangrossman/bootstrap-daterangepicker#804]
When compiled with advanced compilation level some functions get removed and datepicker is not working.

Link to project: https://developers.google.com/closure/compiler/

**Comment by dangrossman** [comment]
Sounds like the compiler has some bugs, huh.

**Comment by aleksandersumowski** [comment]
The Closure Compiler expects its JavaScript input to conform to a few restrictions. The higher the level of optimization you ask the Compiler to perform, the more restrictions the Compiler places on the input JavaScript. Description of limitations:

https://developers.google.com/closure/compiler/docs/limitations

**Comment by dangrossman** [comment]
I'm not going to rewrite this to be compatible with that.

**Comment by aleksandersumowski** [comment]
Well, ok, thanks for the response. 

That makes it way less viable for Clojurescript applications, but I understand this is not your use case. 

Thanks for good library anyway!
