### ISSUE TITLE
Way to set min/max year ranges for dropdowns

### ISSUE THREAD

**Issue by jeserkin** [dangrossman/bootstrap-daterangepicker#805]
As far as I noticed at the moment one can't set min/max year range for dropdowns. Values are static.

**Comment by dangrossman** [comment]
They are not static. The years shown in the dropdowns are bounded by the year of your `minDate` and `maxDate` settings, or if you don't limit the selectable dates, the current year -50/+5 years.

**Comment by jeserkin** [comment]
Yes. But why `-50/+5`? Why not `-20/+20` or anything else. I was talking about those default values. For example I have a field, that I can't limit to some certain range in time, but I would like the year dropdown to be filled with years in `-20/+20` range. How could I do that at the moment(without setting `minDate`, `maxDate` values)?

**Comment by dangrossman** [comment]
By changing the numbers 50 and 5 in your copy of the file. Everything can't be an option, sorry.

**Comment by jeserkin** [comment]
:) Okay :(
