### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by 719media** [dangrossman/bootstrap-daterangepicker#809]
Hello

There is currently a problem with how the timezone/utcOffset functionality in moment js works with datetimepicker. The problem starts with line 300 in daterangepicker.js where we get

this.timeZone = moment(this.startDate).utcOffset();

This sets the timeZone offset to whatever the startDate currently is. Let's assume that we are creating an app where the default datetime in html is

<input type="text" value="2015-09-01 00:00:00" />

Daterangepicker will be initialized and everything will work as expected. However, once you enter into (or out of) daylight savings, the hours will start skipping after setting. This can be easily reproduced by going to the daterangepicker homepage (http://www.daterangepicker.com) and going to the 2nd example (Date and Time). Notice that this example is defaulting to

01/01/2015 1:30 PM - 01/01/2015 2:00 PM

which is standard time (NOT daylight savings). So create paste the following date into the input (which is a date in daylight savings):

08/01/2015 12:00 AM - 08/08/2015 11:59 PM

Once you tab or click away, the hours will skip ahead by 1. In fact, every time the element is blurred from here on out, it will skip another hour each time.

I'm not sure if the best solution is to allow an option to disable utcOffset (personally I don't need it, as the user timezone for my purposes is defined elsewhere, and so users are merely just inputting their own "local time" whatever that may be), or to recalculate utcOffset every time the date changes (seems like a bad choice as it is overwriting the timeZone value for cases where it may be wanted behavior), or something else.

Any thoughts?

**Comment by dangrossman** [comment]
No f**kin' clue, that's my thought. Sorry to unload this on you: I still have no idea why dozens of people DEMANDED timezone support, when, like you, my app is completely timezone aware yet doesn't need anything special from a UI widget to be that way. They say it's absolutely necessary, and I'm a moron for not seeing why. I don't use the timezone option, even though Improvely has user-configurable timezones. I didn't code the timezone option. I don't know how to fix the timezone option. I've tried in the past; touching it anywhere just moves the bugs around. I'd love to rip it out, but then my inbox will be inundated with "issues" demanding its return.

**Comment by 719media** [comment]
Thanks for the reply, sorry for any confusion. I definitely don't want to cause any problems for you to deal with. I don't use timezone at all, but the enforced utcOffset calls are causing the problem for me. Sounds like perhaps we are in the same boat. I'll code up a fix and then you can determine whether or not it's worth the headache to implement. I believe if we just introduced an option "use_timezone" that is set to bool and then if/else blocked all the utcOffset uses it would work.
I should have 20 minutes later today to get it written up. Thx

**Comment by 719media** [comment]
#810 pull request created

**Comment by gregjopa** [comment]
I'm getting burned by this timezone issue too. I agree that the timezone logic should not be in the date range picker code at all. With moment you can globally set a default timezone: http://momentjs.com/timezone/docs/#/using-timezones/default-timezone/. Can we rip out the timezone code from this project and just have users manage the timezone with moment directly? I'm happy to help with a PR for this.

**Comment by dangrossman** [comment]
Alright, we're gonna give this a try. I'm prepping a release without the timezone code at all. Whether that code comes back, with everything wrapped in conditionals so it doesn't effect anyone not using the option, will depend on whether anyone complains.

**Comment by gregjopa** [comment]
Thanks @dangrossman. That's great to hear. Let me know when its' release and I will test it on my end.

**Comment by dangrossman** [comment]
It's up.

**Comment by gregjopa** [comment]
I tested the new release (2.0.14) and everything works great for me. Thanks for making this change.
