### ISSUE TITLE
Month in calendar header doesn't change when days of the next month are picked

### ISSUE THREAD

**Issue by walerian777** [dangrossman/bootstrap-daterangepicker#811]
Hello,

For the singleDatePicker option when I pick a day of the next month, the calendar doesn't move to the next month.
![next_month](https://cloud.githubusercontent.com/assets/6981279/10043212/73185134-61f1-11e5-9636-af49437e5c59.gif)

I have to manually click on the arrow to see the selected date.
![next_month2](https://cloud.githubusercontent.com/assets/6981279/10043414/2a612ff4-61f3-11e5-92d4-6adaaf1c63f3.gif)

However, it does work when I pick a day of the previous month.
![previous_month](https://cloud.githubusercontent.com/assets/6981279/10043222/7d8394bc-61f1-11e5-8e6c-a9a8e35f66e5.gif)

I think it should work the same way as it does for the preceding month.
Any ideas how to fix it?

**Comment by dangrossman** [comment]
I'll fix this in the next update; I didn't consider the single date picker scenario sufficiently last time I updated this part of the code
