### ISSUE TITLE
Any thoughts of releasing this without jQuery?

### ISSUE THREAD

**Issue by peter-mouland** [dangrossman/bootstrap-daterangepicker#813]
It would be great if this was available without jQuery.

Perhaps, the code would work in a standards way and the readme would tell people how to get it working with older browsers using polyfills or a 'bootstrap-daterangepicker-polyfill' could be created to accompany the plugin.

What do you think?

_for completeness: this would help make the plug isomorphic_

**Comment by dangrossman** [comment]
That's not going to happen, sorry.

**Comment by radiodario** [comment]
lol @peter-mouland just make a fork for the people that don't live in 2006

**Comment by peter-mouland** [comment]
ok, do you have any tests?

**Comment by dangrossman** [comment]
You know the answer to that, since the code's right there a click away. No, there are no tests. Please don't waste my time. If you don't have a bug report to make, then you don't need to open an issue.

**Comment by peter-mouland** [comment]
sorry - i'm just trying to get a basis for how you like PR's since i don't see a `contributing.md` or anything. 

Last question, Which browsers should PR's support?
