### ISSUE TITLE
Layout issue with Predefined Custom Range

### ISSUE THREAD

**Issue by ataft** [dangrossman/bootstrap-daterangepicker#819]
If the daterangepicker element is on the left side of the screen, and the Custom Range is selected on a Predefined Ranges type, then the custom ranges get kicked to the bottom. Ideally, if there's not room on the left, then it would open with the calendar on the right of the Custom Range selections.  Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/11670864/10236217/02743a52-6858-11e5-9aa5-7458e7c62a96.png)

**Comment by dangrossman** [comment]
You should specify `opens: right` in your options if you're going to attach it to something on the left.

**Comment by ataft** [comment]
OK, thanks for the feedback.  I would think this would be desired behavior, like most bootstrap or jquery widgets, and that individuals wouldn't want to manage position.  I understand if it's not a priority tho, thanks.

**Comment by dangrossman** [comment]
Most individuals don't manage position. It works "the Bootstrap way". The dropdown expands to the right, unless its container has the Bootstrap class "pull-right", then it expands to the left. You only have to specify if you want it to behave differently.
