### ISSUE TITLE
DataRangePicker not display time

### ISSUE THREAD

**Issue by vnt** [dangrossman/bootstrap-daterangepicker#820]
Hi,
I have a problem, DataRangePicker do not display the time.
This is the code generated  with timePicker
$('#demo').daterangepicker({
    "singleDatePicker": true,
    "timePicker": true,
    "autoApply": true,
    "startDate": "09/26/2015",
    "endDate": "10/02/2015"
}, function(start, end, label) {
  console.log("New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')");
});
I have tried with firefox 40, safari 9  for Mac.

**Comment by dangrossman** [comment]
You have to set a date format that includes whatever portion of the time you want to display.

```javascript
$('#demo').daterangepicker({
    ...
    locale: { format: 'YYYY-MM-DD HH:mm' }
   ....
});
```
