### ISSUE TITLE
"Dedicated" calendar

### ISSUE THREAD

**Issue by margielm** [dangrossman/bootstrap-daterangepicker#822]
Cool feature in line 1.x is that first calendar is dedicated to "start date" and second to "end date". in version 2.x looks like it has change. Both calendars are for start  and end dates and which date one is selecting is based on "order of clicking". I.e. first click is always "start" second always "ends".
This is very cumbersome one one wants to change one date only. User has to ALWAYS reset both ends of the range.
Is this a future or a bug? is there any option to rollback to 1.x behaviour?

**Comment by dangrossman** [comment]
This is a feature, because it's how every other date range picker I could find on the web works. Google Flights. All the hotel booking sites. All the restaurant reservation making sites. Nothing else worked like v1 of this widget worked; it was the strange one.

**Comment by margielm** [comment]
Thank you for fast answer. but just out of curiosity I have check google flight and it is working a little bit differently. 
in google flights we separate inputs for start and end dates. 
![image](https://cloud.githubusercontent.com/assets/684828/10309186/6fefe52c-6c3b-11e5-8a57-68d102ba98d9.png)

if you click on first input then you are selecting "start date" and after doing so you are moved automatically to "end date". If instead you will click directly on "end date" input then you will be  directly selecting that end of the range.
So, to be honest, for me it works more  like v1 rather than v2.
Is there any chance to make it customizable based on some parameter? in my opinion it makes huge sense to do so. it is not only 1 click less, but also more natural (imho).

**Comment by dangrossman** [comment]
No
