### ISSUE TITLE
Methods setStartDate and setEndDate are using the pattern "MM/DD/YYYY" even when the "format:" is configured "DD/MM/YYYY"

### ISSUE THREAD

**Issue by willaleksander** [dangrossman/bootstrap-daterangepicker#823]
I've facing a problem, I have a project that uses the brazilian time pattern "DD/MM/YYYY", I've setted this when I create the daterangepicker, $('#reportrange' + i).daterangepicker({format : "DD/MM/YYYY"... , but when I call setStartDate and setEndDate I need to pass a date with the pattern "MM/DD/YYYY". 
I think the correct is the methods follows the "format:" rule.

**Comment by dangrossman** [comment]
`format` is not a top-level setting, it's one of the properties of the locale setting.

````javascript
$('#reportrange' + i).daterangepicker({
  locale: {
    format: 'DD/MM/YYYY'
  }
});
````
