### ISSUE TITLE
Incorrectly triggering 'change' events

### ISSUE THREAD

**Issue by alvinj01** [dangrossman/bootstrap-daterangepicker#824]
Inside the `daterangepicker.js`, there are multiple occasions where the `change` event is triggered regardless of the value being updated. (ex. https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L1452)

Should they check that the `old_value != new_value` before triggering the `change` event?

**Comment by dangrossman** [comment]
If you'd only like to know when the values actually changed, then I suggest providing a callback function rather than listening for an event.

**Comment by lokywin** [comment]
@dangrossman you are super responsive. Thanks for developed this plugin.

**Comment by alvinj01** [comment]
:+1:
