### ISSUE TITLE
Rendering Issue in Firefox

### ISSUE THREAD

**Issue by rksaxena** [dangrossman/bootstrap-daterangepicker#825]
<img width="764" alt="screen shot 2015-10-08 at 2 29 35 pm" src="https://cloud.githubusercontent.com/assets/5802062/10361986/365b9416-6dc9-11e5-8270-277585f66f35.png">

I am using this date-range picker with following configuration:
```javascript
    $(that).daterangepicker({ 
        autoApply: true, 
        locale: { 
                format: 'YYYY/MM/DD' 
        }, 
        startDate: moment().subtract(start_date, 'days'), 
        ranges: { 
           'Last 7 Days': [moment().subtract(6, 'days'), moment()], 
           'Last 30 Days': [moment().subtract(29, 'days'), moment()], 
           'Last 45 Days': [moment().subtract(45, 'days'), moment()], 
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')] 
        } 
    }, cb); 

```
It works fine in Google chrome but in Firefox its a bit distorted.

**Comment by dangrossman** [comment]
How's it look when you remove your custom stylesheet?

**Comment by rksaxena** [comment]
I have only bootstrap class "form-control" associated with the element/page. I tried to look the daterangepicker css and found that if I remove ```min-width : 32px```, the dates are rendered properly.

``` css
.daterangepicker .calendar td {
    white-space: nowrap;
    text-align: center;
    /* min-width: 32px; */
}
```

**Comment by rksaxena** [comment]
I

**Comment by dangrossman** [comment]
Here's a screenshot from Firefox taken just now. Unlike your screenshot, there aren't 3 different fonts nor any overflow. You must have another stylesheet of your own on the page...

<img width="356" alt="ss" src="https://cloud.githubusercontent.com/assets/407706/10373903/3c0b20c6-6dbe-11e5-95af-d8b3c290e272.png">

**Comment by rksaxena** [comment]
I removed all style-sheets except the bootstrap the ones mentioned but I am still getting the same problem. My Firefox version is `40.0.3`
```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"/>
<link rel='stylesheet', type='text/css', href='//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css'/>
```

**Comment by dangrossman** [comment]
Why are there commas in that last tag?

**Comment by dangrossman** [comment]
Why are there commas in that last tag?

Do the calendars at http://www.daterangepicker.com look wrong on your screen too?

**Comment by lokywin** [comment]
![screen shot 2015-10-08 at 10 42 45 am](https://cloud.githubusercontent.com/assets/545713/10374687/54e9eb3c-6da9-11e5-9844-8db4d730fc4e.png)

I took this just now, on Firefox, from: http://www.daterangepicker.com

**Comment by rksaxena** [comment]
These look fine. Maybe I'll have to remove all elements from the form and try it again.
Thanks a lot for your support and time.

**Comment by ccaper** [comment]
I am experiencing this exact same issue.  Previously, I was using version 1.3.13 without problems.  Upgrading to latest version introduced the problem.  Chrome looks fine, FF the padding on the calendar dates are larger making the calendar off, just like above.  Even extracted everything to a page with only the datarangepicker on an input, using no custom style sheet, still see the problem.  Ideas?

**Comment by ccaper** [comment]
To follow up, I'm including a screen shot, and the code.

Code:
<html>
<head>
  <script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/latest/css/bootstrap.css" />
 
  
  <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
</head>
<body>
  <input type="text" name="daterange" value="01/01/2015 - 01/31/2015" />
<script type="text/javascript">
$(function() {
    $('input[name="daterange"]').daterangepicker({
        linkedCalendars: false
    });
});
</script>
</body>
</html>
![daterangepicker](https://cloud.githubusercontent.com/assets/3731987/10620926/45e4992c-7743-11e5-82dd-ad0f1b71a11c.png)

**Comment by dangrossman** [comment]
No ideas. If I can't reproduce it, I can't investigate or fix it.

**Comment by ccaper** [comment]
```
<html>
<head>
  <script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" />
 
  <!-- Include Date Range Picker -->
  <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
</head>
<body>
  <input type="text" name="daterange" value="01/01/2015 - 01/31/2015" />
  <script type="text/javascript">
    $(function() {
      $('input[name="daterange"]').daterangepicker({
        linkedCalendars: false
      });
    });
  </script>
</body>
</html>
```
![daterangepicker](https://cloud.githubusercontent.com/assets/3731987/10621971/b9da654a-7749-11e5-973f-22b6b87557f6.png)

**Comment by dangrossman** [comment]
This is happening because Firefox is overriding the font size set by Bootstrap with the user agent default, which is larger for table cells. This only happens when the doctype declaration is missing or incorrect. At this at the top of your HTML and the Bootstrap styles will be applied correctly:

    <!DOCTYPE html>

**Comment by ccaper** [comment]
Seriously, thank you.  I've been stumped by this for a day, and had a feeling I was over looking something small like this.  I verified this solved it.  Thanks for the quick response.  Been using this plugin for over a year, love it, thank you for your hard work on this.

**Comment by dangrossman** [comment]
It was a headscratcher for me too. :)

**Comment by rksaxena** [comment]
Thanks a lot!!!
I was struggling with this since a long time and shared the same feeling Christian!

**Comment by divakarcool** [comment]
Yes !
Big Thank to you @dangrossman for the awesome solution. I think we should always use <!DOCTYPE html>

**Comment by dj4388** [comment]
Thank you very much @dangrossman. I was too finding it very difficult to solve for firefox.
