### ISSUE TITLE
clearing a date doesn't actually clear the date

### ISSUE THREAD

**Issue by bolemeus** [dangrossman/bootstrap-daterangepicker#828]
When I clear the date like this

```
$('date-range').val('');
```

I expect the date to be cleared. When I want to enter a new date however I can see that the last known dates are still selected. Selecting thesame dates again doesn't trigger the datechanged callback.

I'd also like to be able to initialize the daterangepicker in a cleared state, with no dates selected yet, but I can't get this to work.

for example when I got the following daterangepicker:

```
	$('#date-range').daterangepicker({
	        "showWeekNumbers": true,
	        "autoApply": true,
	        "locale": {
	            "format": "DD/MM/YY",
	            "separator": " - ",
	            "firstDay": 1
	        }
	    }, function(start, end, label) {
            logger.info("New date range selected: " + start.format('YYYY-MM-DD') + " to " + end.format('YYYY-MM-DD') + " (predefined range: " + label + ")");
	    });
```

There is no defined startDate and EndDate, so I expect there to be nothing selected yet, but it defaults to the current date for both fields. Clearing the field doesn't seem to clear the actual dates either, and reselecting them doesn't cause another callback to be logged.

**Comment by dangrossman** [comment]
There is always a startDate and endDate selected internally. The callback will only be triggered when they are changed. If you want to know every time a date is selected even if there's no change from the previous selection, listen for the `apply.daterangepicker` event instead of using a callback.
