### ISSUE TITLE
autoUpdateInput: false doesn't update the input when selecting a date

### ISSUE THREAD

**Issue by pacMakaveli** [dangrossman/bootstrap-daterangepicker#830]
Having `autoUpdateInput` set to false doesn't update the target anymore. I don't know wether or not this is intentional, but having it enabled, which is default, it's not ideal when using it as part of a Filter system for example.

Leaving it enabled, it populates the target on page load. The date-range filter, at least in my app, is optional, so I cannot leave it populated by default.

Any suggestions?

Much appreciated

**Comment by dangrossman** [comment]
"auto Update Input" is the name of the option. It means the date picker should "automatically update my input". When you set it to false, that means the date picker should NOT "automatically update my input". It is not a bug that your input is then not automatically updated. I honestly don't know what you'd like a suggestion about. It sounds like this is exactly what you want for your filter system...

**Comment by pacMakaveli** [comment]
Yes, but that's the problem. The input doesn't get updated with my daterange while 'autoUpdateInput' is set to false. The input doesn't get updated at all.. I know how it sounds.

@dangrossman

**Comment by dangrossman** [comment]
That's how it's supposed to be. If you want your update to be updated, you do it yourself, either in your callback function or in an event listener.

**Comment by pacMakaveli** [comment]
Cool, I wasn't aware I have to update it myself. I suppose I have to read carefully the Documentation.
Thank you very much for your help.

**Comment by Asimov500** [comment]
There is a problem with this solution. It only works for this case. What if you have multiple date fields. All the dates will change, and not just the one you are on. I tried
$(this).val(picker.startDate.format('YYYY-MM-DD') + ' - ' + picker.startDate.format('YYYY-MM-DD'));
but this doesn't work.
I only want to change the date I am on, without having to specify an id

**Comment by jimmyp80** [comment]
Would be way more helpful to simply mask the initial date range before selection, and then display the selected date range in the usual way.

**Comment by karatana** [comment]
@Asimov500 
`this` variable has `element` property. I solved this problem using it.

```
$('someSelector').daterangepicker({
  ...options..,
}, function(start, end, label) {
  $(this.element).val(start.format('YYYY-MM-DD'));
});
```

**Comment by jayeshClockshark** [comment]
> Right. Your input doesn't get updated by the picker, because you have chosen to handle that yourself so that it's only updated when you want it updated. Or because you attached the picker to something that isn't a text input. For example, in your callback function.
> 
> ```js
> $('input').daterangepicker({
>   ...options..,
> }, function(start, end, label) {
>   $('input').val(start.format('YYYY-MM-DD') + ' - ' + end.format('YYYY-MM-DD'));
> });
> ```
> 
> ...or in an event listener.
> 
> ```js
> $('input').on('apply.daterangepicker', function(ev, picker) {
>   $('input').val(picker.startDate.format('YYYY-MM-DD') + ' - ' + picker.startDate.format('YYYY-MM-DD'));
> });
> ```

Thank you
