### ISSUE TITLE
How make to work Daterange using the current date and using on month in advance.

### ISSUE THREAD

**Issue by thomas1216** [dangrossman/bootstrap-daterangepicker#832]
How make to work Daterange using the current date and using on month in advance.
like if a user enter today, show the today date and one month in advance, no hard coding dates.

```
<input type="text" name="daterange" value="01/01/2015 - 01/31/2015" />

<script type="text/javascript">
$(function() {
    $('input[name="daterange"]').daterangepicker();
});
</script>
```

**Comment by dangrossman** [comment]
There's no built-in way to do that. You will have to program it yourself.
