### ISSUE TITLE
Initialize a Blank date range picker

### ISSUE THREAD

**Issue by alvinj01** [dangrossman/bootstrap-daterangepicker#834]
Hi, Is there a way to initialize the date range picker so that we start with a blank selection?

**Comment by dangrossman** [comment]
Yes. `$('yourinput').val('');`. Or, set the `autoUpdateInput` option to false, and handle updating it when you want yourself using the callback function or events provided.

**Comment by alvinj01** [comment]
Assuming the field is cleared with `$('my_input').val('');` after the daterangepicker widget is initialized with `autoUpdateInput ` set to `true` and some predefined ranges `["Today", "Yesterday", "This Month"]`.

If I click on `my_input`, the widget shows with "Today" selected. What do I need to setup so that widget would show no selection at all?

**Comment by dangrossman** [comment]
There is always a startDate and endDate selected internally. If you don't set them at initialization, they will be today's date, which is why "Today" was highlighted.

**Comment by aarongtz** [comment]
I think the real problem that @alvinj01 refers to is that when using `$('my_input').val('');` the input appears to be empty, but the calendar already selects today's date, but if a user selects today's date, the change callback won't fire...

**Comment by dangrossman** [comment]
The apply event does fire however. http://www.daterangepicker.com/#example5

**Comment by aarongtz** [comment]
What about a single datepicker (without range where the buttons like "apply" don't show), the change callback doesn't fire or am I missing something?

**Comment by dangrossman** [comment]
The apply event still fires.

**Comment by aarongtz** [comment]
I see, what is the difference between doing things inside the callback provided when initializing like this (in the following example, the callback doesn't fire when selecting the same date):

```
$('.calendar').daterangepicker({
	    "singleDatePicker": true,
	    "minDate" : minDate,
	    "drops": "up"
	}, function(start, end, label) {
		//do something
               
	});
```

And when doing this:

```
$('.calendar').on('apply.daterangepicker', function(ev, picker) {
//do something
});
```

**Comment by dangrossman** [comment]
The difference is that the callback doesn't fire when selecting the same date, and the apply event does.

**Comment by aarongtz** [comment]
Okay, thank you, sorry for the inconvenience.

**Comment by loopmode** [comment]
inconvience is using this 🙁 sorry for bringing frustration over here but..
this is a PITA.

If you need a date field that is required for the user, it's a total anti-pattern to provide a default value. Users will simply forget to change the value and submit the form. 
A required field must start without a default value, period.
A required field is therefor basically impossible to do with this library, unless with fiddling around to achieve such basic functionality as "no default value". Meh. Don't have the time to make a PR, just enough time to "make it work"..
