### ISSUE TITLE
Add support for month range

### ISSUE THREAD

**Issue by vToMy** [dangrossman/bootstrap-daterangepicker#840]
Meaning to pick a range of months only, without choosing a day. Of course with the option to decide which day of month will be picker for the start and end range (like, first day, last day, specific day...)
I found an old fork that does it, but it was never merged:
https://github.com/rklachko/bootstrap-daterangepicker

**Comment by dangrossman** [comment]
This is not a feature of this picker. You'll need to use something else.

**Comment by vToMy** [comment]
Will you be willing to merge a pull request implementing this? I understand this is not of the most importance, but I think it's a useful addition.
The name of the project is "daterangepicker" not "dayrangepicker" so I think picking monthly ranges (i.e. 01/04-31/07) would be useful.

**Comment by dangrossman** [comment]
I would be unlikely to merge a PR for that feature. It's going to touch a lot of code, add a lot of maintenance burden for a seldom-requested feature, and an outside contributor is unlikely to consider all the ways all the settings might interact with it when trying to add it.

**Comment by vToMy** [comment]
I see. How about a different approach that would be a lot easier to implement -
Using something like "batch mode" you can see here:
http://longbill.github.io/jquery-date-range-picker/

Basically clicking on a week/month will select the whole week/month.
