### ISSUE TITLE
Setting start date to the same end date but with different hours breaks the plugin

### ISSUE THREAD

**Issue by mribeiro** [dangrossman/bootstrap-daterangepicker#841]
Date ranger picker Version: 2.1.14
Moment version: 2.10.6
Jquery version: 2.1.5

I select the same day for both start and end date.  Let's say, 20/12.
Then, for start date, I select 08:00 and for the end date I select 16:00 (in times, of course).

Then I get the attached result (image).
![image](https://cloud.githubusercontent.com/assets/1676406/10558836/62682f10-74d6-11e5-800c-9104b3e1709c.png)

**Comment by dangrossman** [comment]
Thanks for the bug report, a patch is now in
