### ISSUE TITLE
Validation while selecting a date

### ISSUE THREAD

**Issue by umesh-naik** [dangrossman/bootstrap-daterangepicker#847]
If my date format is like, " 21/10/2015 10:58 AM " and if I want to validate the whole given date, how can I? There is a possibility of making the date input selector to "readonly" and ask the user to pick the date manually without typing. But I don't want to do that. Secondly, if the user enters some random text in the  "input" field, it still takes the input and it would be preferable to show the valid date format.

**Comment by dangrossman** [comment]
This widget is a date picker, not a form validator. You'll need to program that yourself.
