### ISSUE TITLE
disable duplicate days from calendar

### ISSUE THREAD

**Issue by pyra15** [dangrossman/bootstrap-daterangepicker#848]
Thanks for nice plugin. Can't find workaround to this case: how to disable duplicate days from calendar

![Image of issue](http://content.screencast.com/users/marius_p/folders/Jing/media/74b428bc-815f-424e-8136-df2070697512/00000281.png)
Thanks

**Comment by dangrossman** [comment]
There is not an option for that. You would have to program this yourself.
