### ISSUE TITLE
Date in future

### ISSUE THREAD

**Issue by umesh-naik** [dangrossman/bootstrap-daterangepicker#853]
In the input text, where the date is set to moment(), but in the single date picker, the initial date is set in future. Pic has been attached.
![dateinfuture](https://cloud.githubusercontent.com/assets/11293361/10791937/9d036b16-7db0-11e5-8f1e-76c2771c26ee.png)

**Comment by dangrossman** [comment]
I'm afraid I can't identify the problem, or fix it, based on a screenshot. Please share your code, or a live example, what you did, what was the expected result, and what was the actual result.

**Comment by umesh-naik** [comment]
So, code goes like this:
daterangepickerOptions =
            singleDatePicker: true
            showDropdowns:  true
            timePicker: true
            startDate: moment()
            endDate: moment()
            minDate: moment()

and then I'm calling it here:
$('startsOnId, endsOnId').daterangepicker(daterangepickerOptions)
        $('endsOnId').daterangepicker($.extend({},daterangepickerOptions, {
            drops: 'up'
        }))

        $('startsOnId').on("hide.daterangepicker", (e, picker)->
            options = $.extend(daterangepickerOptions, {startDate:picker.startDate,endDate:picker.startDate,minDate : picker.startDate,drops:'up'})
            $('endsOnId').data('daterangepicker')
                .setOptions(options)
        )

**Comment by dangrossman** [comment]
Here's what I get using those options. The initial selected date is today, as expected.

<img width="198" alt="ss" src="https://cloud.githubusercontent.com/assets/407706/10819414/4679e8d8-7e1e-11e5-95dd-e6d04723f153.png">

It doesn't look like you specified a format setting, so "28/10/2015" is not a valid date and "08:09 PM" came from where? The default string format is "MM/DD/YYYY". 

Check off "Locale (with example settings)" in the configurator for an example of setting the format:

http://www.daterangepicker.com/#config

**Comment by umesh-naik** [comment]
Hi again,
format: DD/MM/YYYY hh:mm A

and I have a doubt. Since we are considering timePicker in the daterangepickerOptions  and calling the  same options on an id. It should get timePicker option in the input field right?
