### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by iOsama** [dangrossman/bootstrap-daterangepicker#854]

**Comment by NOtherDev** [comment]
Why was this closed? Does `daterangepicker` support RTL languages? It doesn't seem so, or at least I can't find how to enable it.

+1

**Comment by dangrossman** [comment]
I don't know how to answer that. It was closed because it was an issue with no detail which I could do nothing with.

**Comment by NOtherDev** [comment]
Here is how the calendar looks like when the direction is set to RTL - note the arrows:
<img width="496" alt="calendar_rtl" src="https://cloud.githubusercontent.com/assets/1309057/10939853/d17dc806-8304-11e5-98d9-5c41c1405dd0.png">

**Comment by shahraizhasnain** [comment]
I have come up with a solution may be those in need would get some help.

**Comment by AnanthaPerumal** [comment]
Hi Dan i have a solution for this issue I have styled your component so that it can support rtl. if you wish I can contribute towards it
