### ISSUE TITLE
The picker doesn't allow to change the start date or end date only

### ISSUE THREAD

**Issue by M1chae1** [dangrossman/bootstrap-daterangepicker#855]
The picker only allow user to pick the start date and then end date by sequence.

![daterangepicker](https://cloud.githubusercontent.com/assets/5714586/10813287/1528de70-7e59-11e5-9108-bfcc09d6286b.gif)

Does any way allow the user to change the start date or end date only?

set "linkedCalendars": false doesn't solve the problem

**Comment by dangrossman** [comment]
There is not a way to allow the user to change only the start or end date.
