### ISSUE TITLE
Calendars not floating in IE8

### ISSUE THREAD

**Issue by TomHart** [dangrossman/bootstrap-daterangepicker#856]
In IE8 the calendars don't float, the just stack up. We have respondJS included in the site.

![calendar](https://cloud.githubusercontent.com/assets/1374434/10815669/739f02ba-7e25-11e5-96df-d30a9c5247b1.png)

Is this a known issue or is there a workaround I could do to get the daterangepicker usable in IE8?

If you need to know anything else just ask, but unfortunately I can't get you a link to our site where the issue is (admin panel).

**Comment by dangrossman** [comment]
Try grabbing [v2.0.12](https://github.com/dangrossman/bootstrap-daterangepicker/releases/tag/v2.0.12). I didn't realize some tweaks someone made for mobile broke IE8.

**Comment by dangrossman** [comment]
Also, they don't stack in IE8 when you have respond.js. I just added it to http://www.daterangepicker.com/ to demonstrate. 

Are you testing locally perhaps? Respond.js doesn't work on file:/// URLs.

**Comment by TomHart** [comment]
We do test locally, but it's running inside a Docker so it's on a proper http://www.example.dev style URL.

For the time being we're just always applying the media queries in IE8, which works, and when we get chance later I'll try downgrading to 2.0.12 and see if that resolves the issue.

**Comment by peter-mouland** [comment]
Sounds like the 'mobile first' responsive update; sorry about that, but I'm still not sure what browsers this plug in supports?

**Comment by TomHart** [comment]
To be honest it's not a massive issue I don't think, but I figured I may as well let you guys know anyway. IE8 support should have been dropped long ago, but we still get the odd person who uses it.

**Comment by dangrossman** [comment]
@peter-mouland Every browser it reasonably can. It worked fine in IE8 so there's no reason to break that.

**Comment by peter-mouland** [comment]
@TomHart i'd say it is a broken layout - but usable layout as it is.  
@dangrossman I have asked a few times what browsers you support and never received an answer. 'reasonably' is a vague answer and i would recommend putting exact browsers supported onto the readme to stop confusion in the future.

Personally, I think it is reasonable to expect ie8 to look a little off, as long as it is functional.  IE8 doesn't support media queries by default. Is it worth while adding an ie.css to this plug in, or would you prefer to change from 'mobile-first' to 'desktop-first' which will also fix the problem?

**Comment by dangrossman** [comment]
No changes are necessary. It looks the same in IE8 as it does in other browsers when you use respond.js, which is part of the Bootstrap minimal template.

**Comment by TomHart** [comment]
@peter-mouland Yeah, on desktop, rather than the calendars being side-by-side, they're top and bottom.

**Comment by dangrossman** [comment]
<img src="https://cloud.githubusercontent.com/assets/407706/10823190/dfb73804-7e30-11e5-8075-09f56102a830.png">
