### ISSUE TITLE
Display three or more months at the time

### ISSUE THREAD

**Issue by GeoDz** [dangrossman/bootstrap-daterangepicker#859]
Hi all,
Is there any way to display three or more months at the time? I'd like to achieve the effect close to jQuery UI as you can see there http://jqueryui.com/resources/demos/datepicker/multiple-calendars.html

**Comment by dangrossman** [comment]
There is not any way to display three or more months at a time.

**Comment by mafioznick** [comment]
hello! Is it still not available to do some months? (exactly i need to show 12 months in mobile..) Any hack to do it?

**Comment by dangrossman** [comment]
No, there's not a way to do that with this library, and there is no easy hack to make it possible. You'll want to find a different library, or code it yourself.
