### ISSUE TITLE
request for ability to set the `dropdown` or `hidden` classes

### ISSUE THREAD

**Issue by ingrimmm** [dangrossman/bootstrap-daterangepicker#860]
First - this is an awesome plugin - thanks for making it available!

What I've run into is there's no way to specify the `dropdown` or `hide` classes (as there is with the `buttonClasses`, `applyClass` and `cancelClass`).

Since I'm using Semantic-UI (instead of Bootstrap) this means that on initial page load the dropdown always appears (since the plugin currently relies on Bootstraps `.dropdown-menu` class to hide itself initially - which doesn't exist) and the `autoApply` option isn't able to hide the `apply` or `cancel` buttons since it appears to rely on the `hide` class, which also doesn't exist.
![screenshot 2015-10-30 16 03 47](https://cloud.githubusercontent.com/assets/3489610/10856719/ee2b8ed6-7f1f-11e5-8a20-4ef8cded0c6d.png)
Everything else looks pretty good, tho - and, after interacting with the field the first time, the dropdown appears/dissappears properly. The buttons always show, but at least the dropdown works.
![screenshot 2015-10-30 16 04 26](https://cloud.githubusercontent.com/assets/3489610/10856727/f76f13d2-7f1f-11e5-86a5-421c6d6f2e2c.png)
If it were possible to specify the rest of the classes this uses we'd be able to easily use this in a framework like Semantic UI instead of Bootstrap.

**Comment by dangrossman** [comment]
Looks like someone's already made a fork for that:

https://github.com/BreadMaker/semantic-ui-daterangepicker

**Comment by ingrimmm** [comment]
Hmm. Well, for those who don't want an out-of-date fork and have the same issue, a workaround is to add the following css overrides.

```css
.daterangepicker.dropdown-menu {
  display: none;
}
.daterangepicker .hide {
  display: none !important;
}
```
