### ISSUE TITLE
Left calendar for startDate, right calendar for endDate

### ISSUE THREAD

**Issue by javiermatos** [dangrossman/bootstrap-daterangepicker#867]
Hello,

I would like to ask how to force the left calendar to only set the startDate and the right calendar to set endDate. Actually you can set both on any calendar because the first click on any calendar sets the startDate and the second sets the endDate.

I have found a project that uses your code with angular and it does it the way I have described: http://luisfarzati.github.io/ng-bs-daterangepicker/

The only problem is that they use the 1.x version for their project.

Is there a way to achieve the same result with the 2.x version?

**Comment by boogiebug** [comment]
Set the option 'linkedCalendars' to false should help, I guess

**Comment by javiermatos** [comment]
I tried that option but it does not work. The documentation for that option says:

linkedCalendars: (boolean) When enabled, the two calendars displayed will always be for two sequential months (i.e. January and February), and both will be advanced when clicking the left or right arrows above the calendars. When disabled, the two calendars can be individually advanced and display any month/year.

I think that it is a bit confusing the way it works right now. If I have "two columns", changes done to the calendar of one column only should affect the datetime input that is located over that specific calendar.

**Comment by SlavkoPar** [comment]
It is really confusing !

**Comment by dangrossman** [comment]
> Is there a way to achieve the same result with the 2.x version?

No.

**Comment by javiermatos** [comment]
Thank you for your help.

I will stick to the 1.x version and I will use the ng-bs-daterangepicker project to integrate it. Does it make sense to add the case that I described as a feature? Maybe I am wrong but I think it's usability could be improved by having that behaviour.

Having two calendars in two columns each one with it's corresponding input field on top of it... the obvious thing to think is that each calendar will modify it's own input field.

**Comment by dangrossman** [comment]
It was changed to work this way after complaints that this picker didn't work like all the other pickers on the web, where the first click chooses the start of the range, and the second click chooses the end, regardless of which calendar you click on. I couldn't find any major travel/booking/reservation site that works the way you're saying it should obviously work. They either have separate inputs on the form, or work the way this picker now works. Your site using 1.x will likely be breaking expectations.

**Comment by javiermatos** [comment]
Thank you so much for your explanation. I will take a look at other sites to improve the design and usability of my app. Sorry, I didn't thought about that.

**Comment by SlavkoPar** [comment]
I would prefer to have 2 modes, one for short periods, working like xisting solution, and another mode  for large periods to work like javiermatos suggested, and i intuitively expect.

**Comment by viros** [comment]
+1. Two modes definitely nice to have.
