### ISSUE TITLE
Problem with null input

### ISSUE THREAD

**Issue by cagatayoncul** [dangrossman/bootstrap-daterangepicker#868]
Hi, i have problem with null input. i want to leave blank date input. When focus on input and leave input, automatically selecting today date. How can i solve this ?

**Comment by dangrossman** [comment]
http://www.daterangepicker.com/#ex5

**Comment by cagatayoncul** [comment]
Ok i know that but problem is singledate. If i set autoUpdateInput to false datepicker not working.

**Comment by dangrossman** [comment]
The picker works, but it won't update your input for you. You have to do that yourself. It's all in the example I linked.
