### ISSUE TITLE
Date selection extends beyond the end date

### ISSUE THREAD

**Issue by mshwery** [dangrossman/bootstrap-daterangepicker#873]
I'm encountering a weird bug where I'm using actual Date objects for the start/end dates, and the max is `11/16/2015` (aka today). If I pass the end of today as the endDate (`moment().endOf('day').toDate()`) it highlights the 17th as well.

<img width="514" alt="screen shot 2015-11-16 at 4 32 29 pm" src="https://cloud.githubusercontent.com/assets/710752/11196916/ab70b784-8c7f-11e5-803a-03834a6d39f1.png">

**Comment by dangrossman** [comment]
Are you saying that you set maxDate to 11/16 00:00:00, and endDate to 11/16 23:59:59?

**Comment by mshwery** [comment]
No, rather:

```js
var options = {
    startDate: moment().startOf('month').toDate(),
    endDate: moment().endOf('day'),
    maxDate: '11/16/2015'
};
```

**Comment by dangrossman** [comment]
OK. Thanks. You are in fact setting the endDate to 11/16 23:59:59 and maxDate to 11/16 00:00:00. That doesn't make sense, so don't do that!

**Comment by mshwery** [comment]
Actually. This is still happening without a `maxDate` specified at all.

**Comment by mshwery** [comment]
This actually get's weirder. If I _do_ set a maxDate like so: `moment().endOf('day')` it looks like this:

<img width="527" alt="screen shot 2015-11-16 at 5 30 44 pm" src="https://cloud.githubusercontent.com/assets/710752/11198112/dd66615a-8c87-11e5-8f76-c942decbafef.png">

You can select the future? This seems unintentional. Am I missing something?

**Comment by dangrossman** [comment]
Probably something related to time zones. All datetime bugs end up being related to time zones. Any chance you set one on the global moment object?

**Comment by mshwery** [comment]
I'm updating to the latest. was on `^2.0.9` but that's a few behind.

**Comment by mshwery** [comment]
@dangrossman the latest version _doesnt have the problem_ as long I use a moment object for the maxDate. If I transform it with `toDate()` it still has the same issue.

**Comment by mshwery** [comment]
Thanks for your suggestions.

**Comment by dangrossman** [comment]
If you ever find and fix a bug, I'd be happy to take a pull request.

**Comment by mshwery** [comment]
Still trying to debug whether this is a bootstrap-daterangepicker issue or just something between this and native html5 date inputs (i'm using both depending on screen real-estate)
