### ISSUE TITLE
Alert if time diff is 10 or more

### ISSUE THREAD

**Issue by adgfx** [dangrossman/bootstrap-daterangepicker#874]
![dr_picker](https://cloud.githubusercontent.com/assets/6965294/11204535/61a7139c-8d19-11e5-8506-5323cf73e17e.jpg)
Hi Dan,
On my Photography Booking Area i have this (attached) date range picker where users can select an event's date & time range. Here we want a check for 1 day(short) events, it should alert if the user selects a time range diff is grater than 9 hours. A time diff check! How do we achieve that.
Thanks,
ad

**Comment by dangrossman** [comment]
The chosen start and end date are provided to your callback function. You would do your calculation there.

http://www.daterangepicker.com/#ex3
