### ISSUE TITLE
Date format not working

### ISSUE THREAD

**Issue by luisapuyen** [dangrossman/bootstrap-daterangepicker#875]
The date format is not being applied despite I changed it from MM/DD/YYY to DD/MM/YYY

This is how I set it up:

var $datepickers = $('.datepicker').daterangepicker({
			    "singleDatePicker": true,
			    "locale": {
			        "format": "DD/MM/YYYY",
			        "separator": " - ",
			        "applyLabel": "Aplicar",
			        "cancelLabel": "Cancelar",
			        "fromLabel": "Desde",
			        "toLabel": "Hasta",
			        "customRangeLabel": "Custom",
			        "daysOfWeek": [
			            "Do",
			            "Lu",
			            "Ma",
			            "Mi",
			            "Ju",
			            "Vi",
			            "Sa"
			        ],
			        "monthNames": [
			            "Enero",
			            "Febrero",
			            "Marzo",
			            "Abril",
			            "Mayo",
			            "Junio",
			            "Julio",
			            "Agosto",
			            "Septiembre",
			            "Octubre",
			            "Noviembre",
			            "Diciembre"
			        ],
			        "firstDay": 1
			    },
			    "linkedCalendars": false,
			});

**Comment by dangrossman** [comment]
I just copied and pasted that code into a page, and the picker had the format you set. 

<img width="280" alt="ss" src="https://cloud.githubusercontent.com/assets/407706/11213825/280590a8-8d0c-11e5-9e09-2eadd0b0e4f4.png">
