### ISSUE TITLE
Server date get override

### ISSUE THREAD

**Issue by fccpt** [dangrossman/bootstrap-daterangepicker#876]
I've found that the data coming from server gets override by the plugin.

**Comment by dangrossman** [comment]
You're going to have to explain this more clearly.

**Comment by fccpt** [comment]
When edit / submit a record the date is set to the default date set by:
this.startDate = moment().startOf('day');
this.endDate = moment().endOf('day');

I still can see the real date in input value property when inspect but the date displayed is the acutal computer date.

**Comment by dangrossman** [comment]
I still don't understand.

**Comment by dangrossman** [comment]
If you're saying that you are prepopulating an input and want the date picker attached to it to use that value, ensure your locale.format string matches the format of the date you put into the input value. If it can't parse your input, the picker will default to today.

**Comment by fccpt** [comment]
Exactly... except that the value has the same format.

**Comment by dangrossman** [comment]
Link to a page demonstrating the bug. I don't have time or inclination to decipher and attempt to reproduce for you.

**Comment by fccpt** [comment]
Can you please take a look at: http://s22.postimg.org/xbugxys8h/Screen_Shot_2015_11_17_at_17_07_02.jpg

I believe my locale.format is ok.
Thank you.

**Comment by dangrossman** [comment]
Now share the code?

**Comment by fccpt** [comment]
Dan, what do you need?

**Comment by dangrossman** [comment]
The code you used to create the date picker, or a working webpage to see it.

**Comment by fccpt** [comment]
https://gist.github.com/fccpt/2a79865c5cd861e8590c

**Comment by fccpt** [comment]
I'm working at a local server, but I can see the date returned by the server while the js is loading, which gets replaced right after...

**Comment by dangrossman** [comment]
Remove these two lines:

        "startDate": false,
        "endDate": false,

This setting cannot be a boolean. It should either be a date (date string, date object or moment object) or be omitted.

Here's a working demo showing that only removing those lines causes the input value to be used:

https://jsfiddle.net/81cbxzjh/2/

**Comment by fccpt** [comment]
Thank you so much,
Works flawlessly!
