### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by chandon** [dangrossman/bootstrap-daterangepicker#879]
When you define a range with an invalid date, the custom date field show a "Invalide date" message (message from moment.js). 

Is there a way to change the message without changing the moment.js source code ? (for example, to have a locale message instead of an english one)

**Comment by dangrossman** [comment]
I don't know what message you're referring to, but if it comes from moment.js, then nothing I change in my library will result in changing that message.

**Comment by chandon** [comment]
Thanks
The answer is to initialize moment.js locale. For moment v2.8 (perhaps not working with v2.10) 

    moment.locale(moment.locale(),{invalidDate:"Your_invalid_date_message"});
