### ISSUE TITLE
daterangepicker_start showing past date.

### ISSUE THREAD

**Issue by umesh-naik** [dangrossman/bootstrap-daterangepicker#880]
Hi, this is the problem I'm facing and the code goes like this:

var sDate = moment().subtract(7, "days").format('YYYY-MM-DD');
var eDate = moment().format("YYYY-MM-DD");

now in console, I'm getting expected result but when I'm passing these variables as::

startDate: "sDate",
endDate: "eDate"

then I'm getting this:

![invalid](https://cloud.githubusercontent.com/assets/11293361/11360985/8ff48f22-92af-11e5-8d11-6815f3df826c.png)

**Comment by dangrossman** [comment]
With quotes around "sDate" and "eDate", you're passing those words as the dates, instead of the content of the variables. The word "sDate" is not a date, hence the "Invalid date". You can also pass a moment object for either option, so it's not necessary to call `.format()`.
