### ISSUE TITLE
When I disable autoUpdateInput, the input remains blank

### ISSUE THREAD

**Issue by Leuloch** [dangrossman/bootstrap-daterangepicker#881]
You can test this bug directly on the [Configuration Generator](http://www.daterangepicker.com/#config)

**Comment by dangrossman** [comment]
That's the purpose of the setting.

**Comment by Leuloch** [comment]
I forgot to mention that even when I click the Apply button, nothing happens, the input remains blank.
If this is the expected behavior, what should I do to populate the field with the date range I've selected?

**Comment by dangrossman** [comment]
Yes, that's the expected behavior. You can populate your input with a callback function, or by listening for the apply event. The documentation is full of examples. One is even named "Input Initially Empty".

**Comment by Leuloch** [comment]
Sorry I did see that section, I though there was something like "a parameter" to populate the fields after I've clicked apply.  Wasn't expecting something like "listen to the even". But it's fine.

Thanks.

**Comment by benjieperez** [comment]
@dangrossman this is the test of what the issue he is saying, I test this code to your website and it seems, It doenst update the value even i set it.
![screenshot from 2018-07-19 15-03-06](https://user-images.githubusercontent.com/20369043/42926860-38639b02-8b65-11e8-8ac5-3c7b12ff4015.png)

**Comment by dangrossman** [comment]
@benjieperez Putting code in that box does not run it, and the input next to that box is not named #demo, which is why that didn't work.

If you put this into your console at http://www.daterangepicker.com it will work:

````
$('#config-demo').daterangepicker({ singleDatePicker: true, autoUpdateInput: false });

$('#config-demo').val('');

$('#config-demo').on('apply.daterangepicker', function(ev, picker) { $(this).val(picker.startDate.format('MM/DD/YYYY')); });
````

**Comment by zepernick** [comment]
version 3.0.3 source is calling `this.updateElement();` on the init of the plugin which is filling today's date.  We were also trying to leave our input empty until the user explicitly selected a date from the calendar.  None of the options seem to be able to stop it except for `autoUpdateInput: false` which then breaks the selection of the date from the calendar.

Commenting out line 446 solved the issue.

**Comment by dangrossman** [comment]
@zepernick If you ask the plugin not to fill in the date for you, you're supposed to provide your own code that does so. It's not "broken". You can put that code in your callback function, or an event listener that gets triggered when a new date range is selected. 

There's a full example here, labeled "Input Initially Empty":

http://www.daterangepicker.com/#example5 

You'll notice that `autoUpdateInput: false` is used, yet the input gets updated when you select a date.

**Comment by zepernick** [comment]
@dangrossman I did not mean to imply with "breaks" that it was a bug.  Just that the selection of the date from the calendar no longer populates the input (which is by design).  All I was really after was to stop the plugin init from populating the field.  Thank you for the example.  

I will try and listen for that event globally so it does not have to be managed for every one of our datepickers and still give us a upgrade path for the library.
