### ISSUE TITLE
I cannot create custom date ranges in different years

### ISSUE THREAD

**Issue by MatthewSwarbrick** [dangrossman/bootstrap-daterangepicker#882]
Say if I want to set a range between 01/01/2000 - 01/01/2010, this is quite fiddly to set up as show in the demonstration below:

![daterangepickerbug](https://cloud.githubusercontent.com/assets/8734164/11425764/32bf28c0-944f-11e5-9eab-ea09e3f114e2.gif)

It seems it always moves the left hand calendar whenever you set a date in the right hand calendar and vice versa, is there a way to disable that? I couldn't see it in the options

**Comment by MatthewSwarbrick** [comment]
I saw that this was introduced in version 2.x, so have changed the version I'm using to 1.3.23

**Comment by dangrossman** [comment]
You're looking for the `linkedCalendars` option.

**Comment by MatthewSwarbrick** [comment]
Yeah I saw that but didn't seem to change functionality. I had startDate and endDate set, I removed them and tried again and now it works! I tried creating a jsfiddle to reproduce the issue, but couldn't.
Thanks for letting me know about the linkedCalendars option
