### ISSUE TITLE
Set endDate equal to startDate on selection of startDate

### ISSUE THREAD

**Issue by PhilBroadbent** [dangrossman/bootstrap-daterangepicker#887]
Hi,

Many users of the application I work on want the date picker to automatically set the endDate equal to the startDate when they select the startDate. This is the same behavior as seen on many sites, especially travel/hotel sites (or startDate+1).

There is no API exposed for an actual 'onStartDateChange' event in order to add this function myself. And likewise the callback that can be provided only fires when both dates are selected.

Is there any way that I have missed that this can be done with bootstrap-daterangepicker?

Thanks.

**Comment by dangrossman** [comment]
That's not possible with this selection interface. The first date a user clicks on the calendars becomes the start date, and the second date they click becomes the end date. If the end date is already set by clicking the start date, clicking anywhere sets a new start date, so it's impossible to select a different end date. Most travel sites have two inputs with two single date pickers, which is totally different.
