### ISSUE TITLE
CSS classes sub optimal

### ISSUE THREAD

**Issue by johannesnagl** [dangrossman/bootstrap-daterangepicker#889]
Hi,

I just wanted to upgrade to your latest version and encountered some styling problems. Quick look in the underlying daterangepicker.css made clear that some class names of my app collide with your chosen class names.

It would be really nice to always prefix your internal classes with "bdp-" or something else. Another approach would be [BEM](http://getbem.com/introduction/). 

Biggest problems I've encountered are related to "calendar", "calendar-table", "left", "right".

**Comment by dangrossman** [comment]
Thanks for the feedback.

**Comment by johannesnagl** [comment]
is this something you'll address in the future, or where you would accept any PR? i'm not sure what the "closed issue" means for the future ;)

**Comment by dangrossman** [comment]
Probably not. I don't usually make breaking changes unless there's been at least a few people recommending the change. Nobody else has ever taken issue with the class names.

**Comment by johannesnagl** [comment]
ok, thanks for the additional info!
