### ISSUE TITLE
singleDatePicker when using time does not show daterange input at top

### ISSUE THREAD

**Issue by adamdva** [dangrossman/bootstrap-daterangepicker#890]
When
"singleDatePicker": true
The daterangepicker_input input and clock icon are not shown. The input is useful when a user wants to type the input, specially when using the timePicker function.

**Comment by dangrossman** [comment]
That's correct, and will not be changing. You may change your copy to work how you'd like.

**Comment by adamdva** [comment]
OK, I'm also not seeing the callback called when the widget is changed, only when Apply is clicked. Having issues with keeping original input and widget in sync, so will change my local copy.

**Comment by dangrossman** [comment]
The callback is triggered when the user has selected a new date/time. If you have a single date picker with time picker, that doesn't occur until the button is clicked or the widget is dismissed by clicking outside of it. 

You wouldn't want to start generating an expensive report 4 times as they click a date, click the hour, click the minute, click the second... when those were all just part of choosing the one date/time desired, and the whole thing may still be cancelled.
