### ISSUE TITLE
Disable on date over ability

### ISSUE THREAD

**Issue by spederiva** [dangrossman/bootstrap-daterangepicker#891]
When you over (with the mouse) on a date the from/to input field is updated automatically, this cause a little UX problem because after you select the "to" date the over continue working.

Need a option in order to make this disable if the programmer wishes

**Comment by dangrossman** [comment]
I disagree.

**Comment by spederiva** [comment]
<img width="620" alt="screen shot 2015-12-09 at 17 08 27" src="https://cloud.githubusercontent.com/assets/1193758/11688828/7f94ff6a-9e97-11e5-9e6a-accf0b7a0072.png">

look at this picture! 

the from date is set as 01/04/2015 but you see a different date in the input field.

why not give the option to disable this? working as default as you wish but with the option to disable it

lot of users of mine company request it after we undestand the flow as their work

**Comment by dangrossman** [comment]
You can disable it in your copy. I will not be adding this as an option.
