### ISSUE TITLE
How to configure multiple locale

### ISSUE THREAD

**Issue by Emyleen** [dangrossman/bootstrap-daterangepicker#893]
Hello, I was wondering how to configure daterangepicker to adapt it on every language? Is there a plugin for that? Tanks for your help.

**Comment by dangrossman** [comment]
Check off "locale (with example settings)" for an example of localizing the date picker.

http://www.daterangepicker.com/#config

There is no extra plugin or anything. You can also localize the global moment object; refer to moment.js's documentation.
