### ISSUE TITLE
Selecting a date incorrectly updates the previously selected end time

### ISSUE THREAD

**Issue by motin** [dangrossman/bootstrap-daterangepicker#895]
Say I want to schedule a campaign between two points in time to Date A at 15:00 to Date B at 18:00. 

Now I change the daterange A-B to A-C. Suddenly, the Date C time is set to 15:00 instead of the expected 18:00.

How can I configure the picker not to override the selected times when changing the date(s)?

**Comment by dangrossman** [comment]
There is no configuration for this. It will be improved in a future update.

**Comment by motin** [comment]
Ok thanks, good to know what to expect. Btw, shouldn't the issue remain open until that future update is released?

**Comment by dangrossman** [comment]
Subjective. It already was.

**Comment by motin** [comment]
Confused. What already was what?
