### ISSUE TITLE
Unable to select today in 'range' when 'autoUpdateInput: false'

### ISSUE THREAD

**Issue by mnelsonwhite** [dangrossman/bootstrap-daterangepicker#898]
Please see **[fiddle](https://jsfiddle.net/Lk8cjnp3/1/)**.

**Versions**
jQuery v1.11.3
Moment.js v2.10.6
daterangepicker v2.1.14

**Description**
When using the approach described in the documentation as ['input initially empty'](http://www.daterangepicker.com/#ex5) with a set of ranges, the Today item in the range.

It looks as though the initial state of the daterangepicker has the current start and end dates to be today and for this reason it identifies that the 'Today' range is already selected.

**Possible Solution**
Support nullable start and end dates or have a set/unset state.

**Comment by dangrossman** [comment]
The callback is only fired when the selected date range changes. Clicking the already selected range will not trigger a callback, but it will trigger the apply event. 

https://jsfiddle.net/mhc5u18L/

http://www.daterangepicker.com/#events

This behavior will not be changing.
