### ISSUE TITLE
Events after selecting start and end date

### ISSUE THREAD

**Issue by nnattawat** [dangrossman/bootstrap-daterangepicker#899]
I wonder whether you have the events that I can hook once start date and end date is selected.

**Comment by dangrossman** [comment]
http://www.daterangepicker.com/#events

**Comment by nnattawat** [comment]
Do you have an event after start date selected (not both start and end selected button clicked)?

**Comment by dangrossman** [comment]
No.

**Comment by nnattawat** [comment]
Thanks for explanation. My use case is a bit wired I use it with custom template where there are custom messages in the calendar. So when I use click check-in I wanna change message to 'Please select check out date' as in the following screenshot.
![screen shot 2015-12-17 at 3 32 02 pm](https://cloud.githubusercontent.com/assets/535365/11861372/9f0383f2-a4d3-11e5-84a5-3cf21a041893.png)

I have added the events on my fork and happy to do PR but I agree with you that you might not nee it as it is a rare use case.

**Comment by mightydes** [comment]
Why it was closed?
Assume, that we need to limit selection range to N days from `startDate`.
In this case i need an event handler for `startDate`, to dynamically change `options.maxDate` value.

**Comment by dangrossman** [comment]
It was closed because the question was answered. There is no event for that, so if you require one, you will need to create one.

**Comment by mightydes** [comment]
Can I feel free for PR?

**Comment by aminetchitooss** [comment]
Please how could we limit selection range to N days from startDate ?

**Comment by yoga-try-utomo** [comment]
hai @dangrossman ,, i have case just like @aminetchitooss .
i need to restrict user to change end date. so they only can change the start date.
what should i do ?

any help would be appreciated
thanks

**Comment by dangrossman** [comment]
You should probably use a date picker instead of a date range picker since your user is only actually selecting one date.

**Comment by yoga-try-utomo** [comment]
Hi @dangrossman thank you for your response.
I'm still using your helpfull plugin :)
I found the workaround with the `SingleDatePicker` option and made an adaptation with the event

Thank You

**Comment by pallavpunhani** [comment]
> Thanks for explanation. My use case is a bit wired I use it with custom template where there are custom messages in the calendar. So when I use click check-in I wanna change message to 'Please select check out date' as in the following screenshot.
> ![screen shot 2015-12-17 at 3 32 02 pm](https://cloud.githubusercontent.com/assets/535365/11861372/9f0383f2-a4d3-11e5-84a5-3cf21a041893.png)
> 
> I have added the events on my fork and happy to do PR but I agree with you that you might not nee it as it is a rare use case.

Hey @nnattawat , were you able to get this to work? I have a similar use case, and I need an event that gets fired on selecting startDate as well. Thanks for your help!

**Comment by cavasinf** [comment]
@dangrossman The visual effect of the date range is really important for an end user.
In my case, I just want to force date/week (d+7 for example) with the visual of the range.

I've created a PR, it only add two events `selected.date.start` & `selected.date.end`

```javascript
$('[data-widget="daterangepicker"]').on('selected.date.start',function (ev, picker) {
    const $that = $(this),
        forcedEndDate = picker.startDate.clone().add(7, 'days');

    $that.data('daterangepicker').setEndDate(forcedEndDate);
});
```

There is the PR : https://github.com/dangrossman/daterangepicker/pull/2217
