### ISSUE TITLE
Enable Custom Range selection from the start?

### ISSUE THREAD

**Issue by kmackay21** [dangrossman/bootstrap-daterangepicker#901]
Is there a way to enable Custom Range selection from the start so it opens up with the double calendars? As is, Today is selected from the start. Or even a way to have the double calendars open from the start/once textbox is selected?
Thanks.

**Comment by dangrossman** [comment]
If you provide predefined ranges, but the initial startDate/endDate settings don't match any of those ranges, "Custom Range" will be selected and both calendars will be displayed.

**Comment by kmackay21** [comment]
Thank you for quick reply. Much appreciated!
