### ISSUE TITLE
Cannot select PM on the Right Date

### ISSUE THREAD

**Issue by jkstrawn** [dangrossman/bootstrap-daterangepicker#902]
The new code added for "Preserve the time already selected" on line 850 is breaking my time picker. Its manifesting as two issues:

1. When I have an AM time slot selected for both sides of the time picker, and I try to change the ampmselector on the right side to PM, then when it rebuilds the timepicker it sets it back to AM.

Because of this bug, another one comes up:

2. When both sides are set to AM times, and you change the left picker to PM, it stays. But if you then choose a date, then entire date picker turns to NaNs. (Because the right side cannot be set to PM, and therefore all the available times are disabled since they are all before the PM slot you just chose on the left side. Making the right side date invalid, and cascading to the rest of the calendar)

I'm not sure if the code block starting on line 850 is breaking the picker only for me, but I think it should be addressed.

**Comment by dangrossman** [comment]
Any chance you can give me an exact combination of dates and times that make this happen, so I don't have to guess? My guesses so far haven't turned up the bugs, though I'm sure they're there.

**Comment by jkstrawn** [comment]
http://jsfiddle.net/skwjo689/1/

Click any date.

It seems the problems revolves around this issue: https://bugs.jquery.com/ticket/13097

On line 566 when it tries to retrieve the hour/min/second from the time picker, they're all disabled and return null, which messes up everything else.

**Comment by dangrossman** [comment]
Thanks, that helps. It now takes into account the AM/PM selection, which fixed it for me on your fiddle. I'll push the fix right after I finish typing this. Added a sanity check too, just in case. I should've reviewed the pull request that added this bug better.

**Comment by dangrossman** [comment]
Reopening this because there's still a bug, and I'm probably too tired to track it down tonight.
