### ISSUE TITLE
Toggle display possible issue

### ISSUE THREAD

**Issue by matfish2** [dangrossman/bootstrap-daterangepicker#909]
I'm not sure what in my CSS might be causing this, but the datepicker is not displayed when `display:none` is removed.
I fixed it by explicitly adding `display:block`.

Changed line 1077:

From:
 `this.container.show();`
To:
`this.container.css("display","block");`

**Comment by dangrossman** [comment]
Or, don't remove `display:none`.

**Comment by matfish2** [comment]
I didn't remove `display:none`. It is removed when `this.container.show()` is called.
My change adds 'display:block' on top of this, thus ensuring, or at least making it more probable, that the datepicker shows.
