### ISSUE TITLE
Add Some Methods

### ISSUE THREAD

**Issue by ecosu** [dangrossman/bootstrap-daterangepicker#910]
I think u can add two methods like 'getStartDate' and 'getEndDate'.Now if i want to get the date range,I have to get the text of the tag and then split it.

**Comment by dangrossman** [comment]
You can use `$('yourelement').data('daterangepicker').startDate` and `$('yourelement').data('daterangepicker').endDate`. 

However, any time the selected dates are changed, you have direct access to them either via parameters to your callback function, or the picker object passed to your event listener, so you shouldn't need to write it out like that.

**Comment by ecosu** [comment]
thank you！
