### ISSUE TITLE
Problem with .val()

### ISSUE THREAD

**Issue by svetlinyotov** [dangrossman/bootstrap-daterangepicker#911]
When dynamically enter value of an input with jQuery this way: 
`$("#time_range_edit_input").val("12/30/2015 6:30 AM - 12/30/2015 11:30 AM");`, then I see that the value is updated in the input but when I click on it and the calendars show up, a default range is shown.

**Comment by dangrossman** [comment]
That's true. The picker does not know you programmatically changed the input's value.

**Comment by svetlinyotov** [comment]
Is there a way to make the picker know that the value is changed?
