### ISSUE TITLE
Disabling and enabling the daterangepicker

### ISSUE THREAD

**Issue by ewamarciniak** [dangrossman/bootstrap-daterangepicker#913]
Is there a way that the picker can be disabled? Disabling the input field still allows the picker to open a calendar.

**Comment by dangrossman** [comment]
You can remove it with `$(element).data('daterangepicker').remove();`

**Comment by saif003** [comment]
If you are interested in dynamically disabling / re enabling the daterangepicker, a better approach would be to dynamically add the following styles / class to the element when you ever you want to.
```
.disabled-picker {
  opacity: 0.7;
  pointer-events: none;
}
```
Although not sure whether `pointer-events` property is well accepted across browsers or not.

**Comment by GiuServ** [comment]
> 
> 
> You can remove it with `$(element).data('daterangepicker').remove();`

This should be added to the examples page. 
It's usefull when you want to initialize the plugin, and then disable it.
