### ISSUE TITLE
The Today menu selection is not working

### ISSUE THREAD

**Issue by ewardjr** [dangrossman/bootstrap-daterangepicker#921]
When I click on the Today menu item nothing happens.  If I change the date ranges from: 
<b>'Today': [moment(), moment()], </b> to <b>'Today': [moment(), moment().subtract(1, 'days')],</b>  then it appears to work.

Also, related to this, if the choice for Today is 'Today': [moment(), moment()] and I click on the field just the range options appear with not calendar (unless of course I select Custom), once I do change it to subtract a day and clicking on Today works the calendar's are show along with the ranges all the time. the

**Comment by dangrossman** [comment]
The default startDate and endDate values (the currently selected date range) are today's date, if you don't specify them yourself.

Since "today" is already selected, clicking "today" again will have no effect. This is expected.

It is also not expected for the calendars to be shown until you click on "Custom Range".

**Comment by ewardjr** [comment]
This behavior occurs even when I select another menu option and try to reselect today.

Elliott Ward
Primary Solutions, Inc.
Web Development Lead
Phone: 614.430.0355

[Description: Description: Description: Description: PSI Logo3]
Our vision is to be the recognized leader of information management solutions for Ohio’s DD community.

**Comment by dangrossman** [comment]
You have not described any unintended behavior.

**Comment by ewardjr** [comment]
Thank you for your reply. But just so I understand, they today option on the daterange picker does not pick today, using the following code:

                                            $(document).ready(function () {
                                                $('#ServiceDate').daterangepicker({
                                                    "opens": "right",
                                                    ranges: {
                                                        'Today': [moment(), moment()],
                                                        'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                                                        'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                                                        'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                                                        'This Month': [moment().startOf('month'), moment().endOf('month')],
                                                        'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                                                    }
                                                }, function cb(start, end) {
                                                    $find("<%= RadAjaxManager1.ClientID%>").ajaxRequest('ServiceStartDate=' + start.format('MM/DD/YYYY') + ';ServiceEndDate=' + end.format('MM/DD/YYYY'));
                                                });

                                                $('#ServiceDate').on('cancel.daterangepicker', function (ev, picker) {
                                                    //do something, like clearing an input
                                                    $find("<%= RadAjaxManager1.ClientID %>").ajaxRequest('Cancel:ServiceDateFilter');
                                                });
                                            });

No matter what menu items I select other than they today option, the ‘Today’ option is not causing a callback. I am suree it has to do with how I have declared the picker.


Elliott Ward
Primary Solutions, Inc.
Web Development Lead
Phone: 614.430.0355

[Description: Description: Description: Description: PSI Logo3]
Our vision is to be the recognized leader of information management solutions for Ohio’s DD community.

**Comment by dangrossman** [comment]
Your callback will only be triggered when the selected date range has changed.

The selected date range has not changed when you click on "today" because "today" is already selected.

"Today" is already selected, because the current date is the default value of the startDate and endDate options, which you haven't specified.

You should trigger your callback to run once at initialization, otherwise listen for the apply event instead of using a callback. Because, again, your callback will not be triggered when clicking "today" when "today" is already selected.

**Comment by ewardjr** [comment]
Thank you for your patience. I will give it a try. What is confusing me, is that I will select other menu items, “Yesterday”, “30 day back” the date ranges will change, I then select “Today” and it is not changing.


Elliott Ward
Primary Solutions, Inc.
Web Development Lead
Phone: 614.430.0355

[Description: Description: Description: Description: PSI Logo3]
Our vision is to be the recognized leader of information management solutions for Ohio’s DD community.

**Comment by dangrossman** [comment]
Your callback will only be triggered when the selected date range has changed.

Clicking "Yesterday" or "30 day back" represents a change in the selected dates from [today, today] to [yesterday, yesterday] or [30 days ago, today].

Clicking "Today" represents selecting [today, today] when the current date range is already [today, today]. That's not a change, so your callback is not triggered.

**Comment by ewardjr** [comment]
Ok. Thank you for your time.

Elliott Ward
Primary Solutions, Inc.
Web Development Lead
Phone: 614.430.0355

[Description: Description: Description: Description: PSI Logo3]
Our vision is to be the recognized leader of information management solutions for Ohio’s DD community.
