### ISSUE TITLE
showDropdowns limitation/bug

### ISSUE THREAD

**Issue by iamvitali** [dangrossman/bootstrap-daterangepicker#924]
Hi,
If I set showDropdowns to true and have dropdowns for start and end dates, if I choose a year for start date it sets the year in the end year to the same one, same happens other way around - if I chose the end year it sets the start year to the same one. Ah, you as well need to click on the day after selecting the year in the dropdown for it to reset the other dropdown.

The reason why I'm using the dropdowns is to allow users to easily select the year ranges but this dropdown resetting seems weird.

I'm on 2.1.17 version (latest) with 2.10.3 moment.

**Comment by dangrossman** [comment]
The two calendars always display adjacent months (e.g. January and February of the same year) unless you set `linkedCalendars: false`. You're confusing left/right with start/end. You can click on either calendar to choose the start or the end date of your range. That's determined by the order of your clicks (first click is the start of your range, second click is the end of your range) not by which calendar you click the date in.
