### ISSUE TITLE
difference version "atmospherejs 2.1.13" vs "github 2.1.17"?

### ISSUE THREAD

**Issue by thearabbit** [dangrossman/bootstrap-daterangepicker#925]
difference version "atmospherejs 2.1.13" vs "github 2.1.17"?

**Comment by dangrossman** [comment]
I'm not a meteor developer. I don't know anything about atmospherejs, or how packages get on there.

**Comment by thearabbit** [comment]
but I see `dangrossman:bootstrap-daterangepicker` pcakge in `meteor package`.

**Comment by dangrossman** [comment]
Someone else put it there.

**Comment by thearabbit** [comment]
The `packags.js` file is for the `meteor package`.
So maybe miss to publish on `atmosphere`.

**Comment by dangrossman** [comment]
Someone else submitted that file to this repository. I have never published it on atmosphere.

**Comment by s7dhansh** [comment]
@dangrossman you have to simply go to the directory and run `meteor publish`, given that you have meteor installed and you know the credentials to the dangrossman account on atmospherejs.com.
@dotansimha started the official package. he should have the credentials i suppose.

**Comment by dangrossman** [comment]
I do not have meteor installed or know the credentials to any atmospherejs account.
