### ISSUE TITLE
Has anyone made this work as a CommonJS module? 

### ISSUE THREAD

**Issue by vmasto** [dangrossman/bootstrap-daterangepicker#933]
I'm always getting the following error: `(0 , _jquery2.default)(...).daterangepicker is not a function`, and the daterangepicker object exported by browserify seems to be empty.

Perhaps @kopax has a solution, I saw he has been working on it, @kopax if you can go through your workflow/tooling? I'm using browserify.

**Comment by kopax** [comment]
You will have to debug it using console.log in `node_modules/daterangepicker/daterangepicker.js`

Start doing this  : 


  (function(root, factory) {

    if (typeof define === 'function' && define.amd) {
      define(['moment', 'jquery', 'exports'], function(momentjs, $, exports) {
        console.log("AMD", exports, momentjs, $);
        root.daterangepicker = factory(root, exports, momentjs, $);
      });

    } else if (typeof exports !== 'undefined') {
        var momentjs = require('moment');
        var jQuery = (typeof window != 'undefined') ? window.jQuery : undefined;  //isomorphic issue
        if (!jQuery) {
            try {
                jQuery = require('jquery');
                if (!jQuery.fn) jQuery.fn = {}; //isomorphic issue
            } catch (err) {
                if (!jQuery) throw new Error('jQuery dependency not found');
            }
        }
      console.log("nodejs", exports, momentjs, $);
      factory(root, exports, momentjs, jQuery);

    // Finally, as a browser global.
    } else {
      console.log("window", exports, momentjs, $);
      root.daterangepicker = factory(root, {}, root.moment || moment, (root.jQuery || root.Zepto || root.ender || root.$));
    }

  }(this || {}, function(root, daterangepicker, moment, $) { // 'this' doesn't exist on a server
  console.log("in function", daterangepicker, momentjs, $);


Ex explained here : 

    }(this || {}, function(root, daterangepicker, moment, $) { // 'this' doesn't exist on a server

This shoulnd be here, it should be : 

    }(this || {}, function(root, exports, moment, $) { // 'this' doesn't exist on a server    


and at the end of the file before : 

    return DateRangePicker;

add : 

    exports.DateRangePicker = DateRangePicker;

**Comment by vmasto** [comment]
Yeah makes sense, I did it similarly. I'm not sure what's the point of having the module factories if they're not working. I'll try to push a PR.

**Comment by dangrossman** [comment]
Someone else contributed that code. I have no way to verify/test that it works in whatever environment you intend to use it in.

**Comment by vmasto** [comment]
I know yeah, no problem. I thought we should have this ticket for people searching why it's not working until we can push a fix for this, I'll try to work on it.

**Comment by NAVINCOC** [comment]
i dont know how but in my system **typeof define === 'function'** is 'true' and when same code is run in different system its 'false' and **typeof exports !== 'undefined'** is 'true' in other system.
can anyone tell me why this is happning.

![screenshot from 2016-04-08 13 43 46](https://cloud.githubusercontent.com/assets/18345050/14378039/9aef786e-fd90-11e5-8454-f66b17ba6b83.png)
