### ISSUE TITLE
Option for not autoselecting predefined ranges when using custom picker

### ISSUE THREAD

**Issue by fantapop** [dangrossman/bootstrap-daterangepicker#934]
Every once and a while our users get stuck while using the date picker because they're trying to select the custom range option when the custom range option is already open but it looks like a preset option is chosen.

I tend to agree that this UX is confusing.  I think this is the code that does this:

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L586

It might be nice to add an option for making this behavior optional.

**Comment by jennbriden** [comment]
+1 This is a frustrating user experience.

Repro:
1. Open date picker
2. Click Custom
3. Select a range of a week within the calendar. Notice that the "Last 7 Days" option is selected and that Custom isn't any longer. 
4. Oops, but I meant to pick 8 days. Let me go back and click Custom again to get that set up. Notice that Custom is disabled and not selectable. I have to refresh the page. 

Expected experience:
Once I click Custom, leave me in custom mode.

**Comment by dangrossman** [comment]
You never left custom mode. You did not need to refresh the page. The only thing unexpected is that the highlighted range name corresponds to the last completed date selection, rather than the last label you clicked.

**Comment by fantapop** [comment]
oh, I see.  I didn't realize that the label was still selected from the last time the range was set.  I wonder if this could be fixed by css alone.  Saying if highlight custom range if the calendar is open.  Either that or setting the clicked on element to active.
