### ISSUE TITLE
Unexpected behavior selecting three or more months range

### ISSUE THREAD

**Issue by llstarscreamll** [dangrossman/bootstrap-daterangepicker#937]
when selecting 1st january as start and 25 august as end, the second calendar goes to one month after start date, can't see end date selected. I have the same behaviour when navigating through month to month, I can't see the start or end date selected.

@version: 2.1.17

```javascript

$('#reportrange').daterangepicker({
        format: 'MM/DD/YYYY',
        dateLimit: { months: 12 },
        showDropdowns: true,
        showWeekNumbers: true,
        ranges: {
           'Hoy': [moment(), moment()],
           'Ayer': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Últimos 7 Dias': [moment().subtract(6, 'days'), moment()],
           'Últimos 30 Dias': [moment().subtract(29, 'days'), moment()],
           'Este Mes': [moment().startOf('month'), moment().endOf('month')],
           'Mes Pasado': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        opens: 'left',
        drops: 'down',
    }, function(start, end, label) {
        $('#from').attr('value', start.format('YYYY-MM-DD'));
        $('#to').attr('value', end.format('YYYY-MM-DD'));
    });

```

**Comment by dangrossman** [comment]
That is expected behavior. The calendars always display adjacent months. This is how date range pickers work on most every travel and booking site.

If you'd like the two calendars to be able to show any months simultaneously, set the option `linkedCalendars: false`.

**Comment by llstarscreamll** [comment]
oh!! Excuse me, you are right, and it's documented, thank you so much for your prompt answer... and of course, Great work !! ^_^
