### ISSUE TITLE
using `currentTarget` instead of `target`

### ISSUE THREAD

**Issue by nnattawat** [dangrossman/bootstrap-daterangepicker#938]
Hi, thanks for the great plugin. I have used it to created the calendar as shown below.

![screen shot 2016-01-21 at 12 18 13 pm](https://cloud.githubusercontent.com/assets/535365/12468580/154662ac-c039-11e5-95ba-4378927613b8.png)

Basically, I have added some element on each date cell to show some status on each date, however, when I click on the element that I added, the calendar will be selected as in the code check: 
```
clickDate: function(e) { 
  if (!$(e.target).hasClass('available')) return;
}
```

I have fix it at my end by attach click event on my added div and do 
```
e.stopPropagation();
 $(this).parent().click(); 
```
That works fine but I was wondering wether it's better to use `e.currentTarget` every where in your code? 

I can make changes, test and create a PR if needed.

Thanks

**Comment by dangrossman** [comment]
Could you explain why I would want to change my code?

**Comment by nnattawat** [comment]
So that it will work with extra element in the date cell (if someone custom it). Now the cell wont be able to click.

**Comment by dangrossman** [comment]
In that case, please do not bother creating a PR.
