### ISSUE TITLE
Date Picker - Typing a date in for one end of the range and then clicking a date on the other side of the range results in the Apply button being disabled

### ISSUE THREAD

**Issue by jennbriden** [dangrossman/bootstrap-daterangepicker#939]
Repro:

1. Pick Custom Range
2. Click a date for the first field (mouse).
3. Go into the text box for the end field and type a date. 
4. Try to click Apply. 

Expected
Apply is enabled and works

Actual
Apply is disabled (although the color indicates it's still enabled)

This experience also affects the date picker if you start with the end range first.

**Comment by dangrossman** [comment]
If you start choosing a date range with the mouse, you have to finish with the mouse. Two clicks to make a selection. You can type, or you can click, but you can't do both. Sorry that this broke your expectations, I don't expect to change it.
