### ISSUE TITLE
User can enter garbage for date and get a valid date

### ISSUE THREAD

**Issue by RonanAscendant** [dangrossman/bootstrap-daterangepicker#947]
For example, you have a date in one of the input boxes:

03/16/2016

The user deletes the "016" and types "lkajsd;lklkj;" and loses focus. The datepicker allows the date to change to the year "0002". This is not fixable by simply setting a minimum year - because they can also produce undesirable behavior.

The correct thing to do would be within formInputsChanged, if this.element is an input box, fire a call to isInvalidDate again when checking isValid() on start and end, to give the consuming component the opportunity to invalidate the date. Alternatively, expose an option to enable strict date parsing, and update the moment() calls to use the flag. Or both :)

For now I'm going to access the _i private on moment because I really don't want to maintain another custom fork. I will try to submit a pull request with this change for you.

**Comment by dangrossman** [comment]
You should expect bad inputs from your user. Stricter validation in the UI won't stop them from typing gibberish, or sending weird things directly to your server.

**Comment by RonanAscendant** [comment]
Yes, you should expect bad inputs from your user.. expecting means addressing it. I'm offering a non-invasive solution to allow the consumer of the control to address the issue. The control, as implemented, forces the consumer to *guess* when bad input has been provided. 

I'm not suggesting using UI validation. I'm suggesting including a hook that lets the developer validate how they want instead of having to guess.
