### ISSUE TITLE
daterangepicker-bs3.css and bower

### ISSUE THREAD

**Issue by stadskle** [dangrossman/bootstrap-daterangepicker#950]
Hi,

How can I get the bootstrap specific files when installing using bower?

daterangepicker-bs3.css
daterangepicker-bs2.css

**Comment by dangrossman** [comment]
I am not a bower expert. Perhaps there's a bower mailing list, or stackoverflow.

**Comment by stadskle** [comment]
Not really about bower, should not these files be a part of this project? I have seen them on other pages. They are not on github (hence not being installed as part of the bower installation).

**Comment by dangrossman** [comment]
Oh, I didn't understand your question. Those are not part of the current library. They're from a much much older version. It's `daterangepicker.css` now.

**Comment by stadskle** [comment]
Ok, thanks.
