### ISSUE TITLE
Try to parse dates as ISO 8601 strings first

### ISSUE THREAD

**Issue by StevenLiekens** [dangrossman/bootstrap-daterangepicker#957]
It's not possible to set initial date values as ISO 8601 strings because the code always uses the format of the `locale` object (default: `MM/DD/YYYY`).

Example:

```js
if (typeof options.startDate === 'string')
    this.startDate = moment(options.startDate, this.locale.format);
```
This bit me pretty hard when working with a backend that returns ISO strings only.

Fix: change the code to prefer `moment.ISO_8601` over `this.locale.format`.

```js
if (typeof options.startDate === 'string')
    this.startDate = moment(options.startDate, [moment.ISO_8601, this.locale.format]);
```

**Comment by dangrossman** [comment]
This is not an issue. You should convert from ISO format to date object *before* passing it in as an option to a daterangepicker.

**Comment by StevenLiekens** [comment]
That's not possible in my setup. My backend is a REST API that returns the datepicker options object as a JSON object. It's not possible to assign dates in JSON so it uses ISO 8601 strings instead.

**Comment by StevenLiekens** [comment]
Also I spent 4 hours figuring out why your code does not follow Moment.js default date parsing logic. How is it not an issue?

**Comment by StevenLiekens** [comment]
Please if you're gonna use Moment.js for handling dates then be consistent with its default implementation: http://momentjs.com/docs/#/parsing/

> When creating a moment from a string, we first check if the string matches known ISO 8601 formats, then fall back to new Date(string) if a known format is not found.

**Comment by StevenLiekens** [comment]
> The current default MM/DD/YYYY makes no sense. It is not ISO-compliant,

This is also the reason why this change is backwards compatible.

**Comment by dangrossman** [comment]
You can convert it to a date/moment object in your frontend code. You do not need to change your API.

````
start = moment(your-iso-date);
$('#element').daterangepicker({ startDate: start });
````

**Comment by dangrossman** [comment]
You do not need to change your API. 

Nor does the Date Range Picker have to parse any dates from your API, so this entire discussion about parsing logic is unnecessary.

All integration points for the Date Range Picker (constructor, settings, methods) take date or moment objects as well as strings. You should provide a date or moment object when writing your frontend code.

````
start = json_response.date_field;

//or
start = moment(json_response.date_field);

//then create the UI widget
$('#element').daterangepicker({ startDate: start });
````

The Date Range Picker is a UI widget, not a date parsing library. The format string (MM/DD/YYYY, or whatever you want ti to be) is meant for humans. It is for displaying dates on a webpage, and for consuming dates entered by humans in a form. Humans don't read or write ISO dates, or generally comply with international specifications of any kind.

**Comment by StevenLiekens** [comment]
You still don't get it. This is not my code.
```js
start = json_response.date_field;
$('#element').daterangepicker({ startDate: start });
````

This is my code.
```js
json_response = { startDate: "2016-02-01T00:00:00+01:00", endDate: "2016-02-04T18:53:42+01:00"  }

// in reality, json_response is returned by a webservice instead of generated on the client side
$('#element').daterangepicker(json_response);
```

I absolutely don't mean to use ISO dates in the widget itself. I only mean to use ISO dates to set the initial values.

Your code DOES contain parsing logic (i.e. calls to `moment(string)`) so this is all much more relevant than you make it out to be.

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L169

**Comment by Ruhrpottpatriot** [comment]
> All integration points for the Date Range Picker (constructor, settings, methods) take date or moment objects as well as strings. You should provide a date or moment object when writing your frontend code.

He *is* passing a date object to your code, but since your code uses the US date standard, your code is producing wrong results for anyone not using said standard, which *is* a bug. The date library you are using in your code is *explicitly* stating, that you should you ISO 8601 to handle dates, which you are **not** doing.

This bug report is absolutely valid, and stating that the problem described is not a bug, tells me, you either don't know your code, our are ignorant about bugs.

**Comment by dangrossman** [comment]
He is not passing a date object to the code, he's passing a string. "2016-02-01T00:00:00+01:00" is a string, not a [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date).

I'm telling him not to pass that string to the date picker constructor, since it doesn't conform to the input specification of this library: a date object, a moment object, or a string matching the `locale.format` format string.

I understand "this is not my code", I am telling you to write different code.

**Comment by StevenLiekens** [comment]
You're absolutely mental if you think US date strings are a sensible requirement and ISO dates should be banned

**Comment by dangrossman** [comment]
There is no requirement of US date strings, nor any ban of ISO dates. This discussion is over.
