### ISSUE TITLE
Option to have control on populating the date on hover

### ISSUE THREAD

**Issue by sarathkumarbaskaran** [dangrossman/bootstrap-daterangepicker#964]
This actually confuses the end user. 

First hover - start date (the hovered date will be populated in the start date field)
Second hover -end date (the hovered date will be populated in the end date field)

Assume both the first and end date are selected, but on further hovering (third time), it again populates the hovered date in start date field. This actually confuses the end user.

**Comment by dangrossman** [comment]
This is a visual indicator showing the user what the result of clicking the thing their mouse is over would do. I'm sorry that you are confused by it.

**Comment by sarathkumarbaskaran** [comment]
Absolutely, I'm confused..
I have selected the from date and to date, so it is fixed. Then again the from date input indicator changes when I try to move away from the date range picker.

**Comment by sarathkumarbaskaran** [comment]
#961

**Comment by jschuler** [comment]
This also gets rid of the hover over date change previews:
daterangepicker.prototype.hoverDate = function() {};
