### ISSUE TITLE
Time Range within a single Date

### ISSUE THREAD

**Issue by zthomas1** [dangrossman/bootstrap-daterangepicker#970]
Good afternooon Sir, thank you for this contribution to the community, excellent work.  

One use case that my company and I imagine others would find useful is the ability to support a time range for a single date for scheduling a meeting or similar type situation.

I was curious if there are any plans to handle this use case?

Thank you for your time.

**Comment by dangrossman** [comment]
You can already select the same date using this UI, but it's not very intuitive for scheduling a meeting. You probably want to just have a dropdown menu. You know, a plain old HTML `<select>` to choose the meeting time.

**Comment by zthomas1** [comment]
Good morning Sir. I hope you are well. Our group is trying to use this picker in a variety of situations to provide a consistent UI experience.  Unfortunately, the scenario below is the only one that is giving us some trouble, so, kudos for that!  

In any case, would you consider accepting a pull request if I incorporated this functionality when the picker is in single date mode?

Thank you for your time.

-Zach

**Comment by dangrossman** [comment]
I would likely not accept such a pull request

**Comment by sman591** [comment]
@dangrossman Is there a reason you wouldn't accept such pull request? I'm also looking for this exact functionality for meeting-like events.

@zthomas1 Did you come up with a solution to only display a single date but maintain separate start & end times?

**Comment by zthomas1** [comment]
@sman591 We ended up using separate text boxes for the times.  I too was planning to use it for meeting scheduling.  Our designers are not thrilled about it but, we ultimately decided that we were not going to maintain a customized version of this control in our product.
