### ISSUE TITLE
Touchend event closes calendar when scrolling on touch devices

### ISSUE THREAD

**Issue by LukeKB** [dangrossman/bootstrap-daterangepicker#972]
Line 1062:
This is not ideal for touch devices. Often the daterangepicker calendar
will not be fully inside the viewport on opening. Users then need to
scroll to access the rest of the calendar, however this touchend event
proceeds to hide it. I have noticed this particularly on iPad,
especially when using option drops: "up"

**Comment by dangrossman** [comment]
Touching outside of the picker UI is meant to be a way to dismiss it. I'm not sure how to reconcile that with your suggestion.
