### ISSUE TITLE
Format option doesn't work

### ISSUE THREAD

**Issue by ogazioglu** [dangrossman/bootstrap-daterangepicker#977]
I set the format as 'YYYY-MM-DD' or 'DD.MM.YYYY' but output is always 'MM/DD/YYYY'.
Problem occurs if I set date object instead of string input.
It was working but it had broken with a version...

**Comment by ogazioglu** [comment]
Oh re-checked out the documentation and i saw that format is moved into locale option. I moved my config and solved my issue. Sorry...

**Comment by Frozenlock** [comment]
Got the same problem.

Might be wise to explain the recent changes in the readme.

**Comment by dangrossman** [comment]
This isn't a recent change; it came with v2.0.0, a complete rewrite of this library and a new website for it in July 2015.
