### ISSUE TITLE
Multiple fields

### ISSUE THREAD

**Issue by hlarcher** [dangrossman/bootstrap-daterangepicker#978]
Hi, I have a form with several inputs with the plugin in single mode attached to them, when I type a date and press enter on the first field all goes well but when I do it on any of the other fields it does not close the calendar and in the apply.daterangepicker the e.element is pointing to the first field.
If I remove the first field it does the same but with the second.
So what I'm thinking is that the apply.daterangepicker is returning the first element with the plugin that it finds instead of returning the element itself.
Also, when I tab out of any field it doesnt fire the apply.daterangepicker.

**Comment by dangrossman** [comment]
I do not see this issue at http://www.daterangepicker.com which has lots of date pickers on the page, and uses the apply event. You haven't provided anything necessary to help you with your problem, like code you're using or a fiddle or other live example of the issue.
