### ISSUE TITLE
Restrict dates

### ISSUE THREAD

**Issue by bralemili** [dangrossman/bootstrap-daterangepicker#981]
Is there a way to provide a date-range array to the calendar and restrict those dates or change the background color?

btw. The plugin is great!
Thank you

**Comment by dangrossman** [comment]
Yes, it's the `isInvalidDate` setting. You provide a function that takes a date as a parameter, and returns true if that date should be disabled, or false otherwise.

**Comment by bralemili** [comment]
Thank you, I was looking through the documentation and probably skipped that part.
I knew it had it, because the plugin is just awesome :)
