### ISSUE TITLE
Position of datepicker on fixed element

### ISSUE THREAD

**Issue by jivanshr** [dangrossman/bootstrap-daterangepicker#982]
When we place input(which allow datepicker to open) within a div like modal dialog box with styled position fixed, that datepicker(opened) does not retain its position while scrolling.

**Comment by dangrossman** [comment]
Try setting the `parentEl` option so that the picker is part of or inside of the modal, rather than attached to the document body.

**Comment by jivanshr** [comment]
thanks a lot it worked!
