### ISSUE TITLE
When maxDate is set to current month, opening a custom range should show previous and current month VS current and next (which is invalid)

### ISSUE THREAD

**Issue by TheDartCode** [dangrossman/bootstrap-daterangepicker#984]
When we have linkedCalendars and maxDate set to the current month, and select "custom range", the two calendars that open up show the current and next month.
However, since maxDate is in the current month, it would be more useful to show  the previous and the current month.

Proof: https://jsbin.com/holagob/1/edit?html,css,js,output

**Comment by tim-u** [comment]
+1, I noticed it too.
