### ISSUE TITLE
Time selection closes picker

### ISSUE THREAD

**Issue by zthomas1** [dangrossman/bootstrap-daterangepicker#991]
During execution of DateRange with Time selection, if I edit the input directly and then click on any of the time drop-down menu's the hide event fires and the picker gets hidden??

If i select new dates everything works perfectly.  Is this a possible bug or am I missing something in the lifecycle.

Thank you for any help.

**Comment by dangrossman** [comment]
I'm not able to reproduce this at http://www.daterangepicker.com/ using your description

**Comment by zthomas1** [comment]
My configuration is specified below, I hope this helps.

.daterangepicker({
          "locale": {
            "format": "YYYY-MM-DD HHmm"
          },
          "timePicker": true,
          "timePicker24Hour": true,
          "autoUpdateInput": false,
          "timePickerIncrement": 5,
          "ranges": {
            'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Last 7 Days': [moment().subtract(6, 'days'), moment()],
            'Last 30 Days': [moment().subtract(29, 'days'), moment()],
            'This Month': [moment().startOf('month'), moment().endOf('month')],
            'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
          },
        }, function (start_date, end_date) {
          this.element[0].value = start_date.format(YYYY-MM-DD HHmm) + self.rangeSeparator + end_date.format(YYYY-MM-DD HHmm);
        });

**Comment by dangrossman** [comment]
I'm not able to reproduce it with that code either

**Comment by zthomas1** [comment]
I’ll put together a jsfiddle.

-Zach

**Comment by zthomas1** [comment]
I stripped my use case down to attempt to create jsfiddle example... the problem disappeared... Doh
