### ISSUE TITLE
ranges as array instead of hash

### ISSUE THREAD

**Issue by cgalvarino** [dangrossman/bootstrap-daterangepicker#992]
What a great daterangepicker.  Many thanks!

A humble suggestion is that instead of treating ranges as a hash whose order is not guaranteed, switch gears and assume that ranges is an array.

E.g.
```
ranges = [
  {key: '2015', value: [moment('2015-01-01'), moment('2015-12-31')]},
  ...
];
```

A lazy implementation that does the trick is here, https://github.com/cgalvarino/bootstrap-daterangepicker/commit/de5f26eada256688544c8cd7fd7137a459f1e6f6.  Not worthy of a PR, but I wonder if anyone else would benefit.  Otherwise, the order of options in the range list is most likely alphabetical.

Thanks again!

**Comment by cgalvarino** [comment]
I just realized that my hack doesn't work out of the box.  I'll keep banging on it.  But the idea is there.

**Comment by dangrossman** [comment]
The order of the options is not alphabetical in any browser. This is a non-issue IMO.
