### ISSUE TITLE
Moment.js Deprecation Warning

### ISSUE THREAD

**Issue by zthomas1** [dangrossman/bootstrap-daterangepicker#993]
When the picker is first expanded and the user hover's over "Custom Range" line 871 creates the following warning:

Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.

**Comment by dangrossman** [comment]
Are you using an old copy of this library?

**Comment by zthomas1** [comment]
I was using an older version but, i updated to the latest 2.11.2 and the warning persists.
Thank you for responding!

**Comment by dangrossman** [comment]
Current version is 2.1.18 ...

**Comment by zthomas1** [comment]
I meant that I update my moment.js to 2.11.2, I was using picker 2.1.17, 2.1.18 does not seem to show a warning.  Just when I thought I had a real issue, you already beat me to it.

Hats off Sir.

**Comment by dangrossman** [comment]
2.1.17 didn't have this issue either. It hasn't existed in, oh, a year or so?
