### ISSUE TITLE
Date cell class `.off`

### ISSUE THREAD

**Issue by nnattawat** [dangrossman/bootstrap-daterangepicker#996]
Quick question I wonder why all days before `minDate` have to have class `off`? I think it should just only have `disabled`.

PS: What I try to do is to hide all dates that are not the the months from the calendar which I was assuming all class `.off`.

**Comment by dangrossman** [comment]
I don't know. I can't remember when in the 615 versions of this code that came to be, or why, or what would be affected by changing it.
