### ISSUE TITLE
Different results for ranges when using timepicker

### ISSUE THREAD

**Issue by eskimoblood** [dangrossman/bootstrap-daterangepicker#997]
Is there a way to always have the same result for ranges values either using the the time picker or not. At the moment, when I use the a range for today 0:00 till tomorrow 0:00, the result for datepicker with timepicker is the one I set in the ranges, without the timepicker I got today 0:00 till tomorrow 23:59:59

**Comment by dangrossman** [comment]
Make your range "today to today", which will be today 0:00 to today 23:59:59, which is one second from tomorrow at 0:00. More generally, the answer is no. When the time picker is not enabled, everything operates on whole days.
